### ISSUE TITLE
Processing of supported forensic/virtual disk images recursively

### ISSUE THREAD

**Issue by ronaldorcosta** [sepinf-inc/IPED#102]
When a forensic image (eg E01) contains virtual disks (eg VHD) among its files, it would be useful if IPED had the functionality to automatically export these virtual disks, process them and include them in the case as new evidences.

**Comment by lfcnassif** [comment]
Removed non portuguese text. I also took a look at libvhdi and libvmdk projects, and seems they support snapshots, that is great.

**Comment by lfcnassif** [comment]
I started to work on this. At first I will add a basic solution without snapshot support. Maybe the disk without the snapshot could contain more relevant data, maybe not... And if there are many snapshots, decoding all of them could be very expensive and an overkill...

**Comment by lfcnassif** [comment]
Embedded images could also be splited, at least for dd & e01, I don't know about vmdk and vhd, nof sure if I will target this for now.

**Comment by lfcnassif** [comment]
Just to document here, splitted/segmented images aren't supported for now and this was left as a future improvement.

**Comment by lfcnassif** [comment]
I'm reopening this to implement splited image support, shouldn't be hard. The only disadvantage is that all embedded disks should be sent to second processing queue to allow finding image parts.

**Comment by lfcnassif** [comment]
Reopening to change the logging level to warn instead of error (this goes to console) when processing embedded disks.

**Comment by lfcnassif** [comment]
Closed by commit f5765a8

**Comment by hauck-jvsh** [comment]
This is processing ufdr files recursively too? If I process the folder where the ufdr is it will be expanded?

**Comment by lfcnassif** [comment]
Unfortunately not at the moment, the primary goal was to support common image formats that could be found in suspect's machines (plus others processed in the same way). AD1 is another format that maybe might be supported.

**Comment by lfcnassif** [comment]
PS: actually the UFDR will be processed like generic zip files not like UFDR evidences
