### ISSUE TITLE
Duplicated empty "WhatsApp Account" item in each report generation

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#1033]
This issue was noticed when solving #1028.

Initially a case was processed from tree UFDR files. Filtering by `nome:"WhatsApp Account"` showed this.
![image](https://user-images.githubusercontent.com/2973359/159767260-f6336b5a-9c90-4f8e-adf4-00d7072bdd58.png)

After generating a report from the case, the filtering resulted in:
![image](https://user-images.githubusercontent.com/2973359/159767384-b3b2ae10-a563-4f3f-812c-a88d3d4788da.png)

Finally, generating a second report from the report, the result was:
![image](https://user-images.githubusercontent.com/2973359/159767628-9e5a8ba4-efcf-40c1-b50d-bcc9d505c58b.png)

The item duplication seems to occur only with the item with length 198, that has no relevant information:
![image](https://user-images.githubusercontent.com/2973359/159767927-23a65f05-b5a5-4b96-8b63-9448fb0d77d8.png)

**Comment by lfcnassif** [comment]
Thanks. I'll investigate this tomorrow. Was this happening with other cases before #1028 changes?

**Comment by aberenguel** [comment]
> Thanks. ~I'll investigate this tomorrow~. Was this happening with other cases before #1028 changes?

Sorry for the delay in responding. I will check it tomorrow.

**Comment by aberenguel** [comment]
The parent is the item `/Root/data/com.whatsapp/shared_prefs/com.whatsapp_preferences.xml`

**Comment by lfcnassif** [comment]
Hum... I'll try to reproduce...

**Comment by lfcnassif** [comment]
For some reason I don't remember exactly (maybe I was lazy to include "User Accounts" in all CategoriesToExpand.txt files in all profiles, or maybe this user account expansion is relevant to the graph module) some user accounts mimes were hard coded explicitly to be always expanded....I'll add a check to ignore this behavior if a report is being created.
