### ISSUE TITLE
Optimize external PDF thumb creation running it in the external parsing processes

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1034]
The "external" pdf thumbs config is safer than "internal" (#1032), but slower, we can improve its performance reusing processes.

**Comment by lfcnassif** [comment]
I think we have already proposed this, but other option is generating thumbs in the external parsing processes, like one or two parsers do (e.g. VCFParser). Duplicated thumbs wouldn't be skipped/reused, but we would reuse external processes instead of creating new ones, wasting less memory resources... This implementation should be much simpler.

**Comment by lfcnassif** [comment]
Maybe it's possible to reuse thumbs too, but this would need two tasks, one before ParsingTask to read thumbs from DB and other after ParsingTask to write them to DB, not sure if this is worthy to implement.

What do you think about the general idea of reusing parsing processes @tc-wleite?

**Comment by lfcnassif** [comment]
> e.g. VCFParser

Others create for contacts: (Telegram|Skype|WhatsApp)Parser

**Comment by lfcnassif** [comment]
Some stats with a ~40k pdfs dataset:
14 GB/h with external thumbs on, external parsing off
135 GB/h with external thumbs on INSIDE external parsing on (not reusing thumbs yet)
160 GB/h with internal thumbs on, external parsing on
165 GB/h with no thumbs, external parsing on
170 GB/h with internal thumbs on, external parsing off

**Comment by lfcnassif** [comment]
I minor drawback with creating thumbs inside PDFParser is that a thumb timeout would cause a parsing timeout, but running the thumb creation at the end and catching exceptions, pdf text will still be indexed fine (plus raw strings) before the timeout, the file will be just tagged with a parsing timeout.

**Comment by tc-wleite** [comment]
> What do you think about the general idea of reusing parsing processes @tc-wleite?

I think it would be the better option, performance-wise.
I didn't implement it initially because I was not sure how to change the parsing task, and I tried to minimize the impact on existing functions.

About the reported issue and the tests you ran, what IPED version were used? 
I am asking because, as far as I remember, there was a critical "system-level" contention, when creating PDF thumbs (during the call to PDFBox that renders the page), using Java 8.
I wasn't able to overcome this problem, but it seems to be gone using Java >= 9.
I don't know if this issue is still present, but the excessive number of timeouts *may be* related to this contention.
If you ran your tests with IPED 4/Java 11, please, give a try using 3.18.14/Java 8 (using the current code).

**Comment by lfcnassif** [comment]
> About the reported issue and the tests you ran, what IPED version was used?
> I am asking because, as far as I remember, there was a critical "system-level" contention, when creating PDF thumbs (during the call to PDFBox that renders the page), using Java 8.
> I wasn't able to overcome this problem, but it seems to be gone using Java >= 9.
> I don't know if this issue is still present, but the excessive number of timeouts **may be** related to this contention.
> If you ran your tests with IPED 4/Java 11, please, give a try using 3.18.14/Java 8 (using the current code).

Great tip! I'm trying to reproduce using 4.0-alpha, will try with 3.18.14

**Comment by lfcnassif** [comment]
> a parsing timeout would also affect the thumb creation

About timeouts, I decided to put the thumb creation after parsing code since I think text extraction/indexing is more relevant than pdf thumb view. About exceptions, I'm catching them and rethrowing at the end, so a parsing exception (in a non first page) wouldn't affect thumb creation.

**Comment by lfcnassif** [comment]
> 135 GB/h with external thumbs on INSIDE external parsing on (not reusing thumbs yet)

A final update on tests, reusing thumbs increased the thumb creation in external parsing processes to ~145 GB/h

**Comment by lfcnassif** [comment]
> I am asking because, as far as I remember, there was a critical "system-level" contention, when creating PDF thumbs (during the call to PDFBox that renders the page), using Java 8.

@tc-wleite, reading your original post on #119, seems OpenJDK 8 also solved the issue, right? Maybe we can replace our very old JRE embedded in 3.18.x
