### ISSUE TITLE
Decode base64 values from UFDR xml

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1035]
Some passwords values are being read using the raw value in the report.xml, but they could be in base64 (or other format?) encoding:
![image](https://user-images.githubusercontent.com/7276994/160117107-30ca0b09-35bc-4d1e-bb96-01ed6ede588f.png)

**Comment by tc-wleite** [comment]
@lfcnassif, that would be great.
In many cases I worked recently, there were several valid/useful passwords in "Passwords" category stored in base64. 
At least in the cases I checked, all extracted passwords were in base64.
Sometimes the decoded value is not an actual password, something like an URL or "INVALID TOKEN". 
Still in these cases, decoding the value is necessary, to see the actual extracted data.
