### ISSUE TITLE
ParsingTask causing problems in NSFWNudityDetectTask.py loading on Linux (master)

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#1048]
Version: IPED-4.0.0-snapshot
OS: Kubuntu 22.04
Python: 3.10 (JEP 3.9.1)
Java: Liberica JDK Full version "11.0.14.1" 2022-02-08 LTS

I was trying to enable the `NSFWNudityDetectTask.py` task, but it was throwing this exception: `jep.JepException: <class 'SyntaxError'>: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers`. This happens when the python script tries to execute the line `from keras.models import load_model`.

After some debugging, I discovered that it the `ParsingTask` is causing this execption. If I disable the `ParsingTask`, the  NSFWNudityDetectTask.py` loads without errors.

To make sure that `ParsingTask` is the cause, I made a main class with this code:

```java
    public static void main(String[] args) throws Exception {
        
        new dpf.sp.gpinf.indexer.process.task.ParsingTask();
        
        Jep jep = new SharedInterpreter();
        jep.eval("from keras.models import load_model");
    }
```
 
Ths exception is throw.

```
Exception in thread "main" jep.JepException: <class 'SyntaxError'>: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
	at /home/berenguel/.local/lib/python3.10/site-packages/tensorflow/python/framework/load_library.load_op_library(load_library.py:70)
	at /home/berenguel/.local/lib/python3.10/site-packages/tensorflow/lite/experimental/microfrontend/python/ops/audio_microfrontend_op.<module>(audio_microfrontend_op.py:25)
	at /home/berenguel/.local/lib/python3.10/site-packages/tensorflow/lite/python/lite.<module>(lite.py:33)
	at /home/berenguel/.local/lib/python3.10/site-packages/tensorflow/lite/python/authoring/authoring.<module>(authoring.py:44)
	at /home/berenguel/.local/lib/python3.10/site-packages/tensorflow/_api/v2/compat/v1/lite/experimental/authoring/__init__.<module>(__init__.py:8)
	at /home/berenguel/.local/lib/python3.10/site-packages/tensorflow/_api/v2/compat/v1/lite/experimental/__init__.<module>(__init__.py:8)
	at /home/berenguel/.local/lib/python3.10/site-packages/tensorflow/_api/v2/compat/v1/lite/__init__.<module>(__init__.py:9)
	at /home/berenguel/.local/lib/python3.10/site-packages/tensorflow/_api/v2/compat/v1/compat/v1/__init__.<module>(__init__.py:47)
	at /home/berenguel/.local/lib/python3.10/site-packages/tensorflow/_api/v2/compat/v1/compat/__init__.<module>(__init__.py:37)
	at /home/berenguel/.local/lib/python3.10/site-packages/tensorflow/_api/v2/compat/v1/__init__.<module>(__init__.py:30)
	at /home/berenguel/.local/lib/python3.10/site-packages/tensorflow/_api/v2/compat/__init__.<module>(__init__.py:37)
	at /home/berenguel/.local/lib/python3.10/site-packages/tensorflow/__init__.<module>(__init__.py:51)
	at /home/berenguel/.local/lib/python3.10/site-packages/keras/__init__.<module>(__init__.py:21)
	at <string>.<module>(<string>:1)
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:451)
	at dpf.sp.gpinf.indexer.JepTest.main(JepTest.java:111)
```

If I comment the line `new dpf.sp.gpinf.indexer.process.task.ParsingTask();`, the exception does not occur.

I think that the cause is some static code that is being loaded in `ParsingTask` instantiation. There is lot of dependencies in this class. I need investigate more which one is the cause.

I also tried with JEP-4.0.3 and Python 3.9, but the bug was the same.

**Comment by aberenguel** [comment]
This test code also triggers the exception:

```java
    public static void main(String[] args) throws Exception {

        Jep jep = new SharedInterpreter();

        new dpf.sp.gpinf.indexer.process.task.ParsingTask();

        jep.eval("from keras.models import load_model");
    }
```

**Comment by lfcnassif** [comment]
Thanks @aberenguel for reporting. This looks weird, I'll try to do some tests...

**Comment by lfcnassif** [comment]
I'm not able to reproduce this on Windows 10, python 3.8.6 and Openjdk version "11.0.13" 2021-10-19 LTS x64

I don't think this is related to java dependencies used by ParsingTask, maybe python ones or maybe this is some encoding issue...

Could you try to remove conf/parsers/PythonParserJabber.py script from its folder or to rename its parent folder?
Or could you try to disable all python parsers? Go to conf/ParserConfig.xml and comment out this line:
`<parser class="dpf.inc.sepinf.python.PythonParser"></parser>`

**Comment by aberenguel** [comment]
> I'm not able to reproduce this on Windows 10, python 3.8.6 and Openjdk version "11.0.13" 2021-10-19 LTS x64
> 
> I don't think this is related to java dependencies used by ParsingTask, maybe python ones or maybe this is some encoding issue...
> 
> Could you try to remove conf/parsers/PythonParserJabber.py script from its folder or to rename its parent folder? Or could you try to disable all python parsers? Go to conf/ParserConfig.xml and comment out this line: `<parser class="dpf.inc.sepinf.python.PythonParser"></parser>`
> 
> edit: JEP-3.9.1, Tensorflow 2.4.1

I tried these actions but it did not work.

I'm using tensorflow 2.8.0. I was not possible to download 2.4.1 via pip (only versions >= 2.5.0 were available)

**Comment by aberenguel** [comment]
I've just tried some things. I think the SevenZipParser is causing the issue. I removed it from ParsingTask and the issue did not occur.

**Comment by aberenguel** [comment]
Some news: the root cause is the line `SevenZip.initSevenZipFromPlatformJAR(tmpDir)` being executed statically in `SevenZipParser`.

**Comment by aberenguel** [comment]
Another variant to reproduce the bug:

```java
    public static void main(String[] args) throws Exception {

        Jep jep = new SharedInterpreter();
        
        File javaTmp = new File(System.getProperty("java.io.tmpdir"));
        SevenZip.initSevenZipFromPlatformJAR(javaTmp);
        
        jep.eval("from keras.models import load_model");
    }
```

**Comment by lfcnassif** [comment]
> Some news: the root cause is the line `SevenZip.initSevenZipFromPlatformJAR(tmpDir)` being executed statically in `SevenZipParser`.

Great! Thank you for debugging on your system!

**Comment by aberenguel** [comment]
Debugging one layer deeper, I got the library `lib7-Zip-JBinding.so` that is loaded in `SevenZip.initSevenZipFromPlatformJAR(tmpDir)`.

```java
    public static void main(String[] args) throws Exception {

        Jep jep = new SharedInterpreter();

        System.load("/tmp/lib7-Zip-JBinding.so");

        jep.eval("from keras.models import load_model");
    }
```

It seems that some thing happens in native layer.

**Comment by lfcnassif** [comment]
Native libraries are a headache...

**Comment by aberenguel** [comment]
> Native libraries are a headache...
> 
> PS: just tested with tensorflow-2.8 on Windows, worked fine.

I think it is something related to linux only. 

A possible solution could be to do a lazy load of `SevenZipParser.SUPPORTED_TYPES` and load the `from keras.models import load_model` in very start of `NSFWNudityDetectTask.py`.

**Comment by lfcnassif** [comment]
Try to put NSFWNudityTask.py before ParsingTask in TaskInstaller.xml, but the first needs to be placed after ImageThumbTask (needs to be places before) and after VideoThumbTask, because NSFWTask needs image and videos thumbs to work.

**Comment by aberenguel** [comment]
I did not solved.

```xml
    <task class="dpf.sp.gpinf.indexer.process.task.VideoThumbTask"></task> <!--see issue #100-->
    <task class="dpf.sp.gpinf.indexer.process.task.ImageThumbTask"></task>
    <task script="NSFWNudityDetectTask.py"></task>
    <task script="FaceRecognitionTask.py"></task>
    <task class="dpf.sp.gpinf.indexer.process.task.ParsingTask"></task>
```

I also tried to use `from keras.models import load_model` in the start of `NSFWNudityTask` but it did not worked too.
A thing that worked was remove the load of from static code in ParsingTask

```java
    private static synchronized Set<MediaType> getTypesToCheckZipbomb() {
        if (typesToCheckZipBomb == null) {
            typesToCheckZipBomb = new HashSet<>();
            typesToCheckZipBomb.addAll(PackageParser.SUPPORTED_TYPES);
            typesToCheckZipBomb.add(SevenZipParser.RAR);
        }
        return typesToCheckZipBomb;
    }
```
But I think it is safer to make the `SevenZipParser.getTypes()` lazy too.

**Comment by lfcnassif** [comment]
Thanks @aberenguel. I just pushed a similar lazy load solution in commit b50db54. Please check if it fixes the issue on your environment and let me know, so I'll merge in master.

**Comment by lfcnassif** [comment]
@aberenguel just an unrelated question, have you had any issues when installing JEP on Linux? I'm asking because of this user issue #842

**Comment by aberenguel** [comment]
> Thanks @aberenguel. I just pushed a similar lazy load solution in commit [b50db54](https://github.com/sepinf-inc/IPED/commit/b50db549d58f155df60dcc2da24daaf61a96ed28). Please check if it fixes the issue on your environment and let me know, so I'll merge in master.

Just tested the commit b50db549d. It fixed this issue.

**Comment by lfcnassif** [comment]
Thanks @aberenguel for reporting, debugging and testing!
