### ISSUE TITLE
Implement "shortcut" for filter creation from results table.

### ISSUE THREAD

**Issue by patrickdalla** [sepinf-inc/IPED#1053]
I think would be a good utility to create filters from property values from selected item on results table. A behaviour similar to filter creation on ProcessMonitor of SysInternals, when you right click an item/property value, a popup menu opens with options to create filter to exclude or to only include items with equals value on the same selected property.

**Comment by lfcnassif** [comment]
Couldn't the metadata tab be used to a similar goal? I have already thought to improve it to let the user create many filters instead of just one.

**Comment by patrickdalla** [comment]
Yes. But it would be a shortcut, not a real urgent necessity. for example:
I, as the analyst, see a particular occurrence of a property value, it
would be quickier if I select this value and create a filter based on this
value. My idea is to concatenate the corresponding filter string on the
current top filter input.

As an example: i find a particular tor URL, 56 scrambled characters. I want
to filter to show only where this ocurrence repeats. If i go to the
Metadata, I should select regex, then URL, then find on a huge URL list
where this ocurrence is to select it.



Em qua., 6 de abr. de 2022 15:54, Luis Nassif ***@***.***>
escreveu:

**Comment by patrickdalla** [comment]
Many different filter on the metadata filter tab can be useful also. Maybe
a different ResultSetViewer to show the results in a pivot table like
viewer. But is different and more complex issue.


Em qua., 6 de abr. de 2022 16:42, Patrick Bernardina <
***@***.***> escreveu:

**Comment by patrickdalla** [comment]
The popup menu has many options already. Maybe another popup triggered with CTRL or SHIFT.

**Comment by patrickdalla** [comment]
![image](https://user-images.githubusercontent.com/28692427/162188706-6db96df6-07e5-43ae-8a1b-11cc21fbf1ae.png)
See the highlighted popup menu option. For dates is interesting also the options exclude before/after, and for numbers, exclude smaller/larger than.

**Comment by lfcnassif** [comment]
Nice, this could make user life easier...

**Comment by patrickdalla** [comment]
Hi @lfcnassif , when refactoring MetadataPanel to expose some private classes an fields in a way to adapt to new FilterManager, #39, I saw it could be somewhat easy to reuse it to reach this issue. So, we could include this in 4.2 roadmap too.
I sent a private video of the feature.

**Comment by lfcnassif** [comment]
Great! I'm on external activities in another city today and tomorrow, so I may be slow to respond. If the Metadata panel code part without UI interaction could be moved to iped-engine module, and if it is easy, it would be possible to be used as a filter programmatically, from a python terminal or java/javascript tasks for example, that may be useful.
