### ISSUE TITLE
Support new Telegram versions 8.5-8.7

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#1064]
Telegram has just updated the media table "media_v3" to "media_v4", I will take a look and see if this is the only change.

**Comment by lfcnassif** [comment]
Last week an user sent a processing log to me with this exception:
xxxxxx\cache4.db (4308992 bytes)		org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: messages)

**Comment by hauck-jvsh** [comment]
It is the same thing the message table also changes to messages_v2 in my file

**Comment by hauck-jvsh** [comment]
I just implemented the support for telegram 8.7.
