### ISSUE TITLE
NameEntityTask

### ISSUE THREAD

**Issue by fcscoutinho** [sepinf-inc/IPED#108]
[ERROR] [process.task.NamedEntityTask]                  edu/stanford/nlp/models/ner/english.all.3class.caseless.distsim.crf.ser.gz not found. Did you put the model in the optional lib folder?

Não sei onde incluir o modelo de entidades para ele funcionar com o iped. iNCLUI O "stanford-corenlp-3.8.0.jar" na pasta optional_jars,  mas o arquivo "english.all.3class.caseless.distsim.crf.ser.gz" que baixei eu não sei o que devo fazer com ele....

**Comment by lfcnassif** [comment]
stanford-corenlp-3.8.0.jar is already distributed in optional_jars folder. You need to put the model file(s) in the same folder.

**Comment by lfcnassif** [comment]
Did it work?

**Comment by fcscoutinho** [comment]
Yes.
Tank you!!!!

Em ter, 9 de jun de 2020 15:40, Luis Nassif <notifications@github.com>
escreveu:
