### ISSUE TITLE
Create unit tests for more parsers

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1093]
Dear colleagues, let's welcome our new intern @FelipeFcosta. Welcome, Felipe! I hope you will like to work and learn together with us, I'm always learning, technologies always evolve very fast.

After reading the API documentation I provided to you and configuring your IDE, let's start trying to create new unit tests for parsers that still don't have one. You can use the existing unit tests as a guide, but don't trust them as gold standard, things can always be improved.

You will probably have to collect sample files from the Internet **with suitable license** (Apache, Mozilla, MIT, BSD style or from public domain) to be included in this project, or, if not found, create new sample files from scratch using their default applications to use in tests.

**Comment by FelipeFcosta** [comment]
Thanks for the opportunity, I'm already liking it here!
