### ISSUE TITLE
Fix possible starvation in WhatsAppParser when mergeDBs backups is enabled

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1094]
As reported here:
https://github.com/sepinf-inc/IPED/pull/1065#issuecomment-1117660227
https://github.com/sepinf-inc/IPED/pull/1065#issuecomment-1118552007

**Comment by fmpfeifer** [comment]
The bug with zero length files was also fixed in libfqlite 1.57.05

**Comment by lfcnassif** [comment]
> The bug with zero length files was also fixed in libfqlite 1.57.05

Thank you @fmpfeifer!
