### ISSUE TITLE
Support for WhatsApp version up to 2.22.9

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1105]
WhatsApp-2.22-beta was promoted to final. The database schema was completely changed, breaking our parser and others from other projects. @hauck-jvsh pushed an initial experimental support for Android databases to this branch: https://github.com/sepinf-inc/IPED/tree/new_msgstore

We still need more samples to test Android support and to implement that for iOS (no samples until now).

For those in urgent need, below is a snapshot version of that branch, you must be signed in github to be able to download:
https://github.com/sepinf-inc/IPED/actions/runs/2416113685

**Comment by hauck-jvsh** [comment]
After pull request #1149 the new versions will be supported without the recovery of deleted registers. Is there any documentation on how to use the new interface for recovery registers?
@fmpfeifer How did you discover the MessageType? Is there a leaked source? Or did you look in an extraction and in the phone to guess the message types?

**Comment by fmpfeifer** [comment]
> After pull request #1149 the new versions will be supported without the recovery of deleted registers. Is there any documentation on how to use the new interface for recovery registers?
> @fmpfeifer How did you discover the MessageType? Is there a leaked source? Or did you look in an extraction and in the phone to guess the message types?

Hi @hauck-jvsh , I looked in a database and compared with the app installed in a phone to guess the message types.

**Comment by hauck-jvsh** [comment]
Thank you, I was hopping that you found an easy way, but I see that you make exactly what I think.

**Comment by mpolastro** [comment]
This may help (at least to confirm some findings):
https://thebinaryhick.blog/2022/06/09/new-msgstore-who-dis-a-look-at-an-updated-whatsapp-on-android/

Em dom., 12 de jun. de 2022 19:52, Hauck ***@***.***>
escreveu:
