### ISSUE TITLE
Option to extract a number of video frames as a function of video duration

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1107]
As discussed in other issues #1081 #1102, this could improve search results of a number of video tasks (nudity and faces detection, future similarity search, OCR and photoDNA and others).

`extractFramesMillisecondInterval = 1000` would be a good default value for pedo and forensic profiles and disabled for others?

Or should we make some kind of attenuation targeting huge videos, maybe using a logarithmic or similar function applied to video duration?

**Comment by lfcnassif** [comment]
I'm increasing the priority of this, this can be useful to #1472.

**Comment by lfcnassif** [comment]
@tc-wleite I'm coding to change just the number of subitems extracted (if enabled) to don't mess the mosaic already generated, ok?

**Comment by tc-wleite** [comment]
> @tc-wleite I'm coding to change just the number of subitems extracted (if enabled) to don't mess the mosaic already generated, ok?

Sure! I think it should be fine, as the algorithm that generates the mosaic can receive more images than it actually uses.
I will be out next week, but I can take a look in the changes and test if you want.
