### ISSUE TITLE
#1095: Update Italian translation

### ISSUE THREAD

**Issue by flates** [sepinf-inc/IPED#1113]
I am improving the Italian translation and fixing some typos.

After compiling the sw I noticed a couple of things that I would like to discuss before submitting a PR

- In the file `iped-filters_**.properties`, the entry "Files\ with\ Thumbnails" is missing.
![filter2](https://user-images.githubusercontent.com/26255460/168761253-1234be29-e49e-4e00-95c1-3113280c2390.jpg)
and i added it in the it_IT file.

- In the file `iped-desktop-messages_it_IT.properties` I noticed that the entries that have single quote `'` in the text are not shown correctly in the GUI. 
For example, for line 339:
![apo1](https://user-images.githubusercontent.com/26255460/168779877-a4372243-d256-4d1c-9c94-2b1ff9f4efce.jpg)
If I use two single quote `''`, it is shown correctly.
![apo2](https://user-images.githubusercontent.com/26255460/168779883-6b449f50-733d-4f22-b3a0-a8c99435bc8d.jpg)
Don't know if this is the right way for Java.
I know, in Italian we use lots of `'` eheh

- `iped-categories_**.properties` from line 92 onwards
During one of my tests with the latest IPED snapshot, I noticed that some PDF files were placed in the category "Brazilian Software -> Internal Revenue of Brazil -> PDF Bills of Exchange" and "SPED Program Files"
The category "PDF Bills of Exchange" might be correct as these files are invoices and tax documents but I don't know "SPED Program Files" (and the other entries) and I would like to understand how the categories in "Brazilian Software" work so that I can make translation that also makes sense for Italian users.

**Comment by lfcnassif** [comment]
@flates, since you are dealing with this, could you also translate this new strings from #1065:
```
WhatsAppReport.ContactDeleted=Recovered deleted contact
WhatsAppReport.RecoveredChat=Recovered deleted chat
WhatsAppReport.UnknownMediaMessage=Unknown Media Message
```

**Comment by flates** [comment]
> That's right! That's new info to me too :-) ref: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/text/MessageFormat.html

Great :)


> > * The category "PDF Bills of Exchange" might be correct as these files are invoices and tax documents but I don't know "SPED Program Files" (and the other entries) and I would like to understand how the categories in "Brazilian Software" work so that I can make translation that also makes sense for Italian users.
> 
> They possibly are false positives, since those categories should contain just files related to brazilian software. But most of the rules used for those categories are very very simple, based mostly on name, extension and path:

Yes, in my tests, the files included in the "PDF Bills of Exchange" category have names that fit the search rule, for example "RE_0000001445_2022.pdf," as well as "SPED_XXXX" for "SPED Program Files" category.
Maybe, The possibility of deselecting certain categories (if not already possible) could be useful. For now, for my tests I have tried to create a custom profile with the `conf\CategoriesConfig.json` file without the "Brazilian Software" category. It works but "PDF Bills of Exchange" is still visible in IPED-Searchapp.


> @flates, since you are currently dealing with this, could you also translate these new strings from #1065?
> 
> ```
> WhatsAppReport.ContactDeleted=Recovered deleted contact
> WhatsAppReport.RecoveredChat=Recovered deleted chat
> WhatsAppReport.UnknownMediaMessage=Unknown Media Message
> ```

No problem, I have already added them to the file `iped-parsers-messages_it_IT.properties`

**Comment by flates** [comment]
Okay, I'll submit the PR then.

I also changed the translation of "Brazilian Software" to the Italian equivalent of "Possible Brazilian Software" to further reduce the confusion in Italian users.
