### ISSUE TITLE
ArrayIndexOutOfBoundsException: Index -1 out of bounds after PR #1143

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#1147]
I'm facing some problems when opening the created case. I'm attaching the IPED-SearchApp.log
[IPED-SearchApp.log](https://github.com/sepinf-inc/IPED/files/8871251/IPED-SearchApp.log)

**Comment by lfcnassif** [comment]
Thanks @hauck-jvsh. I'll take a look at this now. From what commit did you compile from?

**Comment by hauck-jvsh** [comment]
![image](https://user-images.githubusercontent.com/67768441/172905243-c5b27de2-a828-4ab7-8061-5538ecc68e54.png)

**Comment by hauck-jvsh** [comment]
After a clean build it opened, but did not load any metadata or the file content.

**Comment by lfcnassif** [comment]
I'm not able to reproduce the first issue, but I reproduced the one in the second log, it was caused by #1143, I'll fix shortly.

**Comment by hauck-jvsh** [comment]
I think that the first one was caused by a problem during compilation as it was solved after a clean build.

**Comment by lfcnassif** [comment]
The cause of this has broken other features, I'll push all fixes together.
