### ISSUE TITLE
The package XXXX is accessible from more than one module: <unnamed>, javax.xml

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1148]
@FelipeFcosta and @tc-wleite warned me about errors like above shown by VSCode and Eclipse. They are conflicts between some dependencies and Java 11 after upgrading to Tika-2. I found this thread: https://stackoverflow.com/questions/55571046/eclipse-is-confused-by-imports-accessible-from-more-than-one-module

I'll push a possible fix, but still needs to process a bunch of files and check the log for NoClassDefFoundError or ClassNotFoundExceptions to be sure everything is ok.

**Comment by lfcnassif** [comment]
Just found at least 2 jars with conflicting javax.xml.bind (removed from java 11) packages:
jakarta.xml.bind-api-2.3.2.jar
jaxb-api-2.3.0.jar

Although they don't cause the error in the title, I think they may result in ClassCastExceptions while processing.

**Comment by lfcnassif** [comment]
Like said in one of the comments in the thread above `Ctrl + Shift + T` works in Eclipse to find the conflicting jars

**Comment by lfcnassif** [comment]
@FelipeFcosta and @tc-wleite please check if commits above fix the issues on your environments.

**Comment by FelipeFcosta** [comment]
Just checked, all errors seem to be gone.
Working as it used to.

**Comment by lfcnassif** [comment]
Thank you!

**Comment by lfcnassif** [comment]
Just checked the log of a 2M case processed during the night, just 1 ClassCastException found thrown by PDFBox that used to happen before, so the fix seems fine.

**Comment by lfcnassif** [comment]
> The errors are gone here too. Thanks @lfcnassif.

Thanks for the feedback!
