### ISSUE TITLE
Processing error 

### ISSUE THREAD

**Issue by silviotassini** [sepinf-inc/IPED#1161]
I'm facing the following error:

java.lang.Exception: Worker-3 Error while processing /21-040505594.E01/vol_vol3/Program Files/WindowsApps/SharedLimitedTime/InfusedApps/Packages/Microsoft.BingWeather_4.9.51.0_x86__8wekyb3d8bbwe/Microsoft.Msn.Weather.dll (10799104bytes)
	at dpf.sp.gpinf.indexer.process.Worker.process(Worker.java:188) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.Worker.run(Worker.java:240) ~[iped-engine-4.0.0-snapshot.jar:?]
Caused by: java.lang.StackOverflowError
	at javax.imageio.stream.MemoryCache.loadFromStream(MemoryCache.java:115) ~[?:?]
	at javax.imageio.stream.MemoryCacheImageInputStream.read(MemoryCacheImageInputStream.java:85) ~[?:?]
	at javax.imageio.stream.ImageInputStreamImpl.readLine(ImageInputStreamImpl.java:297) ~[?:?]
	at com.github.jaiimageio.impl.plugins.pnm.PNMImageReader.readInteger(PNMImageReader.java:772) ~[jai-imageio-core-1.4.0.jar:1.4.0]

**Comment by lfcnassif** [comment]
Thanks for reporting. From what commit was that snapshot built from? Could you share the Microsoft.Msn.Weather.dll triggering file, so we can reproduce the error to test a possible fix?

**Comment by lfcnassif** [comment]
Was the processing aborted?

**Comment by lfcnassif** [comment]
And also please share the full processing log (privately if needed) and post the full stacktrace, thanks.

**Comment by silviotassini** [comment]
> Was the processing aborted?

no, processing stopped by itself.
I don't know which commit I used and the file Microsoft.Msn.Weather.dll is in an image on the service, I don't have access until tomorrow. I need to be there to mount the image and copy the file.
[IPED-2022-06-09-13-12-43.log](https://github.com/sepinf-inc/IPED/files/8904014/IPED-2022-06-09-13-12-43.log)
.

**Comment by lfcnassif** [comment]
Thank you for the log. That DLL seems a corrupted file to me, detected as PNG (maybe it was overwritten). Unfortunately, it is not clear in the log which module has thrown the error (ImageThumbTask, NudityDetection, other...). So I would need that DLL file to confirm the error still happens using latest commit, test a possible fix and to be sure the same error won't be thrown by another image processing module.

**Comment by silviotassini** [comment]
Hi,
It's a deleted file, 
![image](https://user-images.githubusercontent.com/11312417/173826511-55747672-a0d6-4fe9-be
[Microsoft.Msn.Weather.dll.zip](https://github.com/sepinf-inc/IPED/files/8909238/Microsoft.Msn.Weather.dll.zip)
17-69cf04a6b0a7.png)
I'm sending it compressed

**Comment by silviotassini** [comment]
Hi,
It's a deleted file,
I'm sending it compressed
[Microsoft.Msn.Weather.dll.zip](https://github.com/sepinf-inc/IPED/files/8909250/Microsoft.Msn.Weather.dll.zip)

![image](https://user-images.githubusercontent.com/11312417/173827023-47f2bb5b-0092-4f01-8446-2310071ead2c.png)

**Comment by lfcnassif** [comment]
Thank you for the file! But I was not able to reproduce the error with 3.18.15, last commit from master, nor with a snapshot before Tika-2 upgrade #1116 (that could change file type detection). So I ask you to try to reproduce with last commit from master. If you manage to reproduce, please reopen and kindly provide additional details to help us reproduce this, thanks.
