### ISSUE TITLE
Delete temp folder from Bootstrap process

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1170]
Since a long ago, we weren't able to delete the temp folder because of loaded DLLs. They are unloaded just when the class loader that loaded them is garbage collected, which is a difficult situation to trigger.

Now that we have a start up process, I think it should be able to clean the temp folder without problems.

**Comment by patrickdalla** [comment]
Maybe temp dll's could be installed on different temp folder. So it could
be possible to delete temp folder with no loaded temp content.

Em sáb., 18 de jun. de 2022 09:43, Luis Nassif ***@***.***>
escreveu:

**Comment by lfcnassif** [comment]
Unfortunatelly there are some dependencies that extract their own DLLs to java default temp dir to load them...

**Comment by patrickdalla** [comment]
Right. So, just as bootstrap loads a second process, maybe the App exit
could start another process to monitor App finish so it can delete these
files.

Em sáb., 18 de jun. de 2022 13:32, Luis Nassif ***@***.***>
escreveu:

**Comment by lfcnassif** [comment]
Yes, that is an old ideia. That is exactly the current bootstrap process, it finishes after the main process finishes, so we won't need to start a third process.

**Comment by patrickdalla** [comment]
oh, right. You said "start up process" and I didn't realize you were
meaning it would monitor start till the end to clean all the temp folder.
nice



Em sáb., 18 de jun. de 2022 13:46, Luis Nassif ***@***.***>
escreveu:

**Comment by lfcnassif** [comment]
> it finishes after the main process finishes

It is done so the bootstrap process can redirect standard streams from/to the main process to/from console, etc

Maybe it could do other things in the future, like resuming processing automatically for some kind of errors (like OOME), etc, but that is another history...

**Comment by lfcnassif** [comment]
I'm almost finishing this, but some folders aren't being deleted on Windows because of forbidden NTFS chars in their name. Any tip on how to workaround this with a pure windows command?

**Comment by lfcnassif** [comment]
Found a workaround here: https://learn.microsoft.com/en-us/troubleshoot/windows-server/backup-and-storage/cannot-delete-file-folder-on-ntfs-file-system

This worked:
rm -Force -Recurse "\\?\full_folder_path"

**Comment by lfcnassif** [comment]
Now temp folders and files, including loaded DLLs and memory mapped files, are always deleted when application exits, normally or not, except the `index` dir if it exits in temp because --continue needs it. It won't work if user aborts the application abruptly, e.g. using Ctrl+c

**Comment by lfcnassif** [comment]
Just an update, `new File("\\\\?\\" + file.getAbsolutePath()).delete();` also worked for NTFS files which names end with space, so I updated the code.
