### ISSUE TITLE
Multiple "Possible SleuthkitServer X crash reading..." non problematic files

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1187]
This is related to robustImageReading option. I got above error printed in console several times yesterday for 2 different processings of the same evidence, but it usually doesn't happen for this same evidence. Looking at the log, before the first error there is one "Timeout waiting SleuthkitServer X response! Restarting...". Analyzing the code and log, I found a race condition in timeout control in inter process communication.

I'll push the fix for the race condition to don't trigger the timeout wrongly, but I'm still analyzing why the error in the title happened indefinitely in a loop...

**Comment by lfcnassif** [comment]
This is important to fix since robustImageReading is enabled by default in 4.0

**Comment by lfcnassif** [comment]
@tc-wleite since you have used this option for a long time, have you observed similar errors in the console?

**Comment by tc-wleite** [comment]
When I saw your first message about this issue, I remember seeing that error message a couple of times. But I didn't pay much attention as I was testing/working in something else and it disappeared later. 
I can't remember any details, but it was definitely rare.

**Comment by lfcnassif** [comment]
Thanks. Maybe it is less rare when `indexTempOnSSD = false`, I'm using it to compare to other cases processed the same way, so items would be read multiple times from the external process instead of from the temp folder...

**Comment by lfcnassif** [comment]
This is not working on 3.18.15, removing its tag.

**Comment by lfcnassif** [comment]
> This is not working on 3.18.15, removing its tag.

sorry, not happening!

**Comment by lfcnassif** [comment]
Well, tricky, it takes some minutes to start the problematic loop after the first crash, so this happens with 3.18.15 too.

**Comment by lfcnassif** [comment]
> Well, tricky, it takes some minutes to start the problematic loop after the first crash, so this happens with 3.18.15 too.

And, after the crash on 3.18.15, the external process is not restarted. Seems the bad loop begins when other external processes are restarted to clean possible resource leaks.

Anyway, 4.0.0-beta seems to be working fine now.
