### ISSUE TITLE
Create thumbnails for PDFs

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#119]
Create an option (that can be disabled in configuration files) to generate thumbnails for PDFs (at processing time, and later to be displayed in the gallery).

Although the thumbnails are small and would show only the first page of the document, this can be very useful for PDFs containing scanned documents:

![image](https://user-images.githubusercontent.com/7217001/83956169-7e0f0980-a831-11ea-8c0f-1f82d0b30634.png)

**Comment by lfcnassif** [comment]
Great work @tc-wleite ! In the past I thought creating thumbs for documents wouldn't be very useful, because user couldn't read too much info in small thumbs. But seeing your screenshot, I think it can be very useful for non text docs with images or text with "layout" info that could be easily identified by user as a relevant doc or not.

But, I am concerned about stability. In the past it was not rare OOM errors when converting pdf to image before OCR. That's why the ocr module does it in another process. Maybe this could be moved to PDFParser and the thumb returned in metadata? So turning externalParsing on will isolate OOM problems.

And maybe we can reuse pdf images already generated by OCRParser when enabled? Just an optimization...

**Comment by lfcnassif** [comment]
Also it could be extended to other docs in other ticket. I think libreoffice has a cmd line option for that, never tested...

**Comment by tc-wleite** [comment]
Great observations @lfcnassif!

**1. Stability**
I forgot about these issues. I assumed that MemoryUsageSetting used on load() would limit memory consumption, and in worst cases it would fail (not generating the thumbnail). It was indeed what happened when I forced a low memory setting and RAM-only option, but I think the cases I tests didn't contain any of these problematic files (I remember this issue now).
My idea to implement it in ImageThumbTask was to avoid dependencies between tasks, but I agree that moving to the parser would allow a much more stable solution. 
I will try to implement that!
I am not sure if I followed the part "returning the thumb in metadata".
Do you mean something like the parser would generate the thumb and temporarily store it in the item's object as a metadata, and later the image thumb task would just get this data and do the rest (store etc.)?

**2. Reusing OCRParser image**
Again, I tried to avoid dependencies between processing tasks, but it definitely makes sense in terms of performance.
I believe images rendered for OCR use a much higher resolution and grayscale, right? So I guess only the page parsing could be saved, not the image rendering, but it still would help.
I will try to implement that too.

**3. Other Document Types**
Absolutely! It can be useful for office documents too. 
I started with PDFs because I believe this feature would be more useful for this file type (in general) and easier to implement.

**Comment by lfcnassif** [comment]
1. Unfortunatelly I think MemoryUsageSetting does not apply to all internal PDF objects, the format is very complex and was an important source of OOMEs. Actually for PDF rendering before OCR current default is IcePDF lib, in old tests it used less memory than PDFBox, but PDFBox evolved a lot and has much more users and developers, so is more tested today. I thought changing the default many times...
About storing thumb in metadata, it is just an idea to send thumb from externalParsing back to main IPED process temporarily, yes. But, current code for duplicate thumb reuse wouldn't work, thumb would be created before ImageTask...

2. Yes they use a much higher resolution, not sure now what is faster: generating again a small thumb or rescaling a large image. And I forgot the grayscale point! Besides page parsing, maybe decoding image streams could be saved...

3. For sure, it was just a note for the future.

**Comment by tc-wleite** [comment]
1. Yes, duplicated thumbs reuse wouldn't work that way... 
What do you think about another option: create a **new task** (something like DocThumbTask)? 
Common features present in ImageThumbTask could be moved to an abstract class (ThumbTask).
This new task can have an option to run the as a external process.
Of course it is not the simplest option, but I guess it would keep things more organized (comparing to add part of this feature in the parser).
Also it would make sense when we think about 3 (dealing with other file types later).
With a separate task, it would also be easier (for users) to see how much processing time this feature is spending, and decide to turn it on/off.

2. Because of grayscale, resizing the image generated to OCR is not an option, right? Avoiding file and first page parsing would save same time for sure. I think it is possible to measure the time spent in each part (file opening, first page parse and thumb rendering) and see if the saved time would be meaningful.

**Comment by lfcnassif** [comment]
1. Another task is a good idea thinking about 3! About the external process option (take a look at PDFToImage class), it does not take too much time relative to full ocr processing, but just for thumbs it should slow down a bit. Keeping permanent processes for it is better for performance, but I don't like the idea of having more and more long running processes, using more RAM. If pdf thumb goes to PDFParser, already existent external parsing processes will be reused.

2. I though about changing from grayscale to colored images, ocr works with them too. But high resolution colored images will use more memory, maybe it is not worth trying. And if ocr is on, creating another small thumb just for first page probably will be fast relative to full ocr...

**Comment by tc-wleite** [comment]
Ok! For now I removed the implementation from the ImageThumbTask.

**Comment by tc-wleite** [comment]
After revisiting this feature, I am finishing the implementation of an initial version.
I found several issues, that made the process very slow in different situations.
Nevertheless, I think it may be integrated as an experimental feature (disabled by default in all profiles), and then improve this initial implementation.
As discussed before, the feature itself seems useful when applied to real cases.

**Comment by lfcnassif** [comment]
Thank you, @tc-wleite! Do you think it is possible to create thumbs in PDFOCRTextParser class, store the thumb in metadata and read it later? This strategy is already used by e.g. VCardParser and will allow isolating possible OOMEs coming from complex PDFs...

**Comment by lfcnassif** [comment]
If not, user can turn the feature off, but often it is hard to track the source of an OOME, many times I had to analyze heap dumps. One module can consume all heap and OOME can be thrown from other module...

**Comment by tc-wleite** [comment]
@lfcnassif, I created 3 options to PDF thumb extraction: "pdfThumbs" = "internal", "external" and "off" (as the task is DocThumbTask, there is an option to PDFs and other to LibreOffice supported files).

It should be possible to create a 4th option (something like "pdfParser") and implement the behavior you described.

The "external" option is similar to what the parser does, but a bit simpler (only PDFBox support, first page, usually much smaller resolution and color images), so it should take care of OOMEs, while not depending on another task (that can be disabled).

I tested with 250K PDF files extracted from a few cases and didn't had memory issues (using the "internal" mode).
I am planning a much larger test for the next days, to collect some of these PDFs that causes OOME, so we can get a better understanding of the root of such problems, and perhaps report/contribute to PDFBox project to avoid such issues.
But the "external" mode is implemented (although it is much slower, of course). 

I have been working with their code in the last days, to figure out a major slowness when using multiple threads (both in internal and external modes). There is some kind of contention/synchronization going on, but I couldn't figure out where. 
It also happens in the existing PDFToImage, but it is not noticiable in a normal processing, as there are other things running (like the OCR itself). 
It should be something really low level, as it also happens when using external processes, and related to fonts (it doesn't happen with PDFs with images only).
With newer JDK versions (tested with Oracle JDK 11, 14, 15 and 16), there problem is gone. 
But with Oracle JDK 8 (tested a couple of different releases) it slows down things a lot (when using 48 threads and running basically only this thumb creation).

**Comment by lfcnassif** [comment]
PDF is a problematic format, last PDFBox release fixed an OOME, and possibly previous versions too, our version is a bit out of date. Will upgrade PDFBox together with Tika in next IPED major release, I saw compatibility issues with Tika when they upgraded and they had to make some code changes.

About 'external' mode, awesome! That resolves my OOME concerns, no need for a pdfParser mode.

Maybe Liberica or Amazon Corretto JDK 8 distributions could have fixed something? (I know, we need to upgrade to newer jdk...)

**Comment by tc-wleite** [comment]
@lfcnassif, just a quick update about the PDF thumb creation, I ran tests with a large set (~1M PDFs, with ~400K of them carved or deleted).
With the current PDFBox version (2.0.17) there was an accumulative memory issue, that made the process too slow after ~150K files. I couldn't identify which files caused it, but it seems there were many of them, slowing increasing the amount of used memory until it became too close to the upper limit I used (24 GB). 
Good news is that with the latest PDFBox version (2.0.23), it processed all 1M files without any trouble (no signs of abnormal memory increase during the processing).
I guess #178 will include the update of PDFBox, right?

One last comment, the file you sent me privately worked fine with both versions.
I created 10K copies of it, appending some bytes so they all have different hashes, but observed no issue.
Maybe it triggered memory issues with older versions (before 2.0.17) of PDFBox.
Another possibility is that issues happen when other pages (not the first one) were accessed.

**Comment by lfcnassif** [comment]
What a test! Yes, #178 will update our old PDFBox, yesterday I pushed a working branch: https://github.com/sepinf-inc/IPED/tree/tika_upgrade

**Comment by tc-wleite** [comment]
I ran some other tests, together with #419, and as this feature seems pretty stable, I am going to finish it for now, adding it as an **experimental** and **disabled by default** feature.

The only known limitation/issue is related to its performance when using Oracle JDK 8.
It seems to be some kind of system level issue/synchronization going on, related to fonts in Windows environment.
I wrote a standalone program (outside IPED) that takes all PDFs in a folder and creates an image file with the first page content, and the issue is still present. 
When using multiple threads, the program doesn't use all CPU resources, as it seems to be waiting for other threads at some points. It is faster than using a single thread (as there should be parts of the processing outside the "synchronized" part), but much slower than using all threads (48 in my case).
I tried to use ICEpdf (instead of PDFBox), but the behavior was the same (both inside IPED and using the standalone test program).

In newer versions of the Oracle JDK (11, 14, 15 and 16) the issue is gone.
Interestingly enough, using *OpenJDK* 8 also solves the issue.

**Comment by lfcnassif** [comment]
Great @tc-wleite! Which OpenJDK 8 distribution did you test? I think we maybe can switch from Oracle to it, as our Oracle version is outdated because of Oracle distribution license changes...

I know it was not your goal, but did you noticed some unknown incompatibility between IPED and newer java versions?

**Comment by tc-wleite** [comment]
> Great @tc-wleite! Which OpenJDK 8 distribution did you test? I think we maybe can switch from Oracle to it, as our Oracle version is outdated because of Oracle distribution license changes...

I used a Red Hat distribution, but just because I couldn't find a version 8 download from https://jdk.java.net/
It worked well, but I am not sure about its license details... 

> I know it was not your goal, but did you noticed some unknown incompatibility between IPED and newer java versions?

I had most of the options disabled and didn't pay much attention to this, but in general everything worked well, except opening the processed case due to the absence of Java FX (which I guess is used by some viewers). I didn't try to download and setup Java FX, which should be a simple solution...

**Comment by lfcnassif** [comment]
Clodrd by #491
