### ISSUE TITLE
iped-4.0.0-beta - No module named 'numpy'

### ISSUE THREAD

**Issue by fcscoutinho** [sepinf-inc/IPED#1191]
Hello Nasif,
I'm trying to use IPED 4.0.0-beta and when I run the program I get the following error:

**2022-06-25 09:57:20	[INFO]	[app.processing.Main]			Indexador e Processador de Evidências Digitais 4.0.0-beta
2022-06-25 09:57:20	[INFO]	[engine.config.Configuration]			Loading configuration from E:\IPED_24062022\target\release\iped-4.0.0-beta
Warning: Nashorn engine is planned to be removed from a future JDK release
ModuleNotFoundError: No module named 'numpy'
ModuleNotFoundError: No module named 'numpy'
java.lang.NumberFormatException: For input string: "false"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at iped.engine.config.RegexTaskConfig.processTaskConfig(RegexTaskConfig.java:142)
	at iped.engine.config.AbstractTaskConfig.processConfig(AbstractTaskConfig.java:42)
	at iped.configuration.Configurable.processConfigs(Configurable.java:40)
	at iped.engine.config.ConfigurationManager.loadConfig(ConfigurationManager.java:63)
	at iped.engine.config.ConfigurationManager.loadConfigs(ConfigurationManager.java:56)
	at iped.engine.config.Configuration.loadConfigurables(Configuration.java:216)
	at iped.app.processing.Main.main(Main.java:291)**

How can I solve? What am I forgetting to configure?

**Comment by lfcnassif** [comment]
No @fcscoutinho. The numpy warning could be fixed installing numpy:
https://github.com/sepinf-inc/IPED/issues/1190

The error seems unrelated. Have you replaced the RegexConfig.txt file? Seems it has some syntax error, causing the issue.

**Comment by fcscoutinho** [comment]
Nassif, I ran the procedures and I still have the same error!

**E:\IPED_24062022\target\release\iped-4.0.0-beta\python>python get-pip.py
Collecting pip
  Using cached pip-22.1.2-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.1.2
    Uninstalling pip-22.1.2:
      Successfully uninstalled pip-22.1.2
Successfully installed pip-22.1.2

E:\IPED_24062022\target\release\iped-4.0.0-beta\python>set PATH=%PATH%;E:\IPED_24062022\target\release\iped-4.0.0-beta\python\Scripts

E:\IPED_24062022\target\release\iped-4.0.0-beta\python>pip install numpy==1.22.3
Collecting numpy==1.22.3
  Downloading numpy-1.22.3-cp39-cp39-win_amd64.whl (14.7 MB)
     ---------------------------------------- 14.7/14.7 MB 8.3 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-1.22.3

E:\IPED_24062022\target\release\iped-4.0.0-beta\python>**

**Comment by lfcnassif** [comment]
> The error seems unrelated. Have you replaced or edited the RegexConfig.txt file? Seems it has some syntax error, causing the issue.

And about this question?

Have you downloaded or compiled the application? If you compiled, you should run mvn clean before

**Comment by fcscoutinho** [comment]
Eu havia deixado o RegexConfig.txt. Voltei para o original e deu certo.
Obrigado!!!!

**Comment by lfcnassif** [comment]
Thanks for the feedback. I recommend reading the migration guide:
https://github.com/sepinf-inc/IPED/wiki/Migration-from-3.18-to-version-4.0

I'll add some words about RegexConfig.txt, but if I remember, it may be compatible with previous versions, but I'm not sure. Anyway, I don't recommend using any config files from previous versions, several incompatible changes were done.
