### ISSUE TITLE
Simplify Configuration Profiles

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#120]
Although the current way profiles files are organized is simple, containing all configuration files in each profile folder, changes that affect all profiles require editing many files and can be error prone.

**1.** My suggestion is to **make profiles "hierarchical"**. 
The default profile would store all configurations. Other profiles would contain only options that were overridden (i.e. are different from the default). 
For properties files (the most common), this could be at entry level (i.e. only entries that changed from the default profile would need to be added). For other files (plain test, XML), the whole file would need to be added if any change was made).
This would also allow easier creation of new configurations (for developers) and easier identification of what changes from one profile to another (for users).

**2.** A minor (independent, but related to profiles) suggestion:
Currently there is one default profile (English) stored in the root folder. Is this necessary? 

My suggestion is to **keep all profiles inside the "/profiles"** subfolder, organized by language, to avoid confusion. 
Only the LocalConfig.txt would be in the root folder.
```
IPEDConfig.txt |--- move from root ----+
/conf          |                       | 
                                       |  
/profiles                              | 
    /en                                |
        /default <------ to here ------+ 
        /profile1
        /profileN
    /lang2
        /default
        /profile1
        /profileN
```

**Comment by lfcnassif** [comment]
1. Totally agree, that was already suggested by some users. It will make dev updates easier and make differences more clear, as you noted.

2. I thought doing that in 3.17 version, but was concerned about old users becoming confused, they expect a config file in root folder. Actually, things became easier for english users and harder for portuguese ones. It will break some third party processing interfaces too...

**Comment by tc-wleite** [comment]
1. I will try to implement that change. Probably as soon as you close the current release would be a good time, right? 

2. OK. I think it can be a bit confusing for new users too. About the third party tools, yes, but if they already handle profiles subfolders (and they need to do that for using Portuguese, right?), I guess the impact would be minor.

**Comment by lfcnassif** [comment]
After #18 the default profile can be moved to root folder again, what do you think @tc-wleite?

About 1, is it possible to identify a property file with no false positives without using some name pattern like *.properties.txt?

**Comment by tc-wleite** [comment]
> After #18 the default profile can be moved to root folder again, what do you think @tc-wleite?

Definitely! 

> About 1, is it possible to identify a property file with no false positives without using some name pattern like *.properties.txt?

Do you mean programmatically or by the user?

Programmatically, probably yes, but where would we use this?
The current code explicitly reads properties, so it is aware about it.
My idea was to write in a centralized class the code to merge the properties (when a profile is used), so it would be transparent to the rest of the code that reads properties (and any other configuration file).

For the user, I see that "KeywordsToExport.txt" are a TXT file but not properties file, right?
Not sure if it is the only case.
For this particular file, it doesn't make sense to merge its content, right?
So if it is present in a profile, it (the whole file) would override the default configuration.
Perhaps changing its extension would make things more clear (so all TXT would be properties).

**Comment by lfcnassif** [comment]
Programmatically. My thoughts:

Current code copies early the specific profile confs to case folder and the modules read them from there. Each module knows what it is reading (property files or other thing), but the early profile handling code currently not. To be transparent and not change all the modules (I also desire this), I **think** the profile handling code should identify what is a property file or not.

But I plan to implement #24 for version 4.0.0 soon. To be easy for users to start an additional processing, #23 will be needed. And I think each task could have an optional UI configuration to be called, implementing some interface. So, maybe, the task modules configuration will need to be refactored anyway...

**Comment by tc-wleite** [comment]
I see. Well, I guess it is possible to identify properties files. Maybe not covering all generic cases, but good enough for most situations (and for the actual configuration files, of course). 
I agree that no changes in existing tasks code would be better, but maybe a revision (perhaps using a more concise/standardized way to get configurations in some cases) could be done.

**Comment by lfcnassif** [comment]
hey @tc-wleite I will take a look at this from now

**Comment by lfcnassif** [comment]
Just pushed an initial version for this, will test more tomorrow. But I realized that if user changes default profile, all others would be affected, maybe unintentionally, even fastmode or triage. So, at least in fastmode, I kept all configs disabled to protect againt this. Not sure if something should be done for other profiles...

**Comment by lfcnassif** [comment]
PS: Analysis app is not working yet...

**Comment by tc-wleite** [comment]
> Just pushed an initial version for this, will test more tomorrow. But I realized that if user changes default profile, all others would be affected, maybe unintentionally, even fastmode or triage. So, at least in fastmode, I kept all configs disabled to protect againt this. Not sure if something should be done for other profiles...

That is a good question!
It seems reasonable to "protect" fastmode and triage profiles, so tasks that should be disabled in these profiles remain disabled. 
In this new way of handling profiles, the user must be aware that changing the default profile will likely affect other profiles. So it would make more sense creating a new profile and overwrite just a few options (instead of directly changing the default), if it is not intended to be a "global" setting.
In a future UI, these situations could be explicitly shown: 
- If there are other profiles that inherit a certain configuration, in the default profile.
- If a value is absent (and are using default config) in a specific profile.

**Comment by lfcnassif** [comment]
@tc-wleite because changes in default profile will affect others, I'm not sure if default profile should be moved to root folder again, possibly encouraging users to change it, what do you think?

**Comment by tc-wleite** [comment]
> @tc-wleite because changes in default profile will affect others, I'm not sure if default profile should be moved to root folder again, possibly encouraging users to change it, what do you think?

I think both ways are fine.
For many parameters, changing all profiles makes more sense. But it is not the case for others (which is the whole idea of profiles). So making it more accessible can be positive or negative...
Maybe moving to the root folder would make more clear that it is something "global". 
I would still move it, but as I said, both options seem good.
It would be more a matter of users getting used to this new organization.
For first time users, who are not even aware about profiles, I guess moving to the root would make things slightly easier.

**Comment by lfcnassif** [comment]
> For first time users, who are not even aware about profiles, I guess moving to the root would make things slightly easier.

For sure

> Maybe moving to the root folder would make more clear that it is something "global".

This makes sense. I'll move it back to root.

**Comment by lfcnassif** [comment]
@tc-wleite I merged this. Just a few options needed to be overriden by profiles, I think the general result was good. If you find any problems, please let me know!

**Comment by tc-wleite** [comment]
Great! I will take a look and run some tests this week.
