### ISSUE TITLE
Image blur and gray filters in gallery and image viewer

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1202]
Requested by an user/starting dev, this may help analyzing csam cases.

**Comment by abdalla-mar** [comment]
Image blur filter is a feature well known in CSAM triaging tools. After triaging CSAM, the analist can blur the images and focus on the rest of the analysis without being exposed to explicit content. It also can be used to present a case without exposing the audience to CSAM. A GrayScale filter is also interesting. Studies demonstrate that triaging CSAM in grayscale reduces the impact over the analist.

**Comment by lfcnassif** [comment]
I'm reopening this, since Ctrl+F and Ctrl+G were already used by HexViewer (for 'Find' and 'GoTo' actions) and stopped to work there. What other shortcut keys should we use for Blur and Gray filters?

**Comment by lfcnassif** [comment]
> What other shortcut keys should we use for Blur and Gray filters?

Other option instead of changing shortcut keys, would be to make them specific to some panels (gallery and viewer) and not global anymore.
