### ISSUE TITLE
Fixes the content type in the elasticsearch index

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#1216]
The index field content should have a fixed type, as it is a well known field. When leave to the automatic detection it creates a keyword value that is not necessary for the content field. Another advantage is that it can be set to index with term vectors which allows the use of fast vector highlighter.

**Comment by hauck-jvsh** [comment]
> This could make the index much bigger, I think we should do some tests to measure the impact on index size before making this change.
For sure, I will make some test to see the impact

**Comment by lfcnassif** [comment]
I think the `offsets` in `with_positions_offsets` also has another index size impact independent of `term_vectors`. Is that needed?

**Comment by hauck-jvsh** [comment]
Unfortunately, for using the  fast vector highlighter the documentation says it is needed. So I vote for using with_positions_offsets or nothing, or may be this can be a parameter in the elasticsearch config file.

**Comment by lfcnassif** [comment]
I see, into lucene that could be set independently...

> may be this can be a parameter in the elasticsearch config file.

This is a good option!

> For sure, I will make some test to see the impact

This would still be very useful to support the decision.
