### ISSUE TITLE
"Error appending to graph database" --append mode

### ISSUE THREAD

**Issue by milcent-CVM** [sepinf-inc/IPED#1219]
When trying to increment, for the second time (third processing) to indexed texts, I got the error below:
`[ERROR]	[gpinf.indexer.IndexFiles]			Processing Error: Error appending to graph database, currently it can't be in use!`
A part from `--append`, I need to index in `--portable` mode, so users can copy the indexed material to their machines.
I was on a Windows 10 VM, with IPED 3.18.6, the same circumstances in which the previous processings were carried out.
At least for now, I don't need the graph database for the indexed material, since they are just case law text files, and not e-mail or other kind of messages.
I'm attaching the log file for reference.
Thanks in advance.

**Comment by milcent-CVM** [comment]
Log file content:

[IPED-2022-07-11-16-43-12.log](https://github.com/sepinf-inc/IPED/files/9093726/IPED-2022-07-11-16-43-12.log)

**Comment by milcent-CVM** [comment]
How can I disable the graph feature?
The material is not too big, bu t the other time we tried to to everything from scratch, we could not import the bookmark file, which is also as important feature for us. If you have any tips on doing this, I'd appreciate it.

**Comment by lfcnassif** [comment]
> How can I disable the graph feature? Also, the material is not too big, but the other time we tried to do everything from scratch, we could not import the bookmark file, which is also an important feature for us. If you have any tips on doing this, I'd appreciate it.

In IPEDConfig.txt file inside the language/profile you are using.

> we could not import the bookmark file

Unfortunately, it is not supported today. We have an open request for that: #918. If you or someone of your team could help with that, it would be very welcomed, I have other things in my current roadmap...
