### ISSUE TITLE
Index dates/timestamps as Long Points instead of String Fields

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1222]
From Lucene TermRangeQuery documentation:
`NOTE: TermRangeQuery performs significantly slower than point-based ranges as it needs to visit all terms that match the range and merges their matches.
`

I was aware about that, but date range queries was very fast when done from the UI search box.

But **maybe** #306 could benefit from that when counting items/events per different time frames/slots.

Possibly manual date range queries written in the search box would stop to work as they work today, not sure if it is possible to do some query conversion behind the scene.

This is a breaking change...

@patrickdalla do you are using TermRangeQuery queries in your PR #1193 ?

**Comment by lfcnassif** [comment]
> @patrickdalla do you are using TermRangeQuery queries in your PR #1193 ?

I just took a quick look and didn't find any usage, right?

**Comment by lfcnassif** [comment]
Anyway, if you are performing heavy date strings manipulation, maybe handling longs instead could make things faster...

**Comment by lfcnassif** [comment]
> This is a breaking change...

We should decide if this path is worth/will be taken before the final 4.0.0 release. I think I fixed all known bugs specific to 4.0.0-beta.

**Comment by patrickdalla** [comment]
I think it is worth. I don't use any range query when counting values. But
surely it will have some performance improvement.
And once it presents enough eficiency, it can be used in some cases.
I was thinking in implementing some range search to load first the visible
part of the timeline, and later some edges ranges to cache information to
zoom out or pan operations.
Maybe I can help with this issue after my return from vacation. Including
the correct query text transformation.


Em ter., 12 de jul. de 2022 20:19, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by lfcnassif** [comment]
Hi @patrickdalla, thanks for answering. But are you doing heavy/repeated string manipulation?

Fellow devs, what about scheduling this breaking change for 4.1 together with #306? Multicases and --append won't work when mixing 4.0/4.1 versions. Is it a bad problem or is it acceptable?

I would like to release a (more) stable 4.0.0-final tomorrow or on Thursday before I travel on vacation again. If this needs to be into 4.0.0-final, I think I won't have enough time and 4.0.0-final would be delayed until mid August...

**Comment by lfcnassif** [comment]
My vote is to implement this into 4.1

**Comment by fmpfeifer** [comment]
I think it is better to let this for 4.1. It will change something sensitive, and it's good to have some time to test it.

**Comment by lfcnassif** [comment]
> I think it is better to let this for 4.1. It will change something sensitive, and it's good to have some time to test it.

Agreed, thanks for your opinion!

**Comment by patrickdalla** [comment]
Look at the Taxonomy section of this link:
https://norconex.com/facets-with-lucene/

It seems we can implement something like this for dates instead of paths.
And seems simples. I will test the performance improvement of using this
technique.

Il giorno mer 13 lug 2022 alle ore 08:18 Luis Filipe Nassif <
***@***.***> ha scritto:

**Comment by patrickdalla** [comment]
no problem in let this feature to next release.

Well, the string manipulation that is made is parsing these string formated
dates. Maybe it is not so relevant in performance. But is a work that could
be done at index time.



Em ter., 12 de jul. de 2022 21:41, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by lfcnassif** [comment]
> the string manipulation that is made is parsing these string formated dates. Maybe it is not so relevant in performance

I still plan to profile this.

**Comment by lfcnassif** [comment]
After some optimizations I pushed to #1193, parsing String values to Date is faster:
![image](https://user-images.githubusercontent.com/7276994/197666774-9bd443ca-a80a-4c27-aeff-1d7d431058fe.png)

In a 2.2M items case, it is taking just 4.597s from a total of 80s to generate all Date interval caches. So I'll close this for now, we can reopen in the future when we decide to implement breaking changes.
