### ISSUE TITLE
Improvement suggestion: Export WhatsApp Chat to Excel or CSV format.

### ISSUE THREAD

**Issue by wedersonrsouza** [sepinf-inc/IPED#1228]
Hello Guys,

It would be very useful for the daily life of the analyst police that IPED allows the export of the chat to a tabulated format, either Excel or even CSV. It would greatly facilitate the preparation of the analysis report.

**Comment by lfcnassif** [comment]
Wouldn't it be enough if you go to "Instant Messages" category, where each single message is shown as a separate item into the table view, filter by the sender/receipt of interest and then export the messages shown in the table to CSV using the context menu?

**Comment by lfcnassif** [comment]
I'm closing this. If the suggested approach doesn't work for you, please reopen and provide details why it doesn't work.
