### ISSUE TITLE
Automatic transcriptions in game audios and other app music audios.

### ISSUE THREAD

**Issue by wedersonrsouza** [sepinf-inc/IPED#1230]
Automatic transcriptions are running on absolutely all audio files found, including game and music audio files (mp3). One suggestion would be to allow users to choose the file extensions they would like to transcribe. For example, I would like only OPUS audios to be transcribed.

In my test, hours were spent transcribing the audios of the GTA game, tsc.. tsc.. tsc..

**Comment by lfcnassif** [comment]
This is already possible, please take a look at `mimesToProcess` option in `conf/AudioTranscriptConfig.txt`. You can specify for example:
mimesToProcess = audio/opus; audio/aac

**Comment by wedersonrsouza** [comment]
Thanks.
