### ISSUE TITLE
Link files (application/x-lnk) are being parsed by RawStringParser instead of LNKShortcutParser

### ISSUE THREAD

**Issue by hugohmk** [sepinf-inc/IPED#1255]
This behaviour was detected in version "4.0.1". In version "3.18.14", link files were previously being parsed by LNKShortcutParser.

**Comment by lfcnassif** [comment]
Thanks for reporting, I was able to reproduce.

This is caused by a misconfiguration in ParserConfig.xml files pointing to a wrong package name, possibly introduced when the package structure was refactored...

**Comment by lfcnassif** [comment]
I even wrote a separate program trying to instantiate all listed parsers in ParserConfig.xml to warn if some was not found, to catch issues like this, because Tika doesn't warn if some parser is not found. Unfortunately, this one missed the check.

Pushing the fix.
