### ISSUE TITLE
Makes Google and Wav2Vec2 audio transcription not dependent of FFmpeg anymore

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1267]
Ffmpeg is used to break audios longer than 1min and must be set on PATH explicitly by user. Maybe we can use the already embedded mplayer to break large audios, removing that external  dependency.

If anyone already knows the mplayer command for that, please let me know.

**Comment by lfcnassif** [comment]
I wasn't able to find a mplayer option to split audios. Closing.

If anyone knows how, please let me know.

**Comment by tc-wleite** [comment]
I am going to take a look and see if I find a way to use MPlayer instead of FFmpeg.

**Comment by lfcnassif** [comment]
Thank you @tc-wleite for looking into this! I searched for an option for that in mplayer manual 2 times in the past, but didn't find an obvious option for that...

**Comment by lfcnassif** [comment]
Some time ago I thought about breaking WAV files manually. I think splitting the raw audio data would be easy since we always convert to 16Khz 16 bits per sample little endian. But possibly a header with some WAV metadata would need to be added to each chunk, not sure...

**Comment by lfcnassif** [comment]
Yes, there is a WAV header, not that hard, but not trivial. There are several fonts about it:
- https://isip.piconepress.com/projects/speech/software/tutorials/production/fundamentals/v1.0/section_02/s02_01_p05.html#:~:text=The%20WAV%20audio%20format%20was,quality%2016%2Dbit%20audio%20format.
- http://soundfile.sapp.org/doc/WaveFormat/
- https://www.mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/WAVE.html

Of course if mplayer is able to do the job, it would be great.

**Comment by tc-wleite** [comment]
Ok, I think I found a simple solution, using only Java code.
I tested a standalone program with a few audios, and it seems to work fine.
Unfortunately my work PC is down because of building maintenance there, so I will be able to integrate to IPED and run proper tests next week.

**Comment by tc-wleite** [comment]
In case you want to check the idea, here is the standalone program:

```java
import java.io.*;
import javax.sound.sampled.*;

public class WavSplit {
    public static void main(String[] args) throws Exception {
        int partDurationInSeconds = 60;
        AudioInputStream ais = AudioSystem.getAudioInputStream(new File("in.wav"));
        int bytesPerFrame = ais.getFormat().getFrameSize();
        int framesPerPart = Math.round(ais.getFormat().getFrameRate() * partDurationInSeconds);
        byte[] partBytes = new byte[framesPerPart * bytesPerFrame];
        int numBytesRead = 0;
        int seq = 0;
        while ((numBytesRead = ais.readNBytes(partBytes, 0, partBytes.length)) > 0) {
            ByteArrayInputStream bais = new ByteArrayInputStream(partBytes, 0, numBytesRead);
            AudioInputStream audioInputStream = new AudioInputStream(bais, ais.getFormat(), numBytesRead);
            AudioSystem.write(audioInputStream, AudioFileFormat.Type.WAVE, new File(String.format("out-%03d.wav", ++seq)));
            audioInputStream.close();
        }
        ais.close();
    }
}

```

**Comment by tc-wleite** [comment]
By the way, I found a solution with MPlayer to extract a part of the audio (e.g. cut from the beginning until 60s), but that would require multiple calls to achieve what we are looking for.

**Comment by lfcnassif** [comment]
> In case someone wants to check the idea, here is the standalone program:
> 
> ```java
> import java.io.*;
> import javax.sound.sampled.*;
> 
> public class WavSplit {
>     public static void main(String[] args) throws Exception {
>         int partDurationInSeconds = 60;
>         AudioInputStream ais = AudioSystem.getAudioInputStream(new File("in.wav"));
>         int bytesPerFrame = ais.getFormat().getFrameSize();
>         int framesPerPart = Math.round(ais.getFormat().getFrameRate() * partDurationInSeconds);
>         byte[] partBytes = new byte[framesPerPart * bytesPerFrame];
>         int numBytesRead = 0;
>         int seq = 0;
>         while ((numBytesRead = ais.readNBytes(partBytes, 0, partBytes.length)) > 0) {
>             ByteArrayInputStream bais = new ByteArrayInputStream(partBytes, 0, numBytesRead);
>             AudioInputStream audioInputStream = new AudioInputStream(bais, ais.getFormat(), numBytesRead);
>             AudioSystem.write(audioInputStream, AudioFileFormat.Type.WAVE, new File(String.format("out-%03d.wav", ++seq)));
>             audioInputStream.close();
>         }
>         ais.close();
>     }
> }
> ```

Great! Thank you @tc-wleite! I java only solution is much better!!!

**Comment by lfcnassif** [comment]
Code above seems to work fine with a few WAVs I tested here. Headers are properly created in front of each part, with same values, except those related to data size, of course. There are a few WAVs here where byte 16 changed from 0x12 to 0x10, which is good, i.e., the audio was converted to PCM, what is needed by us.

**Comment by rafael844** [comment]
Once I asked in the MPlayer forum and the aswer was:

>  With  -ao pcm I could create wav files, but  dont know the parameters so I could split It. Could you give me an example?
Again, I recommend a tool designed for it, there are quite a few (audacity among others).
But you can use -ss and -endpos to set start and end.
However these values will not be exact, so the files will only be split very approximately and may both overlap or parts might be missing.
If that is not good enough, as said use a tool designed specifically for this.
