### ISSUE TITLE
Option to create thumbs for videos to be shown in the gallery

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#127]
Currently, the thumbnail used in the gallery for videos is the same image displayed in the visualization panel, containing all extracted frames (**1st** screenshot).
In my opinion, this makes the gallery less useful for videos than if less frames were displayed. 
Other IPED users that I talked to had this same impression while working in cases that required visually finding very specific videos in a large unorganized collection.   

Of course, this is a personal view, so my suggestion is to create an **option** to use only a limited number of frames. 
Disabling this option, no thumbnail will be generated, and the full image will be used in the gallery (i.e. it would keep the exactly same behavior we have now) .

With this option (an entry in VideoThumbsConfig.txt file), it would be possible to set a range (minimum and maximum) number of frames to be used, and the VideoThumbTask would pick the number of frames that maximizes the usage of the thumbnail area (similar to what was recently implemented in the visualization area, but during processing time, not dynamically).

Running some tests, my suggestion of default configuration is to use the range [2,3], based on a large sample of videos, with a variety of aspect ratios.
With the proposed default configuration (**2nd** screenshot), there would be at least 2 and at most 3 frames. Note that for portrait videos, it can use 2 or 3 columns and a single row, and the opposite for landscape ones.

It would also be possible to set the range of frames to [1,1], which would make a single frame be used as the video thumbnail (as many programs use in their visualization galleries). (**3rd** screenshot)

Current
![image](https://user-images.githubusercontent.com/7217001/84203812-74c7ac00-aa80-11ea-90a4-19f16ab412f9.png)

Proposed Default Configuration (2,3)
![image](https://user-images.githubusercontent.com/7217001/84203879-8e68f380-aa80-11ea-8ce5-1bac4999c0e7.png)

Another Possible Configuration (1,1)
![image](https://user-images.githubusercontent.com/7217001/84203904-9fb20000-aa80-11ea-9a42-8d51b3acc29d.png)

**Comment by lfcnassif** [comment]
Although currently users can increase thumb size in gallery to see details of video frames (decreasing the number of videos simultaneously displayed), keeping confidence about video content with more frames, this is very useful @tc-wleite!

What do you think about a dynamic option like that one you recently develop for video viewer? I think an option in gui will be better noticed by users than an option in an advanced config file. Or have you already tested that and it became slow because the number of video frames to be adjusted at the same time?

**Comment by tc-wleite** [comment]
The problem with the dynamic generation is the performance. Each example screenshot displays 36 thumbs at time. I see many IPED users with two monitors using one of them for the thumbnail gallery. So we can easily have 100+ thumbs. 

The implemented dynamic layout feature was relatively fast in my tests: ~30 ms/video in my PC and ~90 ms/video in my laptop, which seems perfectly acceptable for a single video, but would be too slow for many of them (even with multi-threading). 

Anyway, as I said, this is very personal. There are users here who don't even use the gallery for videos as it is today (they prefer viewing the full image with extracted frames of each video in the visualization panel and navigating though the items table).

@lfcnassif, feel free to set the default behavior to the current behavior and leave this feature as an option. 
I did talk to other forensic experts and analysts here about this in the past, and they chose the proposed configuration as the default (and that is why I am suggesting it after all). But obviously it wasn't a statistically significant sample.

**Comment by lfcnassif** [comment]
For sure, let's integrate! The default can be changed later, after more feedback.

**Comment by tc-wleite** [comment]
Thinking a bit more about this, keeping the current behavior as the default makes sense as it seems to be the preferred option for most users. 
On the other hand, many users will never be aware that this option (using less frames) is even available, right?!

So, one last suggestion: 
To enable video thumb generation as default (in the configuration files). 
In the application, there would be an action button (in the gallery title bar), to toggle video thumbnails frames configuration between “Complete” and “Reduced”. 
The default would be “Complete”, so it would keep the current behavior, but with a visible button, it would be easier to users learn about this feature.
It won't be as flexible as a actual dynamic solution, but at least would allow alternating between two possible configurations, with no peformance overhead.

**Comment by lfcnassif** [comment]
Perfect! Completely agree!

**Comment by lfcnassif** [comment]
Merged, thank you, Wladimir!
