### ISSUE TITLE
HexViewerPlus Search hexadecimals big terms

### ISSUE THREAD

**Issue by gfd2020** [sepinf-inc/IPED#1290]
Bug: Hexadecimal search does not work if term is greater than MAX LONG.
Example: 14996C6E701401B413AF91A0067709BC

PS: I know the problem. I will fix this.

**Comment by lfcnassif** [comment]
Thank you @gfd2020

**Comment by lfcnassif** [comment]
Just reproduced this, tagging as bug.

**Comment by gfd2020** [comment]
I fix this bug on hexviewerplus-jdk11-fix branch
