### ISSUE TITLE
Continuous navigation with left/right arrows in the gallery

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1300]
A minor usability enhacement. 

When using the gallery to view a large amount of files, sometimes I find a group of thumbnails that may be important, but I need to take a closer look, selecting one of them to view its full content in the visualizer. 
In some situations, I want to continue viewing other files, so I use the right arrow to move to the next item. 
At the end of a gallery row, I need to either use the mouse to click on the first thumb of the next row, or use the down arrow and then use the left key to cover the next row in the opposite directions. 
Both options are not very convenient.

My suggestion is to automatically move to the next row, when using the right arrow (and the opposite when using the left arrow). 
So with a single key it would be possible to navigate through many gallery items.

**Comment by lfcnassif** [comment]
Agreed!

**Comment by lfcnassif** [comment]
Closed by #1301.

**Comment by lfcnassif** [comment]
@tc-wleite I just pushed above commit to make keyboard selection with shift down also continuous, it seems to be working fine.

**Comment by tc-wleite** [comment]
Great @lfcnassif! I will take a look in the afternoon.

**Comment by tc-wleite** [comment]
> @tc-wleite I just pushed above commit to make keyboard selection with shift down also continuous, it seems to be working fine.

Just tested it here and it worked fine. 
And it is better to have the same behavior, either if the right is pressed or not.

**Comment by lfcnassif** [comment]
Thanks for testing!
