### ISSUE TITLE
Huge files parsing

### ISSUE THREAD

**Issue by MariasStory** [sepinf-inc/IPED#1305]
Hi team,
IPED is a cool tool indeed.
It can search through big amount of data fast, thanks to lucene.
I suggest to make improvements to parsing of huge files several GB and up.
Then, IPED can be used for logs analysis. Fast searching capabilities are very useful in this case.

**Comment by lfcnassif** [comment]
Closing, this is too general and there is no actual suggestion here.

If you would like log file analysis, a custom and specific parser would need to be implemented for each log file format of interest.
