### ISSUE TITLE
Move scripts code from conf folder to root

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1319]
There are many source codes inside `conf` folder, like python or javascript tasks, parsers and regex validators. They should be moved from `conf` folder to somewhere else, like a new `root/scripts` folder

**Comment by lfcnassif** [comment]
@patrickdalla, while refactoring this, I noticed there are 2 implementations of DER file carving, one in java and another in javascript. Which one is the last implementation? I think we should drop the unused one to avoid confusion.

Another thing, inside conf/ParsersCustomConfigs folder there are some xml configuration files mixed with js code. The goal of this ticket is to separate code from configuration. Any recommendation about how to organize those files?

**Comment by patrickdalla** [comment]
On DER carver topic:
- I believe that I have implemented the javascript version to validate the possibility of implementing one carver using this type of language. They do the same task. So, for better performance, I think you can keep the java version.

**Comment by patrickdalla** [comment]
On "conf/ParsersCustomConfigs":
This contains some configuration for the unused RegistryParser. The idea was that the user could create some JS to parse registry values.
You can move "js" to the scripts folder. You could only implement some Script repository interface, if there isn't one, so the Registry Parser can find there the scripts it needs.

**Comment by patrickdalla** [comment]
But as the RegistryParser is not used, you could remove it too.

**Comment by lfcnassif** [comment]
> * I believe that I have implemented the javascript version to validate the possibility of implementing one carver using this type of language. They do the same task. So, for better performance, I think you can keep the java version.

Ok I'll keep the java one. I'm also fixing some bugs and copying additional logic from the JS implementation.

**Comment by lfcnassif** [comment]
> But as the RegistryParser is not used, you could remove it too.

Not sure if I understood, you mean removing RegistryParser and all its configs and scripts?

Currently we use regripper to extract registry info by default, as you know. RegRipper-3.0 has about ~250 plugins. In the past it was not possible to activate 2 parsers for the same file, but it is today. We could enable both parsers if yours extracts info not extracted by regripper yet.

Eventually we could port some of your parser features as regripper plugins. Porting all 250-300 regripper plugins I think is not worth to do.

Another possibility is reusing your code to implement a RegistryViewer, allowing the user to navigate the registry tree (that was my original idea years ago, not reimplementing something like regripper...)

**Comment by patrickdalla** [comment]
"Another possibility is reusing your code to implement a RegistryViewer, allowing the user to navigate the registry tree (that was my original idea years ago, not reimplementing something like regripper...)"

Yes, it can be possible. In fact, if you enable the parser and config it to process all registry keys, it will create this tree integrated in the case tree. But as it create 1 HTML to describe each key, it consumes a lot of disc space. 

I don't know exactly all the features and info regripper extracts (as you have said, are more than 250 pluggins). But this parser extracts each key "last modified" date as a metadata. And the "js" plugins could be used to parse key values as dates or other info. The ares one, for example, converts the search history hexavalue in the corresponding search text used.
