### ISSUE TITLE
Render Vcard photos in html preview

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#133]
Not all vcard photos are rendered in generated vcard html preview. Maybe this is related with html-template. I have a number of vcards with photos correctly extracted by the VCardParser (updated in graph_analysis branch) but they are not printed in html preview, just one of them.

@fmpfeifer as you are already experienced with html-template, if you could take a look, that would be great, if not let me know. I can send you some samples.

**Comment by lfcnassif** [comment]
Just found vcard photos are properly rendered in html chat reports, so seems it is a vcard html-template problem.

**Comment by fmpfeifer** [comment]
Will take a look
