### ISSUE TITLE
Database files that are classified in other categories than databases are showing all table content on HTMLViewer

### ISSUE THREAD

**Issue by patrickdalla** [sepinf-inc/IPED#1332]
Database files that are classified in other categories than databases are showing all table content on HTMLViewer.

In initial debug I detected that they are classified as mime types that are registered with HtmlViewer, and are handled by TikaHtmlViewer that calls the parse method again.

**Comment by patrickdalla** [comment]
Yes.
I commented "viewersRepository.addViewer(new TikaHtmlViewer());" and the resumed HTML appears as expected.

Can I remove the class also? Or only the viewer registration code?

**Comment by lfcnassif** [comment]
I kept it because I thought it could be useful in the future, but this has already confused other contributors. So, please, remove it. It will be in the commit history anyway.
