### ISSUE TITLE
Makes analysis UI to work from an unmounted network path again

### ISSUE THREAD

**Issue by hugohmk** [sepinf-inc/IPED#1336]
This behaviour was detected in version 4.0.4. Mapping the network folder seemed to solve the issue.

**Comment by lfcnassif** [comment]
Although it could happen to work in the past, it was never intentional to work. If you could provide further details (IPED-SearchApp.log, console output when calling java directly, not *.exe), I might take a look.

**Comment by hugohmk** [comment]
Oh sorry, I didn't know that... I get the following exception after calling "iped-search-app.jar" from command line: "java.lang.IllegalArgumentException: URI has an authority component"; the IPED-SearchApp.log file doesn't seem to be created at all in this case.

**Comment by tc-wleite** [comment]
@lfcnassif, this is somewhat important here, as users got used in the last years to open cases directly through a network share (without a letter assigned to it). I will try to check if there is simple solution.

**Comment by lfcnassif** [comment]
Sorry, I was working on other stuff... thanks for taking a look into this.

PS: I would also test graph tab behavior, since neo4j doesn't work if the database is read only (we copy it to a local temp) and doesn't like non absolute paths, maybe it could have issues with unmapped shares too...

**Comment by lfcnassif** [comment]
Closed by #1407

**Comment by aberenguel** [comment]
It would be interesting if this solution could be backported to 4.0.x branch.

**Comment by lfcnassif** [comment]
If a 4.0.7 version is released (not planned originally by me), it could be.
