### ISSUE TITLE
How to change language

### ISSUE THREAD

**Issue by marferre63** [sepinf-inc/IPED#135]
Gostaria de saber como configurar o IPED versão 3.17.2 para que ele fique com o idioma e configurações de data em português. 
Eu vinha rodando com versões anteriores dados obtidos em quebra de sigilo telemático e a ferramenta de consulta ficava em português e as datas no corpo dos e-mails no nosso formato dd/mm/aaaa.
Porém na versão 3.17 a ferramenta fica em inglês e as datas no formato americano mm/dd/aaaa.

**Comment by lfcnassif** [comment]
Just change first option in LocalConfig.txt file.

**Comment by lfcnassif** [comment]
Please note currently we just have a few parsers for cellphone artifacts. Now iped supports dbx, mbox, pst, ost, msg and eml emails.

If you want other formats, you would be better processing them in Cellebrite software and importing the resulting ufdr file.

**Comment by marferre63** [comment]
Nassif,

Thanks for answered.

I've changed the localization/language to pt-BR (locale = pt-BR) but the IPED 3.17.2 don't start. 
I'm using a bat file with this command: 
d:\iped-3.17.2\iped-3.17.2\jre\bin\java -jar d:\iped-3.17.2\iped-3.17.2\iped.jar -Xmx=12GB -d "d:\TesteEmail" -o "d:\e-mail_teste_indexado"

In the 'TesteEmail' directory, I'm using a mbox file to test.

Returning the language to 'en', the IPED start normally.

**Comment by lfcnassif** [comment]
Did you read and follow the instructions printed in terminal when you changed locale to pt-BR?

**Comment by marferre63** [comment]
Thanks again

As I was using a bat file, I couldn't see the instructions about profile directory.

After set the language to pt-BR at LocalConfig.txt, I restored the IPED config files at root directory to the default and modified them at profile directory. With that, the indexing worked well. And the date format is showed as the brazilian.

From now on, I'll use the command line, in order to see the further instruccions, if somethig occour.

**Comment by lfcnassif** [comment]
You're welcome. Yes, important errors are printed to console, I suggest always looking at it.
