### ISSUE TITLE
Add file type icons rendering on more panels

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1356]
I just remembered about parent/children/duplicates/references panels, not updated on https://github.com/sepinf-inc/IPED/pull/1291. We could also render the specific file type icons on them.

**Comment by lfcnassif** [comment]
Good ideia!

**Comment by lfcnassif** [comment]
Reopening, folder icons are missing in gallery.

**Comment by patrickdalla** [comment]
@tc-wleite, my main development workstation is running on Linux, and I thought this feature wasn't yet integrated in master. When I opened the IPED to test the timeline on linux, I was surprised with the ICONS. 
That is: the Icons aren't being rendered on my Linux CentOS SO.

**Comment by patrickdalla** [comment]
@tc-wleite, @lfcnassif I don't know if it should be reopened or a new issue created. So I will let you to decide.

**Comment by lfcnassif** [comment]
> That is: the Icons aren't being rendered on my Linux CentOS SO.

Was some stack trace error printed in UI log?

**Comment by lfcnassif** [comment]
As this wasn't released yet, let's reopen.

**Comment by lfcnassif** [comment]
> Was some stack trace error printed in UI log?

Did you get some stacktrace?

**Comment by patrickdalla** [comment]
no

Em qui., 17 de nov. de 2022 17:20, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by patrickdalla** [comment]
yes, it was the same processed case.

Em qui., 17 de nov. de 2022 18:26, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by lfcnassif** [comment]
This is strange... Unfortunatelly right now I don't have a Linux OS with screen device to test this (all my VMs are corrupted/not starting...) just a headless one I used to test #1420. I would appreciate if you could investigate this.

**Comment by patrickdalla** [comment]
i will test better tomorrow. i started from inside eclipse. maybe it is
using some old compiled resources

Em qui., 17 de nov. de 2022 19:34, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by patrickdalla** [comment]
Hi. Sorry. I detected that it is an issue when running from eclipse debug environment.

the line of code:

CodeSource src = IconManager.class.getProtectionDomain().getCodeSource();

from IconManager returns the class path of the compiled classes currently being debugged instead of the "jar" file. So, the following lines of code does not read any Icon, as it expects a zip(jar) file.
