### ISSUE TITLE
OutOfMemoryError caused by processing queue growing too much

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1358]
Before Python modules were introduced, container expansion used to decide if subitems would be processed immediately in parsing thread or sent to processing queue based on queue size. When python modules were introduced, because of issues with JEP being called from different threads, the logic was changed to always enqueue subitems. The queue was left unbounded, because limiting its size could cause dead locks if all workers were expanding containers at the same time. But an unbouded queue could cause OOME and this was reported now, confirmed after analyzing a heap dump sent by an user.

Python modules were completely refactored in 4.0 and I'll test if the old adaptative logic works without issues. If not, maybe it is possible to process subitems immediately in the worker thread corresponding to the parsing thread using some wait/notify logic.

**Comment by lfcnassif** [comment]
Just saw a comment in ParsingTask code remembering that if items are processed immediately and if externalParsing = true, that could cause a deadlock: we start a fixed number of external parsing processes and if all of them are expanding ZIPs, there will be no external process available to parse the zip subitems immediately, then zip expansion will block... So if externalParsing is enabled, items used to be enqueued since a long ago.

Using an unbounded disk based queue may be a solution, but the Item class would need to be serialized and deserialized, that could bring some performance cost.

**Comment by lfcnassif** [comment]
> Using an unbounded disk based queue may be a solution, but the Item class would need to be serialized and deserialized, that could bring some performance cost.

Temp dir usage could also grow a lot (bad for triage Linux distribution). If someone has a better idea, please let me know.

**Comment by lfcnassif** [comment]
> Temp dir usage could also grow a lot (bad for triage Linux distribution). If someone has a better idea, please let me know.

Actually, this temp dir usage growth won't be an issue with the default Triage profile, since containers expansion and enableExternalParsing are both disabled, so the processing queue will obey its soft max limit of 100K items. So will try the on disk processing queue approach, possibly I'll have to change Item class a bit to make it serializable.

**Comment by patrickdalla** [comment]
I suggest implementing subitens prioritization. So when expansion starts
subitems would be selected first to be processed, avoid also other
containers processing starting.

that maybe is not enough to avoid some concurrent situations, like when
many container processing starts simultaneously. But at least it avoids it
and the queue growth.

To avoid the simultaneous multiple container expansion starting case, some
logic for forcing sequential container expansion processing could be
implemented. That is, when the first container starts expanding, it informs
the "context", or maybe the extractEmbedded method can do this, that a
expansion started. Any other expansion should be reenqueued until the
current expansion ends.

I was doing something similar for the "conditionnotmet" exception idea, and
the reenqueue was working, when I halted because you have suggested an
simpler solution for my necessity.


Em ter., 11 de out. de 2022 17:04, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by lfcnassif** [comment]
Thanks @patrickdalla for your thoughts. I had a similar idea yesterday. Subitems are already prioritized and put into queue head. Maybe the number of simultaneous container expansion could be limited to half the number of parsing threads/processes, re-enqueing other containers like you suggested (maybe on queue tail to try to avoid some re-enqueueing loop). I think sequential container expansion is not needed and might cause some bottleneck if there are lots of containers.

Processing subitems immediately (not enqueueing them) and limiting the number of container expansions could workaround the old dead lock and this unbounded queue growth. Re-enqueueing containers without bound may not be a real issue because the number of containers often is much less than the number of case items. I still need to think a bit more about some corner cases, like lots of containers containing containers...

PS: I did some tests yesterday with the on disk queue and the serialization cost is significant, even using specialized serialization libs, to the point of always having some workers idle. I will play with it a bit more, but actually I don't like this idea and I had to do more changes than I would like to make Item class serializable.

PS2: the case that triggered this OOME has lots of backup ZIPs in the same folder containing whole C:\User folders inside.

**Comment by patrickdalla** [comment]
Maybe keeping subcontainers processing in the same container parent worker
thread can be a solution to the cases of container inside other containers.


Em qua., 12 de out. de 2022 09:13, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by patrickdalla** [comment]
Some thoughts:

- Maybe limiting 1 container parsing at a time does not create such a
considerable bottleneck, as the subitems are processed in other worker
threads. When the container processing ends, it releases the "semaphore" so
other containers can enter in the processing pool even if subitems
processing hasn't finished.
- In fact, you could see such containers as datasources to extract items.
Maybe we could even treat them as datasources, adding them to the case, and
mapping some "mounting point" to the tree path they were found, so subitens
could be shown from this "mounting point". And, AFAIK, the ItemProducer
that reads from datasources to produce and enqueue items runs on a single
thread.
- If we limit 1 container parsing at a time, and parse subcontainers items
on the same thread that started the container, passing non-container
subitens to other worker threads, we could even control the limit of the
queue size, as it would only block this worker thread that is parsing the
container.



Il giorno mer 12 ott 2022 alle ore 12:33 Patrick Bernardina <
***@***.***> ha scritto:

**Comment by patrickdalla** [comment]
Well, thinking better, this semaphore could be a greater permit number than 1. What we would need not to block all the workers, in the case of QUEUE mas length limiting, is at least 1 worker thread processing noncontainers subitems.

**Comment by wladimirleite** [comment]
Just adding some info...
The input evidence is a 7z with ~20,000 EMLs, most with few or no attachments.
All tasks before ParsingTask are executed several times for many items (~150 times for some items). It changes between tests, but on average tasks before ParsingTask processed ~1M items, although the total number of items was around 25K (so 40x, on average).

To minimize this behavior, would it be possible to re-enqueue (in ParsingTask when processing items that are expanded and more than 1/2 of the workers are processing items that are expanded) only if the queue is longer than a certain threshold? Maybe increasing the threshold of workers to (threads-1) if the queue is short.

**Comment by lfcnassif** [comment]
Hi @hugohmk and @wladimirleite!

> @wladimirleite found out that several eml files were being processed multiple times by that task, and pointed out that they were being reenqueued by the ParseTask safeProcess method.

Do you mean EMLX are being re-enqueued, not EML, right? Since just EMLX needs to be re-enqueued to try linking to attachments processed by an earlier queue.

> Maybe setting a minimum size for the container to be reenqueued should reduce this issue a bit, while still avoiding OOME problems. What do you think?

Generally I would need the heap dump to analyze it to be sure what is consuming too much memory and try to fix/improve the true source of the problem. 20K EMLs enqueued shouldn't trigger OOME, millions enqueued could, maybe we are not cleaning some memory resource properly. OOME issues are tricky, some module can eat all available memory slowly and the OOME can be thrown by another well behaved module. Could you send me the OOME heap dump so I can take a look?

> All tasks before ParsingTask are executed several times for many items (~150 times for some items). It changes between tests, but on average tasks before ParsingTask processed ~1M items, although the total number of items was around 25K (so 40x, on average).

I'm not happy with that, but I think most modules being executed duplicated times on the same item just do 1 or a few if checks and return, right?

> To minimize this behavior, would it be possible to re-enqueue (in ParsingTask when processing items that are expanded and more than 1/2 of the workers are processing items that are expanded) only if the queue is longer than a certain threshold? Maybe increasing the threshold of workers to (threads-1) if the queue is short.

Seems reasonable, we can adjust that heuristic. The idea of expanding up to workers/2 containers simultaneously was to mix containers expansion (usually IO bound) with content parsing (usually CPU bound), not sure about the performance impact, just testing...

**Comment by lfcnassif** [comment]
> Do you mean EMLX are being re-enqueued, not EML, right? Since just EMLX needs to be re-enqueued to try linking to attachments processed by an earlier queue.

Sorry, I misinterpreted the situation with an unrelated feature, please forget about the comment above.

**Comment by lfcnassif** [comment]
The observed issue was just HashDBLookUp taking a lot of time, not OOME, right?

Maybe just skipping items with `hashdb` properties set, like other tasks do, would be a workaround?

**Comment by wladimirleite** [comment]
> The observed issue was just HashDBLookUp taking a lot of time, not OOME, right?

Correct!
 
> Maybe just skipping items with `hashdb` properties set, like other tasks do, would be a workaround?

Most of items were not found on the hash database, as they are actual e-mail messages, so there are no "hashdb:*" properties. But maybe some other control could be set to avoid any repeated processing.

**Comment by lfcnassif** [comment]
> Most of items were not found on the hash database

Got it.

> But maybe some other control could be set to avoid any repeated processing.

We have temp (not indexed) attributes that could be used for that, as a workaround. But as I said, I'm also not happy with that repeated module processing behavior, newer modules from contributors may not expect that behavior...

**Comment by lfcnassif** [comment]
Have we fixed above multiple EML processing by HashDBLookupTask? The fix is similar to a recent fix we did for DuplicateTask.

**Comment by wladimirleite** [comment]
> Have we fixed above multiple EML processing by HashDBLookupTask? The fix is similar to a recent fix we did for DuplicateTask.

I don't think so.
I believe that with the changes made in the processing queue order, which also increased the queue length in most cases, the probability of a similar situation discussed in this thread were reduced, but still possible...
It seems a good idea to apply a similar fix implemented recently for the `DuplicateTask`.

**Comment by lfcnassif** [comment]
Maybe a possible approach would be to have container specific queue(s), to avoid re-enqueueing containers multiple times...
