### ISSUE TITLE
Minor UI glitch in similar image search panel

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1365]
I noticed a while ago two really minor glitches in the analysis tool user interface.
They depend on the screen resolution and most users won't even notice them. 
Anyway, I would like to fix them.

**Comment by tc-wleite** [comment]
When a search for similar images is made, the UI presents a small panel with the reference image thumbnail.
The red borders look odd and there is a small part of the image drawn outside the borders.

![similarity-odd-borders](https://user-images.githubusercontent.com/7217001/195451307-c9ada4a9-ef0c-4273-8ae9-b9f3a6ca283a.png)

**Comment by tc-wleite** [comment]
In hexadecimal viewer, depending on the screen resolution and the font size used, the vertical line (between the raw hexadecimal values and the corresponding characters) is drawn in the wrong place.

![hvp](https://user-images.githubusercontent.com/7217001/195452137-4e6cf2b2-05e9-4255-806f-8c102c244092.png)

And for some font sizes, characters are drawn out of place, sometimes overlapping other characters.
![hvp2](https://user-images.githubusercontent.com/7217001/195452259-9fdf4fe5-a468-4f3b-a718-23a7f6530001.png)

**Comment by tc-wleite** [comment]
Unfortunately, the glitches in the hexadecimal viewer are inside library code.
We are using version 0.1.3 of the library, and it seems that the latest stable version is 0.2.1 (or 0.2.0 or 0.2.2).
However, it is not simple to update, as there were major refactors, and many classes and methods were renamed, chagend or even removed.

Testing with two other configurations (different resolution, JRE and SO version), I noticed that font size = 13 produced the best results (less noticable glitches). 
So for now, I will only change the default font size from 14 to 13.

**Comment by lfcnassif** [comment]
> When a search for similar images is made, the UI presents a small panel with the reference image thumbnail. The red borders look odd and there is a small part of the image drawn outside the borders.
> 
> ![similarity-odd-borders](https://user-images.githubusercontent.com/7217001/195451307-c9ada4a9-ef0c-4273-8ae9-b9f3a6ca283a.png)

Hi @tc-wleite, I didn't manage to reproduce this. Are you using a 4K resolution monitor? Or changed some configuration?

**Comment by lfcnassif** [comment]
> They depend on the screen resolution

Just read this, I'll try with some resolutions.

**Comment by tc-wleite** [comment]
> Hi @tc-wleite, I didn't manage to reproduce this. Are you using a 4K resolution monitor? Or changed some configuration?

> Just read this, I'll try with some resolutions.

Yes, it depends on the used resolution (screen dimensions and pixel density).
In my laptop I can't notice the same effect.
I didn't change anything recently, but I guess the behavior is present (in my PC) since we starting using Java 11. There is "some" level of scaling (fonts and other things are a bit larger than in Java 8) in my resolution. 

I would like to point out that the new border painting is more "robust", and it should work better in any resolution.

**Comment by lfcnassif** [comment]
Fixed by #1366
