### ISSUE TITLE
User interface scaling is not working (in some environments)

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1368]
I guess as a side effect of other change, user interface scaling (#900) stopped to work.
The scale factor is simply ignored in the analysis app.
It is still working in the processing UI.

I made a few code changes trying to fix this, but no success so far.

**Comment by tc-wleite** [comment]
> Just a guess, maybe it is related to the 2 phase bootstrap?

That is what I guessed too. Maybe it is related, but looking at the code it seems fine. 
I tried to move the code that sets the scale to other places, but no luck.
Maybe it something else, as processing UI also used 2 phase bootstrap, right?!
Anyway, this is just a minor feature.

**Comment by lfcnassif** [comment]
> Maybe it something else, as processing UI also used 2 phase bootstrap, right?!

yes

**Comment by tc-wleite** [comment]
> @tc-wleite I just tested the analysis UI scaling and it worked on master.  

That is great! It is probably something in my local environment. I will try to figure what is going on...

> Not sure what is happening in your environment, maybe the global config in your user_home/.iped folder is broken?

I thought about this, but I reseted the configuration file, hard coded the setting (in different places), used different JVMs, and none of these attempts helped.

**Comment by tc-wleite** [comment]
I tested last night in my home PC (a fresh IPED 4.0.5 install), and the UI scaling didn't work, neither in the analysis UI nor in the processing UI.

I just asked two colleagues here to test in their machines, and scaling worked in the processing UI, but failed (setting was ignored) in the analysis UI.

That is pretty odd! I couldn't come up with any conclusion so far. I will try to investigate a bit more here...
@lfcnassif, please try to test in another PC next week if you have some time, just to see you can reproduce it.

**Comment by lfcnassif** [comment]
> @lfcnassif, please try to test in another PC next week if you have some time, just to see you can reproduce it.

For sure!

**Comment by lfcnassif** [comment]
> @lfcnassif, please try to test in another PC next week if you have some time, just to see you can reproduce it.

Just reproduced in my notebook. UI scaling still works in my work computer when accessing it remotely using RDP.

**Comment by tc-wleite** [comment]
I guess I found the issue.
Well, at least it seems to be fixed in a couple of machines I tested.

It was something trivial, related to the default Locale.
In my PC, `new DecimalFormat("0.000").format(2)` returns `"2,000"`, and `System.setProperty("sun.java2d.uiScale", "2,000")` does not work (should be `"2.000"`).
It should work if the default Locale is US (or another Locale that uses a period as the decimal separator).

I will submit a PR with the proposed changed.

**Comment by lfcnassif** [comment]
> It should work if the default Locale is US (or another Locale that uses a period as the decimal separator).

That's the case of my work computer!

**Comment by tc-wleite** [comment]
I am not sure, but maybe it was working before because of `Locale.setDefault(Locale.forLanguageTag("en"))` was called before setting `sun.java2d.uiScale`. Now the default locale is set in the static initialization of `LocaleConfig` class, which runs after setting the uiScale.
