### ISSUE TITLE
Search for Vendors and Products Identifiers for Hardware Wallets

### ISSUE THREAD

**Issue by mobab-th** [sepinf-inc/IPED#1371]
Search for Vendors and Products Identifiers for Hardware Wallets used on a system. 
Could Regular Expression search task used for?
See https://github.com/INTERPOL-Innovation-Centre/HardwareWallets_DF_List

**Comment by lfcnassif** [comment]
I think so, but looking at the patterns, I think they could bring tons of false positives, since the Regex Task today runs on every case item, like unknown files, unallocated and slacks. Maybe a specific task to lookup specific places, like registry files and EVT logs, would be better.
