### ISSUE TITLE
Faster WEBP images rendering using a Java ImageIO plugin

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1378]
Similar to #562, but for WEBP images.
I tested this about 1.5 year ago, when Twelve Monkeys library started supporting WEBP format, but the results weren't good, comparing to the external conversion we currently use (ImageMagick).

In the latest releases of the library, it seems that WEBP support has improved a lot.

We already use this library for PSDs, so it will only require one extra jar (specific to WEBP) with 65 KB.

### TESTS

Running a larger test with ~150K WEBP collected from many cases.

 - **Using the ImageIO webp plugin 3.8.3**:

   - **Internal Read**:
      - 104,367 (**65%**) were handled by the ImageIO plugin.
      - Average time to generate the thumbnail for those images was **91 ms**.
      - Average failing time was only 1 ms.
 
   - **External Read**:
      - 49,320 (**31%**) had to be handled by ImageMagick.
      - Average time was **395 ms**.

   - **Fail**:
      - 6,905 (**4%**) images failed in both attempts (seem to be corrupted files, as Windows can't render them too).

- **Without the plugin**:

  - 153.661 images (26 images less than internal+external) 
  - Average time was 362 ms

### CONCLUSION

The plugin is about **4x faster** than the external read currently used, for about **2/3** of the images which it can handle. 
Failing time is low, so it will not add any overhead and will fallback to the external read process when the plugin does not support a particular WEBP.

**Comment by lfcnassif** [comment]
Thank you @tc-wleite! I agree to add the plugin.

Out of curiosity, have you compared some of the thumbnails generated by both approaches to see if they agree? (I know this is a difficult manual task...)

**Comment by tc-wleite** [comment]
> Out of curiosity, have you compared some of the thumbnails generated by both approaches to see if they agree? (I know this is a difficult manual task...)

Yes, I opened both processed cases in the gallery, and made a quick visual comparison. Results seem identical. 
But as you said, this is manual and I covered just a small part of the samples I have.

I will try to run an automatic comparison. This could be useful in other situations.

**Comment by lfcnassif** [comment]
> Yes, I opened both processed cases in the gallery, and made a quick visual comparison. Results seem identical. But as you said, this is manual and I covered just a small part of the samples I have.
> 
> I will try to run an automatic comparison. This could be useful in other situations.

Great! Don't worry, it was just a curiosity, please go ahead with this.

**Comment by tc-wleite** [comment]
I ran the automatic comparison here. 
It compares all thumbs from two cases and outputs the "top" N hashes, with the largest pixel-to-pixel differences.
I paste this list of hashes in both cases, and then it is much easier to visually compare the smaller subset.

Anyway, results are very similar.
The visible differences affect less than 0.1% of the WEBPs and have two main causes:

- In some cases the external conversion adds an "extra black border", which is not visible opening the file externally (with Google Chrome), so it seems the ImageIO plugin is better in such cases.

- In other cases, the internal conversion produces a slightly darker image. Image content is still quite visible, so it is not an issue, but in such cases the image produced by ImageMagick seems more similar to what I get opening the file externally.

As we need to upgrade the common libraries used by TwelveMonkeys plugin from 3.7.0 to 3.8.3, this will affect PSD images (currently the only type handle by these plugins).
So I will run a similar test with PSDs, to check performance, success rate and compare visual results, to be sure it won't mess PSD support.

**Comment by tc-wleite** [comment]
Well, I am glad I tested with PSD files...

Updating **PSD** plugin from 3.7.0 to **3.8.3** made thumbnail generation process ~2.5x slower and the number of fails (files not handled by the "internal read") increased by about 5%.

Testing with **3.8.2**, **PSD** results are fine (similar speed and slightly better results comparing to 3.7.0), but WEBP started to have a dangerous kind of fail (about 10% of the files seem to succeed, but the produced thumbnail is completely black).

Mixing **3.7.0 (PSD)** and **3.8.3 (WEBP)** does not work.

Fortunately, using **3.8.2** (for **PSD**) and **3.8.3** (**WEBP**) worked fine.
I will submit a PR changing the POM file with these versions.

When new versions of the plugins are released, I will repeat the tests, so hopefully we can use the same version for both image types in the future.

**Comment by lfcnassif** [comment]
Thank you very much @tc-wleite for all your tests!

Updating dependencies, even with binary compatibilities, is not an easy task as many could think... Particularly, updating Tika is always a nightmare, as it brings hundreds of dependencies together...

**Comment by tc-wleite** [comment]
> Updating dependencies, even with binary compatibilities, is not an easy task as many could think...

That is true! Even this PR, which is trivial, had some pitfalls, and it was related to a library with a very specific usage in IPED project, without dependencies to other libraries.

**Comment by lfcnassif** [comment]
Closed by #1380.
