### ISSUE TITLE
Error indexing internal dates with english locale

### ISSUE THREAD

**Issue by thmme** [sepinf-inc/IPED#138]
Dear All, 

Could you help me please about an error for processing  .pst files as follow: 

Note: I used the Forensic profile

Error: 

2020-06-14 23:21:30     [ERROR] [indexer.parsers.OutlookPSTParser]
        Extraction of emails was interrupted on PST\archive1 (2).pst java.lang.I
nterruptedException: PSTParser interrupted.
2020-06-14 23:21:30     [ERROR] [indexer.parsers.OutlookPSTParser]
        Extraction of emails was interrupted on PST\outlook.pst java.lang.Interr
uptedException: PSTParser interrupted.
2020-06-14 23:21:30     [ERROR] [gpinf.indexer.IndexFiles]
Processing Error:

Regards,

TM

**Comment by lfcnassif** [comment]
Please post at least the full stacktrace after the "Processing Error:" message and inform the version used or send the full log.

**Comment by thmme** [comment]
Dear Luis, 

You can find attached the log file about the error

[IPED-2020-06-15-12-08-28.log](https://github.com/sepinf-inc/IPED/files/4781247/IPED-2020-06-15-12-08-28.log)


Regards,

TM

**Comment by lfcnassif** [comment]
hum it's a bug. Seems like it tried to store more than one value in a 'created' property, previously identified as single valued. Please, check in Outlook if the email "outlook.pst>>Início de Pastas Particulares/Itens Excluídos/Re: Cotação" has attachments. If yes and if you could send the attachments to me privatelly at lfcnassif@gmail.com, that should help a lot to identify the cause and fix it.

**Comment by lfcnassif** [comment]
hum it's a bug. Seems like it tried to store more than one value in a 'created' property, previously identified as single valued. Please, check in Outlook if the email "outlook.pst>>Início de Pastas Particulares/Itens Excluídos/Re: Cotação" has attachments. If yes and if you could send the attachments to me privately at lfcnassif@gmail.com, that should help a lot to reproduce, identify the cause and fix it.

**Comment by lfcnassif** [comment]
I took a look at the code and could imagine a cause for this. Please, try to change locale to 'pt-BR' in LocalConfig.txt file and try to run again. Let me know the result.

**Comment by thmme** [comment]
I will try it and let you know.

Tks!!

**Comment by thmme** [comment]
Hi Luis, 

I changed the Language from english to Portuguese and the processing worked well. 

In additional, after the processing I tried to change the language for english in the folder "indexador\localConfig.txt, but wasn't possible (the IPED openned, but didn't charged the content). Do you know how I can change the laguage after the processing? 

Tks!!

**Comment by lfcnassif** [comment]
Thanks @thmme for the feedback. So, the issue is that you have some file with an internal 'created' metadata property (like exif, but not exif) and that is conflicting with basic 'created' file system date. In portuguese this doesn't happen because 'created' FS date is indexed as 'criacao'. Will fix inserting a prefix for extra property that could conflict.

Unfortunately, for now, you must not change locale after processing. See #18

**Comment by lfcnassif** [comment]
seems like this was introduced in 3.17.2 when internal metadata dates began to be properly indexed.
