### ISSUE TITLE
Render ICO files

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1383]
Currently ICO files (image/vnd.microsoft.icon) are not rendered, neither by the "internal read" (no ImageIO plugin support) nor by the "external read" (ImageMagick does support icons, but the way we call it does work for such files).

Icon files are not usually forensically important, but rendering them if possible would be nice.

Fixing the "external read" would be a possible solution, but it is kind of tricky, and after a few tests, it seems hard to find a simple solution. 
I propose using the TwelveMonkeys plugin, so the "internal read" can handle these files.

**Comment by lfcnassif** [comment]
> I propose using the TwelveMonkeys plugin, so the "internal read" can handle these files.

Agreed!
