### ISSUE TITLE
Unneeded network dependency slowing down application start up

### ISSUE THREAD

**Issue by patrickdalla** [sepinf-inc/IPED#1387]
Some tika parsers try to access info from network. When there is no network the Index still works, but only after a long wait for communication timeout.

This was the case at least for SentimentAnalysisParser, but it can be occurring with other code. Maybe there sould be some parameter to disable long timeout wait for any code that depends on information from the web.

**Comment by lfcnassif** [comment]
We enable/disable Tika parsers explicitly on conf/ParserConfig.xml and SentimentAnalysisParser is not enabled there. Are you sure it is running? A thread dump would help.

**Comment by patrickdalla** [comment]
It doesn't seem to pause on item parsing, but on the startup/configuration
of tika. It registers in iped log a message that the model used by
SentimentAnalysisParser is at a github URL, and after timeout, that it
failed to load the model.


Em seg., 17 de out. de 2022 13:48, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by patrickdalla** [comment]
When I configured a working proxy, iped still logs the
SetimentAnalysisParser model loading error, but without long timeout pause.

Em seg., 17 de out. de 2022 14:32, Patrick Bernardina <
***@***.***> escreveu:

**Comment by lfcnassif** [comment]
> but on the startup/configuration of tika. It registers in iped log a message that the model used by SentimentAnalysisParser is at a github URL, and after timeout, that it failed to load the model.

This seems a Tika issue to me. If the parser is disabled, it shouldn't try to download models, or anything else...

**Comment by lfcnassif** [comment]
If we find out how to fix this into Tika, we can send a PR to them.

**Comment by tc-wleite** [comment]
I observed the same behavior described by @patrickdalla.

@lfcnassif, not sure if makes sense, but I **think** that when `SignatureTask` is initialized, the parsers config used by IPED (ParserConfig.xml) was not informed to TIKA, so a default configuration is used (which includes `SentimentAnalysisParser`).
I made a quick test, changing `Worker` class to initialize `ParsingTask` before other tasks (in the line below), and I am not getting any `SentimentAnalysisParser` messages/delay.

here: https://github.com/sepinf-inc/IPED/blob/e1b235b96f07749985f15c8fd5892637988c1dbe/iped-engine/src/main/java/iped/engine/core/Worker.java#L104),

**Comment by lfcnassif** [comment]
> @lfcnassif, not sure if makes sense, but I **think** that when `SignatureTask` is initialized, the parsers config used by IPED (ParserConfig.xml) was not informed to TIKA, so a default configuration is used (which includes `SentimentAnalysisParser`).

Makes sense! I will try another approach to initialize SignatureTask internal detector in a lazy way (like done in other places), so when loaded, ParsingTask should have already set Tika parser config.

**Comment by lfcnassif** [comment]
@patrickdalla please check if fix above also fixes your slow initialization issue, thanks.
