### ISSUE TITLE
Items with "thumbsOnly" option, doesn't display properly in the generated report.

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1409]
### Description 

When the option "thumbsOnly" is used for one or more bookmarks in the report generation, the items won't display properly when the report is open - Metadata and Text views are empty.
This is a somewhat critical issue, as if you use "thumbsOnly", it is important to have access to item properties, through metadata viewer.

### Versions

I got this issue working in a real case, using 4.0.6, but I believe it affects all versions >= 4.0.0, including master. It may affect 3.18.x, but I didn’t check it.

### Reproduce

Process 2 videos, create 2 bookmarks (one with each video) and then generate a report, using thumbsOnly for one of the bookmarks.
When the report is opened, the "preview" viewer works (showing videos frame mosaic), but the metadata and text viewers do not.

### Cause

Debugging the issue, it seems that items with thumbs only have mediaType = null, which prevents Metadata viewer from working.
https://github.com/sepinf-inc/IPED/blob/22a1c38c6e38562b2d8751e3ce57d36338ff8934/iped-app/src/main/java/iped/app/ui/FileProcessor.java#L150
The mediaType is cleared here:
https://github.com/sepinf-inc/IPED/blob/22a1c38c6e38562b2d8751e3ce57d36338ff8934/iped-engine/src/main/java/iped/engine/task/index/IndexItem.java#L887

**Comment by tc-wleite** [comment]
@lfcnassif, I found out that removing the last line I mentioned (`evidence.setMediaType(null);`) fix the issue, but I am not sure what side effects that may cause, so I would like that you check this problem in more detail, when you got some time.

**Comment by lfcnassif** [comment]
Hi @tc-wleite. If I remember, mediaType is reset to force mediaType detection of viewFiles to redirect them to the right viewer, maybe that is not needed anymore after your Viewers refactoring. The MetadadaViewer should work for thumbsOnly files. Not sure about the TextViewer, since they won't have any content, perhaps just displaying metadata is an option, but may confuse users...

**Comment by lfcnassif** [comment]
I also didn't remember the full purpose of the last part of the if clause just above the resetting line...
