### ISSUE TITLE
Linux, IPED Container and FaceRecognition: processing get stuck on some images

### ISSUE THREAD

**Issue by arisjr** [sepinf-inc/IPED#1424]
I'm making IPED 4.0.6 container. I'm trying to include all the IPED features on this release.

I'm running some final tests on IPED 4.0.6 container (https://github.com/iped-docker/iped) on our test DD images, all the things are running fine so far until I enable FaceRecognition. FaceRecognition prints some process creation errors at the very beginning, but then seems to start running normally ... but workers get stuck always on the same gif images, some of them are pretty small and normally would take no time to process them.

Without FaceRecognition, this test DD image takes about five minutes to complete.

The processing logfile is bellow. I let it process until it get stuck on the gif images, then I manually cancelled it, but it could stay forever stuck on them. 
[ipedlog.txt](https://github.com/sepinf-inc/IPED/files/9961442/ipedlog.txt)

**Comment by lfcnassif** [comment]
This week I'm out of work, I can take a look in the next one, if no other dev looks before me. We need a triggering image to try to reproduce, thanks.

**Comment by arisjr** [comment]
@lfcnassif 

I found the source of the error. I have set the /usr/bin/python to be python3.9, but /usr/bin/python3 was linked to python3.10 binary (the default ubuntu python version). 
Looking at the code, FaceRecognition uses python on windows, but python3 on linux. 

Setting python3 to be python3.9 instead of python3.10 did solve the problem. 

Thanks and regards!

**Comment by lfcnassif** [comment]
Thanks for investigating.
