### ISSUE TITLE
DocThumbTask not working on 4.0.x if enableExternalParsing is enabled

### ISSUE THREAD

**Issue by reacan** [sepinf-inc/IPED#1441]
I am experiencing a problem stated in the subject line. Processed a test sample with documents, paid extra attention to config files and everything seemed to be correct.  I tried using both libreoffice 6 and 7 and the result was the same. Could I be missing something?  Please let me know if you need some additional information.

Log from 4.0.0:  
2022-11-24 20:53:56     [INFO]  [indexer.process.Statistics]                    DocThumbTask:   Processing Time:        9s (16%)
full log: https://pastebin.com/spiApuk0

Log from 4.0.6:
2022-11-24 20:59:46     [INFO]  [engine.core.Statistics]                        DocThumbTask:   Processing Time:        0s (0%)
full log: https://pastebin.com/wQreTXXF

P.S. java version:

IMPLEMENTOR="BellSoft"
JAVA_VERSION="11.0.14.1"
JAVA_VERSION_DATE="2022-02-08"

**Comment by tc-wleite** [comment]
Hi @reacan!
I tried to process a few DOCX files with IPED 4.0.6 and thumbs were generated as expected.

Looking at your execution logs, I couldn't figure out much...
As it shows all task totals ("Total LibreOffice processed", "Total LibreOffice not procesed" and "Total LibreOffice timeout") as zeroes, maybe something is preventing the files to be sent to the task.

Opening your processed case, what is the `contentType` of the test items?
If you try processing PDF files, are thumbs generated? (The task is the same, but internally it is a different process that doesn't rely on Libre Office)

**Comment by reacan** [comment]
hi @tc-wleite!

Thumbs are generated for pdf documents. The problem is with libreoffice and ms office documents. 

The content types are - "contentType	application/msword", "contentType	application/vnd.oasis.opendocument.presentation", "contentType	application/vnd.ms-powerpoint", "contentType	application/msword", "contentType	application/vnd.openxmlformats-officedocument.presentationml.presentation", "contentType	application/vnd.openxmlformats-officedocument.wordprocessingml.document".

I've had this problem processing both folders and images, 4.0.0 works fine, 4.0.3 and 4.0.6 does not generate thumbs for libreoffice and msoffice. Permissions are fine, I am the owner of the items that I am trying to process. I am using Debian 11 and running IPED as a non-root user. 

It's really strange as everything else gets processed. Maybe I should try a specific version of java and libreoffice? What versions did you use when you did your test?

**Comment by tc-wleite** [comment]
> Thumbs are generated for pdf documents. The problem is with libreoffice and ms office documents.
> 
> The content types are - "contentType application/msword", "contentType application/vnd.oasis.opendocument.presentation", "contentType application/vnd.ms-powerpoint", "contentType application/msword", "contentType application/vnd.openxmlformats-officedocument.presentationml.presentation", "contentType application/vnd.openxmlformats-officedocument.wordprocessingml.document".
> 
> I've had this problem processing both folders and images, 4.0.0 works fine, 4.0.3 and 4.0.6 does not generate thumbs for libreoffice and msoffice. Permissions are fine, I am the owner of the items that I am trying to process. I am using Debian 11 and running IPED as a non-root user.

Thanks for the inrfomation.
 
> It's really strange as everything else gets processed. Maybe I should try a specific version of java and libreoffice? What versions did you use when you did your test?

I use Windows (and embedded LibreOffice 6.1.5.2 and OpenJDK 11.0.13).
My test was just to discard some basic regression.

Looking at the task code, LibreOffice documents conversion run 3 main steps:

- Create a temp dir (a subdir in IPED's temp).

- Once, on initialization:
`/usr/lib/libreoffice/program/soffice.bin --headless --quickstart --norestore --nolockcheck -env:UserInstallation=file://<temp-dir-absolute-path>`

- For each file to be converted:
`/usr/lib/libreoffice/program/soffice.bin --convert-to png <input-file-absolute-path> --headless --quickstart --norestore --nolockcheck -env:UserInstallation=file://<temp-dir-absolute-path> --outdir <temp-dir>`

Can you try running these manually in your environment and see if we can find out anything else?

**Comment by reacan** [comment]
I just processed the same test sample using 4.0.6 on Windows 10 and thumbs were also not generated for libreofice and msoffice but they were generated for pdfs. I used the .exe file to start the processing.

full log: https://pastebin.com/Q4Ry1KJt

I ran the commands:

./soffice.bin --convert-to png ~/Forensics/docthumbtest/anketabiblio.docx --headless --quickstart --norestore --nolockcheck -env:UserInstallation=file:///home/watermelon/tmp/

./soffice.bin --convert-to png ~/Forensics/docthumbtest/anketabiblio.docx --headless --quickstart --norestore --nolockcheck -env:UserInstallation=file:///home/watermelon/tmp/ --outdir /home/watermelon/tmp/

convert /home/watermelon/Forensics/docthumbtest/anketabiblio.docx -> /home/watermelon/tmp/anketabiblio.png using filter : writer_png_Export

As a result a .png version of the .docx file was generated, twice the size of the original .docx.

Please let me know if you require more information.

**Comment by tc-wleite** [comment]
Thanks for the quick reply!
It is odd that is also not working on Windows.
As far as I remember there were no changes directly related to DocThumbTask since 4.0.0 (I will review this point).
And as I said before, the log shows no "not processed" items by this task.

I will take a closer look and try to figure out what is happening, or at least come up with other ideas of tests to identify the issue.

**Comment by reacan** [comment]
This is how my test sample looks like in 4.0.6:

![Screenshot-20221125132958-2558x1438](https://user-images.githubusercontent.com/61985693/203977006-39ec37e1-8282-4220-8bb6-6fbbd313ad32.png)

Maybe it is related to encoding? About two years ago when still working with 3.17.1 I noticed that not all IPED source files used UTF-8. Just a wild guess.

**Comment by lfcnassif** [comment]
I just found a bug with this module, it is not working when `enableExternalParsing` is enabled (my fault). @reacan can you check if that is your case?

**Comment by lfcnassif** [comment]
The bug I found was introduced by commit 6baaffb51bb6b506ec360f65b53a7f2e7e386006, but the affected if (that decides if the file should be processed or not) was not correct before...

**Comment by tc-wleite** [comment]
> I just found a bug with this module, it is not working when `enableExternalParsing` is enabled. @reacan can you check if that is your case?

@lfcnassif, I believe you found the issue. From the log files @reacan sent, `enableExternalParsing` was enabled in 4.0.6 and but wasn't in 4.0.0.

**Comment by lfcnassif** [comment]
> @lfcnassif, I believe you found the issue. From the log files @reacan sent, `enableExternalParsing` was enabled in 4.0.6 and but wasn't in 4.0.0.

Great! I forgot to check this on his logs :-)
