### ISSUE TITLE
Disable LED carving on VHDX virtual disks

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1451]
This should have been disabled when VHDX + recursive processing was implemented.

@tc-wleite I also noticed the accepted types of LedCarveTask and KnownMetCarveTask are different. Should we make them equal or this was because of KnownMetCarveTask performance issues?

**Comment by tc-wleite** [comment]
> @tc-wleite I also noticed the accepted types of LedCarveTask and KnownMetCarveTask are different. Should we make them equal or this was because of KnownMetCarveTask performance issues?

I just checked here, and I don't any reason for that difference. 
As far as I remember (not 100% sure), initial implementations accepted fewer types, and at some point other types were added, but some of them were not added to `KnownMetCarveTask`.

I believe other types accepted by `LedCarveTask` can (should) be added to `KnownMetCarveTask`.

**Comment by lfcnassif** [comment]
> I believe other types accepted by `LedCarveTask` can (should) be added to `KnownMetCarveTask`.

Great! I'll open an issue and make them equal.
