### ISSUE TITLE
extraCharsToIndex  version 3 vs version 4 

### ISSUE THREAD

**Issue by leodmonkey** [sepinf-inc/IPED#1459]
Hello , i'm having problems with the parameter "extraCharsToIndex"  and the char @ , in the version 4.0.5, running Windows 10 64bit and java 8.0.3510.

Using the following : conf\IndexTaskConfig.txt -> extraCharsToIndex = @; $; &; 

It's working for the characters "$" and  "&", but not for "@".  

For example,  searching for *@gmail , doesn't bring any results, while in version 3.18.15 the same query returns matches.

Thanks.

**Comment by lfcnassif** [comment]
Now `@` is a Lucene reserved operator used for minimum-should-match clauses:
https://lucene.apache.org/core/9_2_0/queryparser/org/apache/lucene/queryparser/flexible/standard/StandardQueryParser.html

Just escape it with a backslash in your query text.

**Comment by lfcnassif** [comment]
Just a final tip, if your query doesn't have wildcards (*?) you can also put it between double quotes.
