### ISSUE TITLE
Extract features from kml

### ISSUE THREAD

**Issue by patrickdalla** [sepinf-inc/IPED#1460]
Some placemarks on KML are not just a location, but a "feature" with many locations, like lineString, polygon, etc. 
Leaflet suports https://www.rfc-editor.org/rfc/rfc7946 to add those features to map, so the GeoTools API used to parse.
So the implementation seems easy.

**Comment by patrickdalla** [comment]
In fact I have already implemented. I specified a metadata "geo:featureString" that will contain features that any parser may include. If this metadata exists, the feature string is passed to leaflet to be drawn.

**Comment by patrickdalla** [comment]
https://user-images.githubusercontent.com/28692427/209128858-e2b177d1-c7b7-4326-8997-2b7245ba55ce.mp4

**Comment by lfcnassif** [comment]
Very cool, thank you!
