### ISSUE TITLE
Use -Xms arguments

### ISSUE THREAD

**Issue by renthus** [sepinf-inc/IPED#1462]
## Message
The Portuguese version help, visible in preview tab of IPED Search App, guides the program run: `"java -Xms512M -jar iped/lib/iped-search-app.jar"`.

## Picture
![image](https://user-images.githubusercontent.com/49447595/209226774-98a6c5bd-6c76-4fc3-819f-b5e0f94513d4.png)

## Message Error
After run, we get the error. `"Please use -Xms/ -Xmx arguments after iped.jar not after java command, since processing will occur in a forked process using those params."`.

## Message Correct for arguments
`"java -jar iped/lib/iped-search-app.jar -Xms512M"`

Thanks!

**Comment by lfcnassif** [comment]
Thanks, the help is outdated.
