### ISSUE TITLE
Unable to use VisualVM to monitor IPED process

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1463]
I was trying to use VisualVM to monitor IPED 4.0.x process and was getting an error.
The monitoring tool works fine for other Java applications I tested.
I am using VisualVM 2.1.5 and OpenJDK 11.0.13.

Eventually I found a simple **code** fix in `DefaultPolicy` class.

@lfcnassif, you sometimes use VisualVM, right?
Is it working in your environment?
Are you using any special configuration to make it work?

If it is not working for you either, I can submit a simple PR with the change, otherwise I will try to find another solution here.

**Comment by lfcnassif** [comment]
Hi @tc-wleite, yes I use VisualVM. It is not working fine. After a comment from @fmpfeifer, I was disabling the DefaultPolicy to use it. Please send the fix, thank you!

**Comment by lfcnassif** [comment]
closed by #1464
