### ISSUE TITLE
FragmentLargeBinaryTask cannot be disabled

### ISSUE THREAD

**Issue by gfd2020** [sepinf-inc/IPED#1465]
Unless it's a expected behavior, I think the enableSplitLargeBinary flag is not disabling the FragmentLargeBinaryTask.
Version 4.0.2

**Comment by tc-wleite** [comment]
Taking a quick look at the code, it seems that the flag value is loaded correctly, but not being checked in the task.

**Comment by lfcnassif** [comment]
The flag is not being used indeed, thanks for reporting!

**Comment by lfcnassif** [comment]
Just an update here, the `enableSplitLargeBinary` option was removed targeting 4.1 version, since the implemented solution to fix #1281 needs FragmentLargeBinaryTask to be always enabled.
