### ISSUE TITLE
TimelineGraph highlighting selected items if overlap occurs

### ISSUE THREAD

**Issue by FelipeFcosta** [sepinf-inc/IPED#1470]
After defining 2 or more ranges, the graph will start to highlight items of the previously select ranges if the next range the user defines starts overlapping an existing one, although the user didn't ask for it.

<img src="https://user-images.githubusercontent.com/45947947/210440019-0f63dda5-8de9-4ec1-8a05-15ade92fe235.gif"  width="600" />

**Comment by lfcnassif** [comment]
Affects just current master.

**Comment by lfcnassif** [comment]
Fixed by #1479
