### ISSUE TITLE
Selected area while pressing shift persists on the Timeline Graph

### ISSUE THREAD

**Issue by FelipeFcosta** [sepinf-inc/IPED#1471]
after two or more ranges have been defined, a new selected area that overlaps another range persists on the graph if the user releases the mouse button while the graph is highlighting the items (related to #1470):

<img src="https://user-images.githubusercontent.com/45947947/210427238-4b09b1f6-d8a6-446a-a1d7-f58349a42d93.gif"  width="600" />

but it is easily removed with another click on the graph

**Comment by patrickdalla** [comment]
As I have changed the behavior not to highlight items while creating overlapping regions, in attendance of #1470, this error does not occurs any more.

**Comment by lfcnassif** [comment]
Affects just current master.
