### ISSUE TITLE
Increase the image thumbnail resolution

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1474]
Currently, **160** pixels is the default **thumbnail size** used by IPED.
Although it is a parameter, this value is hardcoded in a few places.
As far as I remember, it was chosen a very long time ago, based on common dimensions of embedded thumbnails from compact digital cameras. Nowadays, common thumbnail dimensions are larger.

My suggestion is to increase this value to **256**.
Some tasks/features (e.g. nudity detection and image similarity) use the thumbnail image, instead of the original file, to speed things up.
Increasing a bit the number of pixels should:
- **Improve the visual quality** in the gallery (the difference is small, but it can be noticeable depending on the screen resolution and the number of columns used in the gallery).
- **Provide more information** to tasks/features (both current and future ones, that may use more up-to-date models), but would still keep a relatively small number of pixels (compared to the full original resolution).

I am running a large test to estimate the extra **space** and **processing time** required by this change, and will post the results here.

A new DIE model should be trained, if we decide to make this change, as the current one was trained using 160 pixels. The current model will work, but training a new one with 256 pixels should produce better results.

**Comment by lfcnassif** [comment]
Thank you @tc-wleite for all your tests!

**Comment by tc-wleite** [comment]
`PhotoDNATask` will also be slightly improved by this change, if `computeFromThumbnail` is enabled (which is the default configuration).

**Comment by lfcnassif** [comment]
Thank you @tc-wleite! I also noticed that at some point a long ago, thumbnails of very small images/icons started to be resized to full fill the whole gallery cell area, they used to be rendered at their original size (smaller than the cell). As you are working with related stuff, if you agree old behavior was better and if you have time and could take a look, that would great.

**Comment by tc-wleite** [comment]
Screenshots comparing version 4.0.7 with the proposed changes.
Differences are subtle as I mentioned, but it is possible to note some improvement.

4.0.7:
![4 0 7](https://user-images.githubusercontent.com/7217001/214916989-0e1a65d4-f25e-4776-94c3-92cad4835c26.png)

4.1 - After #1474:
![4 1](https://user-images.githubusercontent.com/7217001/214917111-d6aa37e7-e944-4969-be9d-52e3ee561db1.png)

**Comment by lfcnassif** [comment]
Much better!

**Comment by lfcnassif** [comment]
> A new DIE model should be trained, if we decide to make this change, as the current one was trained using 160 pixels. The current model will work, but training a new one with 256 pixels should produce better results.

This was left as a future improvement, right?

**Comment by tc-wleite** [comment]
No, I was writing a post about this and there was a power outage here :-)

**Comment by lfcnassif** [comment]
Closed by #1492
