### ISSUE TITLE
All timeline intervals items unhighlighted when one interval deleted.

### ISSUE THREAD

**Issue by patrickdalla** [sepinf-inc/IPED#1477]
When 1 of the intervals defined on timeline chart is deleted all intervals items are unhighlighted.

I think that the highlight/unhighlight main management operations should be kept on main results table. So, any operation done on other tabs should affect the highlight state of items if this effect is explicit. So, the deletion of one interval should not affect highlight state of any item, neither the ones that which has timestamps inside the interval. It is only a helper method without a enforced state biding.

For example: if some user highlights all items inside an interval and latter unhighlight one ore two items, he could delete this interval, create and highlight items inside another interval, without unhighlighting the previous highlighted one.

Anyway, the current implementation must be corrected, as it unhighlights all items when the user deleted an interval.

@lfcnassif , what do you think?

**Comment by patrickdalla** [comment]
But I have a doubt on how should be the behaviour of the timeline chart if the "Apply defined filters" is selected (maybe this can imply another issue). 
May the resultset reflect imediatelly the new defined filters (I vote yes)? If yes, should all highlights be cleared, right?

**Comment by lfcnassif** [comment]
I think big changes on old code shouldn't be done now, as we are next to release 4.1. If this could be fixed with simples changes, it's fine to me.

Yes and yes to last 2 questions. Currently if result set changes, highlights are cleared, they are a instante state of current result set.

**Comment by patrickdalla** [comment]
It does not need big change. It is the current behavior if we, with apply filters enabled, define a new filter and click on "filter defined ranges" popup menu item. So, we need only to call the same login of this popup menu item immediately after the new defined filter is created.
Anyway, you can merge it whenever you find viable and after some more tests.

**Comment by lfcnassif** [comment]
OK, let's apply the fix. Could you open a Pull Request when all changes are finished on the fixing branch?

**Comment by patrickdalla** [comment]
It is already opened. It is supposedly finished, some confirmation tests by a third party is recommended. Can you do the tests @filipesimoes?

**Comment by lfcnassif** [comment]
Affects just current master.

**Comment by lfcnassif** [comment]
Fixed by #1479
