### ISSUE TITLE
Fix non thread safe parsers, they can return inconsistent results

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1497]
All parsers should be thread safe, this is a Tika requirement. We use different Tika instances for each Worker thread trying to decrease thread safety issues, but seems Tika is reusing the same parsers instances internally, maybe this changed in Tika-2 at some point.

Below the list of affected parsers:
- GeofileParser: virtualId attribute
- RegistryParser: parentMap & defaultRegistryKeyParser attributes
- OCRParser: at least filePath attribute
- EdgeWebCacheParser: at least itemInfo attr

**Comment by patrickdalla** [comment]
Are you working on this? Or want me to review?

**Comment by lfcnassif** [comment]
> Are you working on this? Or want me to review?

Yes, I'm already on this, I'll ask for your review after pushing, thanks.

**Comment by patrickdalla** [comment]
No. I was reviewing the ui config. If it is simple to fix, can you
continue. Just let me know

Em seg., 30 de jan. de 2023 13:32, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by lfcnassif** [comment]
Yes, I'll do. But the idea here is to review all parsers, not just the GeofileParser.

**Comment by lfcnassif** [comment]
> Below the list of affected parsers (in progress):
> 
> * GeofileParser: virtualId attribute)
> * RegistryParser: parentMap & defaultRegistryKeyParser attributes
> * OCRParser: at least filePath attribute
> * EdgeWebCacheParser: at least itemInfo attr
> * OutlookPSTParser: many attributes :-(
> * LibpffPSTParser: many attributes :-(

List updated. Last 2 are very very bad... I'll prioritize fixing them.

**Comment by lfcnassif** [comment]
Sorry, OutlookPSTParser and LibpffPSTParser are not affected, since they create internal instances of their own before calling the private safeParse method (some kind of thread safe parsing).

**Comment by lfcnassif** [comment]
@patrickdalla GeofileParser is fixed locally here, if you could fix RegistryParser, I would appreciate, thanks.

**Comment by patrickdalla** [comment]
ok

Em seg., 30 de jan. de 2023 15:54, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by lfcnassif** [comment]
Just an observation here, python parsers don't need to be thread safe. As we implemented them from scratch, we guarantee each parsing thread will use a different python parser instance.
