### ISSUE TITLE
Expand timestamp events from UsnJrnlParser and enable it in forensic and pedo profiles

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1503]
Currently the NTFS USN journal parser `extractEntries` parameter is disabled. This can be very useful for e.g. CSAM or malware cases. Usually it extracts about 300k events from each NTFS partition.

Should we enable it in `pedo` profile by default? And perhaps on `forensic` profile?

**Comment by lfcnassif** [comment]
Just saw all USN journal events are being extracted using "created" as `timeEvent` value. They should use the Reason value as `timeEvent`:
- file_create
- data_extend
- close
- basic_info_change
- file_delete
- data_overwrite
- rename_new_name
- indexable_change
- security_change
- data_truncation
- rename_old_name
- hard_link_change
- object_id_change
- reparse_point_change
- stream_change
- named_data_extend
- compression_change
- named_data_overwrite

**Comment by lfcnassif** [comment]
Hi @patrickdalla, thank you for taking a look at this.

> One entry can have many reasons, but one timestamp. Should we create as many timeEvents as the number of reasons, all with same timestamp?

Yes, the same think can happen with file system dates, and creating separate timeEvents would allow to do rage queries for each single event.

**Comment by patrickdalla** [comment]
This is how it will be shown.
![image](https://github.com/sepinf-inc/IPED/assets/28692427/c83d27c2-c00b-43e2-bbf3-a7ca61e21195)

**Comment by patrickdalla** [comment]
I have only to set the metadata as date

**Comment by patrickdalla** [comment]
It is enabled in default config folder. So, it is enabled in any profile, right?
