### ISSUE TITLE
Bug in implementations of InputStream.read() through code

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1510]
Trying to optimize #687, I hit strange errors like invalid json objects being read. After investigating for a while, I found `SeekableFileInputStream` and other similar classes have a flaw, they are not following the `InputStream.read()` method contract. It should return a byte as an int in [0, 255] range when EOF is not reached, but it is returning values in [-128, 127] range. This can cause errors in many modules if that method is used...

PS: Sleuthkit [ReadContentInputStream](https://www.sleuthkit.org/sleuthkit/docs/jni-docs/4.12.0/_read_content_input_stream_8java_source.html#l00040) has the same bug.

**Comment by lfcnassif** [comment]
@hauck-jvsh is this correct or it was a workaround to this bug:
https://github.com/sepinf-inc/IPED/blob/master/iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/usnjrnl/Util.java#L33-L34

@patrickdalla is this correct or it was a workaround to this bug:
https://github.com/sepinf-inc/IPED/blob/master/iped-carvers/iped-carvers-impl/src/main/java/iped/carvers/custom/DERCarver.java#L43

**Comment by patrickdalla** [comment]
I reviewed the specs (https://www.itu.int/ITU-T/studygroups/com17/languages/X.690-0207.pdf) and it follows rule 8.1.3.4 (short form of length). So it is right and is not a workaround.

**Comment by lfcnassif** [comment]
Thanks! I did some tests and there is no need to update current depending code.

**Comment by hauck-jvsh** [comment]
It is correct, this is a mask to read the unsigned value of the actual data, not the number of bytes read.

**Comment by hauck-jvsh** [comment]
Actually, after reading again the description, the code that you describe is actually for removing the signal, if it return a value between 0-255 it should not be necessary.
