### ISSUE TITLE
Occasional NoClassDefFoundError from OCRParser

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1530]
Checking several processing logs with IPED 4.1.0, I noticided in a few of them the following exception:

```
Exception from iped.parsers.ocr.OCRParser on <filename>.pdf: java.lang.NoClassDefFoundError:
com/twelvemonkeys/imageio/stream/DirectImageInputStream
```

@lfcnassif, please check in your logs (if you keep them and OCR was enabled) if you find this exception

In order to reproduce the issue, I processed the same evidence several times, with the same parameters, and most of the time there was no exception. In some of the executions, a lot of these exceptions.
Tracing down the issue, I found out that that sometimes the conversion inside OCRParser uses **JAI** to convert **TIFFs** and in other executions **TwelveMonkeys ImageIO plugin** is used. So it seems to be a similar issue recently mentioned in #1134. 
As a test, I removed JAI jars from the lib folder, then the error is easily reproduced. 
Classes used by TwelveMonkeys ImageIO TIFF plugin **3.8.3** are missing, as "core" part of the library is using version **3.8.2** (**imageio-core-3.8.2.jar**).
Changing the POM to use TIFF plugin 3.8.2 seems to solve the issue. I will submit a PR with this fix, after finishing a set of tests.
I will open another issue to try to converge all TwelveMonkeys libraries to the same version.

**Comment by lfcnassif** [comment]
Hi @tc-wleite. Unfortunatelly I usually I keep OCR disabled most time to speed up tests. This random service loader behavior is hard to trace. I'm not sure if there is a way to make it deterministic, but if it exists, we would be better fixing it.

**Comment by tc-wleite** [comment]
> Hi @tc-wleite. Unfortunatelly I usually keep OCR disabled most time to speed up tests. This random service loader behavior is hard to trace. I'm not sure if there is a way to make it deterministic, but if it exists, we would be better fixing it.

Ok! It seems changing the plug-in to 3.8.2 solve the issue as I said before. I left some tests running and should have a conclusion tomorrow.
It is not a critical problem, as the external conversion is called after this exception. But it is something we should avoid, even if it only happens occasionally.

**Comment by lfcnassif** [comment]
One question, I don't remember why 12monkeys tiff plugin was included, could you remind me why is it needed?

**Comment by tc-wleite** [comment]
I think it is a dependency of IcePDF.
I believe it was using the latest version, and you fixed a version to avoid conflicts in this commit:
https://github.com/sepinf-inc/IPED/commit/f36c1b5bf51921b2dec7b3cfff1f791d5baf4887

**Comment by lfcnassif** [comment]
Sorry and thank you! If I remember, IcePDF calls some 12monkeys TIF class in a hard coded way. I will double check later today and report here.

**Comment by lfcnassif** [comment]
I also forgot this discussion:
https://github.com/pcorless/icepdf/discussions/231

So maybe it is safe to remove the TIF plugin.

**Comment by tc-wleite** [comment]
I wasn't aware of that discussion.
Tests finished here, changing the TIFF plugin to 3.8.2 should solve the issue I described, but removing the TIF plugin altogether seems a better option, if it works.

**Comment by tc-wleite** [comment]
I am testing it (removing the plugin) here.

**Comment by lfcnassif** [comment]
Thank you @tc-wleite for testing! Because I'm not sure if removing it is the best option. IcePDF author said they have fallback code to handle TIF, but if I remember (not very trustful rs) it doesn't rely on ImageIO (JAI or Java11 support) so maybe it could be a bit limited... I'll check their code this afternoon.

**Comment by tc-wleite** [comment]
> Thank you @tc-wleite for testing! Because I'm not sure if removing it is the best option. IcePDF author said they have fallback code to handle TIF, but if I remember (not very trustful rs) it doesn't rely on ImageIO (JAI or Java11 support) so maybe it could be a bit limited... I'll check their code this afternoon.

I see. Well, if removing if not a good option, we can just change the plugin version for now.
I will update here what I found out...

**Comment by tc-wleite** [comment]
After removing the TIFF ImageIO plugin,  I ran a test with ~5K PDFs, and got the same results as before.
Looking at IcePDF code, I found two explicit calls to TwelveMonkeys: one to handle very large images inside PDFs (>10K in each dimension) and the other to decode CCITT images.
The former uses a core class of TwelveMonkeys library, so I guess it wouldn't be affected by the plugin removal.
The latter has the fallback code, which seems to handle the test images I had. Obviously, if the code is there, maybe there are files that are not handled well by the fallback code.

I created a synthetic PDF (containing a very large CCITT Group 4 image), trying to trigger some issue, but it was handled successfully. In the analysis UI, after removing the filter of IcePDF log messages, I got the following message, so it actually used the fallback code:
`[WARN]	[graphics.images.FaxDecoder]			Error during decode falling back on alternative fax decode.`

@lfcnassif , I am submitting a PR removing the TIFF plugin, as it is ready here, but take a closer look when you get some time (it is not a critical issue), and decide which option is better for now, removing or changing the version.

**Comment by tc-wleite** [comment]
Here is the synthetic PDF: [b.pdf](https://github.com/sepinf-inc/IPED/files/10804763/b.pdf)

**Comment by lfcnassif** [comment]
Hi @tc-wleite, I just looked at IcePDF source again. They also have a fallback using JAI. Could you search into your testing log for "Error decoding using JAI CCITTFax decode" and if you find it, send the triggering files to me? So I can test the TwelveMonkeys plugin on them.

**Comment by tc-wleite** [comment]
> Hi @tc-wleite, I just looked at IcePDF source again. They also have a fallback using JAI. Could you search into your testing log for "Error decoding using JAI CCITTFax decode" and if you find it, send the triggering files to me? So I can test the TwelveMonkeys plugin on them.

Yes, I saw that second fallback that uses JAI. Out of the ~5K test PDFs, only ~100 used the first fallback I mentioned before ("Error during decode falling back on alternative fax decode") and no "Error decoding using JAI CCITTFax decode" neither other message coming from `graphics.images.FaxDecoder` class.

I have a larger set with ~900K PDFs. I will process it tonight and see if I can find files that fail in the first fallback (and perhaps in the second, that uses JAI).

**Comment by lfcnassif** [comment]
Thank you! But don't worry, I'm already running on 250K PDFs here. I applied a small patch to skip tesseract but to continue to convert them to images (although it wouldn't catch quality rendering issues)

**Comment by lfcnassif** [comment]
> Thank you! But don't worry, I'm already running on 250K PDFs here. I applied a small patch to skip tesseract but to continue to convert them to images (although it wouldn't catch quality rendering issues resulting in OCR differences)

I aborted the test, it would take too long (about 1 day). I'll crawl some scanned PDF files before.

**Comment by lfcnassif** [comment]
I collected about 40K scanned PDFs from 200 cases. I'm running full OCR task on them with and without TwelveMonkeys plugin, but just on first 3 pages to speed up tests. I think it is very likely the same image encoding is used through all pages for scanned PDFs, so I think that first 3 pages cut is reasonable.

**Comment by lfcnassif** [comment]
Just analyzed the processing results. I used 6 different configurations:
- IcePDF with 12Monkeys
- IcePDF with JAI
- IcePDF with just java11 decoder
- PDFBox with 12Monkeys
- PDFBox with JAI
- PDFBox with just java11 decoder

IcePDF/PDFBox was the value used in `OCRConfig->pdfToImgLib`.

Results changing the TIFF decoding library were the same most time when searching for common words. But TwelveMonkeys threw 4 less exceptions (48 to 44 using IcePDF and 72 to 68 using PDFBox) - all seems related to OOME.

Switching the pdfToImg library to PDFBox resulted in more differences when searching for common words. PDFBox returned from 0.5% to 1% more search results than IcePDF, most time. But it threw more exceptions then IcePDF, as I said above, all seems related to OOME. Changing the TIF decoder didn't make big differences with PDFBox too.

As both libraries threw a few less exceptions with TwelveMonkeys TIF plugin, I think we should keep it.

PDFBox returned a bit better (a noticiable difference) search results most time, possibly it generates better quality images for OCR. So I thought to switch the `pdfToImgLib` default value to PDFBox, but as it threw more exceptions, many related to OOME (which is aligned with tests I did years ago comparing the two libs, PDFBox still seems to be more memory hungry), I won't change `pdfToImgLib` for now.

**Comment by lfcnassif** [comment]
PS: Tests were done with `externalPdfToImgConv = false`, `enableExternalParsing = true` and `externalParsingMaxMem = 512M` so PDF to image conversion was done in external parsing processes limited to 512MB heap.

**Comment by lfcnassif** [comment]
> In order to reproduce the issue, I processed the same evidence several times, with the same parameters, and most of the time there was no exception. In some of the executions, a lot of these exceptions.
> Tracing down the issue, I found out that that sometimes the conversion inside OCRParser uses **JAI** to convert **TIFFs** and in other executions **TwelveMonkeys ImageIO plugin** is used. So it seems to be a similar issue recently mentioned in #1134.
> As a test, I removed JAI jars from the lib folder, then the error is easily reproduced.
> Classes used by TwelveMonkeys ImageIO TIFF plugin **3.8.3** are missing, as "core" part of the library is using version **3.8.2** (**imageio-core-3.8.2.jar**).
> Changing the POM to use TIFF plugin 3.8.2 seems to solve the issue. I will submit a PR with this fix, after finishing a set of tests.
> I will open another issue to try to converge all TwelveMonkeys libraries to the same version.

Thank you @tc-wleite for all your tests and time!
