### ISSUE TITLE
Converge all TwelveMonkeys libraries to 3.9.4

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1531]
IPED 4.1.0 uses:
- imageio-bmp-3.8.3.jar
- imageio-core-3.8.2.jar
- imageio-metadata-3.8.2.jar
- imageio-psd-3.8.2.jar
- imageio-tiff-3.8.3.jar (should be changed to 3.8.2 as discussed in #1530) 
- imageio-webp-3.8.3.jar

Mixing versions can lead to many hard-to-trace issues.

Unfortunately, as discussed in https://github.com/sepinf-inc/IPED/issues/1378#issuecomment-1279362041, tests with PSD plugin 3.8.3 had much worse results than 3.8.2. And WebP 3.8.2 was much worse than 3.8.3. So it wasn't possible to use only 3.8.2 or 3.8.3.

Since then, a few releases came out. I tested with the latest version (3.9.4) a few weeks ago, and the issues with WEBP are still present. I am waiting for the next release to see if we can upgrade all the used plugins. 
If it still fails, I will try to investigate the issue in more detail, and perhaps open an issue there.

**Comment by lfcnassif** [comment]
Hi @tc-wleite, do you mean issues with PSD are still present, or WEBP indeed? If it wasn't done yet, I would suggest reporting the issues to TwelveMonkeys project, maybe they are able fix them in the next release.

**Comment by tc-wleite** [comment]
> Hi @tc-wleite, do you mean issues with PSD are still present, or WEBP indeed? If it wasn't done yet, I would suggest reporting the issues to TwelveMonkeys project, maybe they will be able fix them in the next release.

WebP. In fact, I think there were different failures (read reported as successful, but black/single color images are produced).
I will repeat the tests and report there if I confirm the issue (I was waiting for a new release, because a few fix releases came in a short period of time, but it has been a while since the last one).

**Comment by tc-wleite** [comment]
I probably should have written "issues with WebP were back".

**Comment by tc-wleite** [comment]
> I tested with the latest version (3.9.4) a few weeks ago, and the issues with WEBP are still present. 

Repeating the tests more carefully, I realized that the above conclusion is wrong (I think I didn't use 3.9.4 but some other version 3.9.x before). 

**WEBP** plugin is working fine. With 3.8.3 it handles about 60% of my test images. Now, with 3.9.4 almost 100% (only a single image, out of a few thousand, failed and was successfully read by the external converter). There are some minor rendering differences (comparing thumbnail generated by ImageMagick before, because 3.8.3 didn't handle them, and now with the "internal" read). I am investigating these cases in more detail.

About **PSD**, with 3.9.4 there are 4 images that produced empty thumbnails, which were handled correctly before. I am also looking into this.
Reading PSD files became, on average, a bit slower (~10%), but still pretty fast (compared to the external read process).

I will run similar tests for TIFF, BMP and ICO, but from the release notes of TwelveMonkeys recent versions, I don't expect any changes for these formats.

**Comment by lfcnassif** [comment]
Thank you @tc-wleite!

**Comment by tc-wleite** [comment]
Analyzing the images with different visual results from 3.8.x to 3.9.4, I found out that:

- WEBP: A small number of images have slightly worse thumbnails with 3.9.4, due to incorrect rendering when source subsampling is used. The thumbs are still "visible". As it affects a small subset and in a not critical way, I think this is acceptable. I will report and send some samples to TwelveMonkeys project, but I see similar open issues with other formats, so I don't expect that it is something simple/fast to fix.
- PSD: The 4 images I mentioned before that have empty thumbs with 3.9.4 are two different (and very specific) situations:
    - PSD can contain multiple layers. While 3.8.x returned a single image for the problematic samples, 3.9.4 returned several images (which is the correct behavior). We should always take the first image (which merge all layers in the correct order), but because of a change I made from ICO files, in this particular images there are layers with larger width than the main image (which is odd), and we are (incorrectly) rendering one of these (almost invisible) wider layers. I will fix this.
    - Other two incomplete PSDs were processed fine in 3.8.x and now they are causing exceptions (which I think is fine, as they don't seem to be complete files). The function that checks if "anything useful" was read in such cases (`isMonoColorImage`) can be improved. In these particular images, pixels with different colors are returned, but they are all transparent, so nothing is rendered (and the image is not sent to ImageMagick). I am reviewing this method to be a bit more robust.

**Comment by tc-wleite** [comment]
> I will run similar tests for TIFF, BMP and ICO, but from the release notes of TwelveMonkeys recent versions, I don't expect any changes for these formats.

No changes at all for these other formats. Generated thumbnails are exactly the same and average spent time was also very similar.

**Comment by tc-wleite** [comment]
> WEBP: A small number of images have slightly worse thumbnails with 3.9.4, due to incorrect rendering when source subsampling is used. The thumbs are still "visible". As it affects a small subset and in a not critical way, I think this is acceptable. I will report and send some samples to TwelveMonkeys project.

I just created an issue in TwelveMonkeys project:
https://github.com/haraldk/TwelveMonkeys/issues/736
It is not a simple problem to find and solve, as it is not a coding bug, but more of a conceptual flaw (not critical though). 
After some investigation, I think I found the root cause. I will try to submit a PR there later.

**Comment by haraldk** [comment]
Sorry for jumping into your thread, but... If you are able to share one of the PSDs was read in 3.8.x but no longer In 3.9.x, please raise an issue in TwelveMonkeys, and I'll see if there's something we can be more lenient about. 😀

**Comment by tc-wleite** [comment]
> Sorry for jumping into your thread, but... If you are able to share one of the PSDs was read in 3.8.x but no longer In 3.9.x, please raise an issue in TwelveMonkeys, and I'll see if there's something we can be more lenient about. 😀

Hi @haraldk! 
Thank you for spending your time writing here. You are more than welcome!
As I mentioned in this thread, I found two (similar) files that are read by 3.8.2, but not by 3.9.4. 
However, they seem to be incomplete or corrupted files, as the output images produced by 3.8.2 have some odd artifacts.
ImageMagick is able to read only one of them, and produces a very similar output that 3.8.2 does.
I will open an issue in TwelveMonkeys.

**Comment by tc-wleite** [comment]
By the way @haraldk, because of the nature of our job as a computer forensic expert and IPED project, we deal with a lot of files from different types and sources, including recovered, incomplete and corrupted ones.

You should already have a lot of testing images, but if ever want to run tests of a new version/feature with a different set of images, feel free to contact me directly. 
Most of the files I have can't be shared, but I can run tests here and provide some feedback.
