### ISSUE TITLE
Investigate libheif usage for HEIC/HEIF thumbnail generation

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1537]
Thumbnail creation for HEIC/HEIF images takes some time using ImageMagick. Maybe https://github.com/strukturag/libheif would be a good alternative.

**Comment by tc-wleite** [comment]
I spent quite some time looking for alternatives to read HEIC/HEIF images a few years ago.
Some observations from that time are in https://github.com/sepinf-inc/IPED/issues/81#issuecomment-640901798.

ImageMagick uses libheif, right? So I don't expect a major difference using libheif directly (just a guess, which may be wrong).
And libheif uses native code, which is not very convenient for direct usage in IPED.

My best hope at that time was a TwelveMonkeys ImageIO plugin, but I think it is unlikely to be available in the near future.
https://github.com/haraldk/TwelveMonkeys/issues/440

As mentioned in the old discussion, a huge speed up would be achieved (in the thumbnail generation process) if we manage to extract the thumbnails already present in the majority of these images. They usually have pretty decent quality.
At that time, ImageMagick wasn't able to extract these thumbnails for this particular format, although it did for other formats. Maybe that changed. Or we may find other ways of extracting the embedded thumbnails.

**Comment by lfcnassif** [comment]
> ImageMagick uses libheif, right?

You are right, @tc-wleite, I was not aware about it. I'll close this then.

**Comment by lfcnassif** [comment]
PS: Do you know if the embedded thumbnails uses the same HEIC codec or if they are JPEG thumbs?

**Comment by tc-wleite** [comment]
> PS: Do you know if the embedded thumbnails use the same HEIC codec or if they are JPEG compressed?

As far as I remember, the format is quite generic, so both scenarios happen. For images produced by iPhones (by far the most common source of HEICs we deal with) there are no embedded JPEGs.

**Comment by lfcnassif** [comment]
> As mentioned in the old discussion, a huge speed up would be achieved (in the thumbnail generation process) if we manage to extract the thumbnails already present in the majority of these images

Have you considered trying to use drewnoakes metadata-extractor lib to perhaps extract the thumbnail? Not sure if it supports thumbs extraction directly, but this message suggests it may not be too hard:
https://github.com/drewnoakes/metadata-extractor/issues/574

**Comment by tc-wleite** [comment]
> Have you considered trying to use drewnoakes metadata-extractor lib to perhaps extract the thumbnail? Not sure if it supports thumbs extraction directly, but this message suggests it may not be too hard: [drewnoakes/metadata-extractor#574](https://github.com/drewnoakes/metadata-extractor/issues/574)

No, I don't remember trying that. Seems to be a possible solution.
