### ISSUE TITLE
Show progress in the system task bar (processing UI)

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1546]
Just a minor visual suggestion, applications can show a progress indicator in the system task bar.
The exact visual representation depends on the SO, but most systems support this feature.

The idea is to get a rough estimation about the progress just by looking at the task bar, when processing some case with IPED minimized, while doing other stuff.

**Comment by tc-wleite** [comment]
This is how it looks in Windows 11:
![image](https://user-images.githubusercontent.com/7217001/221376841-8f63862e-3ccc-4404-a662-ab60aa04c26e.png)

And when the processing is paused, it shows it in a different color (again, this is controlled by the SO, we just inform that the application is "paused"). This may be useful because sometimes I pause the processing to run something else, and forget to resume.
![image](https://user-images.githubusercontent.com/7217001/221376984-c0d0b88f-f1db-4108-bdbe-ffb4834477a2.png)

**Comment by lfcnassif** [comment]
> This may be useful because sometimes I pause the processing to run something else, and forget to resume.

This also happens to me, thanks @tc-wleite!
