### ISSUE TITLE
Improve items/categories icons and other minor visual enhancements

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1551]
Using 4.1.0 in real cases, I am enjoying the new icons added in #1291.
However, I found a few somewhat common file types with missing (e.g. JPEG) or incorrect icons (e.g. CDR - Corel Draw Images).
In general, icons for multimedia categories could be improved to be more "informative" and standardized among types of the same category (audio, images, videos).
I plan to review the icons for a few file types and add new ones for missing types/categories.

**Comment by tc-wleite** [comment]
I will update this post while I found icons to be replaced or added.

### Images

- #### Replace
    - [ ] BMP
    - [ ] CDR (use mime type)
    - [ ] DWG
    - [ ] EMF
    - [ ] GIF
    - [ ] HEIC
    - [ ] ICO
    - [ ] JPG
    - [ ] PNG
    - [ ] PSD
    - [ ] SVG
    - [ ] TIF
    - [ ] TIFF
    - [ ] WEBP

- #### Add
    - [ ] AVIF
    - [ ] DCX
    - [ ] EXR
    - [ ] HEIF
    - [ ] J2C
    - [ ] JB2
    - [ ] JP2
    - [ ] JPEG
    - [ ] JPF
    - [ ] PBM
    - [ ] PCX
    - [ ] PGM
    - [ ] PPM
    - [ ] RAS
    - [ ] RGB
    - [ ] WBMP
    - [ ] WMF
    - [ ] XBM
    - [ ] XCF

**Comment by lfcnassif** [comment]
Thank you @tc-wleite for improving this!
