### ISSUE TITLE
New Tab to list Referenced items

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1553]
I thought this was already opened, but I didn't find it. We already have a "References" tab to list items with some reference to the selected item on table tab, e.g. it lists P2P histories or WhatsApp chats referencing the selected media file on table. The idea is to have another tab to do the opposite, e.g.: when some P2P history or WhatsApp chat is selected on table tab, the new tab would list all media files referenced by them.

What would be good tab names to avoid confusion? Rename current tab, called "References", to "Referenced By" and the new one would use "Referencing" or the current "References" name (changing its behavior)? "Incoming References" for current one and "Outgoing References" for new one (maybe not so user friendly)? Other ideas? At first I prefer the "Referenced By" and "Referencing" names.

PS: A bit unrelated, but I think the bottom-central tab group is increasing a bit. I think since a long ago to move the "Hits" tab to the "Viewers" group. It makes sense to me since "Hits" tab displays file content. So the bottom-central group would be used just to display related items to the current selection (parent, subitems, duplicates, referenced By and referencing tabs). User could still move the "Hits" tab to the old place and save the UI layout if he wants.

**Comment by lfcnassif** [comment]
PS2: Months ago @patrickdalla made a code change to list outgoing references in current tab, together with incoming references. I reverted it, because I think the semantic is different and could cause confusion, but reusing the same tab is another option, not sure.

**Comment by lfcnassif** [comment]
If there are no objection, I'll use the ReferencedBy and Referencing names.

**Comment by tc-wleite** [comment]
> If there are no objection, I'll use the ReferencedBy and Referencing names.

I thought a bit about these names since you brought this question, but couldn't find any possibly better alternatives.

**Comment by lfcnassif** [comment]
> I thought a bit about these names since you brought this question, but couldn't find any possibly better alternatives.

Do you think "Referencing" is better than "References" for the new tab?

**Comment by lfcnassif** [comment]
> I thought a bit about these names since you brought this question, but couldn't find any possibly better alternatives.

Ok we can change just the localized strings later.

**Comment by lfcnassif** [comment]
Reopening. @FelipeFcosta just reported the new tab wasn't being displayed because he was using a custom saved layout. I thought about this, but forgot to test... Any suggestion @tc-wleite?

**Comment by tc-wleite** [comment]
> Reopening. @FelipeFcosta just reported the new tab wasn't being displayed because he was using a custom saved layout. I thought about this, but forgot to test... Any suggestion @tc-wleite?

Hmm, that is inconvenient. Not sure, but I think we need to write some code to check and handle this...
I can take a look on this, if you aren't already trying to find a solution.

**Comment by lfcnassif** [comment]
I'm not. If you have time to take a look, since you are already know the layout handling code, that would be great!

**Comment by tc-wleite** [comment]
> I'm not. If you have time to take a look, since you are already know the layout handling code, that would be great!

Sure! I will look into this.

**Comment by tc-wleite** [comment]
@lfcnassif, I opened a new bug issue (#1565). 
This affects any new panel, whenever the layout was saved with a previous IPED version, when the panel didn't exist.
For example, "Timeline" panel is also affected, if the layout was saved with 4.0.x.

**Comment by lfcnassif** [comment]
Oh... that's right! Thank you @tc-wleite!

**Comment by lfcnassif** [comment]
So I'm closing this, thanks!
