### ISSUE TITLE
Support decoding audio and video calls (missed or not) from android WhatsApp databases v2.22.8+

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1559]
An user reported above information is not being decoded by IPED-4.0.7 neither by 4.1.0. I thought support for them wasn't implemented in #1105, but looking at the code, seems it tries to handle those message types.

**Comment by lfcnassif** [comment]
Actually not sure if this is a bug or lack of support because the `call_log` table is not read in the SELECT query, but `mediaCaption` (used to test if the call is audio or video) is always returned as null intentionally, I think.

**Comment by lfcnassif** [comment]
I think it wasn't imemented and some code to handle old DBs was simply copied. @hauck-jvsh or @fmpfeifer do you know what the numbers from 0 to 5 in call_result column of call_log table means exactly? Or at least some of them?

**Comment by patrickdalla** [comment]
Though, this was the whatsapp version analysed by the article:  2.19.53

**Comment by lfcnassif** [comment]
Thanks @patrickdalla!

**Comment by lfcnassif** [comment]
@tc-wleite, since you are working on #1647, if you have available time, would it be possible to check in Cellebrite software to what kind of calls the call_result 3 refers to? Currently we show them as unknown... I guess it might be calls canceled by the origin, but I didn't have time to confirm it...

**Comment by lfcnassif** [comment]
> I checked here, analysing extracted database and what is shown by Whatsapp in the device, "**call_result = 3**" means "**Unavailable**".
> 
> This happens (or happened) when a connection can't be estabilished (e.g. the number called is not connected to the internet). I tried to reproduce it here, but couldn't. Not sure if WhatsApp changed its behavior, but I do have many calls (most recent one in September/2022) with "call_result = 3" (and shown as "Unavailable" in call history, "Indisponível" in Portuguese).
> 
> I include the change to handle this in the PR I am working on.

Great, thank you very much!!! And do you have call_result = 1 in the same DB? I haven't found it in the samples I have...

**Comment by tc-wleite** [comment]
> Great, thank you very much!!! And do you have call_result = 1 in the same DB? I haven't found it in the samples I have...

Not sure, I'll check here.

**Comment by tc-wleite** [comment]
> And do you have call_result = 1 in the same DB? 

No. I checked ~40 WhatsApp database samples, but none of them have any record with "call_result = 1".

**Comment by lfcnassif** [comment]
> No. I checked ~40 WhatsApp database samples, but none of them has any record with "call_result = 1".

Thank you for checking!
