### ISSUE TITLE
Better exception handling and logging messages when transcription service returns errors

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1564]
An user stopped the processing because of misleading error messages printed in the console (specific node down, but he thought the hole cluster was down). And for some errors, like no transcription node available, we should abort instead of just skipping the audio and continuing. For others, we should log WARN and not ERROR in the console.

**Comment by lfcnassif** [comment]
@tc-wleite, just found a minor issue, the ms/audio stat should be divided by numWorkers, right?

**Comment by tc-wleite** [comment]
> @tc-wleite, just found a minor issue, the ms/audio stat should be divided by numWorkers, right?

I am not sure. I guess it depends on how it was measure and what kind of measure you want to use.
As far as I remember, a similar measure for videos (something like the average time spent per video) is not divided by the number of workers/threads.

**Comment by lfcnassif** [comment]
Right, but I think current stat is a bit misleading, it confused me. I have a test case where AudioTranscriptTask took 157s (real), number of audios is 4,816 and that stat gave: `Average transcription time (ms/audio): 1582`. Can I change to output the average real (not cpu) time?

**Comment by tc-wleite** [comment]
> Right, but I think current stat is a bit misleading, it confused me. I have a test case where AudioTranscriptTask took 157s (real), number of audios is 4,816 and that stat gave: `Average transcription time (ms/audio): 1582`. 

I see... 
Maybe adding a second information, something like "Total audio transcription throughput" (in audios/s) would make things clearer. 
In you case that would be simply 4816/157= 30.7 audios/s (which is pretty fast, by the way).

**Comment by lfcnassif** [comment]
Fine!

**Comment by lfcnassif** [comment]
I'm reopening to fix additional issues I found in tests.

**Comment by lfcnassif** [comment]
I fixed the known issues. If more are reported before 4.1.1, I'll reopen this.
