### ISSUE TITLE
"Wait" progress does not hide after quick operation

### ISSUE THREAD

**Issue by patrickdalla** [sepinf-inc/IPED#1595]
Wait progress does not hides after quick file opening.
It seems that when the operation performed between setWaitVisible(true) and setWaitVisible(false) of the method waitEvidenceOpening of FileProcessor class is too quick, the setWaitVisible(false) is executed first, or not executed at all.
It can be reproduced opening an IPED index that has lost its reference to the original evidence file. As it cannot open the file, it returns quickly, but does not hides the progress dialog.

**Comment by tc-wleite** [comment]
I guess I experienced that same issue this weekend, because some evidence files were in a network storage temporarily unavailable.

@patrickdalla, I was planning to look into this later. 
Are you already working on it?

**Comment by patrickdalla** [comment]
You can work on this if you want.

**Comment by tc-wleite** [comment]
Ok, I will take a look on this then. Thanks!

**Comment by lfcnassif** [comment]
Since a try finally block is already used, maybe replacing the `SwingUtilities.invokeLater()` for `SwingUtilities.invokeAndWait()` inside `setWaitVisible()` would be enough? Not sure if it could have side effects...

**Comment by tc-wleite** [comment]
> I guess I experienced that same issue this weekend, because some evidence files were in a network storage temporarily unavailable.

Looking into this in more detail, I am not sure if the issue I observed was the same...

> Since a try finally block is already used, maybe replacing the `SwingUtilities.invokeLater()` for `SwingUtilities.invokeAndWait()` inside `setWaitVisible()` would be enough? Not sure if it could have side effects...

I guess it doesn't work because in the first, it will stop in setVisible(true) as this dialog is modal.

I thought events enqueued with `SwingUtilities.invokeLater()` were processed sequentially.
I tried a few things, but I couldn't reproduced the same issue.
@patrickdalla, did you check the execution log to confirm that an exception was thrown in this try/catch/finally block?

Anyway, I am making a few changes, trying to prevent the issue.

**Comment by tc-wleite** [comment]
> > I guess I experienced that same issue this weekend, because some evidence files were in a network storage temporarily unavailable.
> 
> Looking into this in more detail, I am not sure if the issue I observed was the same...

Now I remembered. My issue was when I was exporting many files (from different evidences), and a few of them were unavailable. The copy was aborted, but the export progress dialog remained opened.

**Comment by tc-wleite** [comment]
> I thought events enqueued with `SwingUtilities.invokeLater()` were processed sequentially. I tried a few things, but couldn't reproduced the same issue. @patrickdalla, did you check the execution log to confirm that an exception was thrown in this exactly try/catch/finally block?

I understand that Java API docs says that these events are indeed handled sequentially and in the same order as they were enqueued (http://docs.oracle.com/javase/8/docs/api/java/awt/EventQueue.html).

I tried putting a sleeps in different places, to force slow execution of the involved threads, but couldn't reproduce the described behavior. 
Maybe something else is going on...

**Comment by lfcnassif** [comment]
> I guess it doesn't work because in the first, it will stop in setVisible(true) as this dialog is modal.

Right!

> I thought events enqueued with `SwingUtilities.invokeLater()` were processed sequentially.

I also think this is true, but didn't check the docs.

> I tried a few things, but couldn't reproduced the same issue.

I also wasn't able to reproduce, even after renaming e01 and folder evidences location.

**Comment by lfcnassif** [comment]
> Now I remembered. My issue was when I was exporting many files (from different evidences), and a few of them were unavailable. The copy was aborted, but the export progress dialog remained opened.

Maybe we should make the dialog not modal again? This would avoid blocking the UI in case of different errors...

**Comment by tc-wleite** [comment]
> > Now I remembered. My issue was when I was exporting many files (from different evidences), and a few of them were unavailable. The copy was aborted, but the export progress dialog remained opened.
> 
> Maybe we should make the dialog not modal again? This would avoid blocking the UI in case of unexpected errors, also in other places...

The other dialog (export) I mentioned is not modal, so I didn't block me. But it was misleading because it remained opened as it was copying.
I am not sure about removing the modality. The user could do some other actions during this wait, which may lead to another unexpected behavior. The try/finally block seems robust enough, except if events were somehow enqueued in a diferent other. 
I think we can try to find out what caused the issue @patrickdalla reported first, and then decide. 
Not sure if @patrickdalla was using Linux. Maybe there is some platform specific behavior that allowed events being enqueue in a different order.

**Comment by patrickdalla** [comment]
I was using linux. Tomorrow i will test it better. But was some strange
error that when debugging with breakpoints, it doesn't occur. And when not
debbuging the wait is kept in the screen.
More strange is that,  i noticed you have said the progress dialog is
opened in modal mode, but the reminescent wait dialog does not block the UI.


Em seg., 20 de mar. de 2023 20:18, Wladimir Leite ***@***.***>
escreveu:

**Comment by lfcnassif** [comment]
> More strange is that, i noticed you have said the progress dialog is opened in modal mode, but the reminescent wait dialog does not block the UI.

I think we are talking about different dialogs here... maybe yours is related to text parsing in TextViewer, please send a screenshot tomorrow.

**Comment by patrickdalla** [comment]
I think this can be some swing/linux/jvm issue. See bellow that on my test today, what remained on screen was a grey rectangle where the dialog was. For some reason, that region painting is not completely occurring, sometimes leaving the original wait dialog image, sometimes leaving this grey rectangle.
![image](https://user-images.githubusercontent.com/28692427/226593484-a3dda71a-849b-46e4-9898-483a8a78765e.png)

**Comment by patrickdalla** [comment]
And it stays there even if I change to Dark theme.

**Comment by patrickdalla** [comment]
And logging it we can check that it is executed in the expected order, setVisible(true) before setVisible(false);

**Comment by tc-wleite** [comment]
I see. So it doesn't seem related to incorrect order of the events, right?
I saw this kind of paintings issues happening when there are exceptions (usually inside painting related code). Can you share an execution log so I can try to find something suspicious.

**Comment by patrickdalla** [comment]
2023-03-21 07:48:35	[INFO]	[engine.search.QueryBuilder]			Expanded query terms: []
2023-03-21 07:48:37	[INFO]	[app.ui.FileProcessor]			Opening Motorola GSM_XT1601_2022-04-13_Relatório.ufdr/Motorola GSM_XT1601.zip/sdcard/Download/1ª Lista de Exercícios – GA.pdf
java.nio.file.NoSuchFileException: /home/patrick.pdb/multicase/indices/indiceDebugGTK/../../../../../mnt/shares/10.65.6.6/MAT_LG_GTK13/UFDR/Motorola GSM_XT1601_2022-04-13_Relatório.ufdr
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
	at iped.engine.io.ZIPInputStreamFactory.init(ZIPInputStreamFactory.java:105)
	at iped.engine.io.ZIPInputStreamFactory.getSeekableInputStream(ZIPInputStreamFactory.java:160)
	at iped.engine.io.UFDRInputStreamFactory.getSeekableInputStream(UFDRInputStreamFactory.java:22)
	at iped.engine.data.Item.getSeekableInputStream(Item.java:562)
	at iped.app.ui.FileProcessor.waitEvidenceOpening(FileProcessor.java:203)
	at iped.app.ui.FileProcessor.process(FileProcessor.java:162)
	at iped.app.ui.FileProcessor.doInBackground(FileProcessor.java:127)
	at iped.app.ui.FileProcessor.doInBackground(FileProcessor.java:1)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-21 07:48:44	[INFO]	[app.ui.ColumnsManager]			Loading default columns

**Comment by patrickdalla** [comment]
Well... I could not find the cause, but I found a workaround. I saw that calling dialogBar.pack() before setVisible(false) was leaving on half the height of the dialog painted. So I changed the preferredSize to 0 before calling pack and restored it after setVisible to false. Now it hides completely.

`
    private void setWaitVisible(final boolean visible) {
        try {
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    if (visible) {
                        String prevMsg = App.get().progressBar.getString();
                        App.get().progressBar.setString(Messages.getString("FileProcessor.OpeningEvidence")); //$NON-NLS-1$
                        App.get().progressBar.setString(prevMsg);
                        App.get().dialogBar.setVisible(true);
                    } else {
                        Dimension d = App.get().dialogBar.getPreferredSize();
                        App.get().dialogBar.setPreferredSize(new Dimension(0,0));
                        App.get().dialogBar.pack();
                        App.get().dialogBar.setVisible(false);                        
                        App.get().dialogBar.setPreferredSize(d);
                    }
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
`

**Comment by patrickdalla** [comment]
A better implementation of this workaround would be to modify on the source object, declared in App class, like this:

        dialogBar = new JDialog(this, Dialog.ModalityType.DOCUMENT_MODAL) {
            @Override
            public void setVisible(boolean b) {
                if(!b) {
                    Dimension d = getPreferredSize();
                    setPreferredSize(new Dimension(0,0));
                    pack();
                    super.setVisible(b);
                    setPreferredSize(d);
                }
                super.setVisible(b);
            }
            
        };

**Comment by patrickdalla** [comment]
Should I push this workaround? Or anyone prefers to find a better/final solution?

**Comment by tc-wleite** [comment]
> Should I push this workaround? Or anyone prefers to find a better/final solution?

Let me take another look after the information you shared.

**Comment by tc-wleite** [comment]
> > Should I push this workaround? Or anyone prefers to find a better/final solution?
> 
> Let me take another look after the information you shared.

Forcing a NoSuchFileException, either very fast or taking some time, I still wasn't able to reproduce.

> Well... I could not find the cause, but I found a workaround. I saw that calling dialogBar.pack() before setVisible(false) was leaving on half the height of the dialog painted. So I changed the preferredSize to 0 before calling pack and restored it after setVisible to false. Now it hides completely.

About the workaround, what happens if the dialog needs to be shown again?
I tested the first code you posted, but it didn't work here. When FileProcessor shows the dialog for the second time (opening another evidence for the first time), nothing is shown. I guess setting the prefered size to zero makes the dialog invisible after that.
The second code you posted didn't work either, as it also made the dialog invisible after the first usage (before FileProcessor usage).

**Comment by patrickdalla** [comment]
> App.get().dialogBar.dispose();

It solved the original issue. I don't know about possible regressions in other places.

**Comment by tc-wleite** [comment]
That was a workaround suggested in the OpenJDK bug I mentioned.
In theory, `dispose()` could be used, but I am not sure if there could be side effects.
As it seems to help in the originally reported issue, I will try to make more test using it here.

**Comment by tc-wleite** [comment]
> Maybe we could recreate the dialog each time it is used?

I thought about that, but it doesn't seem to be necessary. 
I expect to make more tests until the end of the day, to check if only using dispose() in this particular piece of code doesn't introduce any side effects.
