### ISSUE TITLE
build test error in date format (timezone related)

### ISSUE THREAD

**Issue by abdalla-mar** [sepinf-inc/IPED#1596]
CertificateParserTest returning error on lines 70, 124 and 178 when building on a machine with timezone GMT-4. Building works when timezone is configured to GMT-3.

**Comment by lfcnassif** [comment]
Thanks for reporting.

**Comment by lfcnassif** [comment]
@FelipeFcosta did you write this test? Could you take a look at this?

**Comment by lfcnassif** [comment]
@abdalla-mar just fixed this, the time values being checked in those tests were wrong. And they were checking just days, month and year, not hour, minutes and seconds, so those tests used to pass in some timezones but not in others..
