### ISSUE TITLE
processing broken when -d parameter has a comma in the path

### ISSUE THREAD

**Issue by abdalla-mar** [sepinf-inc/IPED#1599]
-d parameter argument parsing is not working properly when the path has a comma in the name of the folder/file, even if passed inside quotes.

**Comment by lfcnassif** [comment]
Shouldn't #1597 fixed this? Could you test last snapshot?
https://github.com/sepinf-inc/IPED/actions/runs/4474292216

**Comment by lfcnassif** [comment]
Closing as duplicate, please reooen if it is not fixed.
