### ISSUE TITLE
Read WhatsApp account information from com.whatsapp_preferences_light.xml (Android)

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1610]
Seems the way WhatsApp stores account info changed at some point and now it is using com.whatsapp_preferences_light.xml file instead of com.whatsapp_preferences.xml.

**Comment by tc-wleite** [comment]
I confirmed this change in the cases I am working on.
@lfcnassif, I can look into this, if you (or someone else) haven't started.

**Comment by lfcnassif** [comment]
Hi @tc-wleite. I haven't. It was reported by an user and I just opened this to don't forget. If you have available time to take a look at this, that would be great, thank you very much!

**Comment by tc-wleite** [comment]
I found out that there are other two file names ("com.whatsapp.w4b_preferences_light.xml" and "com.whatsapp.w4b_preferences.xml") used by WhatsApp Business. 
I will try to handle them too.
