### ISSUE TITLE
OCRParserTests failing on Ubuntu 22.04 + tesseract-5.x

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1611]
Reported by a Linux user. This is strange because all tests pass on Windows + tesseract-5.0. I saw our previous intern configured tesseract-4.1.1 on remote CI tests, maybe because of this...

One of the failing tests are with this image:
![image](https://user-images.githubusercontent.com/7276994/228654840-7460f8de-1738-4672-a16b-8dca329ab947.png)

tesseract 5.0 result on windows:
```
| oil 57% CH 10:04 am

Lena
57 online

e

 

Oi, tudo bem? 24

 

Tudo certo, o que estamos fazendo
aqui? 247PM 4

Isso é um print para testar o
OCRParser. 2:51 PM

Boa sOrte GALeRa 2:522M 4

Type a message 3 6 O

```

tesserac-5.0 result sent by the user:
```
NNTA El EV

[NE
8” online

e

 

Oi, tudo bem? 24

 

Tudo certo, o que estamos fazendo
aqui? 247 PM Z

Isso é um print para testar o
OCRParser. 2:51 PM

Boa sOrte GALeRa 252PM Z

Type a message S 6 º

```

**Comment by lfcnassif** [comment]
@patrickdalla what is your Linux distro and tesseract installed version?

**Comment by patrickdalla** [comment]
Hi. My distro is Cento OS 8. tesseract installed was 4.1.1. I'm updating to 5.

**Comment by patrickdalla** [comment]
sorry, i could not compile tesseract yet. Does not exists a centos pack,
afaik.

Em ter., 4 de abr. de 2023 10:31, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by lfcnassif** [comment]
About this, if tesseract (or other important external tool like pffexport to handle OSTs) is not installed on user's machine, should the test fail or be skipped?

**Comment by lfcnassif** [comment]
> About this, if tesseract (or other important external tool like pffexport to handle OSTs) is not installed on user's machine, should the test fail or be skipped?

I'll keep current behavior to skip the test, to easy the building process for collaborators. If some Linux user runs IPED without some needed external tool, currently IPED warns on the Console.
