### ISSUE TITLE
Delete temp files leaked in temp folder by double click on UI

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1629]
The UI needs to create temp files to open them externally using the native application, when they are inside E01, Ex01, etc, or to avoid changing files processed from a mounted folder with write permission. Currently we don't try to delete them intentionally, because it may be difficult to know when the user stops to view/handle the temp files externally, but this causes a leak of temp files in user temp dir. I'm not sure if there is a safe way to know if user stopped to view the temp files, maybe deleting them if there is no system file handle opened, or after some time... Ideas?

**Comment by tc-wleite** [comment]
Currently, these temporary files are deleted when the analysis application is closed, right?

**Comment by lfcnassif** [comment]
Hum, good point! Tomorrow I'll check if that is done in all places and I think it may be enough to close this.
