### ISSUE TITLE
Menu option to check highlighted items and parents

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#1631]
Currently, we have the menu option `Check highlighted items and subitems`.
It would be interesting if we had an option `Check highlighted items and parents`.
The scenario this option could help is when there is a lot of analyzed Video Thumbnails (images) and it is necessary to check the related videos.

**Comment by lfcnassif** [comment]
Actually that was contributed code... Wouldn't it be enough to copy the parentId of highlighted items in metadata filter tab and search for them?

**Comment by aberenguel** [comment]
> Actually that was contributed code... Wouldn't it be enough to copy the parentId of highlighted items from metadata filter tab and search for them?

It would work. But it is an boring task that takes some time. In several cases we have to do that.
Some colleges already mentioned that this feature would help a lot.

**Comment by aberenguel** [comment]
@lfcnassif this is the old issue related to implementation I'm doing

**Comment by lfcnassif** [comment]
Sorry and thank you @aberenguel! My memory always tricks me...
