### ISSUE TITLE
Use RoaringBitmap internally to implement bookmarks

### ISSUE THREAD

**Issue by patrickdalla** [sepinf-inc/IPED#1632]
Although the current bookmark bitmap implementation is good, it would be a good option to use the best elected generic bitmap representation, RoaringBitmap, as it can be used directly to perform operations with other bitmaps, from filtermanager (#39) for example.

We can refactor the bookmark class or just add some interface method to return this RoaringBitmap.

**Comment by lfcnassif** [comment]
Agreed.

**Comment by wladimirleite** [comment]
I found a couple of issues working with a real case.
I am isolating them and will submit fixes in a new PR as soon as possible.

**Comment by wladimirleite** [comment]
It is possible to reproduce the exception mentioned in this comment https://github.com/sepinf-inc/IPED/pull/1648#issuecomment-2043026370 by following this steps:
- Create a bookmark A;
- Create a bookmark B;
- Delete bookmark A;
- Try to create a third bookmark C.
-

**Comment by lfcnassif** [comment]
Sorry @wladimirleite for causing issues with your real case analysis and thank you for investigating them.

**Comment by wladimirleite** [comment]
Sorry for not catching this before!
I worked during the past week on this same case, but the problem appeared in the first actions I took right after telling you that I finished the tests :-)

**Comment by wladimirleite** [comment]
I found (and fixed) another possible issue, just looking at the code, as BitmapBookmarks.filterNoBookmarks() doesn't seem to be used.
The other exceptions that I saw in the log doesn't seem to be related to this issue, so I will create a PR with the changes I made.
