### ISSUE TITLE
Create an option to make OCR skip known files

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1633]
Create a new option in OCRConfig.txt, similar to the one available for audio transcription, to skip known files.
When enabled, files (PDF and images) with `hashDb:status` = `known` would not be processed by OCR (which is usually a time consuming task).

@lfcnassif, any restriction about having this option?
Can its default value be enabled? 
Or is it better to leave the current behavior as default?

**Comment by lfcnassif** [comment]
Good idea! I think it is fine to enable it by default, although results can confuse some users, but they must read the release notes.
