### ISSUE TITLE
WhatsApp Business "externally" parsed HTMLs are included even if phoneParsersToUse is set to "internal"

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1644]
Using `phoneParsersToUse = internal` (in ParsingTaskConfig.txt), "external"  HTMLs are also being added to the case (together with the internally parsing results), for WhatsApp **Business**.
For the "regular" WhatsApp, the behavior is different, only including internally generated previews when "internal" configuration is used.

This is not the intended behavior, right?

**Comment by lfcnassif** [comment]
It's not, thanks @tc-wleite!
