### ISSUE TITLE
Handle some new (and common) WhatsApp system messages

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1647]
Handle the following new system messages, that are quite common nowadays in WhatsApp chats:

- Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.
- This chat is with a business account. Tap for more info.
- Missed group video call.
- This business account has now registered as a standard account. Tap for more info.
- You blocked this contact. Tap to unblock.
- Message deleted by you.
- Message deleted by the sender.
- This message was deleted by admin [NAME].
- [NAME] started a video call.

EDIT: Added a few more missing system messages I found here.

**Comment by gfd2020** [comment]
> Handle the following new system messages, that are quite common nowadays in WhatsApp chats:
> 
> * Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.
> * This chat is with a business account. Tap for more info.
> * Missed group video call.
> * This business account has now registered as a standard account. Tap for more info.
> * You blocked this contact. Tap to unblock.
> * Message deleted by you.
> * Message deleted by the sender.
> * This message was deleted by admin [NAME].
> * [NAME] started a video call.
> 
> EDIT: Added a few more missing system messages I found here.

Hi @tc-wleite . I saw that you are making some enhancements to Whatsapp. See this issue I opened, as a suggestion. I believe it is easy to implement.

https://github.com/sepinf-inc/IPED/issues/1287

**Comment by tc-wleite** [comment]
Hi @gfd2020!
Thanks for mentionng it!
I will try to take a look on this too.
