### ISSUE TITLE
Replace WhatsApp HTML preview fonts

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1654]
WhatsApp parser and other parser wrote based on it (e.g. Telegram) uses "Roboto-Medium" and "Roboto-Light" fonts.
However, these fonts are usually not present in Windows systems. 

I downloaded and installed them in my PC, but they show as "Roboto Medium" and "Roboto Light" (without an hyphen), so they weren't used. Not sure if that was an issue with the TTFs I used.

As the Roboto font is not found, in the PCs I tested, "Times New Roman" is used, which is kind of odd as Roboto is a sans-serif font while Times is serif.
Anyway, I suggest to replace Roboto by **Arial**, which is usually available and very similar to Roboto.

**Comment by tc-wleite** [comment]
@lfcnassif, I am sorry but I found a small CSS layout issue related to commit [7087a9b](https://github.com/sepinf-inc/IPED/commit/7087a9b74f6250ae9342b35cca3862567086a4bd) that made the balloon points of calls to be shown in a slightly wrong position.
I am submitting a small fix (that basically extends the mentioned commit to "special messages").

**Comment by lfcnassif** [comment]
Don't worry @tc-wleite, enjoy the holiday, thank you!

**Comment by tc-wleite** [comment]
> Don't worry @tc-wleite, enjoy the holiday, thank you!

Thanks! You too!
