### ISSUE TITLE
Improve WhatsApp emojis internal visualization quality 

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1655]
Currently emojis are displayed only in a single color (black), in the WhatsApp chats generated preview, when viewed in the internal IPED viewer. 
The quality is also not as good as shown in external browsers, making some emojis hard to identify in the internal viewer.

**Comment by tc-wleite** [comment]
This also applies to WhatsApp contacts and accounts.
An example:

Current:
![image](https://user-images.githubusercontent.com/7217001/233481134-3288c242-e713-40e8-8046-9317ec091b9f.png)

Improved:
![image](https://user-images.githubusercontent.com/7217001/233481195-6528cc1a-587c-47f7-8cfc-ff3418e8338f.png)

**Comment by lfcnassif** [comment]
Thank you @tc-wleite!
