### ISSUE TITLE
Transcription of huge files are being interrupted by timeout

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#1663]
When a huge file is being transcripted an error occur. This is because the nat being done has a timeout of 900 seconds and the transcription is taking more time to complete. I have some ideias:

1. Send one beacon per minute to keep the connection
2. Send partial transcriptions
3. Split huge files in the client

Which one do you think it is better?
Maybe more than one could be done.
@lfcnassif

**Comment by lfcnassif** [comment]
Well, 3 wouldn't change the communication protocol, but it has very bad side effects, like sending uncompressed audios or compressing them on client side again, wasting CPU...

And I think this can affect other small audios waiting for transcription, if a few huge audios are being transcribed at the same time, causing all waiting audios to timeout...

So, although it will change the communication protocol (what is already planned for #1345), I thin 1 is the best option, it is simple and beacons can be sent to all clients waiting for a transcription slot on the GPUs.

**Comment by hauck-jvsh** [comment]
I will try to not break compatibility, to do so, the client will send a message at the beginning with the protocol version. On the server side if the first message is the protocol version it will send the beacons, if it is MESSAGES.AUDIO_SIZE, I will not send the beacons. This will also allow future changes keeping backward compatibility.

**Comment by lfcnassif** [comment]
Great! Maybe sending the protocol version * (-1) will avoid misinterpretations of protocol version and audio size.

**Comment by lfcnassif** [comment]
Closed by #1667
