### ISSUE TITLE
Problems decoding Cyrillic and other unicode chars from registry files

### ISSUE THREAD

**Issue by NightShadow777** [sepinf-inc/IPED#1664]
Hi!
On time IPED build on Windows OS via maven 3.2.5
an error occurs in the file: GalleryModel.java line 251,
     image = ImageMetaDataUtil.getThumb(CloseShieldInputStream.wrap(stream);
Doesn't find the wrap method. I replaced with this code:
     image = ImageMetaDataUtil.getThumb(CloseShieldInputStream.nullInputStream());

Also during the build process, the following error occurs: commons-io was not found in iped-app, added to the pom.xml file:

       <dependency>
             <groupId>commons-io</groupId>
             <artifactId>commons-io</artifactId>
             <version>2.8.0</version>
         </dependency>

After these edits it was built successfully. When working with iPED, I noticed that it incorrectly processes Cyrillic.

P.S. I started to translate into Ukrainian and Russian lang...

**Comment by NightShadow777** [comment]
I am using Java JDK version 11.0.19+7. At first I wanted to build IntelliJ in the IDE, but it didn’t work out because 
couldn’t find the commons-io library, although I installed it manually through maven. Therefore, I downloaded maven 3.2.5 and decided to build it without an IDE, during the build there were also errors described above.

Cyrillic errors occur in:
- result of sqlite database parsing
- result of registry parsing username and path


Yes, I will help with the support of translations into Ukrainian and Russian, when they are ready I will send them to you.

There are a couple more ideas on the viber messenger, there is a ready-made module in python, but as a friend of the software, when I finish with the translations, I will try to make it for the iPed.

[screenshot.zip](https://github.com/sepinf-inc/IPED/files/11354290/screenshot.zip)

P.S. Sorry for the quality of the screenshots

**Comment by lfcnassif** [comment]
Great! Thank you very much again for helping the project!

I'll try to reproduce the building issues.

About the Cyrillic issues, would you be able to share a sample sqlite or registry file so we could reproduce the issues and test a future fix?

**Comment by NightShadow777** [comment]
happy weekend)

**Comment by lfcnassif** [comment]
> I will try to throw it on Monday, if possible it is better through whatsapp or telegram

Thank you very much, you can send them to my email on my profile if it works for you.

> I am using Java JDK version 11.0.19+7. At first I wanted to build IntelliJ in the IDE, but it didn’t work out because
> couldn’t find the commons-io library, although I installed it manually through maven. Therefore, I downloaded maven 3.2.5 and decided to build it without an IDE, during the build there were also errors described above.

I have just cloned master (I'm supposing you tried to build that branch, or not?) from scratch on another computer with Windows 10 and compiled the project using latest maven-3.9.1 and JDK 11.0.19 too, that finished without problems. The build is also working fine on Github CI (Ubuntu 22.04). Maven 3.2.5 is too old, from 2014. Please give the latest maven version a try.

> happy weekend)

To you too :-)

**Comment by NightShadow777** [comment]
Hi, @lfcnassif ! 
Files in which problems with Cyrillic were found were attached to the letter.
Thank you

**Comment by lfcnassif** [comment]
Thank you!

**Comment by lfcnassif** [comment]
Thanks for the files, I was able to reproduce the issues with sqlite and registry files parsing, a wrong charset is being used to read the results, I'll push the fixes shortly. I'll update the title to better describe the issue related to registry files and open a new one to better describe the issue with sqlite.

Please also test if the building with maven-3.9.1 still fails on your machine.
