### ISSUE TITLE
Timeline chart draw synchronization problems

### ISSUE THREAD

**Issue by patrickdalla** [sepinf-inc/IPED#1666]
I found 2 points of problems when navigating too quickly in timeline chart. 
One is in internal unsynchronized operations on rowTimestamps arraylist of acumultor object.
The other is with unsync ref access to datasets when printing the chart.

**Comment by lfcnassif** [comment]
Hi @patrickdalla, could you create another PR to fix this targeting the 4.1.x branch too?

**Comment by patrickdalla** [comment]
PR created with same modifications for 4.1.x.

**Comment by lfcnassif** [comment]
Fixed by [3c5c6ba](https://github.com/sepinf-inc/IPED/commit/3c5c6ba6a66dc63c1fa5b71544a2b9851dd28506)
