### ISSUE TITLE
Add support to pass the elasticsearch credentials by ENV vars

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#1671]
As it is already supported by the MinIO task, the elasticsearch task should accept receiving the credentials by Environmental Variables.

**Comment by lfcnassif** [comment]
@hauck-jvsh I think this was implemented by #1533, right?

**Comment by lfcnassif** [comment]
Closed by [6f5bb7f](https://github.com/sepinf-inc/IPED/pull/1634/commits/6f5bb7ff2f3eb1fcaf07849a1ae82a1154d1cc2f)

**Comment by hauck-jvsh** [comment]
Yes you are right, I just add it in the other branch that was changing a lot o things in this task.
