### ISSUE TITLE
Metadata with dots not being indexed on opensearch

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#1684]
I processed an evidence containing a PDF with the following metadata name "pdf:docinfo:custom:2.16.76.1.12.1.1" . This metadata fails to index as the opensearch interprets each dot as a subobject. I think that the best approach here is just replace the dots with underscores.
What do you think @lfcnassif ?

**Comment by lfcnassif** [comment]
Into the json sent? Putting all keys and values between double quotes maybe could fix this?

**Comment by hauck-jvsh** [comment]
Actually I just pass the string to a jsonBuilder `builder.array(key, values);`, so the string that is actually sent to opensearch is created bey the builder. I can try to add a quote to the key and see if it will resolve the problem.

**Comment by hauck-jvsh** [comment]
It works, but it index the double quote as part of the name, so to search the lucene query needs to be \"pdf\:2.16.76.1.12.1.1\:value".

**Comment by hauck-jvsh** [comment]
I think that the most common is the first one, as I found here https://discuss.elastic.co/t/how-to-handle-dot-in-field-names-in-es-7-0/176511/7, it was suggested by an elastic employee to replace dots with underscore.

**Comment by lfcnassif** [comment]
Ok, the first suggested approach seems fine to me.

**Comment by lfcnassif** [comment]
Fixed by [86e90ce](https://github.com/sepinf-inc/IPED/commit/86e90ce6a1edf9f6630cb56f9b4df2b71e62be12), thanks @hauck-jvsh.
