### ISSUE TITLE
Possible incorrect association between WhatsApp accounts and chats when there are multiple accounts (in Windows)

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1691]
While working with #1610, I noticed that sometimes the association between the WhatsApp account and the corresponding chats was wrong, when there are multiple accounts in the same evidence. 

Looking at WhatsApp parser code, it tries to match the account file path with the chat path. 
Although the logic is correct, item paths always use "/" as folder separator, but using `File.getParent()` to get the parent folder path as a String produces paths with "\\" when running in Windows, so paths won't match until the loop goes to the first level of path structure, which is the evidence name itself (no folder separator).

https://github.com/sepinf-inc/IPED/blob/234e9e24ebddd8335243ae82be8fa9999cb833de/iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/WhatsAppParser.java#LL810-L819

This is not common at all, as many accounts are being missed because of the change to use "light xml" and WA Business account files are not handled (both addressed by #1610). But once #1610 was implemented, this issue became more common.
I was able to reproduce the issue (in master and 4.1.1) processing a UFDR that contains two different WhatsApp (regular, not Business) accounts (DualSpace), and still used "com.whatsapp_preferences.xml".

**Comment by lfcnassif** [comment]
Thank you very much @tc-wleite for reporting and investigating this!
