### ISSUE TITLE
Any executable in the case root folder is being copied to the report destination folder

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1698]
When a UFDR is processed and the output folder is the same folder in which the UFDR is located, the final structure of files/folders looks like this:

```text
iped (folder)
CellebriteReader.exe
IPED-SearchApp.exe
Lista de Arquivos.csv
item01-moto-g6-plus.ufdr
```

The command line would be something like:

```text
java -jar iped.jar -d D:\XYZ\item01-moto-g6-plus.ufdr -o D:\XYZ
```

"CellebriteReader.exe" was there before processing (placed by Cellebrite Physical Analyzer when the UFDR was created, to allow opening it easily). 

After creating a report (using the report generation GUI option), "CellebriteReader.exe" is copied to the report destination folder.
I found this behavior a bit odd. Obviously, we simply delete "CellebriteReader.exe", as there is no UFDR in the destination folder.
@lfcnassif, is there any reason to copy all executables to the report folder, instead of just "IPED-SearchApp.exe"?

By the way, this was reported by a colleague here, later I reproduced it and found the code that implements this behavior.

**Comment by lfcnassif** [comment]
> @lfcnassif, is there any reason to copy all executables to the report folder, instead of just "IPED-SearchApp.exe"?

I don't remember of any specific reason, maybe this wasn't intentional, I think we can copy just IPED-SearchApp.exe

**Comment by tc-wleite** [comment]
Thanks! It is just a very small detail, but I think it is worth changing this to avoid confusion.
