### ISSUE TITLE
Load Timeline chart data structures just when it becomes visible

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1707]
This would avoid breaking the whole UI with OOM errors when large cases are opened, that happens today even if the feature is not used by the user.

**Comment by lfcnassif** [comment]
Hi @patrickdalla could you try to implement this?

**Comment by lfcnassif** [comment]
I would like to put this into 4.1.3 to make 4.1.x more stable.

**Comment by patrickdalla** [comment]
right

**Comment by patrickdalla** [comment]
Done and PR created. You can close with the PR.
