### ISSUE TITLE
Max heap memory used by analysis App can be greater than RAM

### ISSUE THREAD

**Issue by patrickdalla** [sepinf-inc/IPED#1712]
When opening IPED from "exe", it starts JVM with max heap size, "-Xmx" parameter, with value of 30G. It seems that JVM believes in this value, even if the real RAM installed is less than 30G, postponing some memory disallocation and halting IPED.

This IPED halting occurred in a case reported by Werner, during background timeline graph cache creation on a machine with 8GB of installed RAM, but testing the same case, I found that occurred also when toogling to timeline table view, even with timeline graph disabled, both processes that demand memory. The case worked when configured to use max heap size of 8GB, even with 3GB, but halted when executed via "exe".

**Comment by patrickdalla** [comment]
As nassif suggested, this max heap size can be corrected in Bootstrap class. I found that the following code returns the real installed mem size.
((com.sun.management.OperatingSystemMXBean) ManagementFactory.getOperatingSystemMXBean()).getTotalPhysicalMemorySize()

**Comment by lfcnassif** [comment]
Thanks @tc-wleite. Half the RAM seems reasonable. When processing, we need memory for other processes. When analyzing, we need memory to generate reports.

**Comment by lfcnassif** [comment]
Reopening, the switch introduced in #1713 should also handle lowercase units: g, m, k. If they are used, current code is interpreting the value always as bytes.

**Comment by patrickdalla** [comment]
Maybe this solution can cause some problem in Terminal Servers environment where the real RAM is huge, but there should be some memory usage limit between the different users, as more than one user can use IPED at the same time.
For example, in our TS, the machine has 192GB. This solution would start iped with Xmx as 48GB.

**Comment by wladimirleite** [comment]
@lfcnassif, just a minor detail...
As discussed many times, including in https://github.com/sepinf-inc/IPED/discussions/2047#discussioncomment-8137856, it is better to use less than 32 GB (not "-Xmx32G"), or much higher values (like more than 48G in machines with hundreds GB of RAM).
Using [JOL](https://github.com/openjdk/jol), I was able to find out that the exact threshold (in my environment) is 32736M (= 32GB - 32MB).
Usually I open the analysis UI through the EXE and my PC has 96 GB of RAM, so it will use -Xmx32G (%50 of RAM, limited to 32GB), which disables compressed OOPs, wasting some memory (which can be critical for large cases).
I suggest changing the maximum -Xmx value automatically set from 32G to 32500M.
