### ISSUE TITLE
Dead lock inside elasticsearch task

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#1721]
We were processing a case exporting the index to elasticsearch and a switch was reseted. After that, it entered in dead lock inside the elasticsearch task.

**Comment by lfcnassif** [comment]
Attaching the thread dump took by @hauck-jvsh:
[stack.txt](https://github.com/sepinf-inc/IPED/files/11805191/stack.txt)

**Comment by lfcnassif** [comment]
This seems to me an OpenSearch bug, since the asynchronous call `org.opensearch.client.RestHighLevelClient.bulkAsync(...)` at line 455 shouldn't block. @hauck-jvsh could you check on OpenSearch release notes since th version used by us if they fixed something related?

**Comment by hauck-jvsh** [comment]
I did not found anything related to this, but when I try to update the lib to the last version occurs a conflict of lucene versions. The last opensearch version is using Lucene 9.6

**Comment by lfcnassif** [comment]
> I did not found anything related to this, but when I try to update the lib to the last version occurs a conflict of lucene versions. The last opensearch version is using Lucene 9.6

We can upgrade lucene since 9.6 should be backwards compatible to 9.2:
https://cwiki.apache.org/confluence/display/lucene/BackwardsCompatibility
