### ISSUE TITLE
Add a notice about WhatsApp edited messages

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1725]
Seems this WhatsApp feature was released last month...

**Comment by tc-wleite** [comment]
> Seems this WhatsApp feature was released last month...

We discussed about this here last week.

It has to be checked, but thinking about how they implemented this, it is possible that the original record (in the SQLite) is update when a message is edited, or another record is created referencing the original one...

**Comment by tc-wleite** [comment]
As recently I worked on a few issues related to WhatsApp parser, I may take a look into this, unless someone else wants to.

**Comment by lfcnassif** [comment]
Thank you @tc-wleite! At least from my side, I don't plan to work on this in the near future.

**Comment by tc-wleite** [comment]
I have a couple of Android databases with edited messages and already found out how they are stored.
I still need to find iOS samples.
It seems the WA message edit feature is not that popular (like emojis reaction, for example).

Anyway, I will wait until another PR related to the WhatsApp parser (#1920) is merged before doing any code changes, to avoid possible future merging conflicts.

**Comment by lfcnassif** [comment]
> Anyway, I will wait until another PR related to the WhatsApp parser (#1920) is merged before doing any code changes, to avoid possible future merging conflicts.

I started reading your message and immediately thought about suggesting this :-)

**Comment by wladimirleite** [comment]
The only information available is that the message was edited, and when. So I am adding something like "Edited on 2024-01-06 18:14:00 -03:00". The message record is updated when edited, so the original content does not remain stored anywhere else.
