### ISSUE TITLE
Emule known.met parser can miss several entries

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#1730]
An user sent me a known.met with 14.165 entries and the IPED parser is getting only 3.042 entries.

**Comment by hauck-jvsh** [comment]
@tc-wleite, @lfcnassif 
I think that I found the problem, the bug is when an invalid entry is found several iterations of the for loop are used just to sync, prevent the last ones from being parsed. Just one thing, why do you test against a dataMin and dataMax? In this file there some files with more than 20 years, and this is starting the problem. Even after this fiz these files are not parsed, so instead if 14.165 entries the parser extracts 12.487.

**Comment by tc-wleite** [comment]
> why do you test against a dataMin and dataMax?

This decoder is also used by the carver, so the date check is used to filter garbage, together with other hard coded heuristics (like the number of parts and the number of tags). 
For active/valid files, these constraints should never be violated (in theory), so the bug you found usually doesn't happen.

What are the dates present in the file you have?
Maybe relaxing the date range from 20 to 30 years would be enough.

**Comment by hauck-jvsh** [comment]
I found dates the year 2000.

**Comment by lfcnassif** [comment]
> This decoder is also used by the carver, so the date check is used to filter garbage

Could the date range check be used just if a parameter, set by the carver, is set to true?

**Comment by hauck-jvsh** [comment]
Just to registry, the software emule met viewer can open those files.

**Comment by tc-wleite** [comment]
> That is how the original standalone parser used to work. We may change the behavior to check for constraints or not (using a parameter), as it was done. That would include the date check and also other checks that were based on the samples I collected over the years.

@hauck-jvsh, your submitted fix seems correct and necessary, but we still need to deal with the date range constraint to fully fix the issue, right? 
@lfcnassif, can we implement the change described above in the same PR?

**Comment by hauck-jvsh** [comment]
> @hauck-jvsh, your submitted fix seems correct and necessary, but we still need to deal with the date range constraint to fully fix the issue, right? 

Yes, you were right.

**Comment by tc-wleite** [comment]
> > @hauck-jvsh, your submitted fix seems correct and necessary, but we still need to deal with the date range constraint to fully fix the issue, right?
> 
> Yes, you are right.

Do you prefer to implement it yourself or should I complement your PR with the proposed removal of constraint checks?

**Comment by hauck-jvsh** [comment]
I think that you could do it as you have more knowledge of this parser.

**Comment by lfcnassif** [comment]
> @lfcnassif, can we implement the change described above in the same PR?

Sure!
