### ISSUE TITLE
Improve PDF file format carving

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1748]
According to PDF specification, if a PDF is edited (content replaced, added or deleted), the DIFF is appended to the end of the PDF file and a new Catalog and footer is added. Current PDF carving rule stops when the first footer is found, this is a known limitation:
https://github.com/sepinf-inc/IPED/blob/4.1.3/iped-app/resources/config/conf/CarverConfig.xml#L191

Similarly to EML carving, we could accumulate (valid) footers to recover the final PDF version (or all of them?). But determining if an additional footer is valid (and not from another PDF or just garbage) is not trivial. Maybe we can specify a maximum byte distance from the previous footer and perform some basic validation of the final PDF.

**Comment by patrickdalla** [comment]
According to PDF specs
"Conforming readers should read a PDF file from its end."

And immediatelly follows saying that there is a byte offset information right before, informing the position of the cross reference section (xref tag).

Maybe we could "accumulate" %%EOF hits (and a previous "xref" hit) , not immediatelly extracting a possible match, until a next %%EOF hit is found. If previous accumulated %%EOF are not inside the new found hit (based on the xref offset info), we can consider them as a complete PDF match, carve it, and start "accumulating" this new hit. The last %%EOF match at the end of the carving should also be considered a complete match.

**Comment by patrickdalla** [comment]
This could avoid incomplete PDF carving. I don't know if the PDF parser can somehow still parse partial PDF carving. If so, start hit should also be considered, to try to carve these unfinished PDFs pieces. But the xref offset info preceding the %%EOF could validate if the corresponding %%EOF found is part of the previous PDF header.

**Comment by lfcnassif** [comment]
> This could avoid incomplete PDF carving. I don't know if the PDF parser can somehow still parse partial PDF carving. If so, start hit should also be considered, to try to carve these unfinished PDFs pieces. But the xref offset info preceding the %%EOF could validate if the corresponding %%EOF found is part of the previous PDF header.

I think PDFParser is able to parse "incomplete" PDFs, since actually I think they are complete files, but an older version of the PDF. If possible, I think we should carve all versions.

**Comment by patrickdalla** [comment]
what a meant with partial pdf was a starting piece that had the end
overwritten or fragmented in a non continuous space, without any footer.

EmlParser is a good template to start from. The unique difference that can
be improved is, even if the last footer found is in a position greater than
the Max length, the xref offset info could be checked to see if it is
consistent, and if so, carve from till this footer.

Em ter., 5 de set. de 2023 16:29, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by lfcnassif** [comment]
Right. AFAIK current (and intended) carving behavior is to recover the file just if the footer is found (if it exists by the format spec).

**Comment by patrickdalla** [comment]
I've created a carver and pushed a commit. 

But the some extracted metadata of these edited PDFs are wrong, ex: pdf:charsPerPage and pdf:meta:character-count. It seems it double the count although the edition of PDF simply added a timestamp signature to the document. 

Maybe all of the metadata should be reviewed/improved.

**Comment by patrickdalla** [comment]
I reviewed and detected that xmp timestamps are being extracted without zone info. I've created the corresponding issue #1868.

**Comment by patrickdalla** [comment]
Some relevant metadata aren't extracted also. Like the /Subj that edited the file. Only the original creator was extracted.

**Comment by patrickdalla** [comment]
Another issue is that the PDF parser extracted only the last ModifyDate, althout there was 2 such tags, one for the first creation before the first %%EOF and the last for the second version/modification before the second %%EOF.

**Comment by patrickdalla** [comment]
I saw that since version 2.8 of tika PDFParser somehow parses these incremental updates, maybe extracting their metadata, if properly configured to do it (isParseIncrementalUpdates of PDFParserConfig class).

**Comment by patrickdalla** [comment]
The main initial purpose of this issue I think is covered by PR #1867.

But there is still improvements that can be done that maybe could result in another issue. The implementation of PR #1867 only carves a PDF if a TRAIL, HEADER and XREF signatures are found and a the corresponding XREF is located in the offset from HEADER informed right before the TRAIL. If these rules aren't matched, the carver does not carve as it surely incomplete and inconsistent.

Nonetheless, with some improvement, there would be possible to recover part of an incomplete PDF (overwritten or fragmented). I've made some tests have overwritten the start of a sample PDF with 11 pages and 5892665 bytes with 817753, 1534553, 2558553, 3582553, 4606553, 5630553 bytes of value 0 (in 6 other files). So, these files became without the HEADER signature.

These files could not be opened in Chrome Browser. Firefox, though, could render some pages: 8, 4, 2 pages of the first 3 least overwritten files (from least to most overwritten). The ICEPDF viewer could not view any pages of them and PDFBOX could not parse none of them.

So I have made a modification on org.apache.pdfbox.pdfparser.PDFParser from PDFBOX, so it ignores missed header version exception, and reconstructs some root structures based on a search for pages on XREF section informations. With these modifications, PDFBOX could show 10, 9, 6, 3, 2 pages of the 5 least overwritten files.

Maybe we can implement these changes and substitute ICEViewer with the PDFBOX viewer. What do you think @lfcnassif ?

**Comment by lfcnassif** [comment]
> Maybe we can implement these changes and substitute ICEViewer with the PDFBOX viewer. What do you think @lfcnassif ?

Hi @patrickdalla! I think you noticed we have a basic PDFBoxViewer implementation, not used until now. It still misses the highlight keyword hits feature, after an index search, it's a needed requirement. This viewer was created aiming to replace IcePdfViewer because it didn't support rendering embedded fonts in the past, but after @tc-wleite found IcePdf 7.0 and upgraded to it, that big limitation was gone. Anyway, I think using the same library for parsing and rendering can bring more consistent results.

About your PDFBox patch, it seems very nice! Is it possible to extend PDFBox instead of patching it? I wouldn't like to maintain another library fork, reapply patches on new versions, etc... Or do you think your patch would be welcomed by official PDFBox  project as an optional processing flag/constructor? If they accept it, things would be easier for us in the long run...

**Comment by patrickdalla** [comment]
I've created an issue there and Andreas Lehmkühler is analysing it: https://issues.apache.org/jira/browse/PDFBOX-5683

I've made some suggestions to make it more extendable. The current version (and the older version used by IPED) seems not extendable.

**Comment by patrickdalla** [comment]
Tika PDF parser uses PDDocument.load static method to load and parse the pdf content.
