### ISSUE TITLE
Creation of Indexed Report failed

### ISSUE THREAD

**Issue by mobab-th** [sepinf-inc/IPED#1756]
I've got an error on creating an "Indexed Report" 
Error message:
Caused by: java.lang.IllegalArgumentException: Inconsistency of field data structures across documents for field [mediaSize:number] of doc [4229]. doc values type: expected 'SORTED_SET', but it has 'SORTED_NUMERIC'.

[IPED-2023-07-06-09-28-54.log](https://github.com/sepinf-inc/IPED/files/11965981/IPED-2023-07-06-09-28-54.log)

Some parts in the log deleted for privacy reasons.

**Comment by lfcnassif** [comment]
Hi @mobab-th,

I see you are using version 4.1.0. Last 4.1.3 version fixed a similar issue in #1686. Are you trying to create a report from a multicase? Could you try to replace iped/lib and iped/localization folders within the case for those from 4.1.3 version, reopen the case and try to generate the report again?

**Comment by mobab-th** [comment]
with v 4.1.3 it works!
