### ISSUE TITLE
embed transcription in whatsapp chats

### ISSUE THREAD

**Issue by pettersonfaria** [sepinf-inc/IPED#1760]
When process evidence that has txt file referring to the transcription in the same folder as the opus file, place the text contained in the txt file below the audio in the whatsapp chats

**Comment by lfcnassif** [comment]
Could you better explain the use case? From what source that txt file come from?

**Comment by pettersonfaria** [comment]
Sure. 
Extractions using Avilla Forensics, generate a transcription txt file in same folder than opus file.
In this case, I can skip the transcription from iped and just index.
But in current version, iped do not reconize "foo.txt" like a fie relationated with "foo.opus", even if in same folder or have same "id"

> Could you better explain the use case? From what source that txt file come from?

**Comment by lfcnassif** [comment]
Of course we can't guess another software produces this kind of results. Opus and txt files with the same name pattern can show up in real world evidences and have nothing related to each other.

Anyway, I see no reason to support the output of other tool that doesn't respect the license terms of this project:
https://github.com/AvillaDaniel/AvillaForensics/issues/5

Please tell the author of AvillaForensics to respect the license of all used tools.

Closing as won't fix.

**Comment by pettersonfaria** [comment]
Thank you for answer.

**Comment by AvillaDaniel** [comment]
> Of course we can't guess another software produces this kind of results. Opus and txt files with the same name pattern can show up in real world evidences and have nothing related to each other.
> 
> Anyway, I see no reason to support the output of other tool that doesn't respect the license terms of this project: [AvillaDaniel/AvillaForensics#5](https://github.com/AvillaDaniel/AvillaForensics/issues/5)
> 
> Please tell the author of AvillaForensics to respect the license of all used tools.
> 
> Closing as won't fix.

I think the colleague couldn't explain it right, the txt is generated from the audio .opus. This txt only stores the audio transcript.

**Comment by AvillaDaniel** [comment]
Good evening, Avilla Forensics is a data extraction software, it uses other libraries with an Apache license, as the IPED is distributed by the GPL I will remove the IPED from my software.

**Comment by lfcnassif** [comment]
> I think the colleague couldn't explain it right, the txt is generated from the audio .opus. This txt only stores the audio transcript

I understood. I suggest you not changing the original evidence folder, users may be confused about what is original data and what was produced by the tool. It may be argued by lawyers in court.

> Good evening, Avilla Forensics is a data extraction software, it uses other libraries with an Apache license, as the IPED is distributed by the GPL I will remove the IPED from my software.

Thanks, it is appreciated. Alternatively you can publish the source code of your software as implied by GNU GPL v3. Both solutions are fine and enough.
