### ISSUE TITLE
Improve scrolling smoothness and responsiveness for large HTML WhatsApp chats

### ISSUE THREAD

**Issue by gfd2020** [sepinf-inc/IPED#1763]
Group chats tend to be large and have a lot of incoming messages. A real case with a html chat size of 5 MB was quite slow. The slowdown is caused by the chat bubble arrow. If you remove the 'position: relative' from the '#conversation .incoming' class and the 'position: absolute' from the '#conversation .incoming:before' class, the performance is much better. However, the arrow will be drawn wrong. It would be necessary to find another way of drawing it.

**Comment by lfcnassif** [comment]
Unfortunately CSS is not my best skill, so I'll defer to another dev.

**Comment by tc-wleite** [comment]
I can take a look on this when I return from vacation.

**Comment by gfd2020** [comment]
> Unfortunately CSS is not my best skill, so I'll defer to another dev.

I'm also not an expert in CSS but I managed to make the bubble in another way. I still need to test performance.

**Comment by lfcnassif** [comment]
Great, thank you @gfd2020! Please send a PR when ready so we can integrate your improvement.

**Comment by gfd2020** [comment]
> Great, thank you @gfd2020! Please send a PR when ready so we can integrate your improvement.

Just send the PR 1767. Just take a look and test, please.
