### ISSUE TITLE
Map tab sometimes renders locations but a blank Map

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1769]
This was reported by an user today, by another one a while ago, and also happened to me weeks ago. Not sure how to reproduce (maybe it is caused by one of the available map tiles in the first rendering time), but switching the tile server fixes the issue. Have you already noticed this @patrickdalla or anyone else?

**Comment by lfcnassif** [comment]
I was able to reproduce, closing and opening the application several times and changing the tile server, seems to be random. No error was printed in UI log. It seems to be triggered the the Google tile servers. When the issue happens, changing the tile server to any other one has no effect, map background stays gray.

**Comment by lfcnassif** [comment]
Reported by a 3rd user:
![IMG-20230722-WA0005](https://github.com/sepinf-inc/IPED/assets/7276994/e38619c0-e2d6-41eb-bc07-8f6ccd247814)

**Comment by abdalla-mar** [comment]
Also happened to me. Changing tile server back and forth between the 3 options under Leaflet solved the problem.

**Comment by lfcnassif** [comment]
Reported by a Spanish user yesterday. @patrickdalla could you take a look at this when you have available time? Unfortunately I'm not sure exactly how to reproduce, it seems a bit random...

**Comment by patrickdalla** [comment]
I tryed a lot but could not repeat the error.

Em qua., 9 de ago. de 2023 15:20, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by lfcnassif** [comment]
> I tryed a lot but could not repeat the error.

Thanks for trying! I understand random errors without a reproducible step by step are hard to tackle...

**Comment by hauck-jvsh** [comment]
Three users reported this to me, I was able to reproduce it in a clean machine, which never have executed the ipedsearch app, I open IPED and the map was not loaded. The issue is resolved if change the font from Bing to openstreet maps, after that the users can change back to Bing and the issue didn't in the next time. Even opening different cases.

**Comment by lfcnassif** [comment]
I tried to reproduce it before deleting the user_home\.iped\last_tileserver.txt file, it didn't work. @hauck-jvsh said deleting the whole .iped folder worked to him to reproduce, but it didn't to me...

**Comment by lfcnassif** [comment]
> I tried to reproduce it before deleting the user_home.iped\last_tileserver.txt file, it didn't work. @hauck-jvsh said deleting the whole .iped folder worked to him to reproduce, but it didn't to me...

My fault, I was testing on a patched 4.1.3 version, on released 4.1.3 simply deleting that file or deleting its contents is enough to reproduce the issue consistently.

**Comment by hauck-jvsh** [comment]
I was able to reproduce just deleting the last_tileserver file, as @lfcnassif said.

**Comment by lfcnassif** [comment]
Tried to apply 2 quick fixes but they didn't work and my time is over for today... Since now we have a step to reproduce, I'll leave this to @patrickdalla that has better knowledge about the map code.

**Comment by lfcnassif** [comment]
Maybe I'll roll a new release after this is fixed, since it is affecting many users...

**Comment by lfcnassif** [comment]
PS: master branch is not affected.

**Comment by lfcnassif** [comment]
Just found the fix in the middle of a commit with an unrelated description:
dba8360b58773d0907008e54d7c73f3d8c28b7be

Maybe the issue was introduced in the middle of an implementation and not copied to 4.1.3, a clearer commit message, or a separate commit, may have helped to copy it.

Anyway, just applied to 4.1.x branch and seems fixed. So closing.

**Comment by lfcnassif** [comment]
Just confirmed this affects versions 4.1.0 to 4.1.3

**Comment by patrickdalla** [comment]
Humm, I've noted my tests were done on patched master or on already opened
cases.

Sorry and thanks for the help with the solution.

Em qui., 10 de ago. de 2023 19:48, Luis Filipe Nassif <
***@***.***> escreveu:
