### ISSUE TITLE
Problema em indexação no SSD

### ISSUE THREAD

**Issue by alvarolucasno** [sepinf-inc/IPED#1780]
Colegas, primeiramente parabéns pelo projeto.

Seguindo pra o problema, aconteceu que em um processo de indexação de evidências a partir de um computador com SSD, o processo travou em determinado momento. 

Ao verificar o windows, notei que ele também havia travado.

Ao reiniciar o computador percebi que o SSD não estava em funcionamento mais e havia queimado.

Estou reportando porque isso aconteceu com outro colega também.

**Comment by lfcnassif** [comment]
This seems a hardware issue with your SSD, a software can't damage it in normal usage conditions. Try to use a better quality SSD.
