### ISSUE TITLE
Cannot access evidence data

### ISSUE THREAD

**Issue by gfd2020** [sepinf-inc/IPED#1781]
I cannot access the processing entry evidence data. More precisely in the case of UFDR and AD1 files ( source files ).
Is this right?

![image](https://github.com/sepinf-inc/IPED/assets/59742865/99984973-61ae-4a1f-8ee8-fa5728d6ac05)

**Comment by lfcnassif** [comment]
You mean when you click on the source AD1 or UFDR? I think the content is left empty to avoid computing hashes, parsing raw strings, indexing garbage, etc...

For HDD related content, we do some workaround in code to avoid processing it, but to show its raw content on UI. Maybe we could generalize the behavior to other sources.

**Comment by gfd2020** [comment]
> You mean when you click on the source AD1 or UFDR? I think the content is left empty to avoid computing hashes, parsing raw strings, indexing garbage, etc...

Yes. That's the case. ( E01 files still can be accessed )

But because of that I can't export that file ( on UI ), and I also lost the evidence path reference ( datasourcepath is empty, datasourceinputstream is empty ... ).

**Comment by lfcnassif** [comment]
> I also lost the evidence path reference ( datasourcepath is empty, datasourceinputstream is empty ... ).

I think those properties are populated for items extracted from/contained into those data sources, or not?

About opening an E01 into Hex viewer, that seems useful to me since the decompressed content (the raw DD content) is shown, making it possible to do seaches for terms or regexes into the raw image content. But since AD1 and UFDR are compressed and they are logical files containers, what would be rendered into HEX viewer?

**Comment by gfd2020** [comment]
> I think those properties are populated for items extracted from/contained into those data sources, or not?

Yes. They are.

> About opening an E01 into Hex viewer, that seems useful to me since the decompressed content (the raw DD content) is shown, making it possible to do searches for terms (choosing the desired charset) or regexes into the raw image content. But since AD1 and UFDR are compressed and they are logical files containers, what should be rendered into HEX viewer? PS: Displaying the compressed content seems not useful to me.

Yes. I agree. Just wanted to point out that they are not displayed.

**Comment by gfd2020** [comment]
How @lfcnassif  clarified the issue. I think this issue can be closed.
