### ISSUE TITLE
Upgrade to Lucene to 9.x

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#179]
We are using a very old 4.9 version. A lot of Lucene APIs changed and it will need some work. This is a sensible upgrade and will break back compatibility. At least Lucene query performance and memory usage evolved a lot in 2018 and 2019: https://home.apache.org/~mikemccand/lucenebench/

TermQueries increased from 40/s to 1k/s !

**Comment by lfcnassif** [comment]
updated to lucene-5.5.5 as a first step in 17babcd2a9099ed21e333e9012da7d19873c5fce

**Comment by lfcnassif** [comment]
I'm resuming this work. It's harder than expected, because DocValues, used in lots of places, are not random accessible anymore since Lucene 7.0:
https://issues.apache.org/jira/browse/LUCENE-7407

**Comment by lfcnassif** [comment]
Lucene 9.0.0 was recently released: https://lucene.apache.org/core/corenews.html#apache-lucenetm-900-available
I highlight `Support for indexing high-dimensionality numeric vectors to perform nearest-neighbor search, using the Hierarchical Navigable Small World graph algorithm`
It is a state-of-the-art algorithm that could be used in photoDNA, similar images, similar faces and future vector based features look up.
But `Lucene 9.0 requires JDK 11 or newer`.

What other devs think about setting JDK 11 as minimum version for IPED, as it will use by default the embedded JDK 11 at processing and analysis time? Users won't have issues if they use the *.exe files and will receive a warning before exit if they execute the *.jar files with an older JDK version.
I'm +1.

**Comment by fmpfeifer** [comment]
I think that JDK 11 as minimum requirement is almost mandatory now.
Supporting JDK 8 is already holding us back.
my 2p.

**Comment by lfcnassif** [comment]
> Supporting JDK 8 is already holding us back.

What JDK 11 feature/library would you like to use?
