### ISSUE TITLE
Avoid adding video: prefix to video transcription results

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1801]
Just tested transcription on videos simply adding `video` into `mimesToProcess` in `AudioTranscriptConfig`. I thought it would be necessary to change the `convertCommand` (and that's why I exposed it to interested users) but it wasn't needed (reported by @hauck-jvsh before).

But transcription results are being prefixed by `video:`. That's not good because it splits results between different properties and it also avoids to embed the video transcriptions into chats properly.

**Comment by lfcnassif** [comment]
Tagging as enhancement since transcribing videos wasn't the original intent.

**Comment by hauck-jvsh** [comment]
I don't know if it is a goo idea to expose this, as it will send the entire video file, which maybe large, over the network. In this case I think that the audio should be extracted in the client.

**Comment by tc-wleite** [comment]
I agree. For videos, running MPlayer locally before sending to transcription server makes more sense.

Another detail, maybe the conversion command can be slightly changed to improve performance, completely ignoring the video channel. Not sure if it already does that. I will check this later and update here.

**Comment by lfcnassif** [comment]
Thanks @hauck-jvsh, I agree, but the option was already exposed, user was already able to change the configuration, I just fixed the property name. Let's open another ticket to improve video transcription resource usage.

Thanks @tc-wleite, let us know if the command can be improved.

**Comment by lfcnassif** [comment]
I changed my mind and will tag this as bug.
