### ISSUE TITLE
Unzip Libreoffice files to a AppData\Local directory

### ISSUE THREAD

**Issue by gaffinet** [sepinf-inc/IPED#181]
Hi

During the first launch, IPED copies about 400MB to the directory .indexador

![grafik](https://user-images.githubusercontent.com/9380336/86484472-969e1100-bd56-11ea-8f8c-9105a96daf89.png)

This is an issue in our cooperate environment, because it's blowing up the quota on the user profile.

I think an alternative would be to unzip the files in a temporary folder or perhaps in .\AppData\(Low)Local

**Comment by lfcnassif** [comment]
Hum, don't files under AppData use user quota?

**Comment by gaffinet** [comment]
I'm not sure about appdata\local, but it seams that "by default" this is not included in the roaming profile. 

To be on the safe side, the use of a temporary would be better, but this risks to slowdown the start of iped if the temp directory is cleaned regularly.

**Comment by lfcnassif** [comment]
java default temp dir on Windows is often c:\users\{user}\appdata\Local\Temp but iped user gui uses the same temp configured for processing in LocalConfig.txt if available.

I don't think storing libreoffice in a temp dir is a good idea as you pointed.

We can change to AppData\Local if that would work by default on most systems. That works for you?

**Comment by gaffinet** [comment]
yes, I think it's worth to try this. It will also overstuff less the home folder of the user
