### ISSUE TITLE
Include most python libraries in Windows binary distribution?

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1820]
I have already received this suggestion before. Originally I left installation to end user to avoid issues with portability of dependencies on different environments.

Some deps don't have python wheels and need compilation, depending sometimes on Visual Studio specific SDKs, which makes compilation a hell even for developers. For those cases, I embedded the compiled DLL and its dependencies. So, it may be possible to do this for all python libraries, if needed.

If portability is achieved fine there are 2 drawbacks:
1. Distribution package can increase in about 1.5GB (I don't plan to include tensorflow since I plan to replace YahooNFSW for another CSAM detection module)
2. This can bloat Linux users

Another option would be to distributed a separate IPED python package distribution...

Thoughts?

**Comment by lfcnassif** [comment]
This would also allow us to change default transcription algorithm from Vosk to Wav2Vec2.

**Comment by aberenguel** [comment]
I think it would be good if we had something like a plugin. The main release package would be released like it is being done now. And there would be another release file `iped-python.zip`. 
It would be even better if it existed two releases:  `iped-python-windows.zip` and `iped-python-linux.zip`. It would avoid some tricks among linux distributions.

**Comment by lfcnassif** [comment]
Well, I'm not a daily Linux user, so I would have difficulties to maintain a Linux package distro. If some Linux guy helps to maintain the Linux distro, that would be great! An old related idea is to provide a Linux installation script to download or compile all IPED Linux dependencies.

**Comment by tc-wleite** [comment]
Thinking about Windows users, this will be very useful.

**Comment by aberenguel** [comment]
> Well, I'm not a daily Linux user, so I would have difficulties to maintain a Linux package distro. If some Linux guy helps to maintain the Linux distro, that would be great! An old related idea is to provide a Linux installation script to install or compile all IPED Linux dependencies.

I could help to maintain the linux package. Even better it we could to build it in CI. 
I think that use a Python virtual environments could facilitate the package generation.

**Comment by aberenguel** [comment]
> Some deps don't have python wheels and need compilation, depending sometimes on Visual Studio specific SDKs, which makes compilation a hell even for developers. For those cases, I embedded the compiled DLL and its dependencies. So, it may be possible to do this for all python libraries, if needed.

Which deps we have to compile?

**Comment by lfcnassif** [comment]
> > Some deps don't have python wheels and need compilation, depending sometimes on Visual Studio specific SDKs, which makes compilation a hell even for developers. For those cases, I embedded the compiled DLL and its dependencies. So, it may be possible to do this for all python libraries, if needed.
> 
> Which deps we have to compile?

Sorry for my delay. On Windows, JEP and dlib (face_recognition dependency) are not straightforward to compile, so I distributed them already compiled and with their deps. But I think they are easy to compile/install on Linux.

Additionally to python dependencies, there are the old IPED external dependencies (https://github.com/sepinf-inc/IPED/wiki/Linux). At least our Sleuthkit fork and libagdb need to be compiled.

**Comment by aberenguel** [comment]
Recently I edited the document https://github.com/sepinf-inc/IPED/wiki/User-Manual#python-modules
I was having some issues using IPED in Ubuntu 22.03.
To summarize, I had to use python virtual environments, which in a nutshell creates a folder with such strucuture:
```
.
├── bin
│   ├── activate
│   ├── activate.csh
│   ├── activate.fish
│   ├── Activate.ps1
│   ├── pip
│   ├── pip3
│   ├── pip3.11
│   ├── python -> /usr/bin/python
│   ├── python3 -> python
│   └── python3.11 -> python
├── include
│   └── python3.11
├── lib
│   └── python3.11
│       └── site-packages
│           ├── _distutils_hack
│           │   ├── __init__.py
│           │   ├── override.py
│           │   └── __pycache__
│           │       ├── __init__.cpython-311.pyc
│           │       └── override.cpython-311.pyc
│           ├── distutils-precedence.pth
│           ├── pip
│           │   ├── __init__.py
│           │   ├── _internal

[...]
```

I set up the virtual environment with this commands in a  `ubuntu:22.04` docker container:
```sh
# install dependencies
apt update
apt install python3.10 python3.10-venv openjdk-11-jdk gcc libpython3.10-dev cmake

# create and prepare the environment
python -m venv test
source test/bin/activate

# install pip modules
pip install jep==4.0.3
pip install numpy
pip install keras
pip install tensorflow
pip install pillow
pip install face_recognition
pip install opencv-python
pip install huggingsound
pip install bs4

# replace symbolic link
rm test/bin/python3
cp /usr/bin/python3 test/bin/python3
```

I resulted in a folder with 4.1 GB.
```sh
du test/ -sh
4.1G    test/
```

**Comment by patrickdalla** [comment]
> I think it would be good if we had something like a plugin. The main release package would be released like it is being done now. And there would be another release file `iped-python.zip`. 
> It would be even better if it existed two releases:  `iped-python-windows.zip` and `iped-python-linux.zip`. It would avoid some tricks among linux distributions. 

I think this is good. There is already the docker distribution maintained by @arisjr . 

I, personally, use my own prepared linux container docker, but just to have more control of the docker container. But use docker distributions on linux is very straightforward.

**Comment by lfcnassif** [comment]
> Recently I edited the document https://github.com/sepinf-inc/IPED/wiki/User-Manual#python-modules because I was having some issues using IPED in Ubuntu 22.03.

Thanks for helping to improve the docs!

> I resulted in a folder with 4.1 GB.

Tensorflow is very large...

**Comment by arisjr** [comment]
> Tensorflow is very large...

On ipeddocker/iped, we used to add **all** python modules, but we have recently (maybe a week ago) removed larger and less frequent used modules (like tensorflow) and GPU support due limitations imposed by github actions environment quota.

But since I'm entering on this thread, I would like to leave a desired change: to be added face_recognition and its dependencies support on default analysis results. It's a very nice feature to have on windows analysis environment. :)

**Comment by lfcnassif** [comment]
> But since I'm entering on this thread, I would like to leave a desired change: to be added face_recognition and its dependencies support on default processing results. It's a very nice feature to have on windows analysis environment. :)

Do you mean to enable it on default profile? I think face recognition needs more 250MB, not that much, so the search for internal faces from the case would work. Another think is to search for external faces, that would need us to distribute python + face recognition with the case, so it could work on machines that had never run IPED processing (the UI tries to find the IPED "installation" folder and to reuse its python). One option would be to install face recognition on user machine on demand, anyway portable python would need to be distributed.

**Comment by lfcnassif** [comment]
By the way, have any of you ever used YahooNSFW nudity detection? Since I think to replace it, I would like to know how was your experience.

**Comment by lfcnassif** [comment]
Just updated last release page with a pre-built python plugins package for Windows.

@aberenguel I have no idea if it is possible to do something similar for Linux, just download, unzip and replace the package, since, for now, IPED uses the system (or current virtual env) installed python.

**Comment by lfcnassif** [comment]
Since I published a python plugins package for Windows, I'll close this. If any of you can help to create something similar for Linux (@aberenguel?), or a Linux installation script, please let me know so we can open another ticket to track the progress.

**Comment by aberenguel** [comment]
I'll try to make a package that is almost independent of Linux distribution. I have seen the virtual environments has absolute paths hard-coded in some parts of the scripts. So I have to circumvent this issue and make some tests. 
The intention is to use the python folder like Windows.
