### ISSUE TITLE
New transcription implementation using Whisper

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1823]
As asked on #1335, we can offer Whisper for users and they can decide if they will pay the performance cost or not. Still not sure which would be better: Faster-Whisper or Whisper-JAX.

**Comment by lfcnassif** [comment]
I have some sad news regarding Whisper-JAX, I managed to run it on Linux. Unfortunately it took a bit more than 4h to transcribe my 29h test data set using Whisper medium model and running on one RTX3090. It also used a ton of GPU memory, about 19GB to load the medium model, while standard Whisper uses about 11GB and Faster-Whisper about 5GB, both for the larger model. Faster-Whisper took about 3h to do the same job using the medium model.

So, given the much higher memory usage and a bit slower performance of Whisper-JAX, at least on the hardware we have, Faster-Whisper seems a better option.

**Comment by lfcnassif** [comment]
PS: JAX support on Windows is also experimental and CPU only.

**Comment by joasource** [comment]
You probably already know, but Whisper runs very well with PyTorch using CUDA 11.6. In fact, the best GUI implementation I've seen is this one: https://grisk.itch.io/whisper-gui.

By the way, do you have any plans to implement Whisper in IPED?

**Comment by joasource** [comment]
You probably already know, but Whisper runs very smoothly with PyTorch using CUDA 11.6. In fact, the best GUI implementation I've seen is this one: https://grisk.itch.io/whisper-gui.

I'm eagerly awaiting Whisper on IPED.

**Comment by lfcnassif** [comment]
We plan to integrate Whisper in version 4.2.0, to be released in some weeks. If you can't wait, there is a starting draft code here:
https://github.com/sepinf-inc/IPED/issues/1335#issuecomment-1644745545

**Comment by lfcnassif** [comment]
Starting to work on this...

**Comment by joasource** [comment]
> Starting to work on this...

Wonderful. Any release date forecast?

**Comment by lfcnassif** [comment]
> Wonderful. Any release date forecast?

Hopefully next month.

**Comment by lfcnassif** [comment]
For those interested, a snapshot with this feature will be created here in a few minutes:
https://github.com/sepinf-inc/IPED/actions/runs/9238362650
