### ISSUE TITLE
Select and unselect all events button on timeline page

### ISSUE THREAD

**Issue by felipecostadesousa** [sepinf-inc/IPED#1830]

**Comment by felipecostadesousa** [comment]
Hello @patrickdalla! I'm trying to develop 2 buttons to select and unselect all events from the timeline page. So I would like to ask you about the code "IpedChartPanel" and "LegendItemPopupMenu" that you developed! I couldn't find how to change the stage of the event to selected/unselected when you click and it gets blue! And I got confused about the "show" method on "LegendItemPopupMenu", there are many booleans values about selectionContainsExcluded/Included/Hidden that I didn't understand.

**Comment by patrickdalla** [comment]
Hi @felipecostadesousa.

First we need to define well this feature: Does the selection state should be reflected somehow in the timeline chart? This would demand a little more work, and maybe is such a necessity.

If not, there would not be necessary to reflect this state, so the items on menu should always be shown, without any necessity to modify the "show" method.

**Comment by patrickdalla** [comment]
In the map tab we made this selection state sync with the table as the items are shown individually. But in timeline, as items are grouped, I don't know if it would worth the effort to reflect this state, and maybe it can be confusing? What would be shown if some but not all items of that eventType are already selected, for example, going to the table view and deselection some items?

**Comment by patrickdalla** [comment]
Hi, I think I understood wrongly the issue. Anyway, this is done. Please test @felipecostadesousa.
I also implemented the feature I thought was asked. It seems useful and as it is already implemented, I will create a corresponding issue to document it.
