### ISSUE TITLE
Transcribing audios with more than 2GB on remote service never ends

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#1833]
@arisjr Sent to me two audio files with more than 2GB and they aren't being processed correctly, the server log shows the following error 

> 21:52:55.767 [pool-1-thread-1714] INFO  iped.engine.task.transcript.RemoteWav2Vec2Service - Client 10.244.3.0:50890 - Accepted connection.
21:52:55.767 [pool-1-thread-1714] INFO  iped.engine.task.transcript.RemoteWav2Vec2Service - Protocol Version VERSION_1_1
21:52:55.767 [pool-1-thread-1714] INFO  iped.engine.task.transcript.RemoteWav2Vec2Service - Client 10.244.3.0:50890 - Receiving -2,028,500,146 bytes...
21:52:55.768 [pool-1-thread-1714] WARN  iped.engine.task.transcript.RemoteWav2Vec2Service - Exception while transcribing
java.io.IOException: Received less audio bytes than expected
        at iped.engine.task.transcript.RemoteWav2Vec2Service$2.run(RemoteWav2Vec2Service.java:353) [iped-engine-4.2-snapshot.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

I think that this is due to an integer overflow as the receiving bytes  shown is a negative number.

**Comment by hauck-jvsh** [comment]
Just one thing that I think is worth of notice, this was making the processing to enter in loop, as it thinks it is a network problem it tries again indefinitely.

**Comment by lfcnassif** [comment]
Seems this was introduced when we changed the approach to send original audios instead of wav parts, when chunks larger then 2GB would not happen.
