### ISSUE TITLE
Fix links to audio and videos in WhatsApp chats, if files are in an input folder.

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1840]
When a WhatsApp chat preview is externally opened, attached files may be in their original location (when a folder is processed) or in the exported folder. There is a JavaScript function to choose which location should be used.
Currently, it is working only for images. For audios, videos and other files (like PDFs) it always tries to use the exported folder location, so it will fail if items weren't exported AND the original file is in a visible folder (it won't work if attachments are inside a UFDR or a E01).

See https://github.com/sepinf-inc/IPED/issues/1836#issuecomment-1690690329

**Comment by lfcnassif** [comment]
Hi @tc-wleite, just a comment about this issue. Although our agency common use case is processing UFDRs, I know others use the tool to process raw data extracted from cellphones in a mounted folder, although that is not officially supported by the tool today. So this is important to work for some users, indeed. Thank you for helping with this!

**Comment by tc-wleite** [comment]
> Although our agency common use case is processing UFDRs, I know others use the tool to process raw data extracted from cellphones in a mounted folder, although that is not officially supported by the tool today. So this is important to work for some users, indeed.

I see... didn't know about that.

**Comment by gfd2020** [comment]
> Hi @tc-wleite, just a comment about this issue. Although our agency common use case is processing UFDRs, I know others use the tool to process raw data extracted from cellphones in a mounted folder, although that is not officially supported by the tool today. So this is important to work for some users, indeed. Thank you for helping with this!

But in some cases it is possible to find whatsapp files in backups made by Itunes inside a PC, right?

**Comment by lfcnassif** [comment]
> But in some cases it is possible to find whatsapp files in backups made by Itunes inside a PC, right?

Yes! But since attachments would he located into DD/E01 files, links to them wouldn't work either when double clicking on the chats from UI. We have an open enhancement for this to work and some investigators would like it very much: https://github.com/sepinf-inc/IPED/issues/369
