### ISSUE TITLE
Improve layout for audio and video tags in whatsapp chats opened in browser

### ISSUE THREAD

**Issue by gfd2020** [sepinf-inc/IPED#1842]
The audio and video controls may broken html layout on browser ( whatsapp html chats).

![image](https://github.com/sepinf-inc/IPED/assets/59742865/26e4eefb-d509-40d9-bf70-aea62ce9a9b3)

Repair suggestion below ( CSS ) - Tested on PR 1767:

video {
	max-width:100%;
    display: block;
}
audio {
	max-width:100%;
	width:550px;
    display: block;    
}

**Comment by tc-wleite** [comment]
Thanks @gfd2020!

I added a `<br>` after audio/video titles (commit [8a7604f](https://github.com/sepinf-inc/IPED/pull/1841/commits/8a7604fe140b1cb21ac4f224593a4589b1683d12)) and it seems to have a similar effect of `display: block;`.

I liked the wider audio control. 
Do you want to create a PR yourself, or may I include this in PR #1840?

**Comment by gfd2020** [comment]
> Thanks @gfd2020!
> 
> I added a `<br>` after audio/video titles (commit [8a7604f](https://github.com/sepinf-inc/IPED/pull/1841/commits/8a7604fe140b1cb21ac4f224593a4589b1683d12)) and it seems to have a similar effect of `display: block;`.
> 
> I liked the wider audio control. Do you want to create a PR yourself, or may I include this in PR #1841?

Can you make the changes? Please?

**Comment by tc-wleite** [comment]
Sure! Thank you once again!
