### ISSUE TITLE
support AD1

### ISSUE THREAD

**Issue by Gusdur170845** [sepinf-inc/IPED#1844]
is it possible to support AD1 from FTK Imager content of folder imaging?

**Comment by lfcnassif** [comment]
It works with the AD1 files I have. You should pass the AD1 file directly to -d input  parameter. If it is not working for you, could you provide a sample AD1 that is not being processed fine so we can reproduce your issue?

**Comment by lfcnassif** [comment]
Just remembered I recently tested AD1 support with success here: https://github.com/sepinf-inc/IPED/discussions/1778

So I'm closing this as can't reproduce. If you can create an AD1 sample that shows it's not working and share it with us, please reopen.
