### ISSUE TITLE
APFS password is not being read when opening the case

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#1846]
I processed an image with encrypted APFS partition. The processment decrypted the partition and finished ok.
When I opened the case, there were read error when opening items.
 
Investigating and debugging, I found out that password was being set in [SleuthkitReader.java](https://github.com/sepinf-inc/IPED/blob/55001b3434a4e548f610d987ec7ed24741d62d07/iped-engine/src/main/java/iped/engine/datasource/SleuthkitReader.java#L507C18-L507C18), but it was not being read in [apfs_open.cpp](https://github.com/sepinf-inc/sleuthkit/blob/1655359736a452e84251108a2c4d136c6475efe6/tsk/fs/apfs_open.cpp#L49).

So I changed the `putenv` call by `setenv` in [Util.java](https://github.com/sepinf-inc/IPED/blob/55001b3434a4e548f610d987ec7ed24741d62d07/iped-engine/src/main/java/iped/engine/util/Util.java#L488) and the problem was solved.

I've already has some bad experiences with `putenv` in the past. So I suggest this fix (at least in Linux).

Using IPED 4.1.4 in Ubuntu 22.04

**Comment by lfcnassif** [comment]
Thanks for debugging this! I Just merged the PR, but this will be fixed when applied on master. Could you send another PR targeting master please?
