### ISSUE TITLE
Consider using AmazonCorrettoCryptoProvider

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#1855]
As discussed in #1849 , the AmazonCorrettoCryptoProvider could have great performance improvement.

Using default Provider:
```
[engine.task.HashTask]                  Hash: md5 => 25258ED0BD157CC9D06D9675C9B4B3C3
[engine.task.HashTask]                  Hash: sha-1 => 0229C4D391927DC3B27DA0809F79FFE0EB6DAA2F
[engine.task.HashTask]                  Hash: sha-256 => 792CD8BFD20E81A5C01648D1E45FCC301B255FF94A4865D9183440944FDE0364
[engine.task.HashTask]                  Hash time: 20.032
```

Using `AmazonCorrettoCryptoProvider`:
```
[engine.task.HashTask]                  Hash: md5 => 25258ED0BD157CC9D06D9675C9B4B3C3
[engine.task.HashTask]                  Hash: sha-1 => 0229C4D391927DC3B27DA0809F79FFE0EB6DAA2F
[engine.task.HashTask]                  Hash: sha-256 => 792CD8BFD20E81A5C01648D1E45FCC301B255FF94A4865D9183440944FDE0364
[engine.task.HashTask]                  Hash time: 13.739
```

As it is not supported in Windows yet, the jar file could be added in plugin folder. The code to support could be:
```java
try {
    Class<?> clazz = Class.forName("com.amazon.corretto.crypto.provider.AmazonCorrettoCryptoProvider");
    Method method = clazz.getMethod("install");
    method.invoke(null);
} catch (Exception e) {
    LOGGER.debug("AmazonCorrettoCryptoProvider not installed", e);
}
```

**Comment by aberenguel** [comment]
@lfcnassif Where is the better class to insert this code? Do you think it should be configurable?

**Comment by aberenguel** [comment]
> Is this provider loaded by the java service provider mechanism?

Yes. Internally the provider is added as the highest-priority.

```java
  /**
   * Installs the AmazonCorrettoCryptoProvider provider as the highest-priority (i.e. default)
   * provider systemwide.
   */
  public static void install() {
    Security.insertProviderAt(INSTANCE, 1);
  }
  ```

**Comment by lfcnassif** [comment]
Great! Could you take a look if Bouncy Castle dependency usesnthe same priority?

**Comment by aberenguel** [comment]
The Bo

> Great! Could you take a look if Bouncy Castle dependency uses the same priority? This may cause a conflict or non deterministic behavior...

The `BouncyCastleProvider` is added with `Security.addProvider` (https://github.com/sepinf-inc/IPED/blob/09a8a1e0ed2231d0a03338385e95229ea5e3fe6f/iped-engine/src/main/java/iped/engine/core/Manager.java#L162) which means it is inserted in the end of the provider list (lowest-priority).

**Comment by lfcnassif** [comment]
@arisjr, since you use Linux in your processing farm, this should be of your interest.

**Comment by arisjr** [comment]
Ótima notícia. Testaremos assim que disponível!
