### ISSUE TITLE
Deleted messages are not being exhibited as deleted

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#1856]
Instante messages imported from UFED are marked as deleted, but in the WhatsApp chat viewer  they are shown as if they are not deleted.

**Comment by hauck-jvsh** [comment]
I notice this in the same case of the #1843, but I think that these two are separated issues, but feel free to merge both if you think it is better.

**Comment by lfcnassif** [comment]
Thanks for reporting! From an user perspective, they will think they are the same. So let's use the previous ticket to fix both to avoid bloating the release notes, thanks!
