### ISSUE TITLE
ALT+Key to remove from bookmark not working properly with CRTL and SHIFT shortcuts

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1875]
If we assign shortcut `D` to a bookmark and then `CTRL+D` to another, when pressing `ALT+D` should remove from the first bookmark, but it may remove from the second.
In both cases, the removal shortcut is `CTRL+D`. So depending on the order they were assigned/loaded, one of them takes the removal action. 
The same issue would happen if `SHIFT+D` or `CRTL+SHIFT+D` were also used.

I think the correct (unambiguous) behavior would be: 
shortcut `D` -> removal keystroke `ALT+D`, shortcut `CRTL+D` -> removal keystroke `ALT+CRTL+D`.

**Comment by tc-wleite** [comment]
> I think the correct (unambiguous) behavior would be: shortcut `D` -> removal keystroke `ALT+D`, shortcut `CRTL+D` -> removal keystroke `ALT+CRTL+D`.

Another possible approach would be allowing just a single assignment for each key (so if `D` is used `CRTL+D` can't be assigned). Then `ALT+D` would be the removal shortcut for a single shortcut that uses `D` key (combined with `CTRL`, `SHIFT` or not).

**Comment by lfcnassif** [comment]
Hi @tc-wleite! I haven't expected/anticipated the same key usage with different modifiers because I thought it would be dangerous. However, I think we can delegate this decision to users and we can allow that. So I think your proposed fix is good, thank you!
