### ISSUE TITLE
Improve EML attached image rendering quality

### ISSUE THREAD

**Issue by rodrigohunk** [sepinf-inc/IPED#1882]
Some analysts complain about EML's low-quality rendering. The issue wasn't repeatable when opening in Outlook.
![image](https://github.com/sepinf-inc/IPED/assets/40205207/7aedab05-fa69-49a9-b3ee-a6a1c45eb594)

**Comment by tc-wleite** [comment]
Is this an image or text?
Can you send me the EML?

**Comment by rodrigohunk** [comment]
Actually it was a WIndows scaling issue, the user set up his desktop to
125% scaling. He preferred to keep it, and use a external viewer like
Thunderbird.

So this issue can be closed.

Thanks!

Em sex., 15 de set. de 2023 às 11:20, Wladimir Leite <
***@***.***> escreveu:

**Comment by tc-wleite** [comment]
I see. Well, maybe there is something we can do to improve IPED's visualization.
As far as I know there are different ways to scale Windows interface. I use it myself and don't see any quality issue. I will check the exact option I use and post here.
Other observation, not sure if you are already familiar with, IPED has an option to scale its user interface.

**Comment by tc-wleite** [comment]
A quick update here, I confirmed that I used 125% scaling at work and 200% at home, through the option below:
![image](https://github.com/sepinf-inc/IPED/assets/7217001/df3a1037-9ec2-4b83-9346-8b24b308ec3c)

IPED scaling is set to "auto".
I processed a few EMLs I have here, but I did't observe a similar rendering issue.
I also checked if there was something we can use in the viewer (like rendering hints), but nothing I tried had any visible effect.
So I am closing this issue.

@rodrigohunk, please reopen if you find out anything else.
A last recommendation would be checking if the user's video configuration in Windows are correct (i.e. the video driver is updated and using the maximum resolution of the monitor).
