### ISSUE TITLE
IPED is removing new lines in the text viewer

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#1883]
Our collegue João Paulo reported that with big text files, greater than 10MB, all the new lines were removed in the end of the file. As I remember IPED breaks text files around 10 MB right? Maybe after that break something is being lost.

**Comment by lfcnassif** [comment]
It was intentional a long ago to reduce memory usage. There is already an open enhancement for this: https://github.com/sepinf-inc/IPED/issues/1390

So I'm closing as duplicate. If I misunderstood and this is a different issue, please reopen, thanks!.
