### ISSUE TITLE
Bookmark Management

### ISSUE THREAD

**Issue by brunonbpaixao** [sepinf-inc/IPED#1885]
Currently, the bookmark management screen is initialized with the fields filled in. Please consider resetting the form on the bookmark management screen to avoid overwriting existing bookmarks.

#As Is
![As Is](https://github.com/sepinf-inc/IPED/assets/34874327/f575fa12-a117-43e5-af8d-99127873458d)

#To Be
![To Be](https://github.com/sepinf-inc/IPED/assets/34874327/6ce66078-abd1-41db-8d02-b5b64d1a718c)

Best Regards

**Comment by tc-wleite** [comment]
Hello @brunonbpaixao!
I am working on #1866, and already made small changes to bookmarks manager dialog, but didn't affect the behavior you described.

I don't think the current behavior (filling bookmark name and comment when selecting a bookmark in the list) is ideal, but some users like it.
Another thing to take into account is that the comment field is used both to create a new bookmark and edit an existing one (requires "update" button to be clicked), while the name is used only for a new bookmark and for editing the there is a separated dialog (opened using "Rename").
Finally, if we simply clean the form, as shown in your second screenshot, it wouldn't be possible to edit the comment, right?

Anyway, I think this interface could be improved and it is great to hear suggestions.
I have a couple of ideas myself to change this dialog a bit, but first we need to finish #1866.
When it is done, I will discuss this with @lfcnassif.

**Comment by lfcnassif** [comment]
Hi @tc-wleite. I think what @brunonbpaixao suggested is to clear the bookmark name and comments edit boxes when the Bookmark Manager is closed and re-opened. In 3.x versions, the last created bookmark was kept selected when the dialog is reopened.

@brunonbpaixao, I just tested with version 4.0.2 and your suggested behavior was already implemented in lastest versions. So I'm closing this as not a problem.

If I misunderstood your proposal, please reopen, thanks.

**Comment by tc-wleite** [comment]
@lfcnassif, you are right. From the dialog layout I  realized now that is 3.18.x.

**Comment by brunonbpaixao** [comment]
@lfcnassif and @tc-wleite thanks for your attention and quick response.
