### ISSUE TITLE
Discord Parser showing wrong file

### ISSUE THREAD

**Issue by felipecampanini** [sepinf-inc/IPED#1898]
If there are two files with the same name, the parser could show the wrong file. 

The bug was fixed in commit 902326d. 

Now the file is fetched based on the name and id contained in the URL.

**Comment by felipecampanini** [comment]
Hi @lfcnassif, this affects all previously released versions.

**Comment by lfcnassif** [comment]
Fine! So, if we release a 4.1.5 version, I'll cherry pick the fix, thank you!

**Comment by lfcnassif** [comment]
> The bug was fixed in commit [902326d](https://github.com/sepinf-inc/IPED/commit/902326db21552b731ff2a81544260a7e547b34d6).

Hi @felipecampanini. That commit seems to me to allow a possible ArrayIndexOutOfBoundsException, possibly when handling corrupted data. Could you complement it to check for the array size?

**Comment by lfcnassif** [comment]
I had some spare time and did it. Fixed on master by commit s c5fae0d and d71c6c8.

**Comment by felipecampanini** [comment]
Sorry for the delay, thanks @lfcnassif
