### ISSUE TITLE
Sometimes items are not included in their bookmarks, when generating a report from a multicase

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1940]
This was reported to me by a user from another location, so I didn't have the cases used here.
It is a tricky issue, and took me quite a while to reproduce and find out the root cause. 

**Steps to reproduce the issue:**

1. Open a multicase, with 3 cases.
2. Create 3 bookmarks, each with items from one case.

![image](https://github.com/sepinf-inc/IPED/assets/7217001/470879f9-a195-44f9-ab67-550eae42e34b)

4. Generate a report including all bookmarks.
5. Check the report. All items were included, but sometimes some of them are not associated with their bookmarks. Increasing the existing sleep time inside `SaveStateThread.run()` made the issue easier to reproduce.

![image](https://github.com/sepinf-inc/IPED/assets/7217001/ede423a2-f2e2-42d0-8661-c46e10f0a210)

**Cause:**

When generating a report from a multicase, the method IPEDReader.copyBookmarksToReport() is called multiple times.
At the end of this method, there is a call to `reportState.saveState()`, that will save the state of the report case bookmarks file asynchronously, using a `SaveStateThread`.
The issue happens when saving is slower than the next `reportState.saveState()`. 
The bookmarks to be saved are inserted into a `HashMap` (named `stateMap`), then they can be processed in a different order than they were originally added to the map.

**EDIT:** As there are calls to `loadState()` when copying bookmarks to report, it seems that synchronous `saveState()` should be used here.

**Comment by lfcnassif** [comment]
Thank you @tc-wleite for your time spent investigating this!

**Comment by tc-wleite** [comment]
Just to avoid confusion, I used the #1866 branch to test (and take these screenshots), but this is not related to it.
The user that reported the issue was using 4.1.4, and I was able to reproduce the issue using the master branch.
