### ISSUE TITLE
Sometimes negative parse times are shown

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1950]
I noticed this a few times, but didn't take a screenshot.
The screenshots below were taken by @aberenguel.
I will try to get more information and hopefully reproduce this situation.

![image](https://github.com/sepinf-inc/IPED/assets/7217001/a5d4cc42-f843-401d-92b6-85ab68fe2be4)
![image](https://github.com/sepinf-inc/IPED/assets/7217001/3910affb-7dcc-4602-a927-0ed6aa7abf87)

**Comment by tc-wleite** [comment]
I processed twice the same E01 that @aberenguel observed the negative parse times, but couldn't not reproduce it.
I added a warning in the log if any negative time is added to the total time, which should not happen.
Got no negative times in that E01, but processing other evidence files I got some of these warnings, but it didn't happen every time.
I have a few ideas about possible causes...
I will try to create a synthetic input to increase the chances of reproducing the issue.

**Comment by tc-wleite** [comment]
I managed to reproduce the issue processing a folder with 10 copies of [test.zip](https://github.com/sepinf-inc/IPED/files/13198220/test.zip).
![image](https://github.com/sepinf-inc/IPED/assets/7217001/5eee91f0-0bb1-4b58-af48-f703966e94d0)
I believe that the way `timeInDepth` works in `ParsingTask` is causing the issue, as siblings evidences may affect each other.
I added the following debug message to warn about any negative time added, in `ParsingTask`:
```java
        } finally {
            depth--;
            long diff = System.nanoTime() / 1000 - start;
            Long subitemsTime = timeInDepth.remove(depth + 1);
            if (subitemsTime == null)
                subitemsTime = 0L;
            time.addAndGet(diff - subitemsTime);

            // DEBUG MESSAGE
            if (diff < subitemsTime) {
                System.err.println(">>>NEGATIVE\ndepth=" + depth + "\nName=" + evidence.getName() + "\nParser="
                        + parserName + "\ntimeInDepth=" + timeInDepth + "\ndiff=" + diff + "\nsubitemsTime="
                        + subitemsTime + "\n");
            }
        }
```

**Comment by lfcnassif** [comment]
Good catch! I just took a look at the code and maybe this actually is being caused by a duplicated variable name `depth` as an int attribute of the class and as an Integer in parseEmbedded method. Could you fix this duplication and test with your test data?

**Comment by lfcnassif** [comment]
Sorry @tc-wleite, I just saw you sent the test samples. I was running a lot a tests related to #1958. I will test my suggestion when I return back to home.

**Comment by tc-wleite** [comment]
> Sorry @tc-wleite, I just saw you sent the test samples. I was running a lot a tests related to #1958. I will test my suggestion when I return back to home.

No problem! I already tested it here and it solved the negative parsing times issue (at least with the sample ZIP files I was using).
I wrote an alternative solution, not using `timeInDepth` map (and simplyfing a few other related things).
I am running a few more tests with real evidence files, and will submit a PR later.
