### ISSUE TITLE
Error creating report from command line with graph generation enabled

### ISSUE THREAD

**Issue by rafael844** [sepinf-inc/IPED#196]
Using IPED 3.18-beta.
IPED generates the exported files in the folder Exportados and the  files in indexador folder, but when I open IPED-SearchApp.exe it doesnt show any document.
Can i disable something to stop this error?
[IPED-2020-07-11-15-37-21.log](https://github.com/sepinf-inc/IPED/files/4907469/IPED-2020-07-11-15-37-21.log)

**Comment by lfcnassif** [comment]
hum seems a bug when creating report from command line with graph generation enabled. You can try disabling it or creating the report from graphics interface.

Will fix on monday.

**Comment by rafael844** [comment]
Im getting error again with command line. Disabling graph generation the error stops.
[IPED-2020-08-31-18-59-38.log](https://github.com/sepinf-inc/IPED/files/5152885/IPED-2020-08-31-18-59-38.log)

**Comment by lfcnassif** [comment]
Possibly it is the same issue described in #235 

Please check if it is fixed in this recent snapshot build: https://github.com/sepinf-inc/IPED/actions/runs/227941057

**Comment by rafael844** [comment]
Yes, with the snapshot it worked, thank you!
