### ISSUE TITLE
Increase Tika's SAXParser default pool size

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#1965]
In machines with dozens of CPU cores, default Tika SAXParser objects pool size may not be enough and can cause a bottleneck, like reported at https://github.com/sepinf-inc/IPED/discussions/1964

**Comment by paulobreim** [comment]
Do you think if I limited it to, say, 8 or 16 cores, it would be a good test?

**Comment by lfcnassif** [comment]
> Do you think if I limited it to, say, 8 or 16 cores, it would be a good test?

There is no need, Paulo. Default Tika SAXParser pool size is 10, I increased it to the number of available logical CPU cores. A snapshot should be ready in 10min here if you would like to test:
https://github.com/sepinf-inc/IPED/actions/runs/6750453327/job/18352863681

**Comment by paulobreim** [comment]
Great, I will test now

**Comment by paulobreim** [comment]
@lfcnassif finished well, no more problems with SAXParser.

tks

**Comment by lfcnassif** [comment]
Thanks for testing @paulobreim!
