### ISSUE TITLE
Upgrade TwelveMonkeys to 3.10

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1966]
Recently a new version of TwelveMonkeys library was released:
https://github.com/haraldk/TwelveMonkeys/releases/tag/twelvemonkeys-3.10.0
It includes fixes and enhancements for formats that we use its plugins (WEBP, PSD and TIFF).

Testing with a large set of images I have come to these conclusions (comparing thumb creation task):

- **WEBP** (115,000): Rendering improved a lot for ~3,000 images. Before these images were not rendered at all, just a full white or black area, or rendered very poorly. No performance change;
- **PSD** (1,500): 2 more images were rendered, slightly faster (~10%), but 4 images caused a critical issue (described later);
- **TIFF** (2,200): 10 images were rendered much better (white rectangle before). Slightly faster (~10%);
- **ICO** (300): No changes.

So overall the new release is better, except for a critical issue that happened with 4 malformed (incomplete or corrupted) PSD images. Before (with version 3.9.4) "something" was rendered, but with the new version (3.10.0) it doesn't return from the `ImageIO.read()` function. For the ThumbTask there is a timeout that takes care of it, but it causes a strange (unresponsive viewer) behavior when opening these images in the analysis GUI.
I will open an issue in the TwelveMonkeys project.

**Comment by tc-wleite** [comment]
An example of PSD that cause the issue with 3.10.0:
[corrupted-psd.zip](https://github.com/sepinf-inc/IPED/files/13269078/corrupted-psd.zip)

This is how its thumbnail was rendered with 3.9.4:
![image](https://github.com/sepinf-inc/IPED/assets/7217001/772e8125-3329-4a97-9106-1e5911176f80)

**Comment by tc-wleite** [comment]
https://github.com/haraldk/TwelveMonkeys/issues/860

**Comment by tc-wleite** [comment]
The issue was fixed already. There should be a 3.10.1 bug fix release soon. When it is available, I will repeat the tests.

**Comment by tc-wleite** [comment]
> * **WEBP** (115,000): Rendering improved a lot for ~3,000 images. Before these images were not rendered at all, just a full white or black area, or **rendered very poorly**.

Just for the sake of completeness, an example of a WEBP that is rendered much better with the newer version ([sample-webp.zip](https://github.com/sepinf-inc/IPED/files/13285175/sample-webp.zip)):

**3.9.4**
![image](https://github.com/sepinf-inc/IPED/assets/7217001/b26af1b2-d931-4527-adf2-8aac34c4b86b)

**3.10.0**
![image](https://github.com/sepinf-inc/IPED/assets/7217001/6a2db927-4ce5-4def-95c7-d0a6625599fd)

**Comment by lfcnassif** [comment]
Very nice!
