### ISSUE TITLE
Categorize HFS DECOMP attribute when using fastmode

### ISSUE THREAD

**Issue by rafael844** [sepinf-inc/IPED#197]
Files are not beeing categorized when are decomposed from macbook E01 image file. When I export the whole disk with Encase and then run Iped, it works. When I run E01 with Iped it set files with extention :DECOMP, so its not categorized neither opened with proper software.

After export files to a folder with Encase:
![enc01](https://user-images.githubusercontent.com/31928478/87251530-ce861200-c442-11ea-9558-fe4768d55813.PNG)

E01 with IPED 3.18-beta

![iped01](https://user-images.githubusercontent.com/31928478/87251544-e067b500-c442-11ea-80a6-5f624947ce16.PNG)

**Comment by lfcnassif** [comment]
Maybe it is a sleuthkit issue. Could you check if the hashes of the same file are equal? And check in HexViewer what is the beginning of the same file in each run?

I will take a look if sleuthkit fixed some related issue in recent versions.

**Comment by rafael844** [comment]
Same hash and hex.
![hash2](https://user-images.githubusercontent.com/31928478/87255552-33049980-c462-11ea-8497-7e82d3ca5924.PNG)
![hash1](https://user-images.githubusercontent.com/31928478/87255553-3435c680-c462-11ea-9550-b4184d0b26b6.PNG)
[IPED-2020-07-12-12-24-20-E01-fastmode.log](https://github.com/sepinf-inc/IPED/files/4909346/IPED-2020-07-12-12-24-20-E01-fastmode.log)
[IPED-2020-07-12-15-58-02-E01-default.log](https://github.com/sepinf-inc/IPED/files/4909347/IPED-2020-07-12-15-58-02-E01-default.log)
[IPED-2020-07-12-16-07-06-folder-default.log](https://github.com/sepinf-inc/IPED/files/4909348/IPED-2020-07-12-16-07-06-folder-default.log)
[IPED-2020-07-12-15-58-02-folder-fastmode.log](https://github.com/sepinf-inc/IPED/files/4909349/IPED-2020-07-12-15-58-02-folder-fastmode.log)

**Comment by lfcnassif** [comment]
Seems you are using fastmode profile (or some similar configuration, you changed other things) and processFileSignatures is disabled in it by default. Try enabling it or using another processing profile.

default fastmode profile does file detection based just on name/extension. Not sure if we can remove or ignore :DECOMP suffix put by sleuthkit, would need to take a look at other files with similar names inside the image to see if this is needed to differentiate between "alternate data streams".

**Comment by rafael844** [comment]
With  processFileSignatures turned on it worked, the files were caterorized. 
Thank you.

**Comment by lfcnassif** [comment]
reopening, maybe we can workaround the file name suffix added by tsk for fastmode processing, will try to add something.

**Comment by lfcnassif** [comment]
related: https://github.com/sleuthkit/sleuthkit/issues/1197

**Comment by lfcnassif** [comment]
@rafael844 are you able to compile from source? just pushed #197_enhancement branch with a workaround for this.

**Comment by rafael844** [comment]
I ran from source. Now its categorizing. Thank you.
![beta](https://user-images.githubusercontent.com/31928478/87485938-5ff6af00-c610-11ea-94f2-c56363e0a958.PNG)

**Comment by lfcnassif** [comment]
Great, thank you for testing!
