### ISSUE TITLE
Load localization configuration early

### ISSUE THREAD

**Issue by patrickdalla** [sepinf-inc/IPED#1979]
When making localization code for APK parser, I have noted that the code in getString method of iped.parsers.util.Messages is executed before LocaleConfig proper loading, leading to the use of system configured locale instead of locale configured in "LocalConfig.txt".

**Comment by lfcnassif** [comment]
Thanks @patrickdalla. Is this happening from command line or inside an IDE? Does this affect any other parser in last released version? If yes, we should tag this as bug.

**Comment by patrickdalla** [comment]
It seems this "error" only occurs from inside my eclipse IDE. Running from command line, the localization works well. 
Bootstrap loads the locale on LocalConfig before taskinstaller.
So it is not a BUG.

**Comment by lfcnassif** [comment]
Thanks for double checking!
