### ISSUE TITLE
New Feature - VLC vlc-qt-interface.ini parser

### ISSUE THREAD

**Issue by Descadeirado** [sepinf-inc/IPED#2034]
I would like to ask for a new feature.
It would be a parserr for the vlc-qt-interface.ini file, that has data like the most recent opened files with the application.

Thanks!

**Comment by lfcnassif** [comment]
Hi @Descadeirado, could youb share some samples with me to help testing #2085?

**Comment by Descadeirado** [comment]
Sure, tomorrow i'll contact you.

Em qui., 15 de fev. de 2024, 22:07, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by lfcnassif** [comment]
@Descadeirado I'm reviewing the initial parser @marcus6n wrote. Do you know what date format is used by those VLC files? We need to properly convert them: https://github.com/sepinf-inc/IPED/pull/2085#issuecomment-2008356923

**Comment by wladimirleite** [comment]
> Do you know what date format is used by those VLC files? 
 
These are not dates. 
It is the time (in milliseconds) inside the video of the last skip destination point (0 if there was no skip).
I would say that it is not useful in most of the cases.

**Comment by lfcnassif** [comment]
> These are not dates.
> It is the time (in milliseconds) inside the video of the last skip destination point (0 if there was no skip).
> I would say that it is not useful in most of the cases.

Thank you @wladimirleite! Just saw your reply now. Then, I'll possibly remove them, thanks.
