### ISSUE TITLE
Bookmarks may be lost in multicase reports

### ISSUE THREAD

**Issue by Descadeirado** [sepinf-inc/IPED#2037]
It happened to me in 2 cases already:
Processed a case with multiple devices images, worked in them with multicase and created bookmarks. At the end I generate the report.
When I open IPED-SearchApp on the report the itens are on the case and the bookmarks are there, but all bookmarks are with 0 itens.

On the first case, all my bookmarked itens were from only one material, so I ran the report directly from IPED-SearchApp from that material and generated the report without issues.
On the second case, my bookmarks have itens from more than on material and I don´t know how to proceed.

Thanks!

**Comment by wladimirleite** [comment]
Hello!
I believe this issue was fixed by #1940.
It should be included in the next release.

**Comment by Descadeirado** [comment]
Tried with 4.2-snapshot lib and localization folders. It didnt work.

**Comment by wladimirleite** [comment]
> Tried with 4.2-snapshot lib and localization folders. It didnt work.

Can you share the report creation log?

**Comment by Descadeirado** [comment]
Yes, it's on the corporate email.

Em seg., 1 de jan. de 2024 11:03, Wladimir Leite ***@***.***>
escreveu:

**Comment by wladimirleite** [comment]
Thanks! I will take a look tomorrow.

**Comment by wladimirleite** [comment]
After some investigation (thanks @Descadeirado for providing the access to the environment where the case is processed), I managed to isolate the issue.
Although its effect is somewhat similar to #1940, it is a different issue.

**Comment by wladimirleite** [comment]
I also manage to reproduce it in a small case, following the steps:
- Process 2 folders as 2 cases.
- Open the 2 cases as a multicase.
- Create bookmarks, including only items from the first case (in my test the first in alphabetical order, but may be necessary to repeat using the other case to reproduce).
- Generate a report.
- When the report is opened, items were exported, but bookmarks are empty.

If at least one item of the second case is bookmarked, everything works as expected.
