### ISSUE TITLE
Negative estimated time to finish UFDR processing

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#2064]
Reported by an user running 4.1.5 on UFDR evidence:
![image](https://github.com/sepinf-inc/IPED/assets/7276994/03d86bb2-8326-41dd-9a03-0c68161b06b3)

**Comment by wladimirleite** [comment]
I came across this situation a few of weeks ago. However it was a small amount of negative seconds.

**Comment by lfcnassif** [comment]
> I came across this situation a few of weeks ago. However it was a small amount of negative seconds.

Which version was you using? Just remembered you fixed a similar issue recently into ParsingTask, right? I'll ask the user to try the latest snapshot.

**Comment by paulobreim** [comment]
I've had this situation before, but I didn't care.

**Comment by wladimirleite** [comment]
> Which version have you used? 

I am 99% sure that I was using master, but I didn't take a snapshot.

> Just remembered you fixed a similar issue recently in master into ParsingTask, right?

Right, but the other issue was with the elapsed time. 
This one affects the estimated time to finish, which is just a straightforward calculation (looking at the code).
I see a couple of possible causes. I will try to reproduce it here when I get some time during this week.

**Comment by lfcnassif** [comment]
PS: And those values seem fine.

**Comment by wladimirleite** [comment]
Reproduced with master branch, processing a UFDR.
![image](https://github.com/sepinf-inc/IPED/assets/7217001/b8a528f2-82db-4a28-8bd6-0f8d4ef32157)

**Comment by wladimirleite** [comment]
I managed to find the root cause and fix it.
I will post more details and submit a PR tomorrow.
