### ISSUE TITLE
Case remains image dependent when using blind profile w/ enableHtmlReport off in 3.18

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#210]
When using blind profile with enableHTMLReport off, most files are stored in internal sqlite containers. But iped gui is trying to read them from original forensic images, they are usually discarded when blind profile is used for automatic data extraction scenarios.

**Comment by lfcnassif** [comment]
fixed by 3db30dae3c57b0cc9b05bf631f8a8e99fd62d1cb

**Comment by DHoelz** [comment]
Had this same problem with version **3.18.2** using the **default** profile (pt-BR) with enableHTMLReport **off**. Some files will be listed but won't open and don't have _metadatas_.
The report worked when turning enableHTMLReport **on**.

**Comment by lfcnassif** [comment]
will check

**Comment by lfcnassif** [comment]
I was able to reproduce, but it is a different problem, will open other issue to track.
