### ISSUE TITLE
WhatsApp Parsing Error

### ISSUE THREAD

**Issue by joaovitorlopes** [sepinf-inc/IPED#2119]
Recently, when trying to index a **UFDR** file, in which the **WhatsApp** application was parsed, with the **database and all available attachments**, an error occurred when performing this parse on **IPED** Application.
Both versions **4.1.5 and 4.2.0-snapshot** were used, and the other applications perform the parser correctly, except WhatsApp.
![ufdr-result](https://github.com/sepinf-inc/IPED/assets/27697191/d4530c77-9014-4a01-92b3-e66aed8642d6)
![iped-4 2](https://github.com/sepinf-inc/IPED/assets/27697191/1ed187bc-3f2a-421c-82d1-cbd674df609f)
![iped-4 1 5](https://github.com/sepinf-inc/IPED/assets/27697191/f9a88c51-ad76-4e9d-bd58-c317e505bc98)
[IPED-2024-03-12-08-13-43(4.1.5).log](https://github.com/sepinf-inc/IPED/files/14572528/IPED-2024-03-12-08-13-43.4.1.5.log)
[IPED-2024-03-11-16-09-25(4.2.0).log](https://github.com/sepinf-inc/IPED/files/14572530/IPED-2024-03-11-16-09-25.4.2.0.log)

**Comment by joaovitorlopes** [comment]
> Also see this comment: [#309 (comment)](https://github.com/sepinf-inc/IPED/issues/309#issuecomment-721463990)
> 
> And the recommendations here: #1541

When checking the UFDR file in 7zip it was not possible to find the Databases folder, but when checking in Cellebrite Reader, msgstore.db is there.
Regarding the second recommendation, the IPED was indexed directly in the .ufdr and not in the folder where it was located.

![zip](https://github.com/sepinf-inc/IPED/assets/27697191/6632f7e9-f86d-49c7-9f3b-d19067f5baee)
![ufdr-msgstore](https://github.com/sepinf-inc/IPED/assets/27697191/8ed1fd57-9b4f-4e61-8b14-0d441ac3b89a)

**Comment by lfcnassif** [comment]
> When checking the UFDR file in 7zip it was not possible to find the Databases folder

Then possibly it wasn't exported.

> but when checking in Cellebrite Reader, msgstore.db is there.

Possibly it is just a folder representing the original file, not the DB itself. Are you able to export the original DB from Cellebrite Reader?

> Regarding the second recommendation, the IPED was indexed directly in the .ufdr and not in the folder where it was located.

I referred to all recommendations in that thread, not to the user specific issue. For example, I pointed the possible folder (not file) presence theory.

**Comment by joaovitorlopes** [comment]
> Then possibly it wasn't exported.
>
When analyzing it, it really seems that whoever generated the report ended up removing the databases from the report, and the conversations ended up only being in the ufdr file, thank you in advance for the clarification. 

> Possibly it is just a folder representing the original file, not the DB itself. Are you able to export the original DB from Cellebrite Reader?
> 
When checking the results in Cellebrite Reader, msgstore.db is actually a folder representing the DB file.

> I referred to all recommendations in that thread given by me and @wladimirleite, not to the user specific issue. For example, I pointed the possible folder (not file) presence theory.
> 
Thank you, it is very important to know the hash, it needs to be sha256. For the WhatsApp files link to work.

**Comment by joaovitorlopes** [comment]
> As far as I remember, this way "msgstore.db" is shown (with 44626 files inside) means it is a folder, not the file, which contains files expanded from the database (like message attachments). It seems the database itself was not included (probably "Databases" category was no selected when generating the UFDR).
> 
> PS: @joaovitorlopes, I see you came to a similar conclusion while I was typing.
Thank you very much @wladimirleite, it seems that we didn't really export the databases when generating the report.

**Comment by lfcnassif** [comment]
Thanks @joaovitorlopes for double checking and for returning with the final conclusion.

Anyway, as recommended by the posts I mentioned, you can go to conf/ParsingTaskConfig.txt and change phoneParsersToUse option from internal to external, that will tell IPED to import the WhatsApp decoding results from Cellebrite software instead of decoding the database using IPED internal decoder. `External` gives different results, better in some aspects (it recovers Android deleted messages from the main DB itself), worse in other aspects, `internal` links attachments much better, merge Android backups in a single report (recovering deleted messages from backups)  etc.

**Comment by lfcnassif** [comment]
> Anyway, as recommended by the posts I mentioned, you can go to `conf/ParsingTaskConfig.txt` and change `phoneParsersToUse` option from `internal` to `external`, that will tell IPED to import the WhatsApp decoding results from Cellebrite software instead of decoding the database using IPED internal decoder. `external` gives different results, better in some aspects: it recovers Android/iOS deleted chats/messages from the main DB itself, recover scrambled messages from the DB index, etc. But worse in other aspects: `internal` links attachments much better, merge Android backups in a single report (recovering deleted messages from backups), recover deleted chats/messages from iOS DBs, is able to download deleted attachments still present in WhatsApp servers (must enable the `--downloadInternetData` cmd line option), etc.

Just updated this message as a reference to others.
