### ISSUE TITLE
Thorn CSAM detection plugin

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#2147]
Recently our lawyers (AGU) allowed us to sign the Thorn CSAM detection model terms of use. So, after signed and if we receive the model from Thorn, we plan to integrate it as a plug-in internal to our organization and non distributed to the public or third parties, because of license restrictions.

If the model is CPU heavy, we plan to offer an internal CSAM detection service, like the audio transcription one, after we buy and receive the new GPU cluster.

We may talk to Thorn project to check with them if it is possible to distributed the future plug-in to law enforcement agencies that also sign the Thorn terms of use directly with them. It could be possible, since the technology was recently integrated into commercial products.

**Comment by Lwantstostophim** [comment]
i need someone  to help asap theres tons of people and channels posting selling trading csam of a friend who was 14 at the time and emailing twitter/x  and reporting does nothing and by the time we find the other accounts that posted him its already too late and theres thousandsss of views please there has to be a way to track any posts of him and take them down and prevent anything of him from
being posted and sold there
this is a problem on instagram twitter/x and telegram  his videos are everywhere

**Comment by lfcnassif** [comment]
Hi @Lwantstostophim, I suggest you to report that to police in your country, they should be able to help.

**Comment by lfcnassif** [comment]
Unfortunately the Thorn CSAM detection model has become a commercial product, even for law enforcement, after we asked for it. So I'm closing this as won't fix for now... We can reopen if we decide to buy their technology.
