### ISSUE TITLE
Exception caused by empty linkedItems hashes in Telegram chats preview (master)

### ISSUE THREAD

**Issue by wladimirleite** [sepinf-inc/IPED#2157]
When clicking on some internally parsed Telegram chats, I am getting the following exception:

java.lang.RuntimeException: iped.exception.QueryNodeException: INVALID_SYNTAX_CANNOT_PARSE: Syntax Error, cannot parse (hash:):  
	at iped.engine.search.IPEDSearcher.setQuery(IPEDSearcher.java:107)
	at iped.engine.search.IPEDSearcher.<init>(IPEDSearcher.java:77)
	at iped.app.ui.ReferencingTableModel.listItems(ReferencingTableModel.java:93)
	at iped.app.ui.FileProcessor.process(FileProcessor.java:193)
	at iped.app.ui.FileProcessor.doInBackground(FileProcessor.java:133)
	at iped.app.ui.FileProcessor.doInBackground(FileProcessor.java:1)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

It seems to be cause by empty media hashes that were incorrectly added by the parser.

**Comment by wladimirleite** [comment]
There are also medias with "hashes of byte[0]" (like MD5 "hash:d41d8cd98f00b204e9800998ecf8427e"), which could also be discarded.

![image](https://github.com/sepinf-inc/IPED/assets/7217001/bdb3581f-d084-4ed0-a544-afb17141aa3d)

**Comment by lfcnassif** [comment]
> There are also medias with "hashes of byte[0]" (like MD5 "hash:d41d8cd98f00b204e9800998ecf8427e"), which could also be discarded.
> 
> ![image](https://private-user-images.githubusercontent.com/7217001/321012020-bdb3581f-d084-4ed0-a544-afb17141aa3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MDE4OTMsIm5iZiI6MTcxMjcwMTU5MywicGF0aCI6Ii83MjE3MDAxLzMyMTAxMjAyMC1iZGIzNTgxZi1kMDg0LTRlZDAtYTU0NC1hZmIxNzE0MWFhM2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMjIyNjMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODlkZGE5NDVkOWQ5NmJkZjA5OTkyNGJmYWM4Nzc4ZWVhYzIwZmY1MDhhNWQxZTExNGE0NTdiYzA1MDJhYzAxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6VuWjhkQMhqRkT-cFlZRgJ30c5K460CXPpvmV-0IMmU)

We discard search results for medias with up to 2 bytes AFAIK in WhatsAppParser, to ignore empty files or files with just a newline.

**Comment by wladimirleite** [comment]
> We discard search results for medias with up to 2 bytes AFAIK in WhatsAppParser, to ignore empty files or files with just a newline.

Good observation! Just check in WhatsAppParser's code. I will try to add a similar check in the TelegramParser.

**Comment by wladimirleite** [comment]
> I will try to add a similar verification to TelegramParser.

Unfortunately it didn't work, as it also filtered out valid linked medias that have length 0 (in the decoded database).
I am testing an alternative solution, that just ignores empty hashes (a trivial check) and media hashes that match one of the pre-calculated zero length hashes.
