### ISSUE TITLE
Range queries that use localized properties for date fields are not working properly

### ISSUE THREAD

**Issue by wladimirleite** [sepinf-inc/IPED#2175]
As discussed in https://github.com/sepinf-inc/IPED/discussions/2173.

**Comment by wladimirleite** [comment]
I believe I found a simple fix. I will submit a PR soon.

@lfcnassif, not directly related, but I just checked here and there is no need to escape the colon used as the hour separator.
The trailing "Z" is also not used.
So 
`modified:[2023-07-06 TO 2023-07-07T20\:00\:00Z]`
has the same effect of
`modified:[2023-07-06 TO 2023-07-07T20:00:00]`

Can we update the help HTML to use the simpler version?

**Comment by wladimirleite** [comment]
PS: The "T" between the day and the hour is required, and must be an uppercase "T".

**Comment by lfcnassif** [comment]
Thanks @wladimirleite for taking a look at this. I'm traveling on "vacation" until next Wednesday, inclusive.

What about exclude queries and open range queries (using curly brackets instead of square brackets) do they work without the ending Z?

**Comment by wladimirleite** [comment]
> What about exclude queries and open range queries (using curly brackets instead of square brackets) do they work without the ending Z?

Good questions. I will check it.

**Comment by lfcnassif** [comment]
Thanks @wladimirleite. And if a lowercase z is used, does that fix the open range query?

**Comment by wladimirleite** [comment]
Testing with different date/times, I noticed that sometimes the open range works (using the uppercase Z), but sometimes it doesn't (same result with "]" and "}"). 
Maybe it depends on something else (perhaps if the date contains milliseconds, which are not shown in the formatted field).

**Comment by wladimirleite** [comment]
I found in the search app log an exception related to the implemented fix.
