### ISSUE TITLE
Broken links in HTML report when "thumbs only" option is used

### ISSUE THREAD

**Issue by vitorlco** [sepinf-inc/IPED#2203]
The .htm file of the report gives problem when creating a report with the thumbsonly sitting. When clicking on the .htm report link, the thumbnails of the selected images are not displayed.
![Problema_iped](https://github.com/sepinf-inc/IPED/assets/56724540/7e8285d6-2122-4437-978f-3eb9d497e258)

**Comment by wladimirleite** [comment]
Which IPED version are you using?
I will try to reproduce the issue here in the afternoon.

**Comment by vitorlco** [comment]
> Which IPED version are you using? I will try to reproduce the issue here in the afternoon.
We used the version 4.1.5 and 4.1.6

**Comment by wladimirleite** [comment]
@vitorlco, just to be sure, the screenshot you posted is what you got after following an "exported as" / "exportado como" HTML link (like the one below), right?
I mean, other pages and the thumbnails are shown correctly?

If that is the case, if the file is not exported (only its thumbnail), to avoid this broken link we should not add "exported as" field and  not create links from the thumbnail image.

![image](https://github.com/sepinf-inc/IPED/assets/7217001/f669f577-6aa6-41a0-b196-2acba841b638)

**Comment by vitorlco** [comment]
Correct. The image I posted is displayed after clicking the link
