### ISSUE TITLE
Increase default UI row height a bit

### ISSUE THREAD

**Issue by wladimirleite** [sepinf-inc/IPED#2205]
@lfcnassif, this is a tiny visual enhancement suggestion.
We already have a menu option to increase UI icon sizes, which changes the row height automatically.
However few people use that option and the default value is only 16 pixels (it was chosen to keep the previous behavior).

Although this is a personal preference, most modern user interfaces avoid using too small row heights. 
With the current setting, more rows can be shown, but rows look too close to each other.
I suggest making a minor change in the default value, from 16 to 18.

A comparison with other common UI using the same scale (IPED with the current default setting of 16 pixels).
![image](https://github.com/sepinf-inc/IPED/assets/7217001/bc2b3ea2-6925-4518-b202-e227615d36f5)

**Comment by lfcnassif** [comment]
Hi @wladimirleite. Do you have a screenshot using the new proposed default row height?

**Comment by wladimirleite** [comment]
Sorry, I should have included it. The proposed change is relatively small, so we don't waste space.
Changing icon size from 16 pixels and 18 pixels:
![image](https://github.com/sepinf-inc/IPED/assets/7217001/9eefaa85-2e81-460f-ae3a-718ce0065b36)

**Comment by lfcnassif** [comment]
Seems better, more readable to me!
