### ISSUE TITLE
Jump to WhatsApp quoted messages in reply edited messages are not found

### ISSUE THREAD

**Issue by gfd2020** [sepinf-inc/IPED#2245]
The reference of a quoted message may be lost if the original message is edited.
As in the example below:
![image](https://github.com/sepinf-inc/IPED/assets/59742865/063e6bba-7acf-49f2-9125-d59687934cc0)

I've already found a way to get around this problem on New Android ( on IPhone I'm not sure if it happens). I'll make a PR.
I will need help with regression testing.

**Comment by lfcnassif** [comment]
Thanks @gfd2020 for reporting and taking a look at this!

**Comment by gfd2020** [comment]
> Thanks @gfd2020 for reporting and taking a look at this!

Hi @lfcnassif . 
I did a test here and it's already working. I implemented it in a way that shows the original message in the reply and has the reference to the jump. I think this way is the best of two worlds because you have the original text before editing and there is a jump to the edited message... what do you think?

![image](https://github.com/sepinf-inc/IPED/assets/59742865/ea61b9b6-e50a-4ea1-a978-f47f4b307a4b)

**Comment by lfcnassif** [comment]
> what do you think?

Seems great!

**Comment by lfcnassif** [comment]
Closed by https://github.com/sepinf-inc/IPED/pull/2246
