### ISSUE TITLE
Go to parent in file tree freezes UI when executed from UFDR imported instant messages

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#2264]
`InstantMessage` items parsed from UFDR files when `phoneParsersToUse` is set to `external` don't have parent.

The examples bellow are referenced to same message being received and replied.
```
case.ufdr/_DecodedData/Chat/Chat_1329a150-7242-4a66-afe9-26d0286ef966/InstantMessage_5e01ab03-d134-491a-9771-742ca6a55a8c
case.ufdr/_DecodedData/Chat/Chat_1329a150-7242-4a66-afe9-26d0286ef966/InstantMessage_bc06941c-7da5-4d81-badc-7bffab0f93b8/ReplyMessageData_677b7164-8214-47da-9033-7a30a356a28c/InstantMessage_5e01ab03-d134-491a-9771-742ca6a55a8c
case.ufdr/_DecodedData/Chat/Chat_1329a150-7242-4a66-afe9-26d0286ef966/InstantMessage_9d241346-fdef-4cf0-b968-5f6cb1322a3d/ReplyMessageData_1003de47-c969-4cbc-bab6-bcef67592ac9/InstantMessage_54ea170b-be46-469a-9e8f-4788955e2bff/ReplyMessageData_d1882cfd-f884-4018-a52e-98a78ffcebb4/InstantMessage_5e01ab03-d134-491a-9771-742ca6a55a8c
case.ufdr/_DecodedData/Chat/Chat_1329a150-7242-4a66-afe9-26d0286ef966/InstantMessage_39ae5364-2509-468b-a5ec-36fbd7e3e56d/ReplyMessageData_e3856767-90e6-4fc7-9ab3-8098a807d015/InstantMessage_f3fbb6c6-ce7a-4057-b26b-94b58e258e70/ReplyMessageData_03b361ea-46e5-41bf-801f-ea5a847dfb90/InstantMessage_5e01ab03-d134-491a-9771-742ca6a55a8c
case.ufdr/_DecodedData/Chat/Chat_1329a150-7242-4a66-afe9-26d0286ef966/InstantMessage_f3fbb6c6-ce7a-4057-b26b-94b58e258e70/ReplyMessageData_03b361ea-46e5-41bf-801f-ea5a847dfb90/InstantMessage_5e01ab03-d134-491a-9771-742ca6a55a8c
case.ufdr/_DecodedData/Chat/Chat_1329a150-7242-4a66-afe9-26d0286ef966/InstantMessage_54ea170b-be46-469a-9e8f-4788955e2bff/ReplyMessageData_d1882cfd-f884-4018-a52e-98a78ffcebb4/InstantMessage_5e01ab03-d134-491a-9771-742ca6a55a8c
case.ufdr/_DecodedData/Chat/Chat_1329a150-7242-4a66-afe9-26d0286ef966/InstantMessage_d2555bb0-ce9e-466b-9e9e-9d80745c55b5/ReplyMessageData_46695705-1a95-4063-a027-247fbe6ca0ff/InstantMessage_5e01ab03-d134-491a-9771-742ca6a55a8c
```
Besides the `Chat_1329a150-7242-4a66-afe9-26d0286ef966` item exists, the InstantMessage items don't reference it.
Another behavior that happens in this case is when `Go to parent in file tree` is executed from the InstantMessage item: IPED completely freezes.

**Comment by aberenguel** [comment]
Metadata of `case.ufdr/_DecodedData/Chat/Chat_1329a150-7242-4a66-afe9-26d0286ef966/InstantMessage_5e01ab03-d134-491a-9771-742ca6a55a8c`:
![image](https://github.com/user-attachments/assets/64751f5a-5043-4114-af6b-c2862586a414)

Search for the parent:
![image](https://github.com/user-attachments/assets/40312727-8c37-4810-a2dd-42c28d204796)

**Comment by aberenguel** [comment]
Actually the item with name `Chat_1329a150-7242-4a66-afe9-26d0286ef966` doesn't exits. What exists is the chat with path `case.ufdr/_DecodedData/Chat/Chat_1329a150-7242-4a66-afe9-26d0286ef966>>Chat_Telegram_Group_1329a150-7242-4a66-afe9-26d0286ef966`.

**Comment by lfcnassif** [comment]
> `InstantMessage` items parsed from UFDR files when `phoneParsersToUse` is set to `external` don't have parent.

This is expected. When 'external' UFED results are imported, intant messages are read from UFDR and corresponding items created in UfedXmlReader class. Chat views/items are built later, in UFEDChatParser, which searches for instant items in the case to build chat views. At this time, instant message items already have a parentId, and today there is no API to update indexed items properties, like parentId. Another approach I thought in the past would be to update the content of the first Chat_XXXXX item in the path (it is created to group messages and chat views in the Evidence Tree), but it would change its hash and, again, there is no way to update item properties today...

> Another behavior that happens in this case is when Go to parent in file tree is executed from the InstantMessage item: IPED completely freezes.

I think a detected this a log time ago, but forgot to fix, this is definitely a bug.

**Comment by lfcnassif** [comment]
> Actually the item with name `Chat_1329a150-7242-4a66-afe9-26d0286ef966` doesn't exits. What exists is the chat with path `case.ufdr/_DecodedData/Chat/Chat_1329a150-7242-4a66-afe9-26d0286ef966>>Chat_Telegram_Group_1329a150-7242-4a66-afe9-26d0286ef966`.

It exists just in the Evidence Tree, to avoid confusing the user with one empty Chat item (the parent) in the Chat category, and another corresponding one with the chat view.

**Comment by lfcnassif** [comment]
> Besides the `Chat_1329a150-7242-4a66-afe9-26d0286ef966` item exists, the InstantMessage items don't reference it.

If you click on "go to parent chat position" on the context menu, does it work?

**Comment by lfcnassif** [comment]
> Another behavior that happens in this case is when `Go to parent in file tree` is executed from the InstantMessage item: IPED completely freezes.

Hi @aberenguel, I'm not able to reproduce the freezing. What version are you using? Could you take a thread dump after UI feezes?

**Comment by aberenguel** [comment]
> If you click on "go to parent chat position" on the context menu, does it work?

If the InstantMessage is a directly chid of a Chat, this function works properly. For example: `case.ufdr/_DecodedData/Chat/Chat_1329a150-7242-4a66-afe9-26d0286ef966/InstantMessage_5e01ab03-d134-491a-9771-742ca6a55a8c`.

On the other hand, if the InstantMessage is a child of ReplyMessage, a dialog with message "Parent chat not found" is shown. For exemple: `case.ufdr/_DecodedData/Chat/Chat_1329a150-7242-4a66-afe9-26d0286ef966/InstantMessage_f3fbb6c6-ce7a-4057-b26b-94b58e258e70/ReplyMessageData_03b361ea-46e5-41bf-801f-ea5a847dfb90/InstantMessage_5e01ab03-d134-491a-9771-742ca6a55a8c`.

Btw, the UI freezes with `Go to parent in file tree` only in the last case.

**Comment by aberenguel** [comment]
> Hi @aberenguel, I'm not able to reproduce the freezing. What version are you using? Could you take a thread dump after UI feezes?

I think the ReplyMessage only appears since PA-8. 

Here is the thread dump: [jstack.txt](https://github.com/user-attachments/files/16364667/jstack.txt)

**Comment by aberenguel** [comment]
It seems there is an infinite loop in https://github.com/sepinf-inc/IPED/blob/a5e60df000875f139d370d0e5e5d2d80fa35cfd8/iped-app/src/main/java/iped/app/ui/TreeListener.java#L138

**Comment by lfcnassif** [comment]
Thanks for the additional info, when this feature was implemented a long ago, ReplyMessage wasn't find in the UFDR samples in the past, and it is not handled by current code.

**Comment by lfcnassif** [comment]
Related: #998.

**Comment by lfcnassif** [comment]
Hi @aberenguel, I reproduced the UI freezing issue with reply messages, thanks. I'm applying a simple fix to avoid it. In a test case here, all reply messages are duplicated in "Instant Messages" category, for each of them there is another message with the same name, body, sender and date. In the chat view they are not duplicated. I'll possibly remove those reply messages for now, until #998 is implemented. Could you check in your case if reply messages are also duplicated?

**Comment by aberenguel** [comment]
Before fixes above:
![image](https://github.com/user-attachments/assets/63a6b26c-19ca-49ab-8199-6d7ed7a5d00f)

After fixes:
![image](https://github.com/user-attachments/assets/8e290174-77ff-40cf-8165-f47aadfa3c63)

**Comment by aberenguel** [comment]
The navigation to chat position and to parent item worked properly.

**Comment by lfcnassif** [comment]
Thank you for testing @aberenguel!
