### ISSUE TITLE
Item with no bookmarks are not filtered properly after deleting a bookmark (master only)

### ISSUE THREAD

**Issue by wladimirleite** [sepinf-inc/IPED#2311]
Detected while working on a real case. It seems a critical issue, as I almost missed important items because of it.
I was able to reproduce in a small test case with the following steps.

1. Process a folder with 10 images.
2. Create a bookmark "A" with 5 of them.
3. Create a bookmark "B" with the other 5.
4. Delete bookmark "B".
5. Select "No bookmarks" filter. It should list 5 items (that were previously in bookmark "B"), but non images are shown.

After reopening the case it works.
It may be related to #2251.

After step 3:
![image](https://github.com/user-attachments/assets/c68a683f-b02e-468e-80f7-fb415f61e6b6)

After step 4:
![image](https://github.com/user-attachments/assets/8d6b82d7-dabd-4601-a0ce-2b6616d4d1de)

After step 5:
![image](https://github.com/user-attachments/assets/e4a9bbdb-3939-4370-a870-527c0a2c768f)

**Comment by lfcnassif** [comment]
@patrickdalla, maybe this regression was caused by the bookmarks refactoring to use RoaringBitmaps, could you take a look?

**Comment by patrickdalla** [comment]
ok

Em seg., 26 de ago. de 2024, 09:12, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by patrickdalla** [comment]
The problem was with internal union bitmap cache that wasn't being invalidate (and updated) after the deletion.
@wladimirleite , check if comit in PR 2312 (brach BookmarkCacheInvalidation) to check if the issue was solved.

**Comment by wladimirleite** [comment]
Just tested it, and the issue is gone. 
Thanks @patrickdalla!
