### ISSUE TITLE
Remove splash screen when pass --nogui

### ISSUE THREAD

**Issue by renatormc** [sepinf-inc/IPED#2325]
When you run the application for processing even if you add the --nogui param it shows the splash screen at the beginning

**Comment by wladimirleite** [comment]
To be as fast as possible (that is the whole point of it), the splash screen is shown before any code is executed. 
So it can't see any program parameters, like "--nogui".
Is there any particular reason you want to avoid the splash screen?

I think there is a Java parameter to prevent the splash screen to be displayed. 
I will try to find out...

**Comment by wladimirleite** [comment]
Using the headless mode prevents the splash screen to be shown:
`java -Djava.awt.headless=true -jar iped.jar <iped-parameters>`
@renatormc, does that work for you?

**Comment by wladimirleite** [comment]
Hi @lfcnassif! 
You marked this issue as an enhancement, but the suggested change can't be done.
As I mentioned, the splash screen is shown even before the JVM startup, so it can't read program parameters or make any decision at this point. 

The splash goal is to indicate to the user that the application is launching during possibly long startup times, and depending on the environment, JVM startup (including loading a lot of classes) can take several seconds, before any "feedback" (like opening the main window) is provided. Obviously, the splash screen makes no sense when using "--nogui", but it can't be removed.

There are a few workarounds, like the one I mentioned in the previous post. 
Another workaround would be having another JAR for "nogui", but I think it is not worth the effort.

**Comment by renatormc** [comment]
@wladimirleite the param -Djava.awt.headless=true solves the problem. Thanks.

**Comment by lfcnassif** [comment]
> Hi @lfcnassif!
> You marked this issue as an enhancement, but the suggested change can't be done.
> As I mentioned, the splash screen is shown even before the JVM startup, so it can't read program parameters or make any decision at this point.

Hi @wladimirleite. I see... If the splash screen was displayed just by the second/forked IPED process, that would be possible, but it is launched by the first one, right?

So, I'll tag this as "won't fix" and close the issue, since the suggested workaround worked for @renatormc.

**Comment by wladimirleite** [comment]
> Hi @wladimirleite. I see... If the splash screen was displayed just by the second/forked IPED process, that would be possible, but it is launched by the first one, right?

Yes, it would be possible, but for slow environments (e.g. starting a case directly from a network drive), it would take several seconds before the splash screen becomes visible, going against splash's main goal.
