### ISSUE TITLE
Search positioning in chat differs from the global search

### ISSUE THREAD

**Issue by patrickdalla** [sepinf-inc/IPED#2329]
In a case I am analyzing, when I search for a word in the search text box, it shows me the result with the correct search matches in the tab. But the position that is shown differs from this match. In the case, the searched term was "ossos", and the chat was positioned in a message with the term "nossos".

**Comment by wladimirleite** [comment]
The highlighter and hits navigation in the viewers (HTML, PDF and LibreOffice) use a live search, which matches substrings (i.e. no tokenizer).
This has always been the behavior, right?
What exactly is being suggested?

**Comment by wladimirleite** [comment]
Just to clarify my previous comment, @patrickdalla, are you suggesting to change the current behavior or reporting an issue you noticed in a particular case?

**Comment by lfcnassif** [comment]
> The highlighter and hits navigation in the viewers (HTML, PDF and LibreOffice) use a live search, which matches substrings (i.e. no tokenizer).
> This has always been the behavior, right?

Yes, that was intentional when implemented, I thought it could bring interesting results for users. But I agree it can also be annoying when searching for short terms.

We can discuss here about a possible behavior change...

**Comment by lfcnassif** [comment]
Closing as not a problem, it was intentional, but we can reopen if we decide to change current behavior.
