### ISSUE TITLE
NullPointerException in ShareazaDownloadParser Test

### ISSUE THREAD

**Issue by marcus6n** [sepinf-inc/IPED#2336]
I'm encountering a `NullPointerException `when executing the `ShareazaDownloadParser `test case. The error message indicates that it cannot invoke `iped.data.IItemReader.getPath()` because `item `is null. Here’s the relevant stack trace:

```cmd
java.lang.NullPointerException: Cannot invoke "iped.data.IItemReader.getPath()" because "item" is null
	at iped.parsers.shareaza.ShareazaDownloadParser.parse(ShareazaDownloadParser.java:95)
	at iped.parsers.shareaza.ShareazaDownloadParserTest.testShareazaDownloadParser(ShareazaDownloadParserTest.java:32)
```

This issue seems to occur during the parsing process, despite using a valid test file (`test_shareazaDownload.sd`).

Could someone please investigate this issue? Additionally, if possible, I would appreciate an analysis of the test code for potential errors.

Resources:

[Branch: shareazaDownloadTest](https://github.com/sepinf-inc/IPED/tree/shareazaDownloadTest)
[Commit: c7487bcb6180e5a09ccdad3efa76079de9842008](https://github.com/sepinf-inc/IPED/commit/c7487bcb6180e5a09ccdad3efa76079de9842008)

**Comment by patrickdalla** [comment]
The parser expects a ItemReader object registered in the context object.

Your test case should have to prepare this context, as IPED would do.

Em seg., 14 de out. de 2024, 15:29, Marcus de Oliveira <
***@***.***> escreveu:

**Comment by marcus6n** [comment]
Hi @lfcnassif! I'm facing some challenges with this. Would you mind helping me out? Thanks!

**Comment by lfcnassif** [comment]
Hi @marcus6n. @patrickdalla refers to filling the ParseContext object passed to the parse(...) method in your test. Search for `context.set(ItemReader.class` in other unit tests, you should find a working example.

**Comment by marcus6n** [comment]
Right, I'll check out that example. Thanks.

**Comment by marcus6n** [comment]
I checked this object and tried many times to run the test and it didn't work... With my current knowledge I may not be able to solve it.

**Comment by lfcnassif** [comment]
Try to use `ParseContext context = new BaseItemSearchContext().getContext(testFilePath)`

**Comment by marcus6n** [comment]
In this part `BaseItemSearchContext()`, this error appears `'BaseItemSearchContext' is abstract; cannot be instantiated`.

**Comment by marcus6n** [comment]
Now the test run worked, thank you very much @lfcnassif. Now I'll add more assertions to make the test more complete.

**Comment by lfcnassif** [comment]
Closing as not a problem.
