### ISSUE TITLE
Improve gallery rendering speed

### ISSUE THREAD

**Issue by wladimirleite** [sepinf-inc/IPED#2344]
Although the gallery rendering is already very fast, sometimes when I need to go through a large number of images, I expand the gallery to use one of my screens (as the example below), use page down/up to navigate, and notice a small delay before a new page of thumbnails are rendered. It is possible to see a white background before the actual content is rendered (kind of flickering effect).
It is just a very minor detail, but I made some code changes which minimize the described effect.

![image](https://github.com/user-attachments/assets/dd22717f-cfb7-4093-b891-dc3dd42eee9a)

**Comment by wladimirleite** [comment]
As commented in #2345.

**Comment by lfcnassif** [comment]
Just tested on spinning disk and behavior was not what I expected, I'll submit an improvement shortly.
