### ISSUE TITLE
Parsing error on WhatsApp chat

### ISSUE THREAD

**Issue by oduvaldo-vick** [sepinf-inc/IPED#2373]
Recently we are having parsing errors on WhatsApp chat. Maybe WhatsApp database had some kind of update. On Cellebrite Physical Analyzer the chats are appearing normally. Here is a print:

<img width="1917" alt="image" src="https://github.com/user-attachments/assets/597c78be-5736-4048-b5cb-a7d75b2119cf">

**Comment by wladimirleite** [comment]
There was a small update in WhatsApp DB database indeed.
We already made the necessary changes, but it is only available in the master branch (4.2-snapshot).
I think version 4.2 will be released soon.

**Comment by lfcnassif** [comment]
Yes, please see #2326. You should use a recent snapshot with the update, like this:
https://github.com/sepinf-inc/IPED/actions/runs/11988873341

Closing as duplicate. If snapshot above doesn't work for you, please reopen.
