### ISSUE TITLE
Error generating report if audio transcription is enable, but model or service not available

### ISSUE THREAD

**Issue by wladimirleite** [sepinf-inc/IPED#2381]
When a case is processed with audio transcription (`enableAudioTranscription = true`) and later, if the user tries to **create a report** in a different machine and the audio transcription originally used a local model (not available in the other environment) or a remote transcription service (which is not reachable in a different network), report generation fails (exits during its initialization).

As it is done in other tasks, I believe the correct behavior would be to disable the transcription task (logging the error), if its initialization fails AND it is a report processing.

This was reported by another user, and I was able to reproduce using 4.2-snapshot (master).

**Comment by lfcnassif** [comment]
Thanks @wladimirleite for reporting! I agree with the proposed approach.
