### ISSUE TITLE
Allow importing txt files to create a custom KFF database

### ISSUE THREAD

**Issue by rodrigohunk** [sepinf-inc/IPED#243]
Adding new files to NSRL KFF database is slow and not so easy.
Is it possible to create a functionality to import a list of hashes from a CSV file, to create a custom KFF database?

The funcionality would create a new user-defined tag.
It would it be really useful in child pornography cases, as long as the user have a KFF database of uninteresting files.

**Comment by lfcnassif** [comment]
It is always possible...

This is related to #118.

**Comment by lfcnassif** [comment]
But, using NSRL format is not slow, although not straighforward. You can build your own NSRL hashset, with just your files, and import it, after original nsrl hashset have been imported previously. See #73

**Comment by tc-wleite** [comment]
@lfcnassif Can this issue be closed, as ithe solution to #118 would cover it?
So any comments and updates stay one a single place.

**Comment by lfcnassif** [comment]
Yes, closing as duplicate.
