### ISSUE TITLE
Verify if the hashes of WhatsApp attachments are in the child sexual abuse material hashes.

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#252]
This feature will allow the identification of child pornograf even when the file is not present.

**Comment by hauck-jvsh** [comment]
partially implemented on the commit 83f7dd1f873426cd3b85cd0e95a9c27c4caf9cfe.

**Comment by hauck-jvsh** [comment]
Use the projectVIC hashset as well.

**Comment by lfcnassif** [comment]
Finished by #326
