### ISSUE TITLE
Google Drive Files

### ISSUE THREAD

**Issue by paulobreim** [sepinf-inc/IPED#254]
In the Windows forensic analysis it is possible to have Google drive details information about files transfered, so even if the files are no longer present on the HD, it is possible to know if they were

into the user folder
\Users\%username%\AppData\Local\Google\Drive\ user_default
has valuable information in 2 files in SQLite format

The first sync_config.db has a single table called "data".
Two fields stand out in this table:
user_email (e_mail used to synchronize with Google Drive)
local_sync_root_path (location where the files that are synchronized are)
The query below obtains the information to be analyzed:
SELECT
entry_key as "email",
data_value as "local"
FROM data where entry_key = "user_email" OR entry_key = "local_sync_root_path"

The second SQLite file is snapshot.db and contains the list of transferred files.

Although it has several tables, the table of forensic interest is local_entry.
The query below extracts the important information;

select
filename as "File Name",
size as "Size",
strftime ('% d /% m /% Y% H:% M:% S', datetime (modified, 'UNIXEPOCH')) as "Date Hour (UTC)",
checksum as "MD5"
from local_entry
order by modified

This information could be show as one category into iped.

**Comment by lfcnassif** [comment]
Thanks for sharing your queries.

**Comment by hauck-jvsh** [comment]
I think that MD5 info could be searched on the ledKFF base, just as the knowmet files.

**Comment by lfcnassif** [comment]
On ProjectVIC hashset too

**Comment by mbichara** [comment]
I had a look on this.
I can try to code a parser for these google drive artifacts, using the same pattern as #31. What do you think, @lfcnassif ?

**Comment by lfcnassif** [comment]
That would be great, thank you @mbichara!

**Comment by lfcnassif** [comment]
Closed by #267
