### ISSUE TITLE
Export file tree of checked items is filtering by selected tree node

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#258]
That is a "feature". Originally the user must select a reference tree node to export a file tree. That restriction was removed at some point, so the whole tree of checked items is exported if no tree node is selected. But, if some tree node is left selected unintentionally by the user, just checked items below that selected tree node are exported.

A custom tree export menu could keep filtering behaviour by tree node, and the default export menu should always export all items.

**Comment by lfcnassif** [comment]
@fsicoli I think we should upgrade iped version in triage linux distro because of this.

**Comment by fsicoli** [comment]
I totally agree. There's a high risk of misusing this function, leaving important files behind.

**Comment by lfcnassif** [comment]
That happened in recent trainings
