### ISSUE TITLE
Using variable time-out when generating thumbs according to image size

### ISSUE THREAD

**Issue by fsicoli** [sepinf-inc/IPED#263]
I suggest to be able to use variable time-outs for the thumb generating task, according to image file size. 10 seconds may not be enough to create large files thumbnails.

**Comment by lfcnassif** [comment]
Will take care of this as I warned @fsicoli about the current 10s timeout.

**Comment by lfcnassif** [comment]
10s + 1s per MB is enough? too much?

**Comment by lfcnassif** [comment]
Some 45MB PSDs took ~45s to render in my new Xeon workstation, so I will make it configurable, and maybe 2s or 3s per MB is better.
