### ISSUE TITLE
Tab implementation

### ISSUE THREAD

**Issue by AlissonMendonca** [sepinf-inc/IPED#266]
Implement the use of tabs for bookmarks created, since with this new update there are files that are found in different locations, with that the selection almost always consists of two files and to view or hear one we have to leave the preview of the other.

**Comment by lfcnassif** [comment]
Not sure if I understood. What "this new update" do you refer to? Checking attachments inside chat conversations in the viewer?

When you click on the pictures/audios/videos into the viewer, aren't they opened externally in your installed player?

**Comment by lfcnassif** [comment]
If more than 1 file is selected in the case from the viewer, they should have the same content (hash), so there is no need to view each of them individually, you can open that file from within the viewer directly. After analyzing all chat content, you can filter selected attachments to check if one path is more important than another.

Not sure if I understood correctly. If not, feel free to reopen.
