### ISSUE TITLE
Extract P2P (Emule, Shareaza, Ares) history entries as separate items in case

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#281]
Similar to what is done for browser history or chat messages, so each history entry would be shown in main table view to allow sorting by columns, filtering, searching and to correlate with other time based events.

**Comment by patrickdalla** [comment]
I'm on it right now. But I don't have a test case. Could you share a smaller one and after test on bigger ones?

**Comment by tc-wleite** [comment]
> I'm on it right now. But I don't have a test case. Could you share a smaller one and after test on bigger ones?

I have some samples of these files here. I just sent a ZIP file (~600 MB) privately to you.

**Comment by lfcnassif** [comment]
Thank you both!

**Comment by patrickdalla** [comment]
Wladmir, the entries on Ares is on Local Time, right? So, should I identify (or supose) the configured timezone before converting it to a normalized UTC, right?

**Comment by patrickdalla** [comment]
@lfcnassif , have you already implemented any method to identify (or supose) the configured case timezone for dates normalization as UTC?

**Comment by lfcnassif** [comment]
> How does I tell the viewer to render as HTML?

I don't think we need to generate a HTML item for each of them, but just a "metadata" item, like browser history entries or chat individual messages.

**Comment by patrickdalla** [comment]
We can find timezone information on registry files. And maybe some change history in event logs. Do you want the IPED to guess it automatically? Or you prefer to let this timestamp information out of the case timeline metadatas, as it can induce user error?

**Comment by patrickdalla** [comment]
> > How does I tell the viewer to render as HTML?
> 
> I don't think we need to generate a HTML item for each of them, but just a "metadata" item, like browser history entries or chat individual messages.

And how could we make the link of the entry with and existing file with same hash if not by HTML?

**Comment by lfcnassif** [comment]
I'm out of work, I will return to you on afternoon.

**Comment by patrickdalla** [comment]
> We can find timezone information on registry files. And maybe some change history in event logs. Do you want the IPED to guess it automatically? Or you prefer to let this timestamp information out of the case timeline metadatas, as it can induce user error?

For still existing files, we can compare the dates with dates of the existing entry to validate timezone information.

**Comment by lfcnassif** [comment]
> I haven't. There is the -timezone cmd line option, but I doubt most users use it.

Maybe this could be passed to parsers using the ParseContext, after identified from registry

**Comment by lfcnassif** [comment]
> Do you want the IPED to guess it automatically?

I think we should try to identify it, this timeline info is very important for CSAM cases.

**Comment by tc-wleite** [comment]
> @tc-wleite, the entries on Ares is on Local Time, right?

That is correct.

**Comment by patrickdalla** [comment]
> 

@lfcnassif ,have you already implemented any way do deprioritize an item processing, putting it in the next less priority queue an skipping its current processing, once its processing does'nt find a ParseContext variable (or any other condition)?

**Comment by lfcnassif** [comment]
> I don't remember the name, REFERENCED_ITEM maybe

The correct metadata is ExtraProperties.LINKED_ITEMS, you can put any lucene query into it.

> @lfcnassif ,have you already implemented any way do deprioritize an item processing, putting it in the next less priority queue an skipping its current processing, once its processing does'nt find a ParseContext variable (or any other condition)?

I'm not sure if I understood, do you want to send a specific item to the next processing queue based on some arbitrary condition? No, it doesn't exist today, but it is a good idea. The current approach is just based on mimeTypes and is configured inside QueuesProcessingOrder class.

Currently the WhatsAppParser uses a workaround, changing the mimetype of the main database to send it to the last queue to allow merging it with its backups, but this was a workaround implemented by @hauck-jvsh, because we don't have other alternative today.

**Comment by patrickdalla** [comment]
"I'm not sure if I understood" - Yes, you did.

Well, it seems not too difficult to implement. We only have to agree on the implementation and interface. 

Most of queue methods are implemented in ProcessingQueues class. This class can be accessed via the Manager.getInstance(). But the problem is that this class is not in the API, so it is not visible to parser implementations.

I thought in implementing an Exception subclass of TikaException, (ContextConditionNotMetException or ContextConditionPending) that could be thrown by the Parser implementation and could be catched by the ParsingTask. If that exception is thrown, the parsing task would put the evidence item in the next priority queue to try to parse again. This way we don't need to change the API. 
But still remains a problem: if the item was postponed to reach the last position on the last queue, the parser should choose to parse it anyway, even without the condition met, to parse other informations not dependable of the prior condition. So we have to inform that this another condition is met: "last parsing try".

**Comment by lfcnassif** [comment]
Those are very good thoughts, but since they change the processing pipeline, I think it is a bit sensitive and this change should be implemented in a separate ticket. About the "last parsing try", this could be signaled using the ParseContext too.

Since Emule, Ares and Shareaza histories are already parsed in the second queue, they can access other case items and the result of some Registry parser returning the timezone. Wouldn't this be enough to implement this ticket or do need something else?

**Comment by lfcnassif** [comment]
PS: I liked the TikaException subclass approach

**Comment by patrickdalla** [comment]
Back in here.

@tc-wleite the videothumbtask uses the XMPDM namespace properties. Do you think this is a good namespace to use this too to media information extracted from P2P parsed history?

**Comment by tc-wleite** [comment]
> @tc-wleite the videothumbtask uses the XMPDM namespace properties. Do you think this is a good namespace to use this too to media information extracted from P2P parsed history? Or should I create P2P specific namespace properties?

I think as `xmpDM` is used by TIKA and @lfcnassif kept the same standard when that part of the code (handling metadata) was added to `VideoThumbTask`. 
As far as I remember, those properties also use the prefix "video'.
Not sure if it would make sense for P2P properties. 
Currently, `childPornHashHits` and `p2pHistoryEntries` have no prefix, right?
Probably, if many new properties are created, having a specific prefix would make sense, but certainly @lfcnassif can provide a better view of the pros and cons here...

**Comment by patrickdalla** [comment]
I was intending to use xmpDM prefix on media specific information. The already declared in class org.apache.tika.metadata.XMPDM like album, artist, genre. For other kind of information, other namespaces could be used, or none at all.

**Comment by lfcnassif** [comment]
> I think as `xmpDM` is used by TIKA and @lfcnassif kept the same standard when that part of the code (handling metadata) was added to `VideoThumbTask`.

Correct!

> Do you think this is a good namespace to use this too to media information extracted from P2P parsed history? Or should I create P2P specific namespace properties?

I'm not sure. By default, Tika metadata (like XMP) are extracted from inside the files. In this case, they are metadata from a p2p history entry referring to external files. Probably it was extracted from the original medias, but the values may differ, because p2p programs and Tika are different software, but possibly this is not an issue.

I still need to think better, but I would put some `p2p:` prefix generally. For XMP related ones, the prefix could be `p2p:xmp:` to follow current pattern of other metadata (like those of images and videos). Except if the XMP metadata key is one of those configured in the Common Properties group, take a look at `MetadataUtil.commonKeys` private attribute, we normalized some of them as part of #570

**Comment by lfcnassif** [comment]
Thank you @patrickdalla! I just left work and will return on Tuesday. You can create a PR in "Draft mode", I think it makes easier to receive suggestions from others.

**Comment by lfcnassif** [comment]
> ExtraProperties.LINKED_ITEMS

This metadata also makes the References tab work: if a shared media is clicked, your new history entry item will be shown in References tab

**Comment by lfcnassif** [comment]
> if someone wants to make some appointment about the aproach I already created a branch with this basic implementation named p2pExtractSubitens.

I took a very quick look, the bean approach is very nice! The code is generic and can be applied to a number of similar situations, great!

**Comment by lfcnassif** [comment]
> This metadata also makes the References tab work: if a shared media is clicked, your new history entry item will be shown in References tab

To render in the viewer the linked/referenced media item when clicking on the new history entry item, the ReferencedFileViewer should be updated with the new entry media type, if I remember.

**Comment by patrickdalla** [comment]
Shareaza model classes didn't have all getter methods, and wasn't declared as public. So I had to change them a little.
I also improved the bean metadata extractor. If getter methods return another beans, the a tree will be mounted accordingly.

@fmpfeifer , could you take a look at the code, mainly on BeanMetadataExtraction usage? As you know better the model classes you can suggest some improvements.

**Comment by patrickdalla** [comment]
@lfcnassif I want to change some metadata from a parsed item after the call for extractor.parseEmbedded. I need this because I need to call parseEmbedded before child extraction, and some child extraction may not add any info at all, like getter method that returns empty arrays or collections, so after children processing I want to change the "hasChild" and EMBEDDED_FOLDER metadata info if no child was added at all.

I could do this calling "EmbeddedItem addedItem = context.get(EmbeddedItem.class);" right after parseEmbedded. But as this class is marked as deprecated I think there can be a better way.

**Comment by patrickdalla** [comment]
@lfcnassif I need to update item info after extractor.parseEmbedded. I am using "EmbeddedItem addedItem = context.get(EmbeddedItem.class);" right after to get a reference to the added item. But as this is marked as deprecated could you inform me how can I make this?

**Comment by lfcnassif** [comment]
> @lfcnassif I need to update item info after extractor.parseEmbedded. I am using "EmbeddedItem addedItem = context.get(EmbeddedItem.class);" right after to get a reference to the added item. But as this is marked as deprecated could you inform me how can I make this?

Unfortunately this is not possible today, an API for this is planned to be created and implemented on https://github.com/sepinf-inc/IPED/issues/1185.
Using the deprecated method, the returned item was already sent to processing queue and could have been indexed depending on thread scheduling, so changing its properties could have no effect at all...

**Comment by patrickdalla** [comment]
Does any IPED module already use any Expression Language parser? I ask this so I could use the same and not include a new one.
For the "ExtraProperties.LINKED_ITEMS", as its value is a lucene query, I need to make a transformation of a bean property (or more than one) to the query value. I tried with Spring Expressoin Language (SpEL) and it worked.

I have created a method for transformation registration on BeanMetadataExtraction objects. It would work like this:

        bem.registerTransformationMapping(LibraryFile.class, ExtraProperties.LINKED_ITEMS, "md5:${md5}");

So, for every LibraryFile object found on the beans extraction, it would parse the transformation rule and the result would be put on metadata ExtraProperties.LINKED_ITEMS.

**Comment by patrickdalla** [comment]
@tc-wleite 
I pushed the recent Spring EL support. It populated the properties values on the linked items accordingly. But I could not check on the test case you gave me if the links were really effective because I don't have the corresponding files. 

Don't you, or anyone else (@lfcnassif , @fmpfeifer ), have test cases with the shared files also to share with me. Ideally no CSAM cases.

I tryed to change your code as little as possible, just adding lines to config and call the BeanMetadataExtraction.

**Comment by tc-wleite** [comment]
I can try finding some corresponding files here. 
I need to finish another task today, probably will be able to look into this tomorrow.

**Comment by lfcnassif** [comment]
> Does any IPED module already use any Expression Language parser?

AFAIK no.

> Spring Expressoin Language (SpEL)

That's the size of this new dependency?

> have test cases with the shared files also to share with me

Sure! I can send you tomorrow afternoon when I'm back to work.

**Comment by patrickdalla** [comment]
According to the repository https://mvnrepository.com/artifact/org.springframework/spring-expression/5.3.23 it has 282k.

**Comment by tc-wleite** [comment]
> Don't you, or anyone else, have test cases with the shared files also to share with me. Ideally no CSAM cases.

I just uploaded to our server a sample with ~1400 files (~13 GB) that should match records in the P2P samples I sent you last week. Unfortunately, most are CSAM. Password to open the 7z was sent privately.

**Comment by patrickdalla** [comment]
Some doubts about timezone identification of LocalTime values:

- In multiple evidence processing, each evidence can have a corresponding different timezone configured.
- Timezone configured cannot be the one configured when the fact represented by the date value occurred.

The first one problem can be solved by identifying path similarities. But the last one?

Does anyone foresee some inconsistency that may apply on timezone identification from registry entries?

**Comment by patrickdalla** [comment]
How could we "alert" the user that the information is inferred and may be not so reliable. 
How could we give the user the opportunity to correct this information for a specific item once he identifies some inconsistency and the correct timezone?

**Comment by patrickdalla** [comment]
Well, I've made the following implementations:
- RegistryParser by default does not extract subitems. This can be achieved configuring parser parameter.
- RegistryParser loads the registry files in a caseData SystemRegistry class object, so other parsers can consult this registries.
- The methods for getting the registry files search for the corresponding registry file with same path start, as multiple evidence case can have multiple registry files.
- I created a specific TimeZone hash map for timezone information as it was the main objective for now.

**Comment by lfcnassif** [comment]
> * RegistryParser loads the registry files in a caseData SystemRegistry class object, so other parsers can consult this registries.

The whole decoded registries hive trees are being stored? Just to confirm, this doesn't use too much memory, right?

**Comment by patrickdalla** [comment]
Yes it use. we can keep it out as the main info for now was timezone and it
is stored individually after consulting the registry. Tomorrow i will try
to parameterize this. Maybe to load only preconfigured keys.

Em qui., 13 de out. de 2022 14:24, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by patrickdalla** [comment]
There is already a config file for the original parsing method that would
filter only selected keys. this can be used also for what would be kept in
memory for other parsers to consult.
But for now you could simply leave it out.

Em qui., 13 de out. de 2022 17:49, Patrick Bernardina <
***@***.***> escreveu:

**Comment by lfcnassif** [comment]
Another approach would be to save parsing results as metadata, then later parsers could search for the first parsed item and its metadata results to use when parsing other file, like some parsers do. But since timezone info is very important and could be reused by a number of parsers, I think it makes sense to save it globally and share it by default using ParseContext, as I originally suggested. But for other kind of information less used, the metadata approach may be an option.

**Comment by lfcnassif** [comment]
> According to the repository https://mvnrepository.com/artifact/org.springframework/spring-expression/5.3.23 it has 282k.

It depends on spring-core-5.3.23 that is 1.4MB, but I think it is ok.

**Comment by lfcnassif** [comment]
Closed by #1373
