### ISSUE TITLE
Configurable double click behaviour.

### ISSUE THREAD

**Issue by MariasStory** [sepinf-inc/IPED#283]
Hi,
Let me refer the issue #271.
The double click opening of the executables is very important problem for me. (Thanks for fixing it)
I would love to see the interface behaviour configurable.
In my case, I don't want to have any files to be open.
On another hand someone else might have another use case and this why there should be a setting for this.

**Comment by lfcnassif** [comment]
This was added to AdvancedConfig.txt files:

# Double click behaviour. Possible values: never, ask_always, ask_if_exe, always
openWithDoubleClick = ask_if_exe
