### ISSUE TITLE
Fix known.met generated visualization to allow copying to a spreadsheet style format

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#290]
The current known.met (e-Mule) parser uses DIVs, instead of a HTML table, in order to speed up the rendering of large files.
This change (table -> divs) was done a long time ago and provided a meaningful performance gain. 
However, it caused an undesired side effect that when the viewer content is copied and pasted in an external program (e.g. Excel), it loses the tabular format.

Running tests again using a HTML table, with current JVMs, if the **table cell widths are fixed** (which they already are since that change to use DIVs), the performance is similar to DIVs.

**Comment by lfcnassif** [comment]
Thanks Wladimir. Maybe this change could be copied to AresParser too?

**Comment by tc-wleite** [comment]
Sure! I will commit this one and #291, so you can take a quick look when possible. 
If everything is fine, I will made similar changes to the Ares parser.
