### ISSUE TITLE
Compress LED hashset loaded on memory

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#307]
Currently it uses the HashValue class and because of java object overhead (12 byte header + 4 bytes for array size), a 16 bytes md5 hash could consume 48 bytes of heap space. That could be optimized to save about 500MB of heap space with current hashset size (2.6M hashes and 6 different hashes being loaded).

**Comment by lfcnassif** [comment]
@tc-wleite I think LED software already uses a "all hashes in one byte array" strategy with the same goal, right?

**Comment by tc-wleite** [comment]
Correct!

**Comment by tc-wleite** [comment]
If proposed changes to #118 work as expected, LED hashes won't need to be loaded into memory for hash lookup anymore, which would solve this issue.
For LedCarveTask (proposed new name of KffCarveTask), it would still be necessary to load 2 types of hashes in memory (plus a integer reference to the rest of the entry data). 
As the new implementation uses a plain array of bytes, it would consume only ~(16 x 2 + 4)  x 2.7M = ~90 MBytes.

**Comment by lfcnassif** [comment]
closed by #443
