### ISSUE TITLE
Items count for each bookmark

### ISSUE THREAD

**Issue by Descadeirado** [sepinf-inc/IPED#320]
I would like to ask for item count on each bookmark.
Something like:
Images (345)
Documents (891)
and so on...

Thanks,
Andre

**Comment by lfcnassif** [comment]
hey @tc-wleite, our new trainee @streeg started working on this today :)

My fault, I didn't assign this to him after he accepted the invitation to join the project today.

Anyway, thank you! @streeg, I suggest you trying to implement it yourself and comparing to @tc-wleite implementation later.

**Comment by streeg** [comment]
Thanks @tc-wleite! Sure, I'll do that @lfcnassif. Thank you for the suggestion.
