### ISSUE TITLE
Firefox saved sessions with Firefox-File-Utilities

### ISSUE THREAD

**Issue by Spacial** [sepinf-inc/IPED#334]
I'd like to help with this issue, was thinking to use ffu (by jeffersonscher) to parse [firefox session files](https://support.mozilla.org/en-US/questions/1204253#answer-1075873) (get the parser):

> Lost session (previously open tabs gone):

> %APPDATA%\Mozilla\Firefox\Profiles

> recovery.jsonlz4: the windows and tabs in your currently live Firefox session (or, if Firefox crashed at the last shutdown and is still closed, your last session)
> recovery.baklz4: a backup copy of recovery.jsonlz4
> previous.jsonlz4: the windows and tabs in your last Firefox session
> upgrade.jsonlz4-build_id: the windows and tabs in the Firefox session that was live at the time of your last update
> various .js files from Firefox 55 or earlier 

> Firefox uses a number of compressed files that can't be read without decompression. These tools will decompress files users  commonly need to access for one reason or another.

maybe something similar to:

`    private void parseFirefoxBookmarks(ContentHandler handler, Metadata metadata, ParseContext context,`

If the feature is already implemented, please ignore it. I tested IPED on a training and saw bookmarks and history carved. I'd like to help in case that sessions (even crashed ones) isn't covered. FFU spits JSON file with session data.

**Comment by Spacial** [comment]
Maybe as enhancement/new feature. (if isn't covered yet, of course)

**Comment by lfcnassif** [comment]
Hi @Spacial, we don't have such a parser, thank you for your interest in contributing!

Do you know what is the ffu license? I did not find it. Maybe the lz4-java library, already used by us, could help implementing this.

I could review your contribution after returning from vacation in 10 days, if other dev doesn't beat me.

**Comment by Spacial** [comment]
Just saw on the site, is BSD-3-Clause License.

> Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
>
> 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
> 
> 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
> 
> 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
> 

(site's footer: Copyright © 2020 Jefferson Scher (BSD-3-Clause License). lz4.js © 2016 Pierre Curto (MIT License; Sept. 1, 2016). FileSaver.js © 2016 Eli Grey (MIT License; v1.3.2). MDN code samples © Mozilla Contributors or Public Domain (License). No claim to your data! Updated 2020-11-28. (Previous Version; Older Logic))

Does IPED has any test, so I only test the input (like the mozilla profile directory) and expected output by IPED?

**Comment by lfcnassif** [comment]
Great, BSD-3 is ok. Currently we have a few unit tests for the regex package in https://github.com/sepinf-inc/IPED/tree/master/iped-engine/src/test/java/br/gov/pf/iped/regex

We can create unit tests for parsers and other packages too, this is a big area for improvement. Samples with suitable license are needed.

Between releases I run long running tests on some internal forensic images with hundreds of GBs, unfortunately they can't be shared and are too big for that.

**Comment by lfcnassif** [comment]
Closed by #400. Thank you @thalespr for the PR!
