### ISSUE TITLE
Device Info Category - UFDR x IPED

### ISSUE THREAD

**Issue by ParmaGGP** [sepinf-inc/IPED#336]
It would be nice if IPED could build a "Device Info" category based in the" Device Info" that is showed in the Cellebrite UFED Physical Analyzer (UFDR). This category could summarize the device specs (manufacturer, model, OS version, IMEIs, IMSI, MSISDN, ICCID, SPN, etc.). So a blind extraction would easily show this important data.

**Comment by tc-wleite** [comment]
I implemented a simple feature that just retrieves all "device info" entries from report.xml (as they are) and create an item under a category named "Device Information".
![image](https://user-images.githubusercontent.com/7217001/113936733-968fdd80-97ce-11eb-8e3e-a761dc130540.png)

**Comment by lfcnassif** [comment]
Great, @tc-wleite! I thought exactly about creating a new item under a new category, thank you!

**Comment by lfcnassif** [comment]
Maybe that could be the first rendering of the preview tab, instead of the help, for single evidence cases. I can take care of that. Or maybe that can confuse users to think it is a single evidence case...
