### ISSUE TITLE
Docker problem.

### ISSUE THREAD

**Issue by MariasStory** [sepinf-inc/IPED#338]
Hi, thank you again for the great tool.
Unfortunately, I cannot get docker version working in linux. My script use to work previously. Now I am getting SIGSEGV.
Can someone please check if it works?
----------- From: /root/IPED/iped-3.18.2/hs_err_pid23.log -------------
---------------  T H R E A D  ---------------

Current thread (0x00007fc1f0971800):  JavaThread "Worker-7" daemon [_thread_in_native, id=98, stack(0x00007fc26d20d000,0x00007fc26d30e000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000100000

Registers:
RAX=0x0000000000000000, RBX=0x00007fc26d9e3e68, RCX=0x0000000000100000, RDX=0x00007fc1b4203c00
RSP=0x00007fc26d30bc90, RBP=0x00007fc1b4203c00, RSI=0x00007fc26d30be60, RDI=0x00007fc1f09719e0
R8 =0x00007fc1a80a2ce0, R9 =0x0000000000000007, R10=0x00007fc2a85cd3fb, R11=0x00007fc2bdae8c20
R12=0x00007fc1f09719e0, R13=0x00007fc1a80a2ce0, R14=0x00007fc26d30be98, R15=0x00007fc1f0971800
RIP=0x00007fc26c9ff8ee, EFLAGS=0x0000000000010206, CSGSFS=0x002b000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007fc26d30bc90)
0x00007fc26d30bc90:   0000000000000000 00007fc2a8616620
0x00007fc26d30bca0:   0000000000000400 00007fc26d30bcb8
0x00007fc26d30bcb0:   00007fc1f0971e50 0000000000000000
0x00007fc26d30bcc0:   00007fc26d9e3e68 0000000000000000
0x00007fc26d30bcd0:   0000000000000000 00007fc2bd9fd700
...
Instructions: (pc=0x00007fc26c9ff8ee)
0x00007fc26c9ff8ce:   d5 48 81 ec 28 01 00 00 64 48 8b 04 25 28 00 00
0x00007fc26c9ff8de:   00 48 89 84 24 18 01 00 00 31 c0 48 85 c9 74 0b
0x00007fc26c9ff8ee:   81 39 31 42 20 39 48 89 cb 74 10 4c 89 e7 e8 df
0x00007fc26c9ff8fe:   dd ff ff 48 85 c0 48 89 c3 74 1e 48 85 ed 74 0c

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX={method} {0x00007fc26d9e3e68} 'openFsNat' '(JJJ)J' in 'org/sleuthkit/datamodel/SleuthkitJNI'
RCX=0x0000000000100000 is an unknown value
RDX=0x00007fc1b4203c00 is an unknown value
RSP=0x00007fc26d30bc90 is pointing into the stack for thread: 0x00007fc1f0971800
RBP=0x00007fc1b4203c00 is an unknown value
RSI=0x00007fc26d30be60 is pointing into the stack for thread: 0x00007fc1f0971800
RDI=0x00007fc1f09719e0 is an unknown value
R8 =0x00007fc1a80a2ce0 is an unknown value
R9 =0x0000000000000007 is an unknown value
R10=0x00007fc2a85cd3fb is at code_begin+859 in an Interpreter codelet
method entry point (kind = native)  [0x00007fc2a85cd0a0, 0x00007fc2a85cda40]  2464 bytes
R11=0x00007fc2bdae8c20: <offset 0x9a3c20> in /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so at 0x00007fc2bd145000
R12=0x00007fc1f09719e0 is an unknown value
R13=0x00007fc1a80a2ce0 is an unknown value
R14=0x00007fc26d30be98 is pointing into the stack for thread: 0x00007fc1f0971800
R15=0x00007fc1f0971800 is a thread

Stack: [0x00007fc26d20d000,0x00007fc26d30e000],  sp=0x00007fc26d30bc90,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libtsk_jni_root.so+0x68ee]  Java_org_sleuthkit_datamodel_SleuthkitJNI_openFsNat+0x2e

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.sleuthkit.datamodel.SleuthkitJNI.openFsNat(JJJ)J+0
j  org.sleuthkit.datamodel.SleuthkitJNI.openFs(JJLorg/sleuthkit/datamodel/SleuthkitCase;)J+127
j  org.sleuthkit.datamodel.FileSystem.getFileSystemHandle()J+56
j  org.sleuthkit.datamodel.FsContent.loadFileHandle()V+27
j  org.sleuthkit.datamodel.FsContent.readInt([BJJ)I+18
j  org.sleuthkit.datamodel.AbstractFile.read([BJJ)I+21
j  org.sleuthkit.datamodel.ReadContentInputStream.read([BII)I+109
j  dpf.sp.gpinf.indexer.util.SleuthkitInputStream.read([BII)I+24
J 1657 C1 java.io.BufferedInputStream.read1([BII)I (108 bytes) @ 0x00007fc2a8c83c64 [0x00007fc2a8c83820+0x444]
J 1658 C1 java.io.BufferedInputStream.read([BII)I (113 bytes) @ 0x00007fc2a8c82b94 [0x00007fc2a8c82900+0x294]
J 1661 C1 java.io.FilterInputStream.read([B)I (9 bytes) @ 0x00007fc2a8c8a68c [0x00007fc2a8c8a580+0x10c]
j  java.nio.file.Files.copy(Ljava/io/InputStream;Ljava/io/OutputStream;)J+12
j  java.nio.file.Files.copy(Ljava/io/InputStream;Ljava/nio/file/Path;[Ljava/nio/file/CopyOption;)J+163
j  gpinf.dev.data.Item.getTempFile()Ljava/io/File;+164
j  dpf.sp.gpinf.indexer.process.task.TempFileTask.process(Liped3/IItem;)V+49
j  dpf.sp.gpinf.indexer.process.task.AbstractTask.processMonitorTimeout(Liped3/IItem;)V+2
j  dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(Liped3/IItem;)V+144
j  dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(Liped3/IItem;)V+38
j  dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(Liped3/IItem;)V+205
j  dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(Liped3/IItem;)V+38
j  dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(Liped3/IItem;)V+205
j  dpf.sp.gpinf.indexer.process.Worker.process(Liped3/IItem;)V+68
j  dpf.sp.gpinf.indexer.process.Worker.run()V+69
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x00007fc1e8006000 JavaThread "AWT-Shutdown" [_thread_blocked, id=123, stack(0x00007fc1a22e9000,0x00007fc1a23ea000)]
  0x00007fc1a81a3000 JavaThread "Thread-25" daemon [_thread_blocked, id=114, stack(0x00007fc1a23ea000,0x00007fc1a24eb000)]
  0x00007fc1a819f800 JavaThread "Thread-24" daemon [_thread_in_native, id=113, stack(0x00007fc1a24eb000,0x00007fc1a25ec000)]
  0x00007fc1a819e800 JavaThread "Thread-23" daemon [_thread_in_native, id=112, stack(0x00007fc1a25ec000,0x00007fc1a26ed000)]
  0x00007fc1a8173000 JavaThread "C3P0PooledConnectionPoolManager[identityToken->1bqq1heae1e53v1v2m11mh|122ad10c]-HelperThread-#2" daemon [_thread_blocked, id=110, stack(0x00007fc1a2be7000,0x00007fc1a2ce8000)]
  0x00007fc1a816a800 JavaThread "C3P0PooledConnectionPoolManager[identityToken->1bqq1heae1e53v1v2m11mh|122ad10c]-HelperThread-#1" daemon [_thread_blocked, id=109, stack(0x00007fc1a2ce8000,0x00007fc1a2de9000)]
  0x00007fc1a8169800 JavaThread "C3P0PooledConnectionPoolManager[identityToken->1bqq1heae1e53v1v2m11mh|122ad10c]-HelperThread-#0" daemon [_thread_blocked, id=108, stack(0x00007fc26405b000,0x00007fc26415c000)]
  0x00007fc1a8167000 JavaThread "C3P0PooledConnectionPoolManager[identityToken->1bqq1heae1e53v1v2m11mh|122ad10c]-AdminTaskTimer" daemon [_thread_blocked, id=107, stack(0x00007fc26c08a000,0x00007fc26c18b000)]
  0x00007fc1f09a5800 JavaThread "Thread-18" daemon [_thread_blocked, id=104, stack(0x00007fc26cc07000,0x00007fc26cd08000)]
  0x00007fc1f09a4000 JavaThread "Thread-17" daemon [_thread_blocked, id=103, stack(0x00007fc26cd08000,0x00007fc26ce09000)]
  0x00007fc1f0978000 JavaThread "Worker-11" daemon [_thread_blocked, id=102, stack(0x00007fc26ce09000,0x00007fc26cf0a000)]
  0x00007fc1f0976800 JavaThread "Worker-10" daemon [_thread_blocked, id=101, stack(0x00007fc26cf0a000,0x00007fc26d00b000)]
  0x00007fc1f0974800 JavaThread "Worker-9" daemon [_thread_in_vm, id=100, stack(0x00007fc26d00b000,0x00007fc26d10c000)]
  0x00007fc1f0973000 JavaThread "Worker-8" daemon [_thread_blocked, id=99, stack(0x00007fc26d10c000,0x00007fc26d20d000)]
=>0x00007fc1f0971800 JavaThread "Worker-7" daemon [_thread_in_native, id=98, stack(0x00007fc26d20d000,0x00007fc26d30e000)]
  0x00007fc1f096f800 JavaThread "Worker-6" daemon [_thread_blocked, id=97, stack(0x00007fc26d30e000,0x00007fc26d40f000)]
  0x00007fc1f096e000 JavaThread "Worker-5" daemon [_thread_blocked, id=96, stack(0x00007fc26d40f000,0x00007fc26d510000)]
  0x00007fc1f096c000 JavaThread "Worker-4" daemon [_thread_in_vm_trans, id=95, stack(0x00007fc26d510000,0x00007fc26d611000)]
  0x00007fc1f096a800 JavaThread "Worker-3" daemon [_thread_blocked, id=94, stack(0x00007fc26d611000,0x00007fc26d712000)]
  0x00007fc1f0969000 JavaThread "Worker-2" daemon [_thread_blocked, id=93, stack(0x00007fc26d712000,0x00007fc26d813000)]
  0x00007fc1f0967800 JavaThread "Worker-1" daemon [_thread_blocked, id=92, stack(0x00007fc26d813000,0x00007fc26d914000)]
  0x00007fc1f0966800 JavaThread "Worker-0" daemon [_thread_in_vm, id=91, stack(0x00007fc26fdfe000,0x00007fc26feff000)]
  0x00007fc1f0822800 JavaThread "Thread-15" daemon [_thread_blocked, id=84, stack(0x00007fc26feff000,0x00007fc270000000)]
  0x00007fc1f0027800 JavaThread "TimerQueue" daemon [_thread_blocked, id=60, stack(0x00007fc274099000,0x00007fc27419a000)]
  0x00007fc1f0022800 JavaThread "process reaper" daemon [_thread_in_native, id=59, stack(0x00007fc27c103000,0x00007fc27c13c000)]
  0x00007fc2b99c1800 JavaThread "SwingWorker-pool-3-thread-1" daemon [_thread_blocked, id=57, stack(0x00007fc27439a000,0x00007fc27449b000)]
  0x00007fc2b99be000 JavaThread "Thread-1" daemon [_thread_blocked, id=56, stack(0x00007fc27449b000,0x00007fc27459c000)]
  0x00007fc2b82d6000 JavaThread "Service Thread" daemon [_thread_blocked, id=54, stack(0x00007fc27d968000,0x00007fc27da69000)]
...

**Comment by lfcnassif** [comment]
Have you tried this https://github.com/sepinf-inc/IPED/wiki/Troubleshooting#jvm-crashes ?

Does it happen with any dd/e01 image or with a specific one?

Does it work on Linux without docker? If yes, you would be better reporting this to iped-docker project.

**Comment by lfcnassif** [comment]
Could you answer the first 2 questions?

**Comment by MariasStory** [comment]
Hi @lfcnassif, thank you for the effort to solve the problem and sorry for not answering.
In short, I have few images where iped fails. Windows and docker version. I pasted the docker error.
Yes, I did try the recommended in wiki configuration changes in Windows. Did not help.
I did not try linux native yet.

**Comment by lfcnassif** [comment]
Hi @MariasStory,

Thanks for the feedback. The **robustImageReading** option **should** solve the error above, could you double check if it was enabled in the right profile?

And could you post (or send privately) the windows error logs? Both the processing log in log folder and the related hs_err_pidXXX.log?

**Comment by lfcnassif** [comment]
Not able to reproduce. The above stacktrace is not possible to occur if robustImageReading is enabled, the call stack would use different classes. Please reopen if you can provide the asked info.
