### ISSUE TITLE
Implement a supertimeline view.

### ISSUE THREAD

**Issue by MariasStory** [sepinf-inc/IPED#35]
Please implement a linear - supertimeline view with MACB and the ability to export it to csv.

In such a view, same files are shown few times depending on times associated with it.

**Comment by lfcnassif** [comment]
That's a very useful feature, thank you for demonstrating interest. At least we need three new columns for event date, event type and event source. Events could be put in a new category and may be generated or not depending on configuration, because they will make cases heavier. But I would not call it super timeline if it just uses MACB times. The challenge about timelines is extracting events from different kinds of artifacts and keeping up to date with new versions of them.

**Comment by MariasStory** [comment]
Hi @lfcnassif, thank you for such a detailed explanation.

I am not sure if I got details of your explanation. I thing you mean something like plaso. Don't you?

Actually, for a start, I would like to have a new view in the IPED-SearchApp that would be similar to the current view, but restructured.
Currently, there are 4 times for every file CMA (I am not sure what RecordDate means, maybe B).
Anyway, I would just put it all in one column and if the CMAR times are similar I would just put MACB. Otherwise, for example, I would put "MA.B" time and repeat the record for the file with a different time, like "..C.".
This way it will be easy to correlate events in a timeline. Like timesketch or just in excel.

**Comment by lfcnassif** [comment]
Yes, like plaso and like you described. RecordDate means "MFT Record Change Date", not File Creation Date.

**Comment by lfcnassif** [comment]
I had an implementation idea on #306 and will implement a first version for this.

**Comment by lfcnassif** [comment]
From an user point of view, I'm including a button at top right of Table Tab to toggle between default and timeline view (also present in options menu) and new "TimeStamp" and "TimeEvent" columns. After toggling, each item on table are expanded to one row per "TimeStamp" different value (like you suggested), and the events are shown in the "TimeEvent" column for that timestamp. All events extracted by the tool are dynamically identified and added, and they can also be also filtered in "Metadata" panel:
![image](https://user-images.githubusercontent.com/7276994/113973751-2eafb600-9813-11eb-9d41-f88d562322c8.png)

**Comment by MariasStory** [comment]
Hi @lfcnassif,
It seems that the "Timeline view" is "kind of" working.
My use case is kind of similar to use of https://timesketch.org/:
![image](https://github.com/sepinf-inc/IPED/assets/6576335/9718c706-830d-48d0-89f9-1e66949d078e)
There we have a list of events and can tag them. For this we need to see adjastend events.

Let me suggest some improvements:
* I could not find a good way to find specific entries in the view. I could do a search, but the cursor position is not preserved after the search is changed or emptied.
* I could not properly save the super-timeline. I get repeated entries but they are identical and it is not clear what each of them is:
![image](https://github.com/sepinf-inc/IPED/assets/6576335/90b3823c-f079-4f5e-9a8c-620eb8187cbc)
Can we fix the export?

**Comment by lfcnassif** [comment]
Hi @MariasStory,

> There we have a list of events and can tag them

Unfortunatelly IPED tags/bookmarks are item based, not event based, it would need a efactoring to tag specific events.

> * I could not find a good way to find specific entries in the view. I could do a search, but the cursor position is not preserved after the search is changed or emptied.

In the past, I suggested an aproach using a few steps here: https://github.com/sepinf-inc/IPED/discussions/1304#discussioncomment-3666616
Quoting it: "It is possible to check the item, clear all filters, sort by checkbox, select the artifact of interest, then sort by timestamp to see surrounding events..."

> * I could not properly save the super-timeline. I get repeated entries but they are identical and it is not clear what each of them is:
> Can we fix the export?

The export to CSV feature was always item based, not event based, so it is not a bug to fix, just a lack of functionality. We could add a feature to export events to CSV if the timeline view is enabled, that seems not hard to implement, but of course needs some effort.

**Comment by lfcnassif** [comment]
Hi @MariasStory, just created a ticket about your second suggestion: https://github.com/sepinf-inc/IPED/issues/1860

Thanks
