### ISSUE TITLE
Multicases Function Stopped

### ISSUE THREAD

**Issue by GRCWill** [sepinf-inc/IPED#366]
The multicases function stopped working in this last version 3.18?

When I tried to use the multicase parameter, an error occurred saying that the configuration file was not found.
Thanks.

**Comment by lfcnassif** [comment]
Afaik no. Please send the full log and check the right command at https://github.com/sepinf-inc/IPED/wiki/User-Manual#multicases

**Comment by GRCWill** [comment]
Thanks for the answer, now it worked. I was using the old command

java -jar lib/iped-search-app.jar -multicases (pasta_com_casos | txt_com_casos)

**Comment by lfcnassif** [comment]
IPEDSearch-App.exe basically calls your command. Could you send the log?

**Comment by GRCWill** [comment]
I could not find any log file, there is only this message.
![Error msg](https://user-images.githubusercontent.com/59067366/107700137-d38b9800-6c95-11eb-9199-1b1c9ff88229.png)

**Comment by lfcnassif** [comment]
This feature was never designed to run from the iped folder, but from some case folder. Maybe it worked by luck.

If you run, from one of the cases folder listed in case.txt, java -jar indexador/lib/iped-search-app.jar -multicases... that is what IPEDSearchApp.exe does.

**Comment by lfcnassif** [comment]
just updated the docs to make it clear.

**Comment by lfcnassif** [comment]
Closing as "not a problem".

**Comment by GRCWill** [comment]
Would it be possible, in some way, to make a quality check in relation to the processing / indexing of evidence?
Some document or report that shows that all items present in the evidence have been processed, even if there is an error in a specific item, but at least it has been passed on to the pipeline.
Basically demonstrate to third parties that no items have been left behind.

**Comment by lfcnassif** [comment]
It already exists, it is the processing log. If you want you can turn debug on in conf/Log4j2ConfigurationFile.xml, so it will log all items processed (not just those with errors), but be warned it will became huge.
