### ISSUE TITLE
Keyword List - Indexed Report

### ISSUE THREAD

**Issue by gis-msouza** [sepinf-inc/IPED#372]
Hi!!!

What is the purpose of importing a keyword list when generating an indexed report?
I saw no difference when using this option.

Did the proposal involve being able to export the report without the inclusion of a tag, but only the list of words?

Thank you.

**Comment by hauck-jvsh** [comment]
When you import a keyword list, all the keyword appears in the search field. I use this feature when the annalists must search for all of those terms in a lot of materials, making this task easier.
