### ISSUE TITLE
Export file previews to ElasticSearch and MinIO

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#378]
The previews (mostly HTML) created in the processing of the case should be exported to the ElasticSearch and MinIO. This is important to easy the exhibition of such files, preventing the re-parser of those files by other applications.

**Comment by hauck-jvsh** [comment]
The commit d1baa1c0f31fbfdadeb76d5cad48f097b69fde9a implements the preview exporting in both tasks (ElasticSearch and MinIO).

**Comment by lfcnassif** [comment]
Thanks @hauck-jvsh will try to take a look tomorrow.

**Comment by lfcnassif** [comment]
closed by d1baa1c0f31fbfdadeb76d5cad48f097b69fde9a
