### ISSUE TITLE
Discord cache files parser.

### ISSUE THREAD

**Issue by felipecampanini** [sepinf-inc/IPED#390]
On windows the Discord application caches some conversations in the "C: \Users\{UserName}\AppData\Roaming\Cache" directory.

Create a parser to analyze data from the files.

**Comment by streeg** [comment]
It seems the cache folder stores only the last seven days of content and mostly of them are images. There is a program called [CacheMonkey](https://cachemonkey.app/) that allows you to see the content of that folder.
