### ISSUE TITLE
Faster item count per category 

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#391]
![image](https://user-images.githubusercontent.com/7217001/110993566-37b58080-8356-11eb-9ead-9ff571879989.png)

In larger cases, sometimes it takes a few seconds to update item count per category (shown as "(...)" while counting).
It is already very fast, and done in background, so it is not an issue at all, but it could be faster.

**Comment by lfcnassif** [comment]
Yes, It could look up the existent Lucene SortedSetDocValues, so will be instant!

**Comment by tc-wleite** [comment]
I saw it could be optimized much further, but the change I proposed is something simpler (in fact a one-line change).
It already made this counting instantaneous (~5 ms/category in a test case here, which took ~300 ms/category before).

**Comment by lfcnassif** [comment]
For sure, didn't see your commit before, so simple! Great!
