### ISSUE TITLE
Non ascii chars in extension of exported files could cause problems

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#394]
An user reported a zero sized file named "01. Termos de Colaboração - BJ" was exported as "D41D8CD98F00B204E9800998ECF8427E. termos de colaboração - bj". Later he had problems using fsum to compute hashes of exported files.

Maybe we could remove non ascii chars from detected extensions (original ext is used when no signature is found). File names/extensions are already cleaned to remove forbidden NTFS chars, that is not the case.

But that isn't really an extension. Maybe change extension detection rules to set an empty ext if non ascii chars or spaces are found in the middle of the possible extension? This is a more delicate change.

Any thoughts @tc-wleite?

**Comment by lfcnassif** [comment]
Trailing spaces are also being allowed.

**Comment by tc-wleite** [comment]
> But that isn't really an extension. Maybe change extension detection rules to set an empty ext if non ascii chars or spaces are found in the middle of the possible extension? This is a more delicate change.

Your suggestion (non-ascii or spaces -> use empty extension) above seems to be the best solution.

Maybe adding a rule to limit the extension length would prevent other similar problems.
As exported file names should have less than 256 characters, a huge (e.g. 250 characters) extension would cause problems (and will probably be an invalid/misidentified extension anyway).

**Comment by lfcnassif** [comment]
Filename is already limited to 64 chars (Joliet limit) when exporting.
