### ISSUE TITLE
Integrate a MSGViewer for MSG emails

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#416]
Currently we have no viewer for msg and it is rendered in TextViewer. @gfd2020 implemented one a long time ago and it could be integrated. The viewer output should be coherent with MSGParser results.

**Comment by lfcnassif** [comment]
@gfd2020 are you interested and do you have time to submit a PR with your implementation?

**Comment by gfd2020** [comment]
> @gfd2020 are you interested and do you have time to submit a PR with your implementation?

Hi. I will implement.

**Comment by gfd2020** [comment]
> Great, thank you! Take your time!

OK! Did you see my e-mail?

**Comment by lfcnassif** [comment]
No. Try my personal email in my profile.

**Comment by lfcnassif** [comment]
Reopening, actually I had identified an issue with japanese/chinese/korean chars rendered by the viewer, when rtf-to-html library is used (most time for msg). I left it for future improvemente, but because of #435 I think we should fix this.

Possibly rtf-to-html will need to be fixed. I was able to render chars correctly converting RTF->HTML with Tika (the code was left unused in source), but Tika removes most formatting... If you could take a look @gfd2020, that would be great.

**Comment by lfcnassif** [comment]
I can send you some samples privately if you want.

**Comment by lfcnassif** [comment]
I'm preparing the 3.18.6 release. This is an independent module and should not cause regressions. Should this incomplete feature be included besides the non Latin1 scripts rendering problems?

**Comment by gfd2020** [comment]
> 
> 
> Reopening, actually I had identified an issue with japanese/chinese/korean chars rendered by the viewer, when rtf-to-html library is used (most time for msg). I left it for future improvemente, but because of #435 I think we should fix this.
> 
> Possibly rtf-to-html library will need to be fixed. I was able to render chars correctly converting RTF->HTML with Tika (the code was left unused in source), but Tika removes most formatting... If you could take a look @gfd2020, that would be great.

@lfcnassif   - Could you send me the examples that give error?

**Comment by lfcnassif** [comment]
@gfd2020 sent by email, thanks for taking a look.

**Comment by lfcnassif** [comment]
It is not the ideal solution, but to close this I'm planning to run Tika msg decoding before rtf-to-html library. If Tika's output contains just Latin1 chars, switch to rtf-to-html library. What do you think @gfd2020 ?

**Comment by gfd2020** [comment]
> It is not the ideal solution, but to close this I'm planning to run Tika msg decoding before rtf-to-html library. If Tika's output contains just Latin1 chars, switch to rtf-to-html library, maybe that would work. What do you think @gfd2020 ?

I agree.

**Comment by lfcnassif** [comment]
Will improve rendering of inline images here...
