### ISSUE TITLE
Bookmark disappearing from the Bookmark Management window

### ISSUE THREAD

**Issue by ericardobr** [sepinf-inc/IPED#418]
In the Bookmark Management window an existing bookmark was renamed from "Ronald lemon" (lowercase 'l') to "Ronald Lemon" (uppercase 'L'). After that, it disappeared from the bookmark list in the Bookmark Management window, although it can still be selected from the Bookmark section on the main interface and it shows up on the "Bookmark" field in the item table.

Closing and reopening the Bookmark Management window doesn't fix the issue.

Closing and reopening the case does fix the issue.

**Comment by lfcnassif** [comment]
Original intent was to make bookmarks case insensitive (but wrongly implemented). Should bookmarks be case sensitive or not?

**Comment by ericardobr** [comment]
> Original intent was to make bookmarks case insensitive (but wrongly implemented). Should bookmarks be case sensitive or not?

I don't think case sensitive bookmarks are a good idea, lots of potential for confusion. Keep it case insensitive.

**Comment by tc-wleite** [comment]
IMHO, bookmarks should be case insensitive, but it should be possible to change the displayed name case (like the example in the first post).

**Comment by lfcnassif** [comment]
I just fixed changing bookmarks to be case sensitive. Will change based on your feedback, thanks.
