### ISSUE TITLE
Problem install Jep python library 

### ISSUE THREAD

**Issue by fcscoutinho** [sepinf-inc/IPED#431]
I am trying to install the Jep library to use with iped with python. My version of Java is 251.
When trying to install you receive the following error message: jep unable to find vcvarsall bat setup python setup.py build
How can I fix this problem and put iped to use python properly?

**Comment by lfcnassif** [comment]
Just updated the docs again: https://github.com/sepinf-inc/IPED/wiki/User-Manual#python-modules
