### ISSUE TITLE
Split report

### ISSUE THREAD

**Issue by rafael844** [sepinf-inc/IPED#432]
With UFED Cellebrite, we can use CellebriteReader.exe and split the generated report in 4GB (DVD) parts for example, so it easy to burn. Is there a way to do something like that with iped? Use IpedSearch.exe and "compress" all other folders (index, exported...)  in a file (.IPED, example) so it could be splited.

**Comment by lfcnassif** [comment]
There is no such feature, it is not so easy to implement...

**Comment by rafael844** [comment]
ok! 
Thank you.
