### ISSUE TITLE
Issues with displaying Cyrillic (абвгдеёжз..) and Latvian (aābcčd..) characters in some areas (not all) of the program

### ISSUE THREAD

**Issue by reacan** [sepinf-inc/IPED#435]
Hello everyone! 

I've been facing some issues with encoding for a while now. From what I've learned so far by studying the HTML reports, I think it could be related to the fact that at least two different character sets are used throughout the code - iso-8859-1 and UTF-8.

It appears that where UTF-8 is used, both Cyrillic and Latvian characters are displayed correctly and where iso-8859-1 is used, these characters are displayed as jibberish, at least for Latvian that is the case, not sure about the Cyrillic. I think the issue with Cyrillic could be due to the fact that some of the files that I have use KOI8-R encoding

The below screenshot was taken from the "Emails" subcategory, some of the text in Cyrillic is displayed correctly. 
E-mail headers are in UTF-8 while the body text is in KOI8-R:

![emails](https://user-images.githubusercontent.com/61985693/113269139-d3486a00-92e0-11eb-87b3-0bef23fab635.png)

This one was taken from the "Mailboxes" subcategory, the text in Latvian is displayed correctly in the Preview, Attachs/Subitems fields, apart from the "Name" field, where the first entry should be - "Visas vēstules" and the last one should be "Svarīgi sūdi" (this is from a mock case):

![mailboxes](https://user-images.githubusercontent.com/61985693/113269193-e0655900-92e0-11eb-926b-63785febab69.png)

And the last one was taken from the HTML report, the text in Latvian is displayed incorrectly in the contents.htm and displayed correctly in thumbs_001.htm:

![html_report](https://user-images.githubusercontent.com/61985693/113269878-90d35d00-92e1-11eb-9b27-29368826915c.png)

I'm sure that in the HTML reports the issue is due to different encodings used, Latvian does not go along with iso-8859-1, but regarding the Cyrillic problem could that be due to the older KOI8-R encoding?

**Comment by lfcnassif** [comment]
Thanks for reporting @reacan. I just fixed the report issue.

About the name column issue, java is able to render unicode chars. Were those mbox files with name issues extracted from a zip file or other container? Maybe it is a zip encoding issue, not sure if easy to fix.

The viewer issue maybe could be fixed. Could you send me privately some email sample without confidential info that reproduces the issue?

**Comment by reacan** [comment]
@lfcnassif Thank you for looking into this. It appears that the issue is with those particular .mbox files. Just checked the MFT entries with both sleuthkit and FTK Imager and none of the programs can render these characters correctly. These .mbox files were created with Mozilla Thunderbird so I assume it could be a Thunderbird issue. When I virtualize the image and open Thunderbird, I see the entries displayed correctly in Thunderbird but not in Windows Explorer.

If anyone else gets in trouble with encoding issues I can recommend a program called "enca" to convert files with problematic encoding to UTF-8. Just need to know the language the files are in. For now I have tested this on text files only. enca -L ru <filename> will return the encoding, which in my case was "MS-Windows code page 1251, Mixed line terminators", and then enconv -L ru -x UTF-8 <filename> to convert the encoding.  

I will download and build the new source to test the reports and report back.

**Comment by lfcnassif** [comment]
Just saw your edits today (edits doesn't send emails imho), never have seen that _JAVA_OPTIONS error, good you solved :)

About the email content encoding issue, I think that can be fixed, but I would need some sample. I will try to look for some similar issue in our case database, but possibly will not find the same encoding that caused your problem.

**Comment by lfcnassif** [comment]
Hi @reacan, for the next major version, I changed the default parser for plain text files which are being affected by a similar issue. Please check the details and solution for the current version on #470.

For the email body encoding issue, I will work on it soon. It will need careful testing with a bunch of emails I have already collected, to avoid or at least minimize regressions with other encodings.

**Comment by lfcnassif** [comment]
Hi @reacan, I just pushed an initial branch trying to fix this, worked on most emails you sent to me. Please try on other email samples.

Again, I had to patch java-libpst library to do a better guessing of unknown charsets. I tried their last develop branch, but worked just with a few emails without html body. I still need to test the new approach with the email dataset I collected.

You will find a build with the changes at https://github.com/sepinf-inc/IPED/actions/runs/749534332

**Comment by lfcnassif** [comment]
I detected some regressions with the proposed solution for Latin1 emails, although searches for words with diacritics (e.g. não, são, então, você...) are returning a bit more results. Will take a closer look at the regressions to see if it is possible to workaround them.

**Comment by lfcnassif** [comment]
Fixed as part of more general work on #473. Thanks @reacan for reporting and the samples.
