### ISSUE TITLE
Minor optimization - detectors executing twice 

### ISSUE THREAD

**Issue by mbichara** [sepinf-inc/IPED#457]
I found out that each detector in the CompositeDetector is running two times in a row for every item.

**Comment by lfcnassif** [comment]
Thanks for catching this

**Comment by lfcnassif** [comment]
@mbichara I'll apply the solution to this separately from #458 since that is still draft and needs to be carefully tested with some hundreds of thousands/millions of files of different file formats to catch regressions, thanks.
