### ISSUE TITLE
Allow running multiple parsers on the same file

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#459]
There are a lot of situations when we need that. Tika 2.0-alpha has support for it. Maybe I'll add a simple implementation until Tika-2.0 evolves to a stable status.

**Comment by tc-wleite** [comment]
@lfcnassif, while running unrelated tests, I noticed that processing log contains many errors like this one:
`2021-04-25 11:47:47	[WARN]	[indexer.parsers.IndexerDefaultParser]			ParsingThread-1 Parsing exception: EXE\A0002793.exe (3555328 bytes)		java.nio.file.NoSuchFileException: c:\TempIPED\indexador-temp1619362055725\apache-tika-1266851519226257354.tmp
`

Basically all EXE, DLL and other file types caused this error (and were flagged with "parserException").
I think you should be able to reproduce it processing any executable.
The error doesn't happen with previous versions (3.18.x).

Digging into the code I think it may be related to this feature.
In `MultipleParser`, Shouldn't this `IOUtils.closeQuietly(tis); tis = null;` be moved to the finally outside the loop `for (Parser parser : parsers)` ?

**Comment by lfcnassif** [comment]
Thanks @tc-wleite. Actually, first `tis` (created outside the loop) shoudn't be closed anywhere, just those created inside the loop. I think the error does not happen with mounted folders, so I didn't catch it. Will fix, thank you!

**Comment by lfcnassif** [comment]
fixed, thanks!
