### ISSUE TITLE
EML Attachments being exported even if not selected and automatic export off.

### ISSUE THREAD

**Issue by DHoelz** [sepinf-inc/IPED#468]
Trying to export EML files from Thunderbid e-mail client without unecessary attachments.

However even if I deselect all attachments and check NOT to export e-mail attachments automatically IPED will export the full EML file.

Inside IPED-Search the attachments (PDF, spreadsheets, images...) will not be shown in their categories or even be listed however they can be accessed from the links inside the e-mail message.

Tested on IPED 3.18.4 and 3.18.5. 

Am I doing something wrong or is this the expected behavior?

**Comment by lfcnassif** [comment]
This is expected. The attachments are not re-exported as separate items (wasting more disk space), but the EML file is kept original (instead of being changed to a version without attachments), so the attachments can still be accessed from the EML viewer.

**Comment by lfcnassif** [comment]
Note this behaviour is different from emails extracted from PST/OST, where the original EML file is gone, it is broken into several pieces inside PST/OST and the exact original version can't be rebuilt, so IPED creates a HTML preview where the attachments are not embedded but linked to, so just the email body could be exported without attachments.

**Comment by DHoelz** [comment]
Ok. Thanks for your quick reply.
