### ISSUE TITLE
Log Console Error

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#471]
This is a rare and minor issue that affects only developers.
Sometimes, usually after a full project rebuild, the following error is shown in the console when IPED is executed:
`main ERROR Console contains an invalid element or attribute "PackageRegexpFilter"`
Usually another full rebuild fixes this issue.
When this error happens, the PackageRegexpFilter (that prevents some messages to be included in the execution log) stops to work.
It seems that the problem is somehow related with the order classes are compiled and later loaded by the class loader.

**Comment by tc-wleite** [comment]
@lfcnassif, not sure if you or another developer have seen this happening again.
Recently, I started to get it occasionally, after rebuilding the project.
Anyway, locally I applied the same fix (I guess it was removed at some point).

In **iped-app/resources/config/conf/Log4j2ConfigurationFile.xml**
<Configuration status="INFO" **packages="iped.engine.log"**>

**Comment by lfcnassif** [comment]
I haven't seen. Let's reaply your fix and see it works. @fmpfeifer, as you are the original developer of `PackageRegexpFilter`, do you have any suggestion?
