### ISSUE TITLE
Upgrade java-libpst library and custom detection for unknown charsets

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#473]
While working on #435, I reviewed java-libpst commit history and they fixed a number of issues, although there was no release since 2017. Unfortunately https://github.com/rjohnsondev/java-libpst/issues/60 is not fixed yet (I tested again). Will need to re-apply some of our patches, or send a PR to them.

**Comment by lfcnassif** [comment]
I re-applied some iped patches on last java-libpst develop (avoid some NPE and 3x speed up in pst decoding).

Also added a pluggable charset detector interface to fix #435 and to handle unknown charsets. Current strategy is try to detect utf8/utf16, then fallback to Tika charset detector. Results are better than before for Latin1 scripts too.

**Comment by lfcnassif** [comment]
PS: Tested on 988 PST/OST files with 95GB total size

**Comment by lfcnassif** [comment]
closed by b5294b0

**Comment by lfcnassif** [comment]
@fsicoli with last commit, triage profile (that uses java-libpst) can parse **most** emails and attachments from OST files.

**Comment by fsicoli** [comment]
Great news!

**Comment by lfcnassif** [comment]
java-libpst is still missing ~23% of attachments from OST files comparing with libpff in my last test, but that is better than nothing for triage...
