### ISSUE TITLE
Fix exceptions thrown from PhotoDNATask module

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#477]
I think NPE is being thrown with corrupted images, but not sure. Anyway, we should throw a better exception.

**Comment by tc-wleite** [comment]
@lfcnassif, running several tests here using the latest version of the HashDB branch, I see many log errors from PhotoDNATask.
A lot of them were `java.lang.Exception`, but no NPE, so I am not sure if it is the same issue you want to investigate...

Anyway, I found two related situations that caused exceptions and I made changes to avoid them in the HashDB branch.
If you are seeing a different issue, send me some files that triggered the NPE and I can take a look here.

**Comment by lfcnassif** [comment]
Thank you @tc-wleite for taking a look! I remeber of lots of NPEs from PhotoDNATask in a test some weeks ago. I did mvn clean several times since then and I think I didn't save the log, will try to reproduce next week.

**Comment by lfcnassif** [comment]
I understood you fixed trying to compute pdna of corrupted images (thumb.length = 0) and fixed some transparency issue, right? Great!

**Comment by tc-wleite** [comment]
It seems PhotoDNA library also checks for minimum image dimensions. 
That was triggering errors with wide/tall images.
The other exceptions came from zero length thumbs (corrupted images).
These two changes covered all the cases in a small test set I used, although I was not getting NPE before these changes.
There could be other situations to be avoided.

**Comment by lfcnassif** [comment]
I suspected of wide/tall images a long ago, but didn't investigate, thank you!

**Comment by lfcnassif** [comment]
I saw NPE here in pdna_exception col in a course I'm providing. Will analyze when some time is available.

**Comment by lfcnassif** [comment]
@tc-wleite I managed to reproduce the NPE, I was using an old version of our photoDNA jar (1.3), I fixed it 9 months ago in 1.3.1, my bad :)

I think I will move your exception fallback code to our internal photoDNA lib, so other projects could benefit of it, what do you think?

**Comment by tc-wleite** [comment]
> I think I will move your exception fallback code to our internal photoDNA lib, so other projects could benefit of it, what do you think?
Sure!

**Comment by lfcnassif** [comment]
Fixed by commits referenced here.
