### ISSUE TITLE
Link WhatsApp attachments in Apple Warrant Returns Cellebrite Reports

### ISSUE THREAD

**Issue by fmpfeifer** [sepinf-inc/IPED#486]
There is an issue that, when processing Cellebrite Reports generated from Apple Warrant Returns, some attached files in WhatsApp messages are not being linked in IPED.
I tried to use the external parser, and then the message was linked correctly.
Tried to investigate the issue, and it looks like apple is padding some of the files with zeros at the end.

Here is one example (message item from the ChatStorage.sqlite database):
![image](https://user-images.githubusercontent.com/3900238/115561962-6c3d2600-a28c-11eb-96ad-e4e4f55099cc.png)

Important info: File size: 104199

In IPED:
![image](https://user-images.githubusercontent.com/3900238/115562064-8414aa00-a28c-11eb-9238-f9d4d27a89de.png)

File size: 104208 (9 bytes bigger!)

It is possible to see those 9 byes as zeros at the end of the file:
![image](https://user-images.githubusercontent.com/3900238/115562764-33518100-a28d-11eb-9eb1-40b3d33f57fd.png)

Also in the database, we have the hash of the file:
![image](https://user-images.githubusercontent.com/3900238/115562253-af979480-a28c-11eb-8f80-cb36c611d19e.png)

Converting it to hex (using cyberchef):
![image](https://user-images.githubusercontent.com/3900238/115562300-baeac000-a28c-11eb-99fe-13349201fb6a.png)

Comparing the hash with the hash of the truncated file (getting rid of the last 9 bytes):
![image](https://user-images.githubusercontent.com/3900238/115562390-cfc75380-a28c-11eb-9829-60e30f04e79c.png)

Match.

So if confirms that apple is really padding the end of the file.

**Comment by fmpfeifer** [comment]
Maybe we could implement some workaround: when the file is not found by hash, try to find it by filename and size (not exact size, something like size:[(actualsize) TO (actualsize+15)] )
If it is found, maybe calculate the hash of the truncated file and compare with the hash stored in database to validate.

Not sure if it is worth the effort. Maybe we should just ignore and tell the user to use the external parser.

**Comment by lfcnassif** [comment]
Maybe fallback to searching filename and approximate size and cheking if the size matches after subtracting last 0 bytes? Computing hashes of attachments of large cases could take some time...

**Comment by fmpfeifer** [comment]
May be a good compromise

**Comment by fmpfeifer** [comment]
But, I'm not sure that it is going to be a lot of files to compute hashes. Those files need to have the same name and have a size close to the file being searched for. Only then we would need to check the hash

**Comment by fmpfeifer** [comment]
The name of those files tend to have a uuid form (se my example above), so I'm convinced that the number of false positive will be really low

**Comment by lfcnassif** [comment]
@fmpfeifer we can change this to "Support Apple Warrant Returns..." and change to "enhancement" if you think it makes more sense.

**Comment by fmpfeifer** [comment]
I have a working implementation here. But I'm still not sure about how to proceed:

I implemented the following fallback:
if the media file associated with the message is not found by hash, try to search by filename and approximate size (actualsize + 1 to actualsize + 15). If found, check if the trailing bytes are all zeros.

It actually worked really well, and for the case I'm testing here it was able to link hundreds of media files.

but...

searching for filename and approximate size (or filename and checking approx size in java) takes a long time.

I changed the way that the media are searched for: instead of searching one item at a time when generating the report, search in batches in advance (see 9b6db46). With this change it became much faster, but not as fast as without the filename + app size search.

To make the test, I processed the case without the chatstorage.sqlite file.
Then, processed just the chatstorage.sqlite with the --append option, to test how fast it is to process just that file:
* before change: 177 seconds to complete
* after change: 218 seconds to complete (and lots of media file linked)
* after change, but disabling the filename + app size search: 167 seconds (same result as original, but a little bit faster because of the search in advance)

The problem here is that the case for this change is very specific: workaround a problem generated by Apple in it Warrant Returns.
Don't know it is worth the increase in processing time for something that won't benefit many users.
Or maybe that time increase is not that bad.

What do you guys think? Is it ok like that?
Should I make it an option in a config file?

**Comment by lfcnassif** [comment]
@fmpfeifer not sure if I followed. Second result (218s) was with batch attach searches and third result (167s) was with batch searches but searching just for original hashes and not finding any attachs?

I don't think second result had a big performance impact, and if it is just for Apple Warrant Returns, I think it is fine. Did you tried jvisualvm to see the true bottleneck on Sampler tab CPU button (I like sorting by the third column)?

**Comment by lfcnassif** [comment]
Anyway, a 23% increase in processing time for correct results is better than wrong results.

**Comment by fmpfeifer** [comment]
Yes, the 218s is form the batch with all searches enabled. The 167 is with the batch search, but without the fallback to filename + approx size (not finding most of attached files in my case).
Thinking about it more carefully, it doesn't seem so bad, as this 23% increase is just for one file. In a full case this won't make a big difference.

**Comment by fmpfeifer** [comment]
with that said, I'm removing the draft state from the pull request.. 
I think it's ready for review
