### ISSUE TITLE
Upgrade DIE nudity detection model to 20210505

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#502]
New model uses 50% of the memory it used before (~140 MB reduction in its memory footprint) and it is slightly faster.
There is a minor change in the code too, which came from a set of tests we ran to use this model in an Android app (in which the memory footprint is critical). 

@lfcnassif, I will send you the new model file directly.

**Comment by lfcnassif** [comment]
Thank you @tc-wleite!

**Comment by tc-wleite** [comment]
@lfcnassif, running more tests here I found out that the DIE class (included in the model file) was generating NPE in rare cases. 
I fixed it, so please update the model file once more (version is now 20210505).
I will send you the new model file directly again, and sorry for the trouble.

**Comment by lfcnassif** [comment]
No problem, I will update, thanks.
