### ISSUE TITLE
Remove "Experimental" label from Image Similarity and enable it in some profiles

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#504]
I have been using this feature since it was released, and although we plan to enhance its behavior #358, I believe even in its current state, it can be useful in some situations.

I think most users never tried to use it, or aren't even aware of it.

As it adds almost no extra processing time, the additional disk space used to store the used features is relatively small and the is no extra steps to set it up, I would like to enable it as default in "forensic" and "pedo" profiles. 
With more potential users, we can have more feedback to improve it.

@lfcnassif, this is just a minor suggestion, feel free to reject it.

**Comment by lfcnassif** [comment]
Totally agree! Actually I was +1 to remove the "Experimental" string since the first version!
