### ISSUE TITLE
External thumbnail generation fails for rare valid images

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#518]
When processing evidences, sometimes I notice many warnings in the execution log like the following:
```
[WARN]    [process.task.ImageThumbTask]    Item: b1\Mosaic.xpm type: xbm size: 2758
java.lang.RuntimeException: java.util.concurrent.ExecutionException: 
	java.lang.IndexOutOfBoundsException: off < 0 || len < 0 || off + len > b.length!
	at dpf.sp.gpinf.indexer.util.GraphicsMagicConverter.getImage(GraphicsMagicConverter.java:249) ~[iped-viewers-impl-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.ImageThumbTask.createImageThumb(ImageThumbTask.java:302) [iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.ImageThumbTask.access$000(ImageThumbTask.java:34) [iped-engine-3.18.3.jar:?]
	at dpf.sp.gpinf.indexer.process.task.ImageThumbTask$ThumbCreator.run(ImageThumbTask.java:261) [iped-engine-3.18.3.jar
```

Investigating the issue, which I initially thought to be related to corrupted images, I found out that it happens with valid images, which are handled by external image conversion (ImageMagick).

The external conversion tool works fine, but when reading the resulting BMP, with `ImageIO.read(in)`, it fails, although the BMP output from ImageMagick is fine.
It turns out that the root cause is the BMP decoding executed by a plugin from **jai-imageio-core**.
The standard Java decoder reads these files without trouble.

Checking for a newer version in https://github.com/jai-imageio/jai-imageio-core, I realized that this project is not updated anymore. 
Probably because since Java 9 the formats handled by this library are already supported by ImageIO.
In the future (when IPED is tested for Java >= 9 versions), we should check if this library is still necessary.

This also happens with 3.18.x version (and earlier).
One test file that triggers this issue:
[Mosaic.zip](https://github.com/sepinf-inc/IPED/files/6437204/Mosaic.zip)

I am testing a few options that would fix it.

**Comment by lfcnassif** [comment]
Thanks for the tests @tc-wleite!
