### ISSUE TITLE
Allow filtering property names in Metadata filter panel

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#520]
Recently a nice option was added to filter metadata **values** (#479).
Sometimes there are too many different **property names** in larger cases, like +500 in "Image" group.
In such situation, it is hard to find all possibly useful properties.

The idea would allow typing part of the desired name, and only properties that contains the specified string would be included in the list.

An example of a long list of properties:
![image](https://user-images.githubusercontent.com/7217001/117361583-9b5cb580-ae90-11eb-86f3-7b61d9c42175.png)

**Comment by tc-wleite** [comment]
> Sometimes there are too many different **property names** in larger cases, like +500 in "Image" group.

Out of curiosity, I counted **907** different properties in "Image" group (in a real case with just a single 1TB HDD).

**Comment by lfcnassif** [comment]
W00t
