### ISSUE TITLE
Simpler names for important image metadata

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#522]
After Tika update to 1.26 (#178), I noticed that one of the most useful image metadata name changed from "**image:Model**" to "**image:tiff:Model**".
In fact, I check that in previous versions both were present, with the same value.

I am aware that the general guideline is to keep metadata original names extracted by Tika.
Although this is just a minor detail, and more a matter of getting used to the new name, I propose the following mapping for this particular property (**Model**), one directly related to it (**Make**), and two others that are very important, but their current names are not very "friendly": **image:tiff:ImageWidth** (**width**) and **image:tiff:ImageLength** (**height**).

```
Current Name              Proposed Name
-----------------------   -------------
image:tiff:Model          image:Model
image:tiff:Make           image:Make
image:tiff:ImageWidth     image:Width
image:tiff:ImageLength    image:Height
```

I would prefer using uncapitalized words, but as almost all existing image properties use capitalized words (e.g. "image:White Balance", "image:Camera Serial Number", "image:F Number", "image:Source") I am proposing capitalized words.

**Comment by lfcnassif** [comment]
Agreed, image:tiff:ImageLength in VideoThumbTask could be mapped too to use the new standard.

**Comment by tc-wleite** [comment]
I found a small problem related to this issue.
In `MetadataUtil` class, the case normalization may not worked as expected with the renamed keys (introduced in this issue).

These keys are added for some images (e.g. most PNGs):
`width` (lowercase)
     
As case normalization happens before renaming, it results duplicated keys that only differ from the first letter case:
`image:width` (doesn't change when "case nomalized", as there is no `Width` at that point).
`image:Width` (renamed from `image:tiff:ImageWidth`)

There are several ways of handling this in the code.
I am submitting a possible solution, that places all "rename destinations" keys in the case control map before anything. 
The idea is to give higher priority for these explicitly defined names.
So when `width` is "case normalized" it will become `Width`.

@lfcnassif, feel free to implement another solution.
I just would like to make sure this won't be left behind.

**Comment by lfcnassif** [comment]
Thanks @tc-wleite!

**Comment by lfcnassif** [comment]
Will take a look tomorrow

**Comment by tc-wleite** [comment]
> Will take a look tomorrow

No hurry! 
I am just submitting this (and other stuff) now because we have a local holiday tomorrow, and I will take a vacation break starting next week :-)

**Comment by lfcnassif** [comment]
Have a great vacation, you deserve it!
