### ISSUE TITLE
Properties being duplicated and prefixed with underscore (master)

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#529]
Does not happen in last release.

**Comment by tc-wleite** [comment]
@lfcnassif, not sure if it is the same issue, but do you mean like these:
![image](https://user-images.githubusercontent.com/7217001/117729404-27d4e400-b1c1-11eb-922f-c1c073345056.png)

**Comment by lfcnassif** [comment]
This is caused by lucene-6.6.6 upgrade in master months ago, seems DocValues only fields now are being returned when querying all fields from index, will check the best way to fix.
