### ISSUE TITLE
Increase ALTCOINS Regexes and Validators

### ISSUE THREAD

**Issue by fmpfeifer** [sepinf-inc/IPED#530]
According to the table in [1], there are many altcoins that share the same address schema as bitcoin, just changing a few parameters.
So, implementing this generic decoding, we should be able to validate (checksum) many altcoins, making it possible to enable their corresponding regexes.

some immediate candidates are Litecoin, Dogecoin and Dash

[1] [Altcoin Version Mappings - libbitcoin-system](https://github.com/libbitcoin/libbitcoin-system/wiki/Altcoin-Version-Mappings#bip44-altcoin-version-mapping-table)

**Comment by lfcnassif** [comment]
Great!

**Comment by lfcnassif** [comment]
Closed by #531
