### ISSUE TITLE
Fix ZipBomb control map cumulative memory leak

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#539]
Affects 3.18.5 and master. While testing for 3.18.6 release, I noticed 8GB of memory not being released after GC cycles at the end of a 2 million items case processing. Analyzing the heap dump, all those memory was used by the zipBombStatsMap in ParsingTask introduced in 3.18.5. I was aware about the map not removing items (it must keep recent items), but I thought it wouldn't use too much memory...

Two users reported OOME in 3.18.5, but not in 3.18.4, unfortunately they didn't provide the heap dump to be analyzed. Possibly was caused by this.

Will fix using a limited cache.

**Comment by tc-wleite** [comment]
I noticed an unusual memory consumption in a large case (~12M items), using master branch, but didn't investigate it, as running with more memory "solved" my problem.

**Comment by gis-msouza** [comment]
> I noticed an unusual memory consumption in a large case (~12M items), using master branch, but didn't investigate it, as running with more memory "solved" my problem.

The same thing that happened to me. In my case I put around 32GB of memory and  it was possible to finish the processing.

Good to know the problem was found.

**Comment by lfcnassif** [comment]
For OOME errors, we really need the heap dump to investigate the source.

**Comment by lfcnassif** [comment]
Coincidently, more 2 users reported OOME in 3.18.5 to me after fixing this today.

**Comment by tc-wleite** [comment]
> Coincidently, more 2 users reported OOME in 3.18.5 to me after fixing this today.

There can be other sources of high memory consumption, obviously, but it is great to know this one was identified and fixed!
I will try to process the case that I mentioned again.

**Comment by lfcnassif** [comment]
Thanks @tc-wleite. Actually I was surprised it took more than 1 month for users to start reporting this, it affects all cases in general. If on going tests are ok, I will roll the 3.18.6 release.

**Comment by lfcnassif** [comment]
Hum... actually not all cases in general, looks like those with lots of containers, but the heap dump was very clear pointing to the fixed map.

**Comment by lfcnassif** [comment]
This is not fixed, it is a bit tricky, seems the map is not the problem, because just container ids/sizes are stored. I think the cause is a hidden reference in inner ZipBombStats class to the outer ParsingTask class, keeping other heavier objects around. Will make the ZipBombStats class static and check the results...

**Comment by lfcnassif** [comment]
Last commit fixed this. The non static inner class was keeping decoded text of items around.

**Comment by lfcnassif** [comment]
One of the affected users reported this fix resolved his issue.
