### ISSUE TITLE
Support new Telegram version 7.6/7.7

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#540]
Database schema has changed, @hauck-jvsh noticed the lib used by us as GPL plugin was updated recently: https://github.com/DrKLO/Telegram

**Comment by hauck-jvsh** [comment]
Pull request #541 also fixes a null pointer exception that happens when the lib used cannot decode the message date.

**Comment by lfcnassif** [comment]
Thanks @hauck-jvsh
