### ISSUE TITLE
TelegramParser contact decoding is not thread safe

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#543]
While testing #541 for possible regressions, NPE was being thrown with some databases, and they change in different runs. @hauck-jvsh found a static instance of the decoder class was being used to decode contacts.

**Comment by lfcnassif** [comment]
This happens just if multiple telegram databases are processed at the same time.

**Comment by hauck-jvsh** [comment]
Fixed by commit #165a26167171c8ea9975ef251c5d41128cff01d9

**Comment by lfcnassif** [comment]
Thanks @hauck-jvsh
