### ISSUE TITLE
Standalone WinXTimelineParser fails with an InputStream different from TikaInputStream

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#557]
This issue was introduced by #404. Actually SQLiteContainerDetector just works when given a TikaInputStream, but it does not complain if given a different one. This caused a wrong usage of SQLiteContainerDetector by WinXTimelineParser in #404.

PS: This does not affect the application, as iped detection is always done over TikaInputStreams.

**Comment by lfcnassif** [comment]
thanks @streeg for reporting this

**Comment by mbichara** [comment]
Nice catch, @lfcnassif  and @streeg !
