### ISSUE TITLE
Add file signature for TS videos

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#560]
Recently few **.TS videos** appeared here in case here.
The person working in the case reported to me that they were not detected as videos.
Researching online, I found out that it is a **MPEG transport stream file**.

It is not a common format at all, but I found a few other samples searching in other cases:
[ts.zip](https://github.com/sepinf-inc/IPED/files/6543288/ts.zip)

After adding a custom signature, thumb extraction worked fine.
The signature is just a single "G" in offset 0, but it repeats after each 188 bytes. 
I added six of them, which seems enough to avoid false detections.

@lfcnassif, please review if the way I added the custom signature is correct.

**Comment by lfcnassif** [comment]
Thanks @tc-wleite, it's fine. It is also possible to use regex in signature definitions, not sure what is fastest.
