### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#569]
Some users here, that spent many hours of the day using IPED user interface, requested an optional light-on-dark color scheme (dark mode).
These "dark modes" are kind of common nowadays, although it is not my personal preference.

@lfcnassif, I know this is not a priority, but what do you think? It is a valid enhancement?

I made a quick test, just to see how it would look like:

![image](https://user-images.githubusercontent.com/7217001/119881015-33cfde00-bf03-11eb-9b1d-0b0559fc20f2.png)

![image](https://user-images.githubusercontent.com/7217001/119881042-39c5bf00-bf03-11eb-81d4-4c1c1bc95be8.png)

I noticed that most (80~90%) of the interface would work as it is today.
There are places of the code using fixed colors that would need to be revised, but it should be something simple.

There would be a menu item to change between "themes" (initially "default" and "dark"), and this personal choice would be saved in the user local preferences.

**Comment by lfcnassif** [comment]
It's not my preference too, but if all UI works, I think it's ok to be an optional theme.

**Comment by lfcnassif** [comment]
closed by #634
