### ISSUE TITLE
Normalize again some common metadata keys

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#570]
Currently many metadata keys receive a prefix based on the file type (image: video: pdf: office: html: message:). This was done to easy the organization of metadata keys in groups.

But some common metadata used by different types (title, author, created, date, subject...) were broken in unrelated metadata (image:creator, video:creator, office:creator, pdf:creator). This avoids a search like creator:john if user wants to search for all files created by john, regardless of the file type, for example.

We could remove the prefixes of some common metadata types and move them to a "Common" metadata group. Other option is to duplicate the key: keep it original without the prefix and duplicate it adding the prefix, keeping current behavior.

**Comment by tc-wleite** [comment]
@lfcnassif, is the idea specific for a predefined set of metadata keys, or for all keys?
In general, duplicating things is not good, but if it is for a small set of properties, keeping them in the current group and creating a "common:" group would be great.
The user would have both options (to filter/group by/sort), depending on what he/she wants to do.
Only moving to the "common" group would still allow restricting to a certain "type" (combining with other filters), but wouldn't be as convenient as it is today.

**Comment by lfcnassif** [comment]
If we duplicate, just for a few common keys. I thought about removing the prefix a long ago, but delayed it until 4.0 because this breaks compatibility. The duplicate idea come today.

Just moving to a common: group maybe could make users not aware about some important keys like author or created (date) for some types.

So, let's go with duplicating a few keys.
