### ISSUE TITLE
No meaningful error message with the --continue flag if the output folder is empty

### ISSUE THREAD

**Issue by gaffinet** [sepinf-inc/IPED#581]
Hi

If you start iped.exe with the --continue flag, but the output folder is empty or doesn't exists, you get an error which isn't really meaningful:

![image](https://user-images.githubusercontent.com/9380336/120293383-7dcf1000-c2c5-11eb-8d97-c48a06997026.png)

Would it be possible to show a better error message or, in such a case, to simply ignore the --continue flag.

**Comment by lfcnassif** [comment]
Yes, we can show a better message. What other devs think about simply ignoring --continue when the case doesn't exist

**Comment by tc-wleite** [comment]
> Yes, we can show a better message. What other devs think about simply ignoring --continue when the case doesn't exist?

Although both options seem fine to me, I slightly prefer showing an explicit error message and abort.
It is possible that the `--continue` was intended, but the destination folder was wrong.
In such a case, ignoring would silently create a new case, instead of trying to continue the existing one.

**Comment by lfcnassif** [comment]
Thanks @tc-wleite I agree, will just improve the error message.
