### ISSUE TITLE
Files with 0 bytes not included in "Empty Files" category

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#582]
A user questioned me why some files with 0 bytes were not included in the "Empty Files" category.
Investigating it here, I noticed that it happens both with the latest release (3.18.6) and the master.

In `RefineCategoryTask.js` items are added to "Empty Files" category right in the beginning , but later there are other conditions that overwrite the category (using `setCategory()`) .

I believe this was not intentional, right @lfcnassif ?!
Well, I am submitting a simple fix to this, just moving the empty files check, and adding a comment  to place all rules that modify the item category using `setCategory()` first, then rules that add the item to other categories, using `addCategory()`.

**Comment by lfcnassif** [comment]
It wasn't, thanks! Not sure about other categories using "set" added by @fsicoli
