### ISSUE TITLE
Python modules loading error: jep.JepException: <class 'ModuleNotFoundError'>: No module named 'org.apache'

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#586]
See the description on https://github.com/ninia/jep/issues/323. Although it does not work with `java -jar iped.jar`, it strangely works with `iped.exe`. A different JEP ClassEnquirer implementation should fix this, debugging...

**Comment by lfcnassif** [comment]
Just posted the fix to upstream project issue. Will push the fix and rollback when we upgraded to fixed JEP.

**Comment by wiam-prog** [comment]
ewa quoi ya pas red sehma a bande chien
