### ISSUE TITLE
Inconsistent ocrCharCount

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#590]
I noticed that many images show a different number of OCR recognized characters (`ocrCharCount`) in metadata and text viewer.
The value shown in metadata is always greater (or equal) to the one show in the text viewer.

It is just a minor detail, that seems to be related to leading/trailing white space.
Trim recognized text does make sense, specially when only white space is returned by the OCR.
In such cases, metadata is now showing a value of `ocrCharCount` greater than zero, which can be confusing, as no text is visible in text viewer, and it shows `ocrCharCount: 0`.

![image](https://user-images.githubusercontent.com/7217001/120877860-2c59a600-c58f-11eb-9372-1e9320fc1cf8.png)

**Comment by lfcnassif** [comment]
Good catch!
