### ISSUE TITLE
Some apps in tools folder depend on MS DLLs not always present in processing machine

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#607]
Similar to https://github.com/sepinf-inc/IPED/issues/206#issuecomment-862435690

This was reported months ago by an user and I forgot to create this issue. MS redistributable DLLs should be distributed.

**Comment by lfcnassif** [comment]
I've found at least vcruntime140.dll missing in these tools:
- evtexport
- evtxexport
- libagdb
- sccainfo

@tc-wleite, not sure if you used "Dependencies" tool in #206, but could you confirm below api-ms-win* dlls or ucrtbase.dll are not needed? They are also found in tesseract.exe tree (I think you noticed this):
![image](https://user-images.githubusercontent.com/7276994/122936397-81dfd200-d347-11eb-93fb-9747e4b13a38.png)

I'm asking because sleuthkit MS VC++ project copies all api-ms-win* and ucrtbase.dll to the build output folder, and "Dependencies" shows a similar tree.

Finally, if you have time, could you test those 4 tools listed above in the machine you tested tesseract for missing dependencies and check if vcruntime140.dll solves the issue?

**Comment by lfcnassif** [comment]
Just a little update, although api-ms-win-crt* and ucrtbase dlls are in the same folder as tsk_loaddb.exe, below tree points to system dlls:
![image](https://user-images.githubusercontent.com/7276994/122941691-016fa000-d34c-11eb-8768-d17fdec4f726.png)
so maybe them do not need to be distributed...

**Comment by tc-wleite** [comment]
> @tc-wleite, not sure if you used "Dependencies" tool in #206, but do you know if below api-ms-win* dlls or ucrtbase.dll are not needed? They are also found in tesseract.exe tree (I think you noticed this):

Yes, tried a couple of other tools and this one you mentioned .

> I'm asking because sleuthkit MS VC++ project copies all api-ms-win* and ucrtbase.dll to the build output folder, and "Dependencies" shows a similar tree.

These indeed show as tesseract dependencies, but in the DLL properties details, they are listed as part of Windows, while the other 3 DLLs I mentioned are identified as part of MSVC redistributable runtime.
 
> Finally, if you have time, could you test those 4 tools listed above in the machine you tested tesseract for missing dependencies and check if vcruntime140.dll solves the issue?

I will try to run these tools and update here.

**Comment by lfcnassif** [comment]
@tc-wleite don't waste your time here, I found a machine where I'm able to reproduce this. I will also test new tesseract.

**Comment by lfcnassif** [comment]
tesseract-5.0.0 with dlls is ok. Including vcruntime140.dll fixes this for the tools listed above.
