### ISSUE TITLE
Typing some keys cause an undesired advance to the next item in the main table 

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#609]
This is caused by the type-to-find feature in the items table, and happens when keys like ESC, BACKSPACE, TAB and ESCAPE are typed, while sorting by a text column that contains empty values.

To reproduce, just sort by bookmark (or other column with empty values), and type one of these keys.
It will advance to the next item.

This can be an issue when one of these keys are used as a bookmark shortcut.

**Comment by lfcnassif** [comment]
Thanks @tc-wleite!
