### ISSUE TITLE
Add a metadata with the number of pages for TIFFs

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#614]
As discussed in #593, it would be useful to have the number of pages information available for TIFFs.

A new metadata named **image:tiff:NumPages** will be created, removing **image:exif:PageCount**, which is not present in most TIFFs, and sometimes contains an inconsistent value.

This will be implemented as a very simple parser, to be added to TIFF existing parsers (Tika's and OCR), using multiple parsers feature.

**Comment by lfcnassif** [comment]
closed by #593
