### ISSUE TITLE
Always use embedded JRE on Windows

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#622]
On Windows, instead of just exiting if JavaFx is not found or warning if installed java version is not tested, we could restart the application using the windows embedded JRE.

**Comment by ronaldorcosta** [comment]
It would be useful to have a mechanism to allow the application to be started preferably with the built-in java. Something like:
IPED-Search.app.exe -java built-in

This would allow a case delivered on a fast media to be self-contained.

**Comment by lfcnassif** [comment]
> It would be useful to have a mechanism to allow the application to be started preferably with the built-in java. Something like:
> IPED-Search.app.exe -java built-in

We use Launch4j to build the IPEDSearch.exe (basically calls iped-search-app.jar with a few options). It has a "fallback" option, where the embedded JRE can be used if the detected/installed JRE on the system does not respect a min/max version range. Currently just min version is specified and we can specify the max version. I don't know if Lauch4j allows to change this behavior at runtime with a command line switch like you proposed.

**Comment by lfcnassif** [comment]
PS: For others, the idea of using the installed system JRE if available and supported is because application starting is very slow if executed from some devices, such as DVD optical medias, where report cases are often delivered in. This was tested a long ago with old versions, and could be re-tested.

**Comment by lfcnassif** [comment]
> IPED-Search.app.exe -java built-in

Thinking better about this, if you could use a command line param, you can simply run `indexador\jre\bin\java.exe -jar indexador\lib\iped-search-app.jar` using a bat file, right?

**Comment by ronaldorcosta** [comment]
That's a good idea.

In this case, how would the reporting functionality inside the IPED behave,
when IPED invokes IPED itself to process the bookmarks?
IPED would invoke the built-in java or invoke the java installed on the
machine?

If IPED always invokes the same java that was used to launch it, it would
work perfectly.

**Comment by lfcnassif** [comment]
> IPED would invoke the built-in java or invoke the java installed on the machine?

Currently it calls installed java, but this could be changed to always use embedded or even behave differently depending on detected java version, because we have full control on this part of the code.

**Comment by lfcnassif** [comment]
As Java 11 has removed JavaFX and it is not too easy to be installed by users, I'll change the default behavior to always use the embedded JRE on Windows from IPED-SearchApp.exe

**Comment by lfcnassif** [comment]
While testing #1336 I noticed opening a case from a network share became slower, as expected, since now the embedded JRE is always used.

But now with the two phase bootstrap (#1119) it would be easy to implement the original idea: check if user JRE is supported and if it has JFx. If not, warn user the slower embedded JRE will be used, suggesting to install and pointing to a JRE 11 with JFx already embedded, e.g. Liberica. Thoughts?

**Comment by tc-wleite** [comment]
Using a local JRE if available/compatible would be good in this scenario. It is a bit slower using a JRE from a network (or a slow HDD) location.

**Comment by tc-wleite** [comment]
Just a side note, here JRE 11 is not available in the machines, but we can try to request its installation, if IPED uses it when opening cases.
