### ISSUE TITLE
Change TelegramParser to handle just Android databases by default when processing UFDR

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#623]
Seems iPhone telegram database parsing is still experimental, so using PhysicalAnalyzer output seems better for now, as suggested by @hauck-jvsh, right?

**Comment by hauck-jvsh** [comment]
You are right, the android version is using a plugin to decode the database, for the IOS I was not able to get find equivalent, so it was entirely developed by me and it still needs more tests.

**Comment by hauck-jvsh** [comment]
If you have databases for IOS would be great for testing and improvements.

**Comment by lfcnassif** [comment]
If I remember, we have already collected a few samples in our case database months ago and they were used for the development. We can try to crawl again.

**Comment by lfcnassif** [comment]
I created an option enabledForIOSUfdr, disabled by default, that can be overriden in ParserConfig.xml files
