### ISSUE TITLE
IPED is not starting without JEP (only in master)

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#625]
I try to run IPED and it doesn't start with an error related to JEP. The log file is attached.
[IPED-2021-06-23-18-00-38.log](https://github.com/sepinf-inc/IPED/files/6704851/IPED-2021-06-23-18-00-38.log)

**Comment by lfcnassif** [comment]
Thanks @hauck-jvsh, I will look tomorrow.

**Comment by hauck-jvsh** [comment]
I think that I manage to solve the problem with commit bd61dc1caee860484a1e77e06e24d592862064d0, please take a look on it.

**Comment by lfcnassif** [comment]
Thanks @hauck-jvsh, I just cherry picked to master.
