### ISSUE TITLE
Optimize TelegramParser html report output

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#633]
Currently the generated html report uses HTML5 \<audio\> and \<video\> tags. Unfortunately the embedded Iped HtmlViewer does not support those tags and is very slow when parsing them. This affects #49 scroll performance with Telegram chats.

The html report could simply get rid of those tags (like done by UFEDChatParser), or embed them dynamically if the detected viewer is not the iped embedded html viewer, like is currently done by WhatsAppParser.

**Comment by hauck-jvsh** [comment]
@lfcnassif  will you take a look on this, or can I start working on this?

**Comment by lfcnassif** [comment]
No, I just created the issue to register it. Feel free to work on this if you would like, thanks!

**Comment by lfcnassif** [comment]
closed by #660
