### ISSUE TITLE
Rename 'recordDate' file system date to 'metaChanged'

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#637]
This refers to last metadata change date on FS (like MFT record entry updates), or the C in MACB times (https://www.andreafortuna.org/2017/10/06/macb-times-in-windows-forensic-analysis/) altough MAC terminology is different on Windows systems (https://en.wikipedia.org/wiki/MAC_times)

Not sure how this could be translated properly to portuguese, any ideas?

**Comment by hauck-jvsh** [comment]
Why can't be "modificado"?

**Comment by lfcnassif** [comment]
> Why can't be "modificado"?

'modified' is already translated to 'modificacao'. Maybe current pt-BR translation is good enough (alteracao do registro). The reverse translation to english (recordDate) wasn't good actually.

And we can detail the difference between the dates in user manual.

**Comment by lfcnassif** [comment]
or maybe we could use metaChanged for english?

**Comment by hauck-jvsh** [comment]
I think metaChanged is closer to the what really happened.
