### ISSUE TITLE
Processing rarely aborts with MalformedInputException because of invalid unicode strings being created

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#638]
Trace:
```
2021-07-01 15:25:03     [ERROR] [gpinf.indexer.IndexFiles]                      Processing Error:
java.lang.Exception: Worker-3 Error while processing xxxxx\cache4.db.sqlite>>Telegram_Group_xxxxx?/Telegram_Group_xxxxx?_message_5967 (nullbytes)
        at dpf.sp.gpinf.indexer.process.Worker.process(Worker.java:188) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.Worker.run(Worker.java:240) ~[iped-engine-4.0.0-snapshot.jar:?]
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(Unknown Source) ~[?:1.8.0_152]
        at sun.nio.cs.StreamEncoder.implWrite(Unknown Source) ~[?:1.8.0_152]
        at sun.nio.cs.StreamEncoder.write(Unknown Source) ~[?:1.8.0_152]
        at java.io.OutputStreamWriter.write(Unknown Source) ~[?:1.8.0_152]
        at java.io.BufferedWriter.flushBuffer(Unknown Source) ~[?:1.8.0_152]
        at java.io.BufferedWriter.write(Unknown Source) ~[?:1.8.0_152]
        at java.io.Writer.write(Unknown Source) ~[?:1.8.0_152]
        at dpf.sp.gpinf.indexer.process.task.ExportCSVTask.flush(ExportCSVTask.java:198) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.ExportCSVTask.process(ExportCSVTask.java:179) ~[iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processMonitorTimeout(AbstractTask.java:252) ~[iped-engine-4.0.0-snapshot.jar:?]
```

**Comment by lfcnassif** [comment]
This is taking from me more time than I expected... I thought this line https://github.com/sepinf-inc/IPED/blob/master/iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/ExportCSVTask.java#L187 was causing problems, possibly removing 1 char of a java unicode pair and resulting in an invalid unicode string, but removing that line did't fix this...

How could error above be thrown when writing an arbitrary java string to a UTF-8 BufferedWriter? This is not related to well/malformed csv. Any idea @tc-wleite?

**Comment by lfcnassif** [comment]
or @hauck-jvsh?

**Comment by lfcnassif** [comment]
I'm still trying to clean control chars properly, not sure if they are the problem...

**Comment by tc-wleite** [comment]
I am trying to figure out here, but not idea so far...

**Comment by hauck-jvsh** [comment]
What is the input string that throws this exception? It can be printed?

**Comment by tc-wleite** [comment]
I think it possible that there are characters between **55297** and **57343** (decimal).
These would cause an exception when trying to write to a UTF-8 file.
Maybe filtering this range in the `escape()` function would help...

**Comment by hauck-jvsh** [comment]
Maybe you can use this on the escape function, as the getBytes always replaces malformed-input and unmappable-character sequences with this charset's default replacement string.
`value=new String(value.getBytes(StandardCharsets.UTF_8),StandardCharsets.UTF_8);`

**Comment by lfcnassif** [comment]
> I think it possible that there are characters between **55296** and **57343** (0xD800 to 0xDFFF).

Changing to this didn't work:
`if (c >= '\u0020' && !(c >= '\u007F' && c <= '\u009F') && !(c >= 0xD800 && c <= 0xDFFF))`

Is the idea to filter out high/low surrogates that could be without its pair?

I got this printed for now:
`"•??????????????????? ????????™"`
will try to print hex values...

**Comment by lfcnassif** [comment]
> value=new String(value.getBytes(StandardCharsets.UTF_8),StandardCharsets.UTF_8);

still didn't worked :-( this is driving me crazy, will continue tomorrow. This is being thrown while processing a 1,5GB cache4.db.sqlite Telegram database, maybe TelegramParser is creating invalid strings, concatenating invalid char sequences, not sure...

**Comment by tc-wleite** [comment]
> This is being thrown while processing a 1,5GB cache4.db.sqlite Telegram database

@lfcnassif, can you share this file (in our WebDAV)?

**Comment by hauck-jvsh** [comment]
> 
> 
> > This is being thrown while processing a 1,5GB cache4.db.sqlite Telegram database
> 
> @lfcnassif, can you share this file (in our WebDAV)?

That would be great.

**Comment by tc-wleite** [comment]
This file (it need to be unzipped to a folder, then process the folder, not the ZIP directly) caused a similar exception here:
[a.zip](https://github.com/sepinf-inc/IPED/files/6751267/a.zip)

@lfcnassif , but the fix in `escape()` you tried was enough in this case.
So there is something else in your file...

**Comment by lfcnassif** [comment]
Sorry @tc-wleite and @hauck-jvsh, both your solutions worked in ExportCSVTask, but then it throws a very similar exception/stacktrace from TextCache class (that confused me), TextCache also tries to flush text to disk using UTF-8. I **think** this is some issue with TelegramParser, this error has never happened before. I will share the 1,5GB DB. If @hauck-jvsh could take a look when some time is available, that would be great.

**Comment by lfcnassif** [comment]
Seems to be a problem with subitem names produced by TelegramParser

**Comment by hauck-jvsh** [comment]
Maybe I can place a escape function there. I don't know exactly what charset is used in telegram database, as I use the name o the user as the file name. that may be the cause.

**Comment by tc-wleite** [comment]
> I **think** this is some issue with TelegramParser, this error has never happened before.

Although it would be better to avoid these problematic names in the Telegram parser, it could happen anyway. For example, when processing a folder containing a file like the one I created.
It is definitely not common.
When processing disk images, I believe these characters are discarded/replaced by TSK. The same happens when such names are inside a ZIP (or other archives).

**Comment by lfcnassif** [comment]
@tc-wleite not sure, but maybe some cleaning should be made in FolderDataSourceReader then. Current error is thrown in ExportCSVTask and TextCache classes, but could be thrown from a future class to be implemented... but I agree current triggering classes could be protected against it. TextCache throws this because the DB is huge, so extracted text is cached to disk, I think that doesn't happen with your file (small), but I will include it in my regression dataset for sure.

**Comment by lfcnassif** [comment]
> so extracted text is cached to disk

and this just includes subitem names

**Comment by lfcnassif** [comment]
char sequence triggering this:
x0022xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80x0020xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83Dx0022x003Bx0022x0022x003Bx0022x0032x0032x0037x0039x0022x003Bx0022x0022x003Bx0022x0022x003Bx0022x0043x006Fx006Ex0074x0061x0063x0074x0073x0022x003Bx0022x0044x0033x0038x0037x0042x0031x0030x0032x0043x0039x0046x0032x0035x0030x0034x0032x0042x0043x0033x0036x0030x0033x0039x0039x0041x0045x0032x0032x0044x0032x0030x0038x0022x003Bx0022x0066x0061x006Cx0073x0065x0022x003Bx0022x0066x0061x006Cx0073x0065x0022x003Bx0022x0022x003Bx0022x0022x003Bx0022x0022x003Bx0022x006Cx0061x0070x006Cx0061x0063x0065x005Cx0063x0061x0063x0068x0065x0034x002Ex0064x0062x002Ex0073x0071x006Cx0069x0074x0065x003Ex003ExD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80x0020xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83DxDC80xD83Dx0022x003Bx0022x0030x0039x0061x0033x0034x0038x0030x0061x0039x0034x0032x0063x0062x0033x0033x0037x0038x0037x0032x0030x0039x0066x0066x0064x0063x0038x0033x0039x0063x0033x0065x0039x0022x000Dx000A

**Comment by lfcnassif** [comment]
some xD83Dx0022 invalid pairs

**Comment by lfcnassif** [comment]
Interestingly
`writer = Files.newBufferedWriter(output.toPath(), StandardOpenOption.APPEND);`
throws the exception, but
`writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(output, true), "UTF-8"));`
doesn't when writing the invalid string

**Comment by tc-wleite** [comment]
> Interestingly
> `writer = Files.newBufferedWriter(output.toPath(), StandardOpenOption.APPEND);`
> throws the exception, but
> `writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(output, true), "UTF-8"));`
> doesn't when writing the invalid string

Yeah, I noticed this same thing in my tests.
Following the source code, it seems that the second method contains a treatment for these invalid characters.

**Comment by lfcnassif** [comment]
Another user reported this with 3.18.6/3.18.7, processing an iphone ufdr and with phoneParsersToUse = all/external. So, seems invalid strings are also being created in other place(s) different than TelegramParser.

**Comment by lfcnassif** [comment]
I managed to track the source of the original problem to this line: https://github.com/sepinf-inc/IPED/blob/master/iped-parsers/iped-parsers-impl/src/main/java/org/apache/tika/fork/EmbeddedDocumentParser.java#L102

It is responsible to limit subitem names larger than 256 chars and it can break a valid surrogate pair. I really apologize @hauck-jvsh for making him wating his time.

Will push the fix shortly.

**Comment by lfcnassif** [comment]
I think it is crazy java 8 allows you to break a valid unicode string with a simple String.subString(start, end). I think it should handle this scenario or at least throw an exception if user pass invalid offsets... I don't know if later java versions changed this...
