### ISSUE TITLE
TelegramParser building invalid unicode strings in subitem names

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#640]
See #638 . Current classes triggering MalformedInputException were fixed, but it would be good to fix the issue in the source to avoid problems in future classes.

**Comment by hauck-jvsh** [comment]
After 8bd18e0833c1bb2608542a772b6c9686091fa14f it is not throwing the MalformedInputException, but it is strange, If I sanitize it against UTF-8 char-set it won't work, but if use ISO_8859_1 to escape it works. Do you have any thoughts why @lfcnassif @tc-wleite ?

**Comment by lfcnassif** [comment]
Really strange, I Will think more about it tomorrow. What do you mean by "don't work"?

**Comment by hauck-jvsh** [comment]
I mean that the MalformedInputException continues. This branch still has the issue reported in #638.

**Comment by lfcnassif** [comment]
I don't know why first commit didn't work, but last commit shouldn't be the final solution, that charset is too restrictive...

**Comment by hauck-jvsh** [comment]
Ok, I will try to manually remove the problematic chars.

**Comment by lfcnassif** [comment]
Not sure what you are thinking about, but if you are going to remove the char range pointed by @tc-wleite in https://github.com/sepinf-inc/IPED/issues/638#issuecomment-872590382 I think next char should be checked to not remove valid char pairs (high and low surrogate pairs). I think your first commit here would be a good solution, but again I don't know why it didn't work...

This is low priority because #638 was fixed, so take your time and have a great weekend!

**Comment by hauck-jvsh** [comment]
Looks like that removing Unicode surrogates solves the problem. Commit fefd44ebc6da4378c269d84fe9e3645651dae135 implements this.

**Comment by lfcnassif** [comment]
@hauck-jvsh the real source of the problem is not TelegramParser, I'm really sorry about that. I will close this and post details on #638
