### ISSUE TITLE
Localized Number Formatting

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#646]
@lfcnassif, first of all, I am not sure if this should be contained in #18, so I created a new issue to avoid mixing things up, but feel free to close as duplicated, or discard if it goes against what you are working in #18.

Since the initial internationalization (not #18, but the older one), the behavior of number formatting changed in some places.
For example, in some parsers, although the date formats were externalized and loaded depending on IPED Locale configuration, number formatting relied on the default Locale, which is always set to `Locale.forLanguageTag("en")`, right?

Of course this is not a big deal, but it may be confusing when using Locale=pt-BR.
A practical example (which was my initial motivation) is copying records from P2P evidences HTML views and pasting into MS Excel. Numbers formatted as "123,456" (in pt-BR) are misinterpreted.

I propose using localized number formats in the few places IPED currently use number formatting:

- KnownMetParser
- AresParser
- SkypeParser
- ProcessingFrame/Console
- HTML Report
- File length (in result table)
- MetadataPanel (ranges for numeric fields)

**Comment by tc-wleite** [comment]
While implementing this, I fixed two possible minor regressions related to #18 (only happen if Locale=pt-BR):

- Total length not showing in result table header.
- Length not right-aligned.

I know you are still working on #18, but as I needed the first one to test changes from this issue, I added the changes (in separated commits). 
If you already fixed this or see a better/easier way of fixing, please discard them.

**Comment by tc-wleite** [comment]
A minor comment, not directly related, in MetadataPanel, numeric ranges always show as "X **TO** Y", which is the syntax for queries (and I guess your intention was to use the same syntax), but wouldn't be clearer using a localized word (and possibly lowercase, to keep the emphasis on the numbers), as the rest of this panel is localized? 

![image](https://user-images.githubusercontent.com/7217001/124539711-5bfd0780-ddf4-11eb-8704-8b3eac1df098.png)

**Comment by lfcnassif** [comment]
Thank you, @tc-wleite! This weren't on my todo list on #18, I think we can keep this separately.

**Comment by lfcnassif** [comment]
> is always set to `Locale.forLanguageTag("en")`, right?

yes, but, actually, I don't remember the purpose of this, maybe I will have to track the reason of the change in the commit history of the old internal repo, if it is still on line...

**Comment by lfcnassif** [comment]
> "X a Y" (pt-BR)
> "X to Y" (en)

Of course, I will change to this, I think the rendered string is not used for filtering.

**Comment by tc-wleite** [comment]
> > is always set to `Locale.forLanguageTag("en")`, right?
> 
> yes, but, actually, I don't remember the purpose of this, maybe I will have to track the reason of the change in the commit history of the old internal repo, if it is still on line...

Changing that would be a solution, but I am afraid this would cause side effects (not sure where though).
That is why a went for the explicit localized format, in the places it is really desired.

**Comment by lfcnassif** [comment]
Ok I'll try to find or figure out the reason why this was added in the past, maybe that is not necessary.

**Comment by tc-wleite** [comment]
> > "X a Y" (pt-BR)
> > "X to Y" (en)
> 
> Of course, I will change to this, I think the rendered string is not used for filtering.

It is obviously trivial, but I plan to submit other very minor enhancements in MetadataPanel, so I can include this.

**Comment by lfcnassif** [comment]
> is always set to `Locale.forLanguageTag("en")`, right?

I found the commit that introduced this: f1ebe243d7cfc8849355b24ef24440daea163bea

I don't remember exactly, but I _think_ there was some issue when setting locale = en when the OS was pt-BR, or the opposite. I remember the ResourceBundle.getLocale() returning "und" (undefined), maybe the "iped-locale" sys prop was null at the first call. Maybe it was a good idea to set the java default locale to en, as it is the default application language today, to avoid mixing string/number locales with machines from other regions, not sure...

But the initialization changed a lot since then and we can try to remove that static `Locale.setDefault(Locale.forLanguageTag("en"));`

My OS is english, are yours pt-BR? We would need to test this change on both systems at least. Do you think it is worth?

**Comment by lfcnassif** [comment]
> Maybe it was a good idea to set the java default locale to en, as it is the default application language today, to avoid mixing string/number locales on machines from other regions, not sure...

I'm not sure about this. If you think this isn't a problem, we can try to remove that static locale setting from LocaleConfig

**Comment by tc-wleite** [comment]
> Maybe it was a good idea to set the java default locale to en, as it is the default application language today, to avoid mixing string/number locales with machines from other regions, not sure...

Ok, it makes sense.

> But the initialization changed a lot since then and we can try to remove that static `Locale.setDefault(Locale.forLanguageTag("en"));`
> 
> My OS is english, are yours pt-BR? We would need to test this change on both systems at least. Do you think it is worth?

Mine is pt-BR.
Sure, we can give a try.
Is it possible that number formatting affect Lucene queries?

**Comment by lfcnassif** [comment]
> Is it possible that number formatting affect Lucene queries?

Not sure, for integers no, maybe floating point values...

**Comment by tc-wleite** [comment]
Anyway, I will run some tests here to identify potential issues, so we can decide the way to go.

**Comment by lfcnassif** [comment]
ok let me know if you want me to test something here or when you think #647 is ready

**Comment by tc-wleite** [comment]
I run a test setting the default Locale to pt-BR. 
Everything seems to work fine (during processing and later using the analysis tool).

I found minor changes (some of them were expected), related to floating point values (as you predicted).

For queries you need to use localized decimal separators, which would change the current behavior, but I think it is acceptable.

One issue that I found was a mix for metadata values, some using the localized decimal separator and others (most of them) using the standard decimal point. 
Sorting the columns with localized floating point values (in results table and metadata panel) doesn't work as expected (values treated as strings, not numbers).
This seems to be caused because some libraries (or even "internal" code) use DecimalFormat and others just output the raw double (which won't be localized).

It isn't a major issue, and certainly could be fixed, but it is possible that other (more serious) issues happen, as it was just a single test.

So I would keep the current behavior (always set Locale default to "en" and use localized number formatting explicitly, only in desired places) as it would be more predictable, avoiding possible issues (specially in external libraries).
The static methods added in e3dd67a to use the "IPED localized" number format should be straightforward to use, when desired.

**Comment by lfcnassif** [comment]
Thanks @tc-wleite!

> Sorting the columns with localized floating point values (in results table and metadata panel) doesn't work as expected (values treated as strings, not numbers).

Is this happening on master? If yes, I can take a look.

**Comment by tc-wleite** [comment]
> Thanks @tc-wleite!
> 
> > Sorting the columns with localized floating point values (in results table and metadata panel) doesn't work as expected (values treated as strings, not numbers).
> 
> Is this happening on master? If yes, I can take a look.

Just in the test in which I set (hard coded) the default locale to "pt-BR" (using a local branch created from master).
As I said, it should be possible to fix this, but I would keep the current setup. 
A potential gain would be having the numbers formatted according the used locale, but many libraries don't use a number formatter.
And there can be other issues that I didn't notice...

**Comment by tc-wleite** [comment]
Just to be clear, a deeper revision of float pointing metadata (and possibly other parts) can be done if you think it is relevant.
My previous comments were thinking about the effort vs the benefits (and other priorities).
