### ISSUE TITLE
Merge and fix dynamic metadata types divergences in multicases

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#661]
It is possible that unknown metadata have different detected types in different cases. They should be checked and String could be used if they differ. This can affect sorting and range searching

**Comment by lfcnassif** [comment]
So, this was a silent issue in 3.18.x and in 4.0, Lucene 9 has field consistency checks and opening a multicase now may throw:
```
2022-08-12 12:07:22	[INFO]	[engine.data.IPEDMultiSource]			Opening MultiReader...
java.lang.IllegalArgumentException: cannot change field "audio:xmpDM:discNumber" from index options=NONE to inconsistent index options=DOCS_AND_FREQS_AND_POSITIONS
	at org.apache.lucene.index.FieldInfo.verifySameIndexOptions(FieldInfo.java:254)
	at org.apache.lucene.index.FieldInfo.verifySameSchema(FieldInfo.java:215)
	at org.apache.lucene.index.FieldInfos$Builder.add(FieldInfos.java:692)
	at org.apache.lucene.index.FieldInfos$Builder.add(FieldInfos.java:664)
	at org.apache.lucene.index.FieldInfos.getMergedFieldInfos(FieldInfos.java:210)
	at iped.engine.lucene.SlowCompositeReaderWrapper.<init>(SlowCompositeReaderWrapper.java:122)
	at iped.engine.lucene.SlowCompositeReaderWrapper.wrap(SlowCompositeReaderWrapper.java:97)
	at iped.engine.data.IPEDMultiSource.openIndex(IPEDMultiSource.java:178)
	at iped.engine.data.IPEDMultiSource.init(IPEDMultiSource.java:129)
	at iped.engine.data.IPEDMultiSource.<init>(IPEDMultiSource.java:79)
```

**Comment by hauck-jvsh** [comment]
@lfcnassif , I have a suggestion, you could add a sub field for each type. So audio:xmpDM:discNumber will become audio:xmpDM:discNumber.number. This should be enough, as if different data types are found they would be mapped to different fields. Queries can be executed against audio:xmpDM:discNumber.* if they are a matching query, or against  audio:xmpDM:discNumber.number if they are a range query. Of course this will increase the complexity a little, so if you have other idea would be better.

**Comment by lfcnassif** [comment]
Explaining in detail, a new unknown property X in case A can be dynamically detected as Double but in case B can be dynamicaly detected as String. When opening multicase A+B, exception above could be thrown.

I see some possible solutions:
1. Today, when processing a case, if the values of an unknown property X are detected initially as number, they are indexed as Double. Later, if some String value comes in field X in a different item, we create a new property X:string to index that inconsistent value. We could invert the suffix logic, and index firstly as X:double (or X:date) and fallback to X if some string value comes later while indexing. This should avoid type conflicts when opening multicases
2. We could use a similar strategy used by 3.x versions, indexing both X:string AND X:double (or X:date) under the hood (user would see just X) for a new unknown property and use the X:double field if all values in all items are detected as double or X:string if some value is a string between all indexed doubles. But this uses a bit more index space for unknown fields (indexed twice as double and string) and if a corrupted document inserts a corrupted string value in the new X:double field, that would break sorting and range searches on X field because a corrupted value was found. This would not happen with approach (1) above because it creates 2 separate fields if different types are detected (current behavior).
3. Simply ignore string values that come in fields dynamically detected as Double or Date. But the dynamic detection could be wrong if the first value used for detection was the corrupted one or if simply if a Date or Double comes in a String field (pretty common), so we would loose the correct String values.

I'm in doubt of approaches (1) and (2). Both should be backwards incompatible with 4.0.

@tc-wleite, @hauck-jvsh, @patrickdalla, @fmpfeifer any opinions or suggestions? If you also have a better idea, please let me know.

**Comment by lfcnassif** [comment]
> @lfcnassif , I have a suggestion, you could add a sub field for each type. So audio:xmpDM:discNumber will become audio:xmpDM:discNumber.number. This should be enough, as if different data types are found they would be mapped to different fields. Queries can be executed against audio:xmpDM:discNumber.* if they are a matching query, or against audio:xmpDM:discNumber.number if they are a range query. Of course this will increase the complexity a little, so if you have other idea would be better.

hehehe thanks, I was writing the longer text above. If you think approach (2) may be better, please let me know.

**Comment by hauck-jvsh** [comment]
I think that both approaches are equivalents. Just one think, in both approaches a treatment for the searches must be done, because if a corrupted date is inserted in a date field it will create the string mapping and if it searches on this field by default it will lose a lot of values.

**Comment by lfcnassif** [comment]
Maybe a quick and dirty fix could be implemented in 4.0.x simply ignoring the conflicting fields, and the proper fix in 4.1

**Comment by lfcnassif** [comment]
I'll go with the simpler approach (1), also suggest by @hauck-jvsh. User may see 2 columns with different suffixes, but that wouldn't loose any value.

**Comment by lfcnassif** [comment]
After the fix:
![image](https://user-images.githubusercontent.com/7276994/184747199-87af9228-33b2-4503-add8-4a55e909ac81.png)

One last question: now, in situation above, when a string value comes in a new unknown field previously detected as number or date, the field type is updated to string and all future values in documents to be processed are put in the string column (without suffix). Should future values continue to pass through the auto-detection code and distributed between all those 3 columns instead? This could be good to protect against corrupted values detected as string, but could be bad since an actual string field could have its values distributed between 3 columns...

**Comment by lfcnassif** [comment]
Side note: for built-in fields with types fixed as number or date, a corrupted value was already put in a `property:string` field.

**Comment by hauck-jvsh** [comment]
Maybe after a string value is added all values can be indexed as string and the detected type.

**Comment by lfcnassif** [comment]
> Maybe after a string value is added all values can be indexed as string and the detected type.

Or maybe always indexing unknown fields as string (like approach 2) and the detected value type? This would use a little bit more index space like (2), but the difference to (2) would be to expose to user all those columns, so (s)he could use the desired column to do string, date, number exact or range searches or proper sorting.

**Comment by lfcnassif** [comment]
> This would use a little bit more index space like

Probably not that much, because this would apply just to unknown fields.

**Comment by lfcnassif** [comment]
> Or maybe always indexing unknown fields as string (like approach 2) and the detected value type? This would use a little bit more index space like (2), but the difference to (2) would be to expose to user all those columns, so (s)he could use the desired column to do string, date, number exact or range searches or sorting property.

Reopening to change the approach to this.
