### ISSUE TITLE
missing extention

### ISSUE THREAD

**Issue by paulobreim** [sepinf-inc/IPED#665]
I selected some emails to export.
When using the export selected items option, the messages are exported one by one with the .eml extension correctly.
If I use the option to export to ZIP and ZIP tree, the messages are exported to ZIP without the .eml extension.

**Comment by lfcnassif** [comment]
What is the original extension of the files? Export to ZIP feature was designed to preserve original information, like extension, to be used at crime scenes.

**Comment by paulobreim** [comment]
The test that I did is a .thundebird folder with a lot of e-mails.

After this, I selected all e-mails from one person to another person to analise in details.
Than I use the option to export all using zip in order to import to another thunderbird and analise.

i thought the zip option was just to generate a single file, but i agree with you keeping the original is more convenient.

**Comment by tc-wleite** [comment]
Adding my two cents... 
Indeed preserving original extensions makes more sense when exporting to a ZIP. 
However, it is possible that in particular situations other behavior is desired (e.g. adding extensions).
The main idea behind #104 is to show a dialog with the default options, allowing the user to select different ones. 
It would be useful in cases like the one described in this issue.
