### ISSUE TITLE
Recover deleted records from SQLite databases

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#667]
This is an old desired feature. I will push an old "study" branch (not even a draft or prototype) about sqlite structures.

**Comment by lfcnassif** [comment]
just pushed the sqlite_record_undelete study branch

**Comment by lfcnassif** [comment]
Some references I used:
- https://www.sqlite.org/fileformat.html
- https://www.sciencedirect.com/science/article/pii/S1742287619301677
Other references:
- https://github.com/inflex/undark
- https://github.com/aramosf/recoversqlite (with more references)

**Comment by lfcnassif** [comment]
> * https://www.researchgate.net/publication/226423207_A_recovery_method_of_deleted_record_for_SQLite_database

this article has an important and easy picture about what goes on with a deleted row:
![image](https://user-images.githubusercontent.com/7276994/125840341-0ac8856e-775b-439d-b3a8-9a97887dc4d7.png)

I think the record type header (with unknown size...) could be checked against the existing tables schemas possibly to guess to which table a recovered record belongs.

**Comment by lfcnassif** [comment]
And just to document here too, my old idea was to insert the recovered records into the same database, after some ALTER TABLE table_name ADD 'deleted_col', so parsers would need small changes to know if a record was deleted or not.

**Comment by lfcnassif** [comment]
Good article: https://conceptechint.net/index.php/CFATI/article/view/17/6
And its GNU GPLv3 tool: https://www.staff.hs-mittweida.de/~pawlaszc/fqlite/

**Comment by lfcnassif** [comment]
> And just to document here too, my old idea was to insert the recovered records into the same database, after some ALTER TABLE table_name ADD 'deleted_col', so parsers would need small changes to know if a record was deleted or not.

This could make integration of third party parsers (like aLeap/iLeap) harder, because they won't know the changed schema...

**Comment by lfcnassif** [comment]
I've contacted the author of FQlite tool asking for a possible integration. The paper states it is dual licensed under GNU GPL v2 and Mozilla Public license v2, which seems compatible to this project.

**Comment by lfcnassif** [comment]
The author answered my email and sent the link to https://github.com/pawlaszczyk/fqlite
The source is in master branch. I've just replied to double check MPL v2 is also used.

**Comment by lfcnassif** [comment]
> The author kindly answered to my email and sent the link to https://github.com/pawlaszczyk/fqlite
> The source is in master branch. I've just replied to double check MPL v2 is also used.

Professor Pawlaszczyk kindly said he will update the license terms to make MPL v2 license more clear.

**Comment by lfcnassif** [comment]
> Professor Pawlaszczyk kindly said he will update the license terms to make MPL v2 license more clear.

I forgot to say it was updated.

**Comment by lfcnassif** [comment]
> does a very good job recovering deleted records from the database

Not sure if you have already done, but I think it is a good idea to test with real world databases. The published results with synthetic data are awesome, but I wonder if it performs well with real world data, maybe it can help us decide the path...

If it goes well, forking is an option, although it will make fqlite updates difficult... But possibly it will need less effort than writing this feature from scratch, what do you think?

And we can send a pull request to original project too, maybe this is the better approach, although will need additional work...

**Comment by hauck-jvsh** [comment]
As @lfcnassif has already contact Professor Pawlaszczyk and he Changes the license of the project, the author may accept a pull request with the changes needed to write it as a lib.

**Comment by fmpfeifer** [comment]
> 
> 
> > does a very good job recovering deleted records from the database
> 
> Not sure if you have already done, but I think it is a good idea to test with real world databases. The published results with synthetic data are awesome, but I wonder if it performs well with real world data, maybe it can help us decide the path...

I did a few tests with some msgstore.sqlite I have, and it seems to do the job. But more test are needed, indeed
> 
> If it goes well, forking is an option, although it will make fqlite updates difficult... But possibly it will need less effort than writing this feature from scratch <edit> or from my brainstorming branch rs </edit>, what do you think?

Indeed, it would be much easier to have something working to start with
> 
> And we can send a pull request to original project too, maybe this is the better approach, although will need additional work...

Good, I will skim through the options and, if it is the case, make the fork.
Thanks

**Comment by fmpfeifer** [comment]
> 
> 
> As @lfcnassif has already contacted Professor Pawlaszczyk and he changed the license of the project, the author may accept a pull request with the changes needed to write it as a lib.

Yes, that is what I had in mind

**Comment by lfcnassif** [comment]
More different implementations, **if we decide IN THE FUTURE**, to compare current results of libfqlite with others:
- https://github.com/Defense-Cyber-Crime-Center/sqlite-dissect (discovered by @mpolastro today)
- https://github.com/bring2lite/bring2lite (I thought I've pointed it out in the past)

**Comment by lfcnassif** [comment]
I'll close this since the basic structure and classes were implemented in #1065. We can open other issues for other specific sqlite databases.
