### ISSUE TITLE
Korean chars rendered as squares in TextViewer

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#685]
Triggering files attached:
[LIVE-Seoul-ntfs-utf-16-be.txt](https://github.com/sepinf-inc/IPED/files/6946763/LIVE-Seoul-ntfs-utf-16-be.txt)
[LIVE-Seoul-ntfs-utf-16-le.txt](https://github.com/sepinf-inc/IPED/files/6946764/LIVE-Seoul-ntfs-utf-16-le.txt)
[LIVE-Seoul-ntfs-utf-8.txt](https://github.com/sepinf-inc/IPED/files/6946765/LIVE-Seoul-ntfs-utf-8.txt)
[Korean lessons_ Lesson 2 – Learnkorean.com.pdf](https://github.com/sepinf-inc/IPED/files/6946772/Korean.lessons_.Lesson.2.Learnkorean.com.pdf)

**Comment by lfcnassif** [comment]
Upstream issue: https://issues.apache.org/jira/browse/TIKA-3515

**Comment by lfcnassif** [comment]
But just pasting 서울 into the search bar doesn't work.

**Comment by lfcnassif** [comment]
> Upstream issue: https://issues.apache.org/jira/browse/TIKA-3515

This is not a Tika issue.

Seems to be some font rendering problem, at least on Windows. Searches work (it finds the right files and highlights the "right squares"). Copying the squares from TextViewer and pasting to notepad or other Windows text input works (glyphs are rendered fine), this makes me think it is not a Windows Font package missing.

I tried all java logical fonts (Dialog, Serif, SansSerif, Monospaced, DialogInput) and also "Arial Unicode MS" (suggested in 
https://github.com/JabRef/jabref/issues/2503#issuecomment-276595283), none worked.

Also tried Oracle, Liberica and Amazon Correto JDKs 8. Finally tried nimbus, default and native look and feel. Nothing worked.

If anyone has some idea to fix this, I'm glad to hear.

**Comment by tc-wleite** [comment]
I think I found something here...
I will test and update later.

**Comment by lfcnassif** [comment]
> Arial Unicode MS

This seems to be not distributed anymore by Windows 10. This seems related: https://bugs.openjdk.java.net/browse/JDK-8190907

**Comment by tc-wleite** [comment]
> This seems related: https://bugs.openjdk.java.net/browse/JDK-8190907

I also think it is related to this issue.


In Windows 10, I found a simple "workaround" (or solution?), that is installing the Korean language pack.
This solved the problem, except in the text viewer.
Some characters were still missing there.
I found that is necessary to change the font from "Courier New" to Font.MONOSPACED in ATextViewer :

```
public abstract class ATextViewer extends Viewer implements KeyListener {
    public static Font font = new Font(Font.MONOSPACED, Font.PLAIN, 11); // Use monospaced here
```

**Comment by tc-wleite** [comment]
Additional test files: [Korean.zip](https://github.com/sepinf-inc/IPED/files/6964996/Korean.zip)

**Comment by lfcnassif** [comment]
Thanks @tc-wleite!

> change the font from "Courier New" to Font.MONOSPACED in ATextViewer

I tried this, but without the language pack...

Do you know if there is an easy way to check if the language pack is installed? So we could display some warning to user about that.

**Comment by lfcnassif** [comment]
So I will just fix ATextViewer and let the language pack installation to the user, thank you @tc-wleite!
