### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by MariasStory** [sepinf-inc/IPED#692]
Hi team,
It would be nice to have a usable web interface.
I know that there is a web API: https://github.com/sepinf-inc/IPED/wiki/Web-API
Is someone developing the interface?

**Comment by lfcnassif** [comment]
Yes, @hauck-jvsh is developing, but it is an internal project and I don't know if it will be open source some day. Maybe @mpolastro could have some opinion about this?

**Comment by lfcnassif** [comment]
For now we have in this open source project modules to index to an ElasticSearch cluster and export files/artifacts to a MinIO cluster, and the internal Web interface would access them. Eventually the current Java interface could be adapted to access those clusters, but this would be an overlap between projects and our human resources are very limited unfortunately.

**Comment by lfcnassif** [comment]
I'm closing this, because it is being implemented in an internal closed source project, to not duplicate efforts. I don't know if it will be open sourced some day. If someone from the community would like to contribute with this, please reopen.
