### ISSUE TITLE
Map previous/next buttons first click after sorting change are considering previous sorting order

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#697]
This is a minor issue discovered in #680, happens just after changing table sorting column and just on first button click, subsequent clicks work as expected.

**Comment by lfcnassif** [comment]
@patrickdalla did you have a chance to look at this?

**Comment by patrickdalla** [comment]
I've just finished the implementation of the bug correction on MapNavigationBug branch. See there and make the final tests.

**Comment by lfcnassif** [comment]
@patrickdalla I assigned this to you, so others will know you are working on this (thanks!) to avoid duplicate efforts

**Comment by patrickdalla** [comment]
I have already implemented this correction on MapNavigationBugCorrection2. Should I create a PR?

**Comment by lfcnassif** [comment]
Yes, please!

**Comment by lfcnassif** [comment]
Fixed by #1333
