### ISSUE TITLE
[Question] Is LED 1.29 incompatible to IPED?

### ISSUE THREAD

**Issue by thalespr** [sepinf-inc/IPED#704]
Not sure if it was dealed in another issue, but I want to know if the latest version of LED (1.29) is incompatible to IPED? Tried to run some processing using it, but got some errors. If it is, I would like to ask to gently leave an issue about that opened (if there isn't one already...) in order to keep track on this and other people be aware of that.

**Comment by tc-wleite** [comment]
In fact it is intentionally incompatible, so I guess it is not a issue.
It is explicitly stated on LED's "LEIAME.txt" notes of 1.29.00 release, LED internal WIKI (versions section) and I warned about that in the e-mail in which LED 1.29 release was announced, but I know people usually don't read any of these :-)

The new IPED version (4.x) won't be compatible as it was before (pointing to LED's folder), but I will release a CSV file with LED's database to be used with IPED.

That being said, I am fine with keeping this issue open until IPED 4.x is released, but I am not sure how helpful it would be.
Not sure, but maybe moving to discussion would make more sense.

**Comment by thalespr** [comment]
> In fact it is intentionally incompatible, so I guess it is not a issue.
> It is explicitly stated on LED's "LEIAME.txt" notes of 1.29.00 release, LED internal WIKI (versions section) and I warned about that in the e-mail in which LED 1.29 release was announced, but I know people usually don't read any of these :-)
> 
> The new IPED version (4.x) won't be compatible as it was before (pointing to LED's folder), but I will release a CSV file with LED's database to be used with IPED.
> 
> That being said, I am fine with keeping this issue open until IPED 4.x is released, but I am not sure how helpful it would be.
> Not sure, but maybe moving to discussion would make more sense.

 I honestly don't remember reading email about that (If I did, I couldn't recall that). So I spent some time to discover that it wasn't compatible to IPED on purpose (shame on me I didn't look up for LED Releases Notes, my bad for sure). At first sight, looking IPED output, I thought it could be a bug. Maybe other people can think the same, that's why I suggested to keep an issue opened.

You said that IPED 4.x won't be compatible? Is there a plan to make it compatible?

Sharing CSV file along LED database will be appreciate since IPED is able to import it AFAIK.

**Comment by tc-wleite** [comment]
> You said that IPED 4.x won't be compatible? Is there a plan to make it compatible?

The current compatibility is convenient in the sense that users of both tools can just point to LED's database when setting IPED.
But there are a  few drawbacks: 
- I can't change LED's format, which I sometimes need/want to do, without changing IPED.
- There are information used by LED that are useless to IPED, so IPED needs to read a larger file.
- The opposite also happens (e.g. PhotoDNA of LED database files can be used in IPED, but not in LED). 

The idea for the new IPED version is to have a simpler and unique way to handle all hash sets (LED, NSRL, ProjectVIC, PhotoDNA, and possibly user custom hash sets).
So LED database will be just another hash database, in a standard CSV format.
Whenever I update LED database, I will also release (in our internal server) a LED CSV (and a SQLite with "everything" already imported).
In the future, there will be a centralized CSAM database, and probably a CSV release from time to time.

By the way, I plan to release LED 1.29.01 this week.
I will try to highlight this limitation, as I totally agree it is confusing, while IPED 4.x is not released.

**Comment by lfcnassif** [comment]
@thalespr see #118 for the new centralized hash database details. I agree and will move this to discussions. As IPED-3.18.8 is around, I will add a warning to state that LED >= 1.29 format is not compatible anymore.
