### ISSUE TITLE
Print Shareaza albums entries in a new column instead of new rows

### ISSUE THREAD

**Issue by hugohmk** [sepinf-inc/IPED#708]
childPornHashHits counter is being incremented multiple times for a single file index/hash (once for the Library Folder and then once for each time it is listed in an Album Folder). Tested on v. 3.18.8.

**Comment by lfcnassif** [comment]
I tested with some samples here, childPornHashHits is in sync with the entries printed in table. Looking at the code, seems to me the file could be printed multiple times for each album reference. @fmpfeifer was that intentional?

**Comment by fmpfeifer** [comment]
The same file can be in many different albums. Are they showing um multiple times in the same album folder?

Regarding the childpornhashhits, we are incrementing each time it shows in table (if the same file is in multiple albums, it is counting each reference). Should it count only once per hash?

**Comment by lfcnassif** [comment]
IMHO, I think the report should reflect the number of sharings. If the file is in multiple albums, was it shared multiple times?

**Comment by fmpfeifer** [comment]
Not really. It's just how the user organized his files.

I can change to count only once per file.

But... Shareaza maintains two copies of the data (Library1.dat and Library2.dat).The same file can be in both (and usually will). Those files are parsed independently, so it will be counted twice.
Is it ok?

**Comment by lfcnassif** [comment]
> Is it ok?

I think it's fine, the examiner should know one is a backup of the other.

But about the report table, wouldn't it be better to create a new column "Album(s)" instead of listing the files again? And files in some album but not in the library could simply result in an empty "Path" cell, what do you think?

**Comment by fmpfeifer** [comment]
> But about the report table, wouldn't it be better to create a new column "Album(s)" instead of listing the files again? And files in some album but not in the library could simply result in an empty "Path" cell, what do you think?

I think it is a good idea, this way the file will only show once in the table, and all information will still be there.

May I implement this way?

**Comment by lfcnassif** [comment]
> May I implement this way?

Yes, please, thank you!

**Comment by lfcnassif** [comment]
I put the bug label because I think current approach is misleading to the user, possibly resulting in wrong conclusions about the number of downloaded/shared files. @fmpfeifer feel free to change it, I understood the current way was intentional.

**Comment by fmpfeifer** [comment]
I'm finishing the implementation here, but I'm not sure what is the best way to display multiple albums in the same column.

I tried to use a html unordered list:
```html
<ul>
  <li>album1</li>
  <li>album2</li>
  ...
</ul>
```
this was the result:
![image](https://user-images.githubusercontent.com/3900238/130154502-76289441-348e-421f-b2b0-5556e17581b7.png)

any ideas?

**Comment by fmpfeifer** [comment]
this way makes it impossible to sort the table if the data is copied and pasted in excel:
![image](https://user-images.githubusercontent.com/3900238/130154985-f055e5d9-dc26-46ad-acb8-d3534890c50f.png)

**Comment by lfcnassif** [comment]
Does the sorting issue happen just when sorting by Albums? (maybe that is not a big problem)
\<p\> or \<div\> or simply \<br\> works?

**Comment by fmpfeifer** [comment]
no, the sorting doesn't work, regardless of which column is used for sorting.

didn't try with `<p>`, `<div>` or `<br>`

The issue I see is that normally the album name is big, and the words may wrap to the next line, potentially leading to confusion if there is no visual hint (is it a different album or just a continuation of the previous one?)

Will try those and post here the results.

**Comment by lfcnassif** [comment]
> The issue I see is that normally the album name is big, and the words may wrap to the next line, potentially leading to confusion if there is no visual hint

got it, no need to post.

**Comment by lfcnassif** [comment]
maybe \<hr\> as separator?

**Comment by fmpfeifer** [comment]
Tried a few options here..
`<div>`, `<br>` and `<p>` gave very similar results, like this:
![image](https://user-images.githubusercontent.com/3900238/130164774-84ffb3eb-08c9-42d8-972f-7736e8a0d205.png)

`<hr>` like this:
![image](https://user-images.githubusercontent.com/3900238/130164816-d483fa8e-603f-47c1-b877-3dc33fafedb9.png)

All the above didn't work well with excel sorting. The `<hr>` option resulted in a very slow copy and paste operation. Took a few minutes to generate the spreadsheet.

I also tried not to use html tags inside the cell, using just a pipe (" | ") as separator. This was the result:
![image](https://user-images.githubusercontent.com/3900238/130164979-f2f60757-0369-4c72-b8a2-1de305dacf16.png)

the last one resulted in a sortable spreadsheet.

It is not pretty, but I think it makes more sense here.

What do you think?

**Comment by lfcnassif** [comment]
The last one seems better to me, sorting is important.
