### ISSUE TITLE
Rename DIE properties

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#713]
Currently properties generated by fast nudity detection algorithm (DIE) are named "scoreNudez" and "classeNudez" (in Portuguese).
@lfcnassif, wouldn't it make more sense to use them in English (as done for other properties in version 4.x), and create aliases in Portuguese (as done for basic properties, like name and path)?
I am considering changing "scoreNudez" to "nudityScore" and "classeNudez" to "nudityClass".

**Comment by lfcnassif** [comment]
I've already noticed that, totally makes sense.
