### ISSUE TITLE
Avoid conflict between bookmark shortcuts and navigation/assigned keys

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#722]
A minor usability enhancement: 
when the focus is in bookmark list (in the bookmark manager window), it is possible to assign keys that will conflict with the navigation in the list itself, items list or items gallery.
These keys include: 
- HOME, END, PAGE UP, PAGE DOWN, ARROWS (4 directions).
- Already used combinations: CTRL+A (select all), CTRL+B (open bookmarks manager window) and CTRL+C (copy selected cell content).

Although the user can just avoid using these keys as bookmarks shortcuts, it is better to prevent its usage, as it can lead to strange behaviors.
CTRL+A can be useful in the bookmark list (to select all bookmarks for exclusion or removal of items), but currently it is not possible to use it for selection, as it would try to also assign this combination. 

I propose to ignore these keys when assigning bookmarks shortcuts, so they will be handled in the standard way.

**Comment by lfcnassif** [comment]
Thanks @tc-wleite. What about also including SPACE?

**Comment by tc-wleite** [comment]
> Thanks @tc-wleite. What about also including SPACE?

Definitely! I will include it.
I noticed now that I also forgot about CTRL+R (recursive selection) and R (alone, as ALT+R is used for removing selection recursively).
