### ISSUE TITLE
Save bookmarks shortcuts

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#724]
Another minor enhancement proposal.
Once I started working with shortcut keys for bookmarks I found it very useful.
In some cases, using keys for several bookmarks, I found a bit inconvenient that assigned keys are lost when the case is closed.
I usually try to keep the cases opened to avoid losing assigned keys, but I believe that it would be better if they were saved, so when the case is reopened, they are still there.

I guess bookmark shortcuts are currently not saved just for simplicity, or is there any inconvenient or concern related to this @lfcnassif?

One detail, when a report is generated, I think it is reasonable to clear all assigned keys (current behavior).

**Comment by lfcnassif** [comment]
No concern! Just not implemented nor imagined.
