### ISSUE TITLE
Optimize MinIOTask

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#732]
MinIO task should group small files in a tar and send them in a single request.
References
https://blog.min.io/minio-optimizes-small-objects
https://docs.aws.amazon.com/snowball/latest/developer-guide/batching-small-files.html

**Comment by hauck-jvsh** [comment]
I found a bug that was resending items that were already in the bucket, after fixing it I ran some tests and the results were:
458s (65%) for the minIO task without tar packing and 377s (54%) for the minIO task with the tar pack. Do you think I should proceed or the gain is not worth the effort? @lfcnassif @tc-wleite

**Comment by lfcnassif** [comment]
Maybe we can just fix the check for existing file hashes on minio server for now and leave the tar feature in another branch as a future improvement?

**Comment by lfcnassif** [comment]
closed by #743

**Comment by hauck-jvsh** [comment]
In the last version of the MinIO they add support to download individual files inside zip files, this can used to minimize the number of small files save in the bucket.

**Comment by lfcnassif** [comment]
Thank you @hauck-jvsh!

**Comment by lfcnassif** [comment]
Closed by #1000
