### ISSUE TITLE
Imagemagick 6.x version does not work with IPED on Linux

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#740]
IPED version: 4.0.0-snapshot (3231e9463)
OS: Ubuntu 22.04

I'm using the latest version of Ubuntu (21.04) and it comes with `ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25`, which does not have the `magick` command.
The version 7.x of ImageMagick (compatible with IPED) uses `magick` as a wrapper of common ImageMagick sub-commands  like `convert`, `identify`, while the version 6.x uses these sub-commands as commands directly.

The impact of this is that some image formats like EXR, HEIC, RGB, SGI,WEBP, XBM and AVIF are not being thumbed.

It also affects ~~3.18.x~~ 3.18.7 version.

A workaround in linux was to make symbolic link using `ln -s /usr/bin/convert /usr/bin/magick` (but it is not safe!)

I will post a fix I think can be interesting.

**Comment by aberenguel** [comment]
Forgot to commit the property in txt file. Tomorrow I'll push it.

**Comment by lfcnassif** [comment]
Are you sure this affects latest 3.18.8? Checking the 3.18.x branch, there is a function to adjust the command line automatically: https://github.com/sepinf-inc/IPED/blob/3.18.x/iped-viewers/iped-viewers-impl/src/main/java/dpf/sp/gpinf/indexer/util/GraphicsMagicConverter.java#L141

I think it was removed accidentally by 5d3bd01d007f1ad1e1bf0c19e80de411b75bfcee just on master branch in #593

**Comment by lfcnassif** [comment]
I also propose an automatic cmd line detection like done before to fix this.

**Comment by aberenguel** [comment]
Sorry. I'm sure it affects 3.18.7. I didn't test with 3.18.8

**Comment by tc-wleite** [comment]
> Thanks @aberenguel. Are you sure this affects latest 3.18.8? Checking the 3.18.x branch, there is a function to adjust the command line automatically: https://github.com/sepinf-inc/IPED/blob/3.18.x/iped-viewers/iped-viewers-impl/src/main/java/dpf/sp/gpinf/indexer/util/GraphicsMagicConverter.java#L141
> 
> I think it was removed accidentally by [5d3bd01](https://github.com/sepinf-inc/IPED/commit/5d3bd01d007f1ad1e1bf0c19e80de411b75bfcee) just on master branch in #593

Sorry, I overlooked this when doing those changes.
I agree that putting back the detection to use "convert" directly if "magick" fails is better.
I can fix this, once @aberenguel has checked what is going on with 3.18.x. Maybe it is something else, or the code to switch to "convert" is not working properly.

**Comment by lfcnassif** [comment]
> Sorry, I overlooked this when doing those changes.

And I also forgot this detail when merging, sorry.

I will test 3.18.8 on Windows and return back. And if you are busy I can  take care of this @tc-wleite

**Comment by lfcnassif** [comment]
> I will test 3.18.8 on Windows and return back

Just confirmed it doesn't work on Windows if the embedded imagemagick is replaced by the legacy 6.x version. This affects only Linux systems because IPED embed the appropriate version for Windows. Will fix shortly.

**Comment by lfcnassif** [comment]
I think now both branches are ok, @aberenguel let me know if not.

**Comment by aberenguel** [comment]
I do confirm the fixes worked in branch 3.18.x as well as in branch master! 
In both branches the EXR, HEIC, RGB, SGI,WEBP, XBM formats are being thumbed now.
Thanks @lfcnassif !

**Comment by lfcnassif** [comment]
Thanks for testing @aberenguel.
