### ISSUE TITLE
Remove "bookmark" and "score" properties from metadata panel and autocomplete

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#761]
I believe "bookmark" property cannot be used in user typed filters, right @lfcnassif?
And it also does work properly when selected in the Metadata Panel.

Some users here are getting confuse with this, so I propose to simply remove it from the properties allowed to be selected in the Metadata Panel and also remove it from properties suggested pressing TAB in the filter field.

**Comment by lfcnassif** [comment]
Correct, I've already thought about removing it from metadata panel, thanks @tc-wleite.

**Comment by hauck-jvsh** [comment]
I think that now as you are already changing the search tree to do the translation, maybe a search in the bookmarks could be implemented. If the leaf is bookmark removes from the lucene query and apply it independently. Do you think it is possible?

**Comment by tc-wleite** [comment]
> Correct, I've already thought about removing it from metadata panel, thanks @tc-wleite.

I think "score" could also be omitted, right?

**Comment by lfcnassif** [comment]
> I think that now as you are already changing the search tree to do the translation, maybe a search in the bookmarks could be implemented. If the leaf is bookmark removes from the lucene query and apply it independently. Do you think it is possible?

I think it wouldn't be easy with complex queries to combine the results later. As result of #24 one possible approach is changing the bookmarks to be stored in the index, so searches would work, although will be slower than current in memory bitset control, I'm not sure about this. Also there is #452 to refactor the bookmarks, and I'm also not sure if it is possible to store all possible future bookmark types in index. I think just hiding bookmarks as @tc-wleite proposed is enough for now and we can refactor them in #452, I'm open for ideas.

**Comment by hauck-jvsh** [comment]
> 
> 
> > I think that now as you are already changing the search tree to do the translation, maybe a search in the bookmarks could be implemented. If the leaf is bookmark removes from the lucene query and apply it independently. Do you think it is possible?
> 
> I think it wouldn't be easy with complex queries to combine the results later. As result of #24 one possible approach is changing the bookmarks to be stored in the index, so searches would work, although will be slower than current in memory bitset control, I'm not sure about this. Also there is #452 to refactor the bookmarks, and I'm also not sure if it is possible to store all possible future bookmark types in index. I think just hiding bookmarks as @tc-wleite proposed is enough for now and we can refactor them in #452, I'm open for ideas.

You are right I forgot that user may use the bookmark inside a complex query. I thought of simple queries, when they do a search and filter the results by the bookmarks. But there several possibilities when you allow the user to use bookmarks in lucene queries.
