### ISSUE TITLE
Ignore search matches when the search expression is used to filter (exclude)

### ISSUE THREAD

**Issue by patrickdalla** [sepinf-inc/IPED#766]
When it is needed to write a search to find some word in files content combined with a filter to exclude some file name patterns, when I click a resultant item, the matches for the exclusion terms are included in the tab with the matches results.
These terms are used for exclusion of files on the result, and the corresponding matches overloads the matches result.
So, when a search term is used to exclude results, they may be shown in the matches result.

**Comment by lfcnassif** [comment]
> So, when a search term is used to exclude results, they may be shown in the matches result.

I think you mean filtering/excluding terms shouldn't be highlighted in TextViewer or HitsTab, right?

**Comment by lfcnassif** [comment]
I didn't detect any kind of overloading, all used search terms are highlighted.

**Comment by lfcnassif** [comment]
I was not able to reproduce this, _image_ string is not highlighted in file content:
![image](https://user-images.githubusercontent.com/7276994/143293431-68859ee0-da08-4372-8338-ff117f48decc.png)

Could you provide an example query and file name and content to reproduce this?

**Comment by patrickdalla** [comment]
I will try to repeat. I remember that I was looking for terms in the Unallocated Space, and .

> > So, when a search term is used to exclude results, they may be shown in the matches result.
> 
> So you mean filtering/excluding terms shouldn't be shown (highlighted) in TextViewer or HitsTab, right?

Yes.

Excuse-me, it should be written: "So, when a search term is used to exclude results, they SHOULD NOT be shown in the matches result."

I will try to recover the search I used and reproduce the problem.

**Comment by lfcnassif** [comment]
> the exclusion terms are included in the tab with the matches results

Ok this was a bit ambiguous. I was looking for the issue in the HitsTab, that shows the matches results. TextViewer also seems to work fine. But I was able to reproduce in Preview tab using Phrase queries:
![image](https://user-images.githubusercontent.com/7276994/143296258-a6cd9a94-7803-4521-a319-5e2f07971840.png)

Will fix. Please let me know if you are able to reproduce this in the HitsTab/TextViewer.

**Comment by lfcnassif** [comment]
> I remember that I was looking for terms in the Unallocated Space

Unallocated is always rendered in TextViewer, but this viewer seems ok to me. Let me know if not.

**Comment by lfcnassif** [comment]
Looking at the code, terms are being collected from BooleanQueries of any type, including exclusion clauses, I will fix this.

And terms from PhraseQueries (between double quotes) are being collected for highlighting regardless of the field being searched, so a search for author:"John Stewart" would highlight "John Stewart" in file content. I think this could be useful and probably will keep this behavior. But this is valid just for phrase queries, single term queries are highlighted just if searched in the **content** field (it is the default field together with **name** if the field is not specified). So, should single term queries be also highlighted in file content regardless of the field being searched for or should we stop this behavior for phrase queries?

**Comment by lfcnassif** [comment]
> terms from PhraseQueries (between double quotes) are being collected for highlighting regardless of the field being searched

This is why `are -name:"license terms"` reproduce this but `are -name:license` doesn't.

**Comment by patrickdalla** [comment]
I could repeat. In fact I have written the query with backslashes before the quotes. Maybe I've written it wrong.
For example, try in your search: 
are -name:\"license terms\"

**Comment by patrickdalla** [comment]
this site removed the backslashes in the previous message. Correcting, try:
are -name:\\"license terms\\"

**Comment by lfcnassif** [comment]
> are -name:\"license terms\"

Well this works as expected to me, it's the same as a search for `(are OR terms) -name:license` and `license` is not highlighted anywhere.

**Comment by lfcnassif** [comment]
I fixed this for Preview Tab, please reopen if it is happening in other places.

> And terms from PhraseQueries (between double quotes) are being collected for highlighting regardless of the field being searched, so a search for author:"John Stewart" would highlight "John Stewart" in file content. I think this could be useful and possibly will keep this behavior. But this is valid just for phrase queries, single term queries are highlighted just if searched in the **content** field (it is the default field together with **name** if the field is not specified). **edit2**: _This behavior is inconsistent_. So, should single term queries be also highlighted in file content regardless of the field being searched for or should we stop this behavior for phrase queries?

We can open another ticket if someone thinks this should be changed.
