### ISSUE TITLE
New property to flag artifacts/reports generated by the tool

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#777]
Quoting https://github.com/sepinf-inc/IPED/pull/776#issuecomment-937320227:

> This can also be extended to a broader discussion about actual files (allocated, subitems from containers or carved) and "files" (reports/results) generated by the tool. I have already thought about creating a specific property to flag artifacts/reports created by the tool, to differentiate them from actual files. Or maybe putting them in a second "category" tree, separating actual files from analysis results, as called by some tools...

Suggestions about the property name? is(Generated|Decoded|Created)(Artifact|Data|Info|Report)?

+1 for isDecodedData

**Comment by lfcnassif** [comment]
Examples of artifacts/reports generated by the tool (most html):
- emails extracted from PST/OST
- chats from IM apps
- tables extracted from databases
- registry reports
- browser history reports
- UsnJournal report CSV

Should this flag be also applied to records extracted from databases like individual chat messages or browser history entries?

**Comment by tc-wleite** [comment]
> Should this flag be also applied to records extracted from databases like individual chat messages or browser history entries?

It seems reasonable to set this flag for these items.

**Comment by lfcnassif** [comment]
Actually, many things are "decodedData", like blobs extracted from databases or subitems from zips, but those are actual files and the goal is to flag data that is not an actual file, still not 100% sure about the new property name...
