### ISSUE TITLE
Aborting NullPointerException from NamedEntityTask not fixed

### ISSUE THREAD

**Issue by lzomatos** [sepinf-inc/IPED#794]
We detected this exception when try to process an UFDR file generated by Physical Analyzer 7.49.0.28 of an iOS device extraction.
We try with IPED 3.18.7 and 3.18.9 versions. The logs are available at:
[](https://bit.ly/3B3hdOF)

**Comment by lfcnassif** [comment]
Thank you very much for the complete logs.

This is not related to WhatsApp chats. Seems this is the same issue as #329 (not fixed properly). A null metadata key is being stored in the metadata map by NamedEntityTask. But inspecting its code (and also Tika NamedEntityParser) I couldn't find where this is happening. Maybe some background (parsing) thread is changing the metadata object...

**Comment by lfcnassif** [comment]
#329 has driven me crazy that time. If another dev could take a look and confirm NamedEntityTask and Tika's NamedEntityParser aren't storing null metadata keys, I would appreciate a lot.

**Comment by lfcnassif** [comment]
How many times did you try 3.18.7 and 3.18.9? They always aborted with error? If you could provide the UFDR file privately, that would help a lot.

You can also try to disable enableNamedEntityRecogniton on 3.18.7/3.18.9, I think the issue is related with that option.

**Comment by lfcnassif** [comment]
> If another dev could take a look and confirm NamedEntityTask and Tika's NamedEntityParser aren't storing null metadata keys

@tc-wleite, when you have some time available, if you could help me with this, I would appreciate a lot, this is very weird to me. I just can think about some parsing thread left behind changing the metadata object in parallel, but this may just happen when a parsing timeout is triggered, that should not occur with simple whatsapp individual messages...

**Comment by tc-wleite** [comment]
> > If another dev could take a look and confirm NamedEntityTask and Tika's NamedEntityParser aren't storing null metadata keys
> 
> @tc-wleite, when you have some time available, if you could help me with this, I would appreciate a lot, this is very weird to me. I just can think about some parsing thread left behind changing the metadata object in parallel, but this may just happen when a parsing timeout is triggered, that should not occur with simple whatsapp individual messages...

Sure! I will take a closer look tomorrow.
