### ISSUE TITLE
Add support to download and decode WhatsApp attachments

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#802]
WhatsApp attachments that were not present in the extraction may be recovered. On the msgstore database there is a link to the encrypted file and the key used to decode the file. As long as the file stills presented on the WhatsApp servers it is possible to download and decode them.

**Comment by hauck-jvsh** [comment]
How can I allow the user to enable/disable this function? Do you think that a command line parameter is better or maybe a profile configuration?

**Comment by lfcnassif** [comment]
> Do you think that a command line parameter is better

I think this is better to be more explicit, as discussed in #687. And the command line could set a system property since parsers are located in another module and can't read cmd line params directly.
