### ISSUE TITLE
Analysis UI rarely freezing in ViewerController (just in master)

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#807]
An user testing master kindly sent this thread dump after I asked for:
[iped_40_congelado_thread_dump.txt](https://github.com/sepinf-inc/IPED/files/7438340/iped_40_congelado_thread_dump.txt)

@tc-wleite I think the issue is the new ViewerController.reload() method being called from EDT before `init` boolean is set to true in finally block in constructor. This causes the `checkInit()` in `loadFile(...)` to block on EDT. In the past I thought the `checkInit()` method a bit dangerous. I see 2 options:
- make sure `loadFile(...)` is always called outside EDT (this was original intent because file loading could be slow);
- simply replace the `checkInit()` in `loadFile(...)` for `if (!isInitialized()) return;` this would ignore file load actions called before initialization;

What do you think?

**Comment by tc-wleite** [comment]
I checked the related code here, and agree with your explanation.
I tried to force the concurrence with extra locks, but couldn't reproduce the issue.

It seems that the first option is better, but I am not sure how simple it would be to implement it.
Wouldn't be enough (at least for now) to make the second change and keep an eye on it?

**Comment by lfcnassif** [comment]
> I tried to force the concurrence with extra locks, but couldn't reproduce the issue.

This just happens in a specific SETEC/PR server, maybe some environment thing is affecting thread scheduling. I checked their logs, but I think no related errors are logged.

> It seems that the first option is better, but I am not sure how simple it would be to implement it.

I thought in something like:
```
    public void loadFile(IStreamSource file, IStreamSource viewFile, String contentType, Set<String> highlightTerms) {
        if (SwingUtilities.isEventDispatchThread()) {
            new Thread() {
                public void run() {
                    loadFileOutOfEDT(file, viewFile, contentType, highlightTerms);
                }
            }.start();
        } else {
            loadFileOutOfEDT(file, viewFile, contentType, highlightTerms);
        }
    }

    private void loadFileOutOfEDT(IStreamSource file, IStreamSource viewFile, String contentType,  Set<String> highlightTerms) {
        (...)
    }
```
But I saw there are some UI components being changed in loadFile() method, I _think_ they should be changed in EDT. But most calls of loadFile(...) come from a worker thread started in FileProcessor class. Not sure if this could be a problem, if it is not safe, maybe this class would need some refactoring...

> Wouldn't be enough (at least for now) to make the second change and keep an eye on it?

I agree, will apply it and we can improve later.

**Comment by lfcnassif** [comment]
I'll just wait feedback from user to confirm pushed commit fixes the issue before merging.

**Comment by tc-wleite** [comment]
In this particular case, the dead lock happened when the case was opened, right?
Probably not related, but I noticed that the Java version is very old (1.8.0_121 if I interpreted the log correctly).

**Comment by lfcnassif** [comment]
> In this particular case, the dead lock happened when the case was opened, right?

yes!

> Probably not related, but I noticed that the Java version is very old (1.8.0_121 if I interpreted the log correctly).

hum... good catch! This and other info could be logged in the analysis GUI log...

**Comment by lfcnassif** [comment]
User confirmed the proposed fix solved this, so I merged the it.

**Comment by lfcnassif** [comment]
Just un update, user updated java version on server and previous code worked fine. But I think the code is safer now.
