### ISSUE TITLE
Parse eMule part.met files

### ISSUE THREAD

**Issue by hugohmk** [sepinf-inc/IPED#809]
eMule part.met files may present some useful data about incomplete p2p downloads (located in eMule's Temp folder), such as the file ed2k hash, uploaded bytes (tag 0x50), number of received file requests (0x51) and number of accepted file requests (0x52).
This information can be helpful in some cases where the known.met file is missing or has incomplete sharing data.

**Comment by lfcnassif** [comment]
closed by #814
