### ISSUE TITLE
Improve decoding of E-Mule known.met entry file names with diacritics

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#811]
This has been happening since this parser was implemented, many years ago.
Strings in known.met file are encoded using UTF-8 or ISO8859_1, with a BOM marker to identify when UTF-8 is used.
Although it works in many cases, some file names are not decoded properly, as the binary content does not match UTF-8 standard encoding.

An example: `Versão Acústica.mp3` is incorrectly decoded as `VersÃ£o AcÃºstica.mp3`

Going deeper into this issue, I found a possible workaround, that seems to handle most of the cases, without affecting other strings that were decoded successfully.

**Comment by lfcnassif** [comment]
@tc-wleite I changed this to enhancement, since the used encoding seems to be not using any standard charset.

**Comment by lfcnassif** [comment]
closed by #818
