### ISSUE TITLE
error on --continue task

### ISSUE THREAD

**Issue by rafael844** [sepinf-inc/IPED#822]
Hi,
We are trying to continue the process of a report that got error, but we cant. Is it possible to continue processing a report (after the .iped) or only the E01 file?
[parte_primeiro_log.txt](https://github.com/sepinf-inc/IPED/files/7488638/parte_primeiro_log.txt)
[IPED-2021-11-05-17-03-20.log](https://github.com/sepinf-inc/IPED/files/7488672/IPED-2021-11-05-17-03-20.log)

**Comment by lfcnassif** [comment]
This was possibly fixed on 3.18.9:
https://github.com/sepinf-inc/IPED/blob/master/ReleaseNotes.txt#L86

Please try to update your version.

**Comment by lfcnassif** [comment]
PS: you can use 3.18.9 to create a report from 3.18.7 case.

**Comment by lfcnassif** [comment]
Please reopen if the error happens in 3.18.9
