### ISSUE TITLE
Upgrade to java 11 LTS

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#827]
As discussed in #48. Known issues to be addressed so far:
- #478 
- #205

**Comment by tc-wleite** [comment]
Another issue is that JavaFX was removed from the Java JDK, right?
Fortunately, moving to https://openjfx.io/ seems to be straightforward.

**Comment by lfcnassif** [comment]
I've also used https://bell-sw.com/pages/downloads/ (Full JRE, not Standard) with success.

**Comment by lfcnassif** [comment]
I just processed a medium 2 million size case with both java8 and java11. There are about 26% more parsing exceptions with java11 and the number of generated image thumbs were a bit lower, will take a closer look next week.

**Comment by lfcnassif** [comment]
Update: all new parsing exceptions came from partial PNG files, previously parsed fine by JDK8 PNGImageReader. I still was not able to isolate the specific PNGImageReader change that caused this in java 11, but using JDK8 PNGImageReader as a SPI plugin fixed the regression for all inspected files. Just started the full test again.

About thumbs not generated, most of them are PNGs, possibly affected by the issue above, and a few GIFs.

I didn't detect any other regression on java 11.

**Comment by lfcnassif** [comment]
Triggering file:
![image1](https://user-images.githubusercontent.com/7276994/142082828-2d2cc4de-e068-4563-98f6-a29af87b0150.png)

**Comment by lfcnassif** [comment]
The problematic block is around this: https://github.com/openjdk/jdk11u/blob/jdk-11%2B28/src/java.desktop/share/classes/com/sun/imageio/plugins/png/PNGImageReader.java#L794
Seems they changed the decoding to be more specification compliant...

With partial images, the IEND_TYPE chunk is not found and the loop continues. JDK8 PNGImageReader stops the loop in the IDAT_TYPE case clause. I tried to report this to OpenJDK, but seems external users can't open issues...

Reverting that block to JDK8 code, the full case was processed fine throwing the same number of exceptions and the same number of PNGs have the thumb generated (about 0.5% more, same as JDK8). All affected PNGs were partially overwritten and metadata are extracted fine with JDK11 default SPI, even throwing the exception. We have some options:
- Use default java 11 SPI and accept the new exceptions for those partially PNGs. This can have impact on CarverTask if ignoreCorrupted is enabled (it is disabled in forensic & pedo profiles by default, enabled in others), those PNGs could be lost if carved. But would run the generic strings extractor on that files, this eventually may index some relevant info;
- Use a Wrapper Parser for PNGs, to just swallow the new exception. A small amount of thumbs would still be lost (about 0.5%);
- Use an alternative SPI using JDK8 code for that block, this would need more maintenance efforts from our side.

I'm inclined to last option. @tc-wleite do you have any opinion on this?

**Comment by lfcnassif** [comment]
Pushed a patched PNGImageReader to this repo: https://github.com/sepinf-inc/png-reader

Relevant commit is this: https://github.com/sepinf-inc/png-reader/commit/58e904b28336b85194e2cff378aaf73969885163

**Comment by lfcnassif** [comment]
@tc-wleite could you advice if this change is ok?
https://github.com/sepinf-inc/png-reader/commit/468e46d037dfad75c48bc18c01e75078c2e49fea#diff-b8738129f135540ae726ade402b0aeef0c8eb2ba4954e26e5f94be17eecfbe97L52-R51

I tried to protect against some internal java classes not visible anymore in recent java versions.

**Comment by tc-wleite** [comment]
Sure! I'll take a look later.

**Comment by lfcnassif** [comment]
Don't worry, take your time, thank you!

**Comment by lfcnassif** [comment]
>  This can have impact on CarverTask if ignoreCorrupted is enabled (it is disabled in forensic & pedo profiles by default, enabled in others), those PNGs could be lost if carved

Maybe this would be desired by users as those images are partially corrupted.

I also detected some few less search hits for common keywords with java 11, will take a closer look.

**Comment by tc-wleite** [comment]
> edited: @tc-wleite could you advice if changes below are ok? 

I took a look at the code and I ran a few tests here, using a standalone program and different JREs, everything seemed fine.

> * Use default java 11 SPI and accept the new exceptions for those partial PNGs. This can have impact on CarverTask if ignoreCorrupted is enabled (it is disabled in forensic & pedo profiles by default, enabled in others), those PNGs could be lost if carved. But would run the generic strings extractor on those files, this eventually may index some relevant info;
> * Use a Wrapper Parser for PNGs, to just swallow the new exception. A small amount of thumbs would still be lost (about 0.5%);
> * Use an alternative SPI using JDK8 code for that block, this would need more maintenance efforts from our side.
> 
> Edited: I'm a bit inclined to last option, but not sure. @tc-wleite do you have any opinion on this?

I would go with the third option.

**Comment by lfcnassif** [comment]
Great, thank you very much @tc-wleite for your help!

**Comment by lfcnassif** [comment]
> couldn't find the specific commit...

I think I found it:
http://hg.openjdk.java.net/jdk10/jdk10/jdk/rev/6581f08c67b6

These are related:
https://bugs.openjdk.java.net/browse/JDK-8211422
https://bugs.openjdk.java.net/browse/JDK-8164971

**Comment by lfcnassif** [comment]
> I also detected some few less search hits for common keywords with java 11, will take a closer look.

I spent some hours here and I still don't have a final diagnosis. This was caused by some application/xml files (~2k from ~93k) now being detected mostly as text/plain (and some as text/html or message/rfc822). Most (if not all) of them seems corrupted XML: starts with UTF-16 xml and ends abruptly or have some zeroed bytes, garbage or text at the end (or a mix of them) after the starting xml.

I think this is caused this Tika line (https://github.com/apache/tika/blob/6f4365b9ef03ac99de21f10a6e3f2a98452c5007/tika-core/src/main/java/org/apache/tika/mime/MimeTypes.java#L252) returning null. Maybe because of a different xml SAXParser in java 11. But with standalone Tika-1.26, those files are detected as text/plain with both java 8 or 11, when iped+jdk8 detects them as xml. So maybe there is some dependency in classpath changing/configuring the SAXParser depending on JRE used...

**Comment by lfcnassif** [comment]
update: all ~2k xml files, but 1, have an odd file size. Adding a 0x00 at the end of some samples makes them to be detected as XML again using iped + java 11, this seems related to the UTF-16LE encoding. Standalone Tika always detects them as XML with both JVMs, so this seems related to some dependency in classpath, I think...

**Comment by lfcnassif** [comment]
com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl is used by Iped on both JVMs, but possibly the internal implementation was updated...

> Standalone Tika always detects them as XML with both JVMs

Actually some are detected as text, others as xml. Different behavior between standalone Tika and Iped is because Tika-App embeds xerces2 for xml sax parsing, switching the impl to org.apache.xerces.jaxp.SAXParserFactoryImpl, and I explicitly excluded that dependency from pom.xml in tika-parsers block (I don't remember why...). Will do more tests in the next days...

**Comment by lfcnassif** [comment]
Some related conversations:
https://issues.apache.org/jira/browse/TIKA-2802
https://sourceforge.net/p/jackcess/discussion/456473/thread/de8776c701/
https://issues.apache.org/jira/browse/XERCESJ-1654

**Comment by lfcnassif** [comment]
After some thoughts, I think this xml detection problem is a Tika issue. I just opened https://issues.apache.org/jira/browse/TIKA-3596. If another Tika committer agrees with me, I'll change its behavior and we can update later.

Until then, we are having different results depending on JDK, because of possible differences in internal JDK implementation for  `com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl`, throwing more exceptions for corrupted xml in JDK11, what seems correct. As xerces2 now gives us better detection results than JDK11 internal impl (and worse than JDK8), one option is to include xerces2 in our classpath, like Tika does, so we will have the same results across different JDKs, at least until Tika is changed (or not...). This can have impact in many other places that uses xml SAX parsing, but we will be aligned with Tika results. @tc-wleite what do you think?

I'll start the full regression test again using xerces2 to see if we get bad surprises...

**Comment by tc-wleite** [comment]
> Until then, we are having different results depending on JDK, because of possible differences in internal JDK implementation for `com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl`, throwing more exceptions for corrupted xml in JDK11, what seems correct. As xerces2 now gives us better detection results than JDK11 internal impl (and worse than JDK8), one option is to include xerces2 in our classpath, like Tika does, so we will have the same results across different JDKs, at least until Tika is changed (or not...). This can have impact in many other places that uses xml SAX parsing, but we will be aligned with Tika results. @tc-wleite what do you think?

Well, if you "full test" goes fine, I think including Xerces2 seems a good option.
By the way, I have been following this thread, this issue you identified is **really** tricky! I am glad you spotted it! 
You probably had a lot of trouble isolating it (and finding possible solutions). 
I am not very familiar with the libraries/details involved, but let me know if I can help somehow.

**Comment by lfcnassif** [comment]
I had issues when including xerces in classpath, it brings in xml-apis and it has classes already included in the JDK (like org.w3c.dom.*), loaded by different class loaders (default and ours), causing crazy thinks like LinkageErrors or ClassCastException. Tried removing xml-apis from classpath, but causes a NoSuchMethodError.

As my proposal at TIKA-3596 was accepted, I fixed it in there. So I think it is better to upgrade Tika when released, instead of including xerces. I'll open a ticket here to don't forget it. As I think this truncated/corrupted xml detection as text/plain is a minor issue (actually application/xml is a subtype of text/plain), I think we can move on with jdk11 upgrade.

Will just take a look at a few GIFs mentioned before (45 from 45k) without thumbs when processing with jdk11.

**Comment by lfcnassif** [comment]
> Will just take a look at a few GIFs mentioned before (45 from 45k) without thumbs when processing with jdk11.

All of them seems corrupted GIFs. Although they don't throw Tika parsing errors on both JDKs, on JDK8 they are rendered as 1 color or blank images. Imagemagick is not able to render any of them and returns error. Windows is able to render some of them, but they have no visual information as I said. I found similar images affected in another case, with no visual information again, so I think this isn't a real issue. I'm attaching them here for posterity.
[gifs-java11-error.zip](https://github.com/sepinf-inc/IPED/files/7591020/gifs-java11-error.zip)

I haven't detected any other regression on java 11, so I think we are good to upgrade.

**Comment by lfcnassif** [comment]
Just tested above with ~200k GIFs from 324 different cases, just 9 complete black or white GIFs were rendered by JDK8 and not by JDK11, so this is fine, I will merge #827
