### ISSUE TITLE
insufficient memory 

### ISSUE THREAD

**Issue by thmme** [sepinf-inc/IPED#830]
Dear all, 

I have a issue to processing a .E01 file using the version iped-3.18.9. 

the processing not started and show a message error "insufficient memory available: below 200MB.... increase heap memory with -Xmx java option or decrease 'numthreads' in advanced configuration. 

I tried several ways to set the file AdvancedConfig.txt, but did not work well. 

PC settings: 8 Gbytes RAM.

Regards,

TM

**Comment by tc-wleite** [comment]
How many cores are being used?
Check if you are using a 64-bit JRE.
I think the number of processing threads used can be changed in LocalConfig.txt.

**Comment by tc-wleite** [comment]
There are other tips that should help in Discussions:
https://github.com/sepinf-inc/IPED/wiki/Performance-Tips

**Comment by lfcnassif** [comment]
> in advanced configuration.

This message should be updated as Wladimir pointed out.

Maybe using
java -Xms4G -Xmx4G -jar iped.jar...
together could help.

**Comment by lfcnassif** [comment]
I'm moving this to discussions
