### ISSUE TITLE
Problemas com JEP - Java Embebeded Python

### ISSUE THREAD

**Issue by rogerioubiratan** [sepinf-inc/IPED#841]
Boa tarde, estou com esse problema, ja fiz de tudo e não consegui resolver, estou usando o Ubuntu 20.10, java 8, versão build 1.8.0_202-b08, versão IPED 4.0.0, e da a mensagem:  2021-11-22 16:49:43	[ERROR]	[sepinf.python.PythonParser]			JEP não encontrado, todos os módulos python foram desligados. Veja https://github.com/sepinf-inc/IPED/wiki/User-Manual#python-modules
Gostaria de saber também qual prejuizo posso ter não obtendo esses modulos carregados. obrigado de antemão.

**Comment by lfcnassif** [comment]
What step didn't work for you? JEP installation on Linux should be pretty straightforward, it is more problematic on Windows.

Current features using Python/JEP are listed in the section of the manual you've liked above.

**Comment by lfcnassif** [comment]
Moving to discussions.
