### ISSUE TITLE
Some export files/properties dialogs take a long time to open

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#846]
This is happening for a long time. I didn't find the cause in the past, but didn't investigate deeply. Maybe this could be related to file system transversal, not sure...

@tc-wleite do you have any idea about this (don't waste your time debugging please)?

**Comment by tc-wleite** [comment]
> @tc-wleite do you have any idea about this (don't waste your time debugging please)?

To be honest, I don't remember observing this behavior here, at least in IPED. 
However,  I believe I saw that in other Java applications, long time ago, and as far as I remember it was related to network mapped volumes in Windows, so probably not related to what you are talking about.

**Comment by lfcnassif** [comment]
> To be honest, I don't remember observing this behavior here, at least in IPED.

Interesting, here the first time an export file/props dialog is opened, it takes some time. Find similar images/faces dialogs open fast. I will take a look again.

**Comment by lfcnassif** [comment]
> it was related to network mapped volumes in Windows

Indeed, this is totally related. The cause is this line introduced when @fsicoli made changes to the iped-triage Linux distribution:
https://github.com/sepinf-inc/IPED/blob/a689b043ac5dfd9a047dc8cb1726d873973bd9ba/iped-app/resources/localization/iped-desktop-messages.properties#L176

The double slashes are being converted to double backslashes by java, causing a network scan on windows, taking some seconds. Simply replacing them by a single backslashes fix the issue.

**Comment by lfcnassif** [comment]
This affects a lot of dialogs that share the same JFileChooser.
