### ISSUE TITLE
Identify QRcodes

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#847]
It would be great if IPED identify and decode QRcodes present in the case images.

**Comment by hauck-jvsh** [comment]
Reference lib
https://docs.opencv.org/4.x/javadoc/org/opencv/objdetect/QRCodeDetector.html

**Comment by lfcnassif** [comment]
As we discussed internally, this could be useful to find crypto wallets related info and bank accounts IDs (like PIX)

**Comment by lfcnassif** [comment]
> https://github.com/zxing/zxing

This lib seems a good option.
