### ISSUE TITLE
Index similar faces features using new Lucene-9 vector indexing support

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#890]
Depends on #888. This would allow faster look up and nearest neighbors search. @tc-wleite I saw ImageSimilarity uses 1044 features but I think the max vector dimension supported by Lucene-9 is 1024. Do you think that could be a problem? Could the number of dimensions of ImageSimilarity be decreased to 1024 with small impact on results? And after this feature is implemented, I think the faster filter for RGB+gray channels could be removed to evaluate more images, what do you think?

**Comment by lfcnassif** [comment]
These new methods must be implemented properly as part of this issue: https://github.com/sepinf-inc/IPED/pull/888/commits/49d56135ef4180627afb936b02fe0844d02821dc

**Comment by tc-wleite** [comment]
> @tc-wleite I saw ImageSimilarity uses 1044 features but I think the max vector dimension supported by Lucene-9 is 1024. Do you think that could be a problem? Could the number of dimensions of ImageSimilarity be decreased to 1024 with small impact on results? 

The number of features can definitely be reduced to 1024.
There are several ways of doing that, so I will need to take a closer look, but it should be simple.

> And after this feature is implemented, I think the faster filter for RGB+gray channels could be removed to evaluate more images, what do you think?
Sure, makes sense.

**Comment by lfcnassif** [comment]
Related to #308

**Comment by tc-wleite** [comment]
@lfcnassif, I tested here (in a standalone program) a way of reducing image similarity features to 1024. It seems to provide very similar results. 
Checking the changes that would be necessary in IPED, I realized that I don't know how to implement the Lucene related part.
Not sure how you plan to deal with this issue, but if you implement the changes for Similar Faces, I can later use them as an example and make the necessary changes for the image similarity, including reducing the number of features used.

**Comment by lfcnassif** [comment]
@tc-wleite I started working on this. Unfortunately, seems the new Lucene KnnVectorField (https://lucene.apache.org/core/9_0_0/core/org/apache/lucene/document/KnnVectorField.html) is single valued :-(. For image similarity feature I think it's ok. But for faces, there can be more than one per image... One solution would be to store additional faces in different vector fields (face1, face2...) and search for all those fields. I'm not sure if it will be better than current approach where we store raw byte[] vectors in one single multivalued field and do an exhaustive search for similar faces. It is fast today, if I remember, taking some hundreds of milliseconds in my machine with a case with hundreds of thousands of images, because its is multithreaded and usually the number of images with faces is much smaller than the total number of images in the case.

If you could push your image similarity vector changes to some branch, I can work from that point.

And if you have any opinion about what to do with the similar faces vectors, I'm glad to hear...

**Comment by tc-wleite** [comment]
> If you could push your image similarity vector changes to some branch, I can work from that point.

Sure! Should I use the branch you created ([#890_index_vectors](https://github.com/sepinf-inc/IPED/tree/%23890_index_vectors)) or a new one?

**Comment by tc-wleite** [comment]
> Use the same please, thank you!

Just pushed the changes to reduce the number of features used by image similarity to 1024.
I also made a temporary change to not use SimilarImagesSearch (that was filtering by features that were removed).
Let me know if you find any issue while implementing the Lucene related part.
Other than that, let me know when it is working, so I can run some tests here.

**Comment by lfcnassif** [comment]
Thank you @tc-wleite! I'll start working on this now.

**Comment by lfcnassif** [comment]
@tc-wleite just an observation, we can index a float[1024] array, image features now uses a byte[1024], maybe that could be useful to store more information.

**Comment by lfcnassif** [comment]
Closed by #981. As discussed on #980, we are just indexing face encodings for a possible usage in a future lucene upgrade, since they are float[128], no changes were done in the face search code nor in the image similary feature.
