### ISSUE TITLE
Allow user-global setting for the User Interface Scale (UiScale)

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#900]
As discussed in #48, after making IPED compatible with Java 11 (#827), the user interface will be automatically adjusted to the screen resolution. 
It is now also possible to adjust the user interface scale explicitly, using the command line parameter `sun.java2d.uiScale`:
`java -Dsun.java2d.uiScale=1.5 -jar iped\lib\iped-search-app.jar` 

However, setting this value and using the command line every time may be inconvenient.
I propose a simple solution to allow setting this UiScale factor in a plain configuration file, in the ".iped" folder.
Another option would be using the LocalConfig.txt file for such setting, but that file is sometimes copied to other machines, with other screen resolution. 

It would be possible to create an option in the user interface to edit this value,  but my initial idea was to add only the file configuration support.

**Comment by lfcnassif** [comment]
Thank you, @tc-wleite.

> It would be possible to create an option in the user interface to edit this value, but my initial idea was to add only the file configuration support.

I'll add this option since the new config file won't be noticed by most users. Simply giving a message to manually restart the application after changing the setting is enough?

**Comment by tc-wleite** [comment]
> I'll add this option since the new config file won't be noticed by most users. 

Yes, it is hidden this way. I thought about adding to the documentation, but probably wouldn't help much. 

> Simply giving a message to manually restart the application after changing the setting is enough?

That would be a good solution. 
It is not something to be changed often anyway, so a manual restart seems acceptable.

**Comment by lfcnassif** [comment]
@tc-wleite, I just pushed the changes, if you agree with them, I'll merge.

**Comment by tc-wleite** [comment]
> @tc-wleite, I just pushed the changes, if you agree with them, I'll merge.

Great! I will take a look and reply here.

**Comment by tc-wleite** [comment]
I just tested here and reviewed the code, everything looks fine.
Adding the configuration dialog was a simple but good idea, I should have done that :-)

Just one somewhat related comment:
This one and all other new menu options are great, but the menu has been growing a bit.
What do think about this? 
There are other (more complex) solutions, but I was considering just grouping a few related items:

- Reset to default layout
- Color Theme
- Change User Interface Zoom
- Change Gallery Column Count

These are all in the same group (menu horizontal dividers) and are not supposed to be used very often.
My suggestion was to create a "Layout/Appearance" menu item, and move these 4 items as subitems of it.
It would save 3 lines in the main menu.

**Comment by lfcnassif** [comment]
> Adding the configuration dialog was a simple but good idea

well, that was your idea :-) but I know you are a busy guy

> What do think about this?

I thought about adding a JMenuBar in the future, but that would need more work...

> My suggestion was to create a "Layout/Appearance" menu item, and move these 4 items as subitems of it.

I'm ok with that and would also add "Change vertical/horizontal layout".

I'll merge #901 and we could do this separately. Thank you @tc-wleite!

**Comment by tc-wleite** [comment]
> I'm ok with that and would also add "Change vertical/horizontal layout".
> 
> I'll merge #901 and we could do this separately. Thank you @tc-wleite!

Cool! It is a pretty simple, I can do this menu change here. 
And I forgot to add the "Vertical/Horizontal" item when wrote my previous comment, but it should definitely be moved with the other four.
