### ISSUE TITLE
Some features that iterate over docValues could not work together with index searches after Lucene-7 upgrade (master)

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#925]
Possibly this was caused by lucene upgrade, will investigate tomorrow.

**Comment by lfcnassif** [comment]
> Possibly this was caused by lucene upgrade, will investigate tomorrow.

Specifically, by last lucene-9.0.0 upgrade.

**Comment by lfcnassif** [comment]
> Specifically, by last lucene-9.0.0 upgrade.

Actually I think this is happening since lucene-7x upgrade and affects other features that must iterate over docValues (bookmark duplicates, similar images/faces search, etc). This was a bit hard to debug and is related with large items that were splitted while indexing.

After searching the index, result references are converted from indexID to itemID. Later, when those features must iterate over docValues, itemID is converted again to indexID, but this can give a different value for splitted items (the conversion could pick the indexID of a different item fragment in index, all fragments have the same itemID). That can break the increasing indexID order required when iterating over docValues with lucene >= 7.

I'll push a fix shortly.

**Comment by lfcnassif** [comment]
Just to complement the explanation, the case have a itemID -> indexID array for all items, and that maps to the smaller indexID used by splitted items. I thought about using the larger indexID value, but that leads to issues with different searches. For example, let's say we have 2 items A & B, and B was broken into B1 & B2 in index. After indexing, we can get indexID(B1) < indexID(A) < indexID(B2). Some search could return {indexID(A), indexID(B2)} result. That would be mapped to {itemID(A), itemID(B)}. Later, when some of the affected modules need to convert to indexID again, the smaller indexID mapping logic would result in {indexID(A), indexID(B1)} set, breaking the increasing indexID sorting needed by docValues iteration.

If we use the larger indexID mapping logic for fragments, a different search result like {indexID(B1), indexID(A)} would be mapped to {itemID(B), itemID(A)} and later to {indexID(B2), indexID(A)}, breaking docValues iteration too. So the fix sorts the results after all those mappings.

**Comment by lfcnassif** [comment]
Reopening. @aberenguel reported on #1074 that it sometimes fails. This is printed in IPEDSearchApp.log:
```
java.lang.IllegalArgumentException: can only advance beyond current document: on docID=1536869 but targetDocID=217674
	at org.apache.lucene.index.MultiDocValues$MultiSortedDocValues.advanceExact(MultiDocValues.java:761)
	at dpf.sp.gpinf.indexer.lucene.DocValuesUtil.getOrd(DocValuesUtil.java:41)
	at dpf.sp.gpinf.indexer.desktop.BookmarksManager.includeDuplicates(BookmarksManager.java:391)
	at dpf.sp.gpinf.indexer.desktop.BookmarksManager$1.run(BookmarksManager.java:536)
```
I've also saw above trace recently in log while using the Metadata panel filter with the 33M files regression dataset.

**Comment by lfcnassif** [comment]
@aberenguel please test if commit above fix the bookmarking duplicates issue on your case.

**Comment by aberenguel** [comment]
I processed the case before tika upgrade 5a8e2458f7e44b4dacd09300d029ad7eacea13e7 commit.
Is there something special to update? I'm getting some exceptions like that

```
Caused by: java.lang.ClassNotFoundException: org.apache.tika.parser.jpeg.JpegParser
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at dpf.sp.gpinf.indexer.parsers.MultipleParser.setParsers(MultipleParser.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tika.config.ParamField.assignValue(ParamField.java:107)
	at org.apache.tika.utils.AnnotationUtils.assignFieldParams(AnnotationUtils.java:115)
```

**Comment by lfcnassif** [comment]
Try to replace the whole iped/lib and iped/conf folders into your case. Or apply the patch over your build, since you can get different search results or highlights in TextViewer using Tika 2.

**Comment by aberenguel** [comment]
Just tested with 5f2efb7 commit.
It worked as expected.
Thanks, @lfcnassif !

**Comment by lfcnassif** [comment]
Thank you @aberenguel. I'm struggling here for hours to fix a similar issue with another module, will close this when I find the cause and solution...

**Comment by lfcnassif** [comment]
@aberenguel I just saw I introduced another bug in the commit you've checked out: just checked items being listed on main table are being bookmarked if you choose to bookmark checked items, sorry about that. I'll fix it when I arrive at home.

**Comment by aberenguel** [comment]
> @aberenguel I just saw I introduced another bug in the commit you've checked out: just checked items being listed on main table are being bookmarked if you choose to bookmark checked items, sorry about that. I'll fix it when I arrive at home.

I reproduced this bug. After the last commit it was fixed!

**Comment by lfcnassif** [comment]
> I reproduced this bug. After the last commit it was fixed!

Thanks for testing again!
