### ISSUE TITLE
Change checked items localization to portuguese

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#929]
Currently those strings are translated as:
- highlighted items -> itens destacados
- checked items -> itens selecionados

The proposal is changing to:
- highlighted items -> itens selecionados
- checked items -> itens marcados

Original translation was chosen because I thought "marcados" could be confused with items in bookmarks ("marcadores"). But this choice confused even me a lot of times...

Or maybe keep the current translation for "highlighted items" and just change the second to:
- checked items -> itens marcados

maybe would be less confusing for old users... What other devs/users think? Any other suggestion?

**Comment by tc-wleite** [comment]
> The proposal is changing to:
> * highlighted items -> itens selecionados
> * checked items -> itens marcados

This is my favorite option. 
I guess there are no "perfect" translations for these terms, and the original ones in English seem more intuitive, but I believe the proposed terms are used by other softwares in Portuguese.

> Or maybe keep the current translation for "highlighted items" and just change the second to:
> * checked items -> itens marcados
> maybe would be less confusing for old users...

This is a good alternative, and would be less confusing for old users as you said, so that would be my second option.

**Comment by lfcnassif** [comment]
I also thought about changing the english expression "highlighted items" to "selected items". But I think the current english string is already intuitive, so changing it could just confuse old users instead of making things better.

**Comment by lfcnassif** [comment]
After talking with some colleagues here, let's go with the second proposal
