### ISSUE TITLE
Minor Fixes to local (Vosk) audio transcription (master)

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#949]
- While working in a case with relevant audio files, I tried using the local (Vosk) audio transcription feature. Initially it was not working. After investigating the issue, I found that the conversion to WAV (before call Vosk library) was not working anymore. It seems to a similar issue that affected video thumb generation explained here https://github.com/sepinf-inc/IPED/issues/908#issuecomment-1014844052. I applied the same fix @lfcnassif made for videos, changing the current directory before calling MPlayer, instead of passing the output file full path (which escaping was tricky).

- Later, Ifound out that report generation wasn't working because the Vosk model file is not present in the case. I applied the same fix other tasks already use: just warn and disable the task when the model is not present, if it is a report.

- Made another minor modification: only change the language to English (when the model is not found), if it is not already in English and English model exists.

- Another minor detail, some audio files are not converted to WAV by MPlayer and MPlayer process still exits with zero code. So I add a test to check if the WAV file exists, before calling the audio transcription engine. This avoids a lot of FileNotFoundException's (and their stack traces) in the log. 

- Finally, I added some basic statistics to the log, as other tasks do.

**Comment by tc-wleite** [comment]
Forgot to write in my previous post... 
It was the first time I tried the local audio transcription, and found it a very promising feature. 
Although the transcription results could be a bit better, in general they were good, and contained several important words from the audios I had. Considering it is a free option (comparing with cloud services already available) and trivial to use (no extra setup required, just enable it in the configuration file), I guess it will be very useful. 
And it seems that Vosk is an active project, so new versions/models will hopefully provide even better results.

**Comment by lfcnassif** [comment]
> Although the transcription results could be a bit better

Thank you @tc-wleite for trying this new feature and for the fixes! For sure the pr-BR model can be enhanced, I added a configuration to filter out words with low confidence scores. The english model and possibly others have higher accuracy, so I think this will be even more useful for foreign users.
