### ISSUE TITLE
Optimize WhatsAppParser memory usage

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#972]
While reviewing #923 I remembered all chat/message data is kept on memory, including thumbnails.

Now that decoded data from identified backups are kept in a static cache (temporarily until all DBs are processed) to allow merging them with the main database, maybe it would be a good idea to try to optimize the memory footprint.

Early today I did some heap dumps and profiling and found out that spooling thumbnails to disk saved about 32% of memory used by whatsapp decoded data, tested with one medium size (420MB) and one large size (1.2GB) database, plus 8 backups for each. Heap usage decreased from ~1.15GB to 784M and 4GB to 2.72GB respectively. I was expecting a bigger memory saving, not sure if it is worth to apply. Opinions?

**Comment by aberenguel** [comment]
Is it possible to use some cache that evict data when it reach some size?
In the past I used the guava library cache. It has a lot of features for cache policy.
https://github.com/google/guava/wiki/CachesExplained

**Comment by lfcnassif** [comment]
Before merging #923, although the decoded data was not kept in a static cache, the main WA DB and its backups used to be processed at the same time when running in a CPU with many cores, so about the same amount of memory was used before. This usually is not a problem because high end CPUs often comes with dozens of GBs of memory. But now, even CPUs with a few cores (that usually has less memory available, e.g. notebooks), keeping all backups decoded data in a cache could be a problem...

PS: mergeDBs option now was enabled by default, but it could be disabled by users with memory issues.

**Comment by lfcnassif** [comment]
> Is it possible to use some cache that evicts data when it reaches some size?

Actually I'm misusing the "cache" word. If we throw away decoded data larger than some limit/after some time, the mergeDBs feature won't work. But we could use some Map out of heap implementation, maybe using native memory or paged to disk.

**Comment by lfcnassif** [comment]
I did a few more tests and seems simply spooling thumbs to disk can save up to 40% of memory used by WhatsAppParser depending on dataset. Instead of spooling, another solution would be to read thumbs from WA databases on demand, but this would require much more code changes (opening and reusing connections, new SQLs for different WA versions, updating the old ones...). Using one single thumbs file container accessed concurrently by a FileChannel caused very little performance impact when using a temp SSD disk. So I'll apply the spooling solution.

**Comment by lfcnassif** [comment]
Reopening. I didn't test databases together with attached medias, but seems the changes made on #486 are keeping all references (and thumbnails) to attached items found in case on memory, this could be improved too.

**Comment by lfcnassif** [comment]
Reopening, this is causing an error when there are Android and iOS whatsapp databases mixed in the same case.
