### ISSUE TITLE
Group participants aren't being extracted

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#973]
Group participants are not being extracted, and the field Message-To in each group individual message are also not being populated;

**Comment by lfcnassif** [comment]
My fault, sorry. This is a regression introduced in 3.18.9 in this commit: d043e8692bd7ccf96fde2f30484710ab196f5b27

**Comment by hauck-jvsh** [comment]
Just one more thing, I notice that the group id is not being exported to any metadata. What do you think about export it?

**Comment by hauck-jvsh** [comment]
The group ID is a string formatted as {creator's phone number}-{creation time}@g.us;

**Comment by lfcnassif** [comment]
closed by #974
