### ISSUE TITLE
Change a few more property names in index

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#983]
This needs to be done before 4.0.0. Some properties that come to my mind:
- similarityFeatures -> imageFeatures
- Message-From -> From or Party-From (also used by Calls)
- Message-To -> To or Party-To (also used by Calls)
- Message-Date -> Date, Communication-Date or maybe we could have separate Message-Date and Call-Date. Just the two above (From/To) must be the same for both Messages and Calls categories, because those properties are used to build connections in the Graph Tab.

Any others?

**Comment by lfcnassif** [comment]
> * Message-From -> From or Party-From (also used by calls)
> * Message-To -> To or Party-To (also used by calls)

I'm not sure about this. I like the current position of those fields in Metadata filter panel, at the beggining of the "Message" property group:
![image](https://user-images.githubusercontent.com/7276994/163443658-265ada84-38b2-4f51-80fc-d9a2fb995ce0.png)

Renaming `Message-To` to `To` would move it to the end of above list, because properties are alphabetically sorted.
One option would be to duplicate the property, having `Message-To` and `To` fields.
But `Message-To` makes no sense for calls.
Maybe we can rename and fix the position of the new `From`/`To` fields in above list?

**Comment by lfcnassif** [comment]
> * similarityFeatures -> imageFeatures

@tc-wleite are you ok with this? I think other kinds of similarity vectors could be added in the future (for text, video, audio, etc...), so I think above would help avoiding confusion.

And if you have, I would also appreciate a lot ideas to rename Message-From, Message-To, Message-Date, since they are also used by Calls, not just by Emails and Instant Messages.

**Comment by tc-wleite** [comment]
Sure!

**Comment by lfcnassif** [comment]
I'm going to rename Message-From|To|Date to Communication:From|To|Date into the index. We can later translate those properties in the localization files, removing the Communication: prefix, if desired

**Comment by lfcnassif** [comment]
Now those properties are being displayed like:
![image](https://user-images.githubusercontent.com/7276994/173148795-962b51d7-32cd-4c0a-8f32-2ec3d35048b7.png)
As I said, we can rename those properties display string, but I liked it, I think it's a matter of getting used to the new names.
