### ISSUE TITLE
Support ProjectVIC Data Model 2.0

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#985]
As discussed in https://github.com/sepinf-inc/IPED/discussions/944#discussioncomment-2062294.

**Comment by lfcnassif** [comment]
@tc-wleite if you don't have yet, I can download a sample json using the new 2.0 model for dev/testing.

**Comment by tc-wleite** [comment]
> @tc-wleite if you don't have yet, I can download a sample json using the new 2.0 model for dev/testing.

I am using the one you uploaded to out internal server a few days ago (that you later replaced by the 1.3).
By the way, I requested the access to ProjectVIC hashes, already sent a few additional emails, but still waiting...

**Comment by lfcnassif** [comment]
> By the way, I requested the access to ProjectVIC hashes, already sent a few additional emails, but still waiting...

I think I'll get in touch to them and ask about the 1.4M photoDNA hashes missing in last version...
